<?php
require __DIR__.'/app/bootstrap.php';require_once __DIR__.'/app/compat.php';require_once __DIR__.'/app/sales-table.php';$u=require_any_permission(['tables.view','sales_sessions.record','sales_sessions.manage','settings.manage']);$msg='';$err='';
if($_SERVER['REQUEST_METHOD']==='POST'){csrf_check();$a=(string)($_POST['action']??'');try{
 if($a==='init_sales_qr_secret'){if(!user_can($u,'sales_sessions.record')&&!user_can($u,'sales_sessions.manage')&&!user_can($u,'settings.manage'))throw new RuntimeException('ไม่มี Permission สำหรับตั้งค่า QR โต๊ะ Sales');db_mutate(function($d){st_initialize_public_secret($d);return $d;});$msg='สร้าง QR Secret สำหรับสาขานี้แล้ว';}
}catch(Throwable $e){$err=$e->getMessage();}}
$d=db_load();$canInitSalesQr=user_can($u,'sales_sessions.record',$d)||user_can($u,'sales_sessions.manage',$d)||user_can($u,'settings.manage',$d);$hasSalesQrSecret=st_public_secret($d)!=='';$today=date('Y-m-d');$todayC=array_values(array_filter($d['checkins'],fn($c)=>str_starts_with((string)($c['created_at']??''),$today)));$completed=array_values(array_filter($todayC,fn($c)=>($c['status']??'')==='completed'));$active=array_values(array_filter($todayC,fn($c)=>!in_array(($c['status']??''),['completed','cancelled'],true)));$shifts=$d['shifts'];
$base=(isset($_SERVER['HTTPS'])&&$_SERVER['HTTPS']!=='off'?'https':'http').'://'.($_SERVER['HTTP_HOST']??'localhost').rtrim(dirname($_SERVER['SCRIPT_NAME']??'/it/admin-tools.php'),'/');
?><!doctype html><html lang="th"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>MR BAR — Sales QR Tools</title><link rel="stylesheet" href="assets/admin.css?v=1140"><style>.qrgrid{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:14px}.qrcard{text-align:center;padding:18px;border:1px solid #7c3cff55;border-radius:20px;background:#ffffff06}.qrcard img{width:150px;height:150px;background:white;padding:7px;border-radius:12px}</style><link rel="stylesheet" href="assets/admin-v14.css?v=1140"><link rel="stylesheet" href="assets/admin-sales-qr-print-v14841.css?v=14841"></head><body class="admin-v14-page"><?php require_once __DIR__.'/app/admin-nav.php'; echo admin_sidebar('tools',$u); ?><main style="max-width:1500px;margin:auto;padding:28px"><header class="topbar"><div><p class="eyebrow">ADMIN / OPERATIONS TOOLS</p><h1>เครื่องมือร้าน • QR โต๊ะ Sales</h1><p>จัดการ ทดสอบ และพิมพ์ QR สำหรับเปิด–ปิดโต๊ะ Sales</p></div><div style="display:flex;gap:8px"><a class="ghost" href="night-ops.php">Night Ops →</a><a class="ghost" href="admin.php">← Admin Control</a></div></header><?php if($msg):?><div class="notice ok">✓ <?=h($msg)?></div><?php endif;?><?php if($err):?><div class="notice err">⚠ <?=h($err)?></div><?php endif;?>
<section class="kpis"><article class="kpi pink"><span>Check-in วันนี้</span><b><?=count($todayC)?></b><small>รายการ</small></article><article class="kpi green"><span>จบงานวันนี้</span><b><?=count($completed)?></b><small>รายการ</small></article><article class="kpi blue"><span>กำลังดำเนินการ</span><b><?=count($active)?></b><small>รายการ</small></article><article class="kpi gold"><span>กะที่จัดไว้</span><b><?=count($shifts)?></b><small>กะ</small></article></section>
<section class="panel wide qr-print-panel"><div class="panel-head qr-panel-head"><div><h2>QR เปิด–ปิดโต๊ะ Sales</h2><p>สแกนแล้วเข้าหน้าโต๊ะได้ทันทีโดยไม่ต้อง Login · เลือก Sales เจ้าของยอดและเปิด/ปิดรอบได้จาก QR</p><a href="sales-table.php?public_branch=<?=h(rawurlencode((string)(branch_current($d)['slug']??'')))?>">ดูประวัติรอบโต๊ะ Sales →</a><p class="qr-security-note">QR แต่ละโต๊ะมี Signed Token เฉพาะสาขา/โต๊ะ · หน้า Public QR ไม่แสดงประวัติหรือเครื่องมือ Admin</p></div><div class="qr-print-actions"><button class="ghost no-print" type="button" onclick="window.print()">พิมพ์ A4 / Save PDF</button><small class="no-print">ในหน้าต่าง Print เลือก “Save as PDF” ได้</small></div></div><?php if(!$hasSalesQrSecret):?><div class="notice err">ยังไม่มี QR Secret จึงยังออก QR ที่ใช้งานได้ไม่ได้. <?php if($canInitSalesQr):?><form method="post" style="display:inline"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><input type="hidden" name="action" value="init_sales_qr_secret"><button class="mini primary">ตั้งค่า QR สำหรับสาขานี้</button></form><?php else:?>ให้ผู้ดูแลที่มีสิทธิ์ Sales QR หรือ Settings เป็นผู้ตั้งค่า<?php endif;?></div><?php else:?><div class="qrgrid"><?php foreach($d['tables'] as $t):if(empty($t['active']))continue;$branchSlug=(string)(branch_current($d)['slug']??'');$token=st_public_token($d,$branchSlug,(int)$t['id']);$url=$base.'/sales-table.php?'.http_build_query(['public_branch'=>$branchSlug,'table_id'=>(int)$t['id'],'qr_token'=>$token]);?><div class="qrcard"><b class="qr-table-code"><?=h($t['code'])?></b><p class="qr-zone"><?=h($t['zone']??'Main')?></p><img loading="lazy" src="https://api.qrserver.com/v1/create-qr-code/?size=220x220&data=<?=urlencode($url)?>" alt="QR <?=h($t['code'])?>"><small class="qr-public-label">SCAN TO OPEN TABLE</small><small class="qr-url no-print"><?=h($url)?></small><a class="no-print" href="<?=h($url)?>" target="_blank" rel="noopener">ทดสอบ QR โต๊ะนี้</a></div><?php endforeach;?></div><?php endif;?></section>
<footer>MR BAR Operations Tools · <?=h((string)(app_config()['version']??'1.48.89'))?></footer></main></body></html>
