<?php
require __DIR__.'/app/bootstrap.php';require_once __DIR__.'/app/compat.php';
$u=require_permission('dashboard.view');
$d=db_load();
require_once __DIR__.'/app/dashboard-sales.php';
$canSales=user_is_super_admin($u)||user_can($u,'reports.view',$d)||user_can($u,'employees.manage',$d);
$salesSource=(string)($_GET['sales_source']??'bills');
if(!isset($_GET['sales_source'])&&empty($d['pos_bill_batches']))$salesSource='menu';
$sales=$canSales?dash_sales($d,$salesSource,max(0,(int)($_GET['sales_batch']??0))):null;
$today=date('Y-m-d');
$todayRows=array_values(array_filter($d['checkins']??[],fn($c)=>strpos((string)($c['created_at']??''),$today)===0));
$completed=array_values(array_filter($todayRows,fn($c)=>($c['status']??'')==='completed'));
$active=array_values(array_filter($todayRows,fn($c)=>!in_array((string)($c['status']??''),['completed','cancelled'],true)));
$pending=array_values(array_filter($todayRows,fn($c)=>in_array((string)($c['status']??''),['pending','rejected','assigned'],true)));
$inService=array_values(array_filter($todayRows,fn($c)=>($c['status']??'')==='in_service'));
$occupied=count(array_filter($d['tables']??[],fn($t)=>($t['status']??'')==='occupied'));
$available=count(array_filter($d['tables']??[],fn($t)=>($t['status']??'')==='available'));
$blocked=count(array_filter($d['tables']??[],fn($t)=>($t['status']??'')==='blocked'));
$totalTables=max(1,count($d['tables']??[]));
$onlinePr=count(array_filter($d['prs']??[],fn($p)=>in_array((string)($p['status']??''),['online','busy'],true)));
$busyPr=count(array_filter($d['prs']??[],fn($p)=>($p['status']??'')==='busy'));
$openAttendance=count(array_filter($d['attendance']??[],fn($a)=>empty($a['check_out'])));$attendanceExceptions=count(array_filter($d['attendance']??[],fn($a)=>in_array(workforce_attendance_state($a),['missing_checkout','provisional'],true)));$pendingSubstitute=count(array_filter($d['substitute_requests']??[],fn($r)=>($r['status']??'')==='pending'));$pendingCorrections=count(array_filter($d['time_correction_requests']??[],fn($r)=>($r['status']??'')==='pending'));
$todayReservations=array_values(array_filter($d['reservations']??[],fn($r)=>($r['date']??'')===$today&&!in_array(($r['status']??''),['cancelled','no_show'],true)));
$waitlist=count(array_filter($todayReservations,fn($r)=>($r['status']??'')==='waitlist'));
$unread=count(array_filter($d['notifications']??[],fn($n)=>empty($n['read_at'])));
$serviceCalls=array_values(array_filter($d['service_calls']??[],fn($x)=>empty($x['resolved_at'])&&(($x['created_at']??'')===''||strpos((string)$x['created_at'],$today)===0)));
$closeToday=array_values(array_filter($d['daily_closes']??[],fn($x)=>($x['date']??'')===$today));
$completionRate=count($todayRows)?round(count($completed)/count($todayRows)*100):0;
// 7-day trend
$trend=[];for($i=6;$i>=0;$i--){$date=date('Y-m-d',strtotime("-$i day"));$trend[]=['label'=>date('d/m',strtotime($date)),'value'=>count(array_filter($d['checkins']??[],fn($c)=>strpos((string)($c['created_at']??''),$date)===0))];}
// PR performance based on completed jobs today
$perf=[];foreach($d['prs']??[] as $p){$n=count(array_filter($completed,fn($c)=>(int)($c['pr_id']??0)===(int)$p['id']));if($n||in_array(($p['status']??''),['online','busy'],true))$perf[]=['name'=>$p['name'],'code'=>$p['code'],'jobs'=>$n,'status'=>$p['status']];}usort($perf,fn($a,$b)=>$b['jobs']<=>$a['jobs']);
$recent=array_slice(array_reverse($d['notifications']??[]),0,7);
$manifest=@json_decode((string)@file_get_contents(__DIR__.'/manifest.json'),true);$version=(string)($manifest['version']??'1.7.0');
function dash_table_name(array $d,int $id):string{foreach($d['tables']??[] as $t)if((int)$t['id']===$id)return (string)$t['code'];return '-';}
?><!doctype html><html lang="th"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#070914"><title>MR BAR — Dashboard</title><link rel="stylesheet" href="assets/admin.css?v=1140"><style>
.dash-grid{display:grid;grid-template-columns:1.2fr 1fr .9fr;gap:18px}.chartbox{height:250px;display:flex;align-items:end;gap:12px;padding:24px 10px 5px;border-top:1px solid #ffffff0b}.barcol{height:100%;flex:1;display:flex;flex-direction:column;justify-content:flex-end;align-items:center;gap:8px}.barcol i{width:80%;min-height:4px;border-radius:9px 9px 3px 3px;background:linear-gradient(180deg,#ff44d0,#673cff);box-shadow:0 0 24px #a53cff55}.barcol small{color:#8e97ba}.donut{width:180px;aspect-ratio:1;border-radius:50%;display:grid;place-items:center;margin:12px auto;background:conic-gradient(#2ee89c 0 var(--occ),#26314f var(--occ) 100%);position:relative}.donut:after{content:"";position:absolute;inset:22px;border-radius:50%;background:#0c111e}.donut strong{z-index:1;font-size:35px}.status-legend{display:grid;gap:8px}.status-legend div{display:flex;justify-content:space-between;background:#ffffff06;border-radius:10px;padding:9px 11px}.quick{display:grid;gap:10px}.quick a{text-decoration:none;padding:14px;border-radius:12px;background:#ffffff08;border:1px solid #ffffff14;font-weight:800}.quick a:hover{border-color:#7c4cff;box-shadow:0 0 25px #7c4cff25}.table-mini{display:grid;grid-template-columns:repeat(5,1fr);gap:9px}.table-mini div{padding:11px 6px;text-align:center;border-radius:10px;font-weight:900;border:1px solid #ffffff14}.table-mini .available{border-color:#23e79a;color:#67ffc2}.table-mini .occupied{border-color:#ff4779;color:#ff91ad}.table-mini .blocked{border-color:#f0b84c;color:#ffd477}.perf-row{display:grid;grid-template-columns:1fr auto;gap:10px;padding:11px;border-bottom:1px solid #ffffff0c}.perf-row small{display:block;color:#8e97ba}.queue-row{display:grid;grid-template-columns:90px 1fr auto;gap:10px;padding:11px 4px;border-bottom:1px solid #ffffff0c}.queue-row b{color:#cda8ff}.badge2{padding:5px 8px;border-radius:99px;background:#202744;color:#cbd4ff;font-size:10px}.warning-card{margin-top:18px;padding:15px 18px;border-radius:14px;background:#4a291055;border:1px solid #ffbe4470;color:#ffdb94}@media(max-width:1200px){.dash-grid{grid-template-columns:1fr 1fr}.dash-grid>.panel:last-child{grid-column:1/-1}}@media(max-width:820px){.dash-grid{grid-template-columns:1fr}.dash-grid>.panel:last-child{grid-column:auto}.table-mini{grid-template-columns:repeat(4,1fr)}}
</style><link rel="stylesheet" href="assets/admin-v14.css?v=1140"><link rel="stylesheet" href="assets/dashboard-v14921.css?v=14921"></head><body class="dash-v21"><div class="ambient"><i></i><i></i><i></i></div>
<?php require_once __DIR__.'/app/admin-nav.php'; echo admin_sidebar('dashboard',$u); ?>
<main><header class="topbar"><button class="menu-btn" id="menuBtn">☰</button><div><p class="eyebrow">ADMIN / LIVE OVERVIEW</p><h1>ภาพรวมการดำเนินงานวันนี้</h1><p><?=h((string)($d['settings']['shop_name']??'MR BAR'))?> · ข้อมูลสรุปสำหรับตัดสินใจ ไม่รวมหน้าตั้งค่า</p></div><div class="top-actions"><div class="clock-card"><b id="liveClock"><?=date('H:i:s')?></b><small id="liveDate"></small></div><a class="logout" href="settings.php">⚙ ตั้งค่าระบบ</a></div></header>
<?php if(!$closeToday && date('H')<6):?><div class="warning-card">⚠ คืนนี้ยังไม่มี Daily Close — หลังจบงานสามารถปิดรอบได้ที่ Night Operations</div><?php endif;?>
<div class="ds-view-switch" aria-label="มุมมอง Dashboard"><button type="button" data-dash-view="all" aria-pressed="true">ภาพรวม</button><?php if($canSales):?><button type="button" data-dash-view="sales" aria-pressed="false">ยอดขาย POS</button><?php endif;?><button type="button" data-dash-view="ops" aria-pressed="false">งานวันนี้</button></div>
<?php if($canSales): $sb=$sales['batch']; ?>
<section data-dash-section="sales" class="ds-section" id="salesOverview" aria-label="ยอดขายจาก POS">
  <div class="ds-title"><div><h2>ยอดขายร้าน</h2><p><?=h((string)($d['settings']['shop_name']??'MR BAR'))?> · ข้อมูลจากไฟล์ POS ที่ Process แล้ว</p></div><div class="ds-source" aria-label="แหล่งยอดขาย"><a href="?sales_source=bills#salesOverview" <?=($sales['source']==='bills'?'aria-current="page"':'')?>>รายละเอียดบิล / ค่าคอม</a><a href="?sales_source=menu#salesOverview" <?=($sales['source']==='menu'?'aria-current="page"':'')?>>ยอดขายเมนู / ค่าดื่ม</a></div></div>
  <form class="ds-controls" method="get" action="admin.php#salesOverview"><input type="hidden" name="sales_source" value="<?=h($sales['source'])?>"><label>รอบข้อมูล<select name="sales_batch" <?=!$sales['batches']?'disabled':''?>><?php if(!$sales['batches']):?><option>ยังไม่มีไฟล์ที่ Process แล้ว</option><?php endif;?><?php foreach($sales['batches'] as $batch):?><option value="<?=(int)$batch['id']?>" <?=$sb&&(int)$sb['id']===(int)$batch['id']?'selected':''?>>#<?=(int)$batch['id']?> · <?=h($batch['period_start'].' ถึง '.$batch['period_end'].' · '.($batch['filename']??$batch['source_name']??'POS'))?></option><?php endforeach;?></select></label><button type="submit" <?=!$sales['batches']?'disabled':''?>>ดูรอบนี้</button><a href="admin.php?<?=h(http_build_query(['sales_source'=>$sales['source'],'sales_batch'=>$sb['id']??0]))?>#salesOverview">รีเฟรช</a><a href="pos-reports.php">รายงานทั้งหมด →</a></form>
  <?php if($sales['total']===null):?><div class="ds-empty"><?=($sb?'ไม่พบรายการยอดขายที่ใช้งานในรอบนี้':'ยังไม่มีข้อมูลยอดขายจากแหล่งนี้')?></div>
  <?php else:?>
  <div class="ds-metrics"><div><small>ยอดขายสุทธิในไฟล์</small><strong data-countup="<?=h((string)$sales['total'])?>"><?=number_format($sales['total'],2)?></strong><span>บาท · <?=h($sb['period_start'].' ถึง '.$sb['period_end'])?></span></div><div><small><?=$sales['source']==='bills'?'จำนวนบิล':'จำนวนรายการเมนู'?></small><strong><?=number_format($sales['count'])?></strong><span><?=$sales['source']==='bills'?'บิล':'แถวข้อมูล'?></span></div><div><small><?=$sales['source']==='bills'?'ยอดเฉลี่ยต่อบิล':'จำนวนหน่วยขาย'?></small><strong><?=number_format($sales['source']==='bills'?$sales['average']:$sales['qty'],2)?></strong><span><?=$sales['source']==='bills'?'บาท / บิล':'หน่วยตามไฟล์'?></span></div></div>
  <div class="ds-layout"><div><h3><?=$sales['summary']?'ยอดขายรวมตามเมนู':'ยอดขายตามวันที่ในไฟล์'?></h3>
  <?php if($sales['summary']):?><div class="ds-empty">ไฟล์นี้เป็นยอดรวมช่วงวันที่<br><?=h($sb['period_start'].' ถึง '.$sb['period_end'])?></div><?php elseif($sales['series']): $points=array_slice($sales['series'],-31);$maxSales=max(1,...array_map(static fn($p)=>abs($p['value']),$points));?><div class="ds-chart"><?php foreach($points as $point):$pointLabel=$point['label'].' · '.number_format($point['value'],2).' บาท';?><div class="ds-bar"><button type="button" data-sales-point aria-label="<?=h($pointLabel)?>" title="<?=h($pointLabel)?>" style="--height:<?=max(1,round(abs($point['value'])/$maxSales*80))?>%;<?=$point['value']<0?'background:#e99b66':''?>"></button><small><?=h(substr($point['label'],8,2).'/'.substr($point['label'],5,2))?></small></div><?php endforeach;?></div><p class="ds-readout" id="salesReadout" aria-live="polite"><?=h($points[count($points)-1]['label'])?> · <?=number_format($points[count($points)-1]['value'],2)?> บาท</p><p class="ds-note">สูงสุด 31 วันที่มีข้อมูล · วันที่จากไฟล์ หรือวันสิ้นรอบที่ระบบนำเข้ากำหนด · สีส้มคือยอดติดลบ</p><?php else:?><div class="ds-empty">ไม่มีวันที่สำหรับกราฟ</div><?php endif;?></div>
  <div><h3><?=$sales['source']==='menu'?'เมนูขายดี':'รอบนำเข้าล่าสุด'?></h3><div class="ds-list"><?php if($sales['source']==='menu'):foreach($sales['items'] as $item):?><div><span><b><?=h($item['name'])?></b><small><?=number_format($item['qty'],2)?> หน่วย</small></span><strong><?=number_format($item['amount'],2)?></strong></div><?php endforeach;else:foreach(array_slice($sales['batches'],0,5) as $batch):?><div><span><b><?=h($batch['period_start'].' ถึง '.$batch['period_end'])?></b><small>#<?=(int)$batch['id']?> · <?=h((string)($batch['filename']??'POS'))?></small></span><strong><?=isset($batch['total_sales'])?number_format((float)$batch['total_sales'],2):'—'?></strong></div><?php endforeach;endif;?></div></div></div>
  <?php endif;?>
  <p class="ds-note">แสดงครั้งละหนึ่งรอบไฟล์ ไม่รวมบิลกับเมนูซ้ำกัน · ไม่ใช่ยอดสดจาก POS · ไม่ใช่ค่าคอม/ค่าดื่มที่ต้องจ่าย<?php if($sb):?> · นำเข้า <?=h((string)($sb['imported_at']??'ไม่ระบุเวลา'))?><?php endif;?></p>
  <?php if($sales['undated']):?><p class="ds-note ds-warning">รายการไม่ระบุวันที่ <?=number_format($sales['undated'])?> รายการ รวมในยอดแต่ไม่อยู่ในกราฟ</p><?php endif;?>
  <?php if($sales['difference']!==null&&abs($sales['difference'])>.01):?><p class="ds-note ds-warning">ยอดรายการต่างจากยอดบันทึกตอนนำเข้า <?=number_format($sales['difference'],2)?> บาท กรุณาตรวจรายงานต้นทาง</p><?php endif;?>
</section>
<?php endif;?>
<section data-dash-section="ops" class="kpis"><article class="kpi pink"><span>Check-in วันนี้</span><b><?=count($todayRows)?></b><small>จบแล้ว <?=count($completed)?> · <?=h((string)$completionRate)?>%</small><i>⌁</i></article><article class="kpi blue"><span>โต๊ะใช้งาน</span><b><?=$occupied?></b><small>จาก <?=count($d['tables']??[])?> โต๊ะ</small><i>▦</i></article><article class="kpi green"><span>PR ออนไลน์</span><b><?=$onlinePr?></b><small>กำลังทำงาน <?=$busyPr?> คน · เข้าเวร <?=$openAttendance?></small><i>♛</i></article><article class="kpi gold"><span>งานรอดำเนินการ</span><b><?=count($pending)+count($serviceCalls)?></b><small>คิว <?=count($pending)?> · Call <?=count($serviceCalls)?></small><i>⚡</i></article></section>
<section data-dash-section="ops" class="dash-grid"><article class="panel"><div class="panel-head"><div><span class="step">7D</span><h2>แนวโน้ม Check-in</h2><p>จำนวนลูกค้า 7 วันล่าสุด</p></div></div><div class="chartbox"><?php $mx=max(1,...array_column($trend,'value'));foreach($trend as $x):?><div class="barcol"><i style="height:<?=max(4,round($x['value']/$mx*100))?>%"></i><b><?=$x['value']?></b><small><?=h($x['label'])?></small></div><?php endforeach;?></div></article>
<article class="panel"><div class="panel-head"><div><span class="step">T</span><h2>การใช้งานโต๊ะ</h2><p>สถานะโต๊ะรวมแบบรวดเร็ว</p></div></div><div class="donut" style="--occ:<?=round($occupied/$totalTables*100)?>%"><strong><?=round($occupied/$totalTables*100)?>%</strong></div><div class="status-legend"><div><span>● ใช้งาน</span><b><?=$occupied?></b></div><div><span>● ว่าง</span><b><?=$available?></b></div><div><span>● ปิดใช้</span><b><?=$blocked?></b></div></div></article>
<article class="panel"><div class="panel-head"><div><span class="step">!</span><h2>สถานะที่ต้องสนใจ</h2><p>สิ่งที่ควรเห็นทันที</p></div></div><div class="quick"><a href="night-ops.php">予約 จองวันนี้ <b><?=count($todayReservations)?></b> · Waitlist <?=$waitlist?></a><a href="dashboard.php">⌁ คิวหน้าร้าน <b><?=count($active)?></b></a><a href="dashboard.php#alerts">◉ Notification ยังไม่อ่าน <b><?=$unread?></b></a><a href="night-ops.php">☎ Service Call รอรับ <b><?=count($serviceCalls)?></b></a><a href="workforce-exceptions.php">⚠ Attendance Exception <b><?=$attendanceExceptions+$pendingCorrections?></b> · คนมาแทน <?=$pendingSubstitute?></a></div></article></section>
<section data-dash-section="ops" class="dash-grid" style="margin-top:18px"><article class="panel"><div class="panel-head"><div><span class="step">▦</span><h2>สถานะโต๊ะ</h2><p>ดูภาพรวมโดยไม่ต้องเข้าโหมดแก้ไข</p></div><a class="ghost" href="admin-manage.php#tables">จัดการโต๊ะ →</a></div><div class="table-mini"><?php foreach($d['tables']??[] as $t):?><div class="<?=h((string)$t['status'])?>"><b><?=h((string)$t['code'])?></b><small><?=h((string)$t['status'])?></small></div><?php endforeach;?></div></article>
<article class="panel"><div class="panel-head"><div><span class="step">♛</span><h2>PR Performance วันนี้</h2><p>เรียงตามงานที่ปิดสำเร็จ</p></div><a class="ghost" href="employees.php?position=pr">จัดการ PR →</a></div><?php if(!$perf):?><div class="empty">ยังไม่มีข้อมูล PR วันนี้</div><?php endif;?><?php foreach(array_slice($perf,0,7) as $p):?><div class="perf-row"><div><b><?=h($p['code'].' · '.$p['name'])?></b><small><?=h((string)$p['status'])?></small></div><strong><?=$p['jobs']?> งาน</strong></div><?php endforeach;?></article>
<article class="panel"><div class="panel-head"><div><span class="step">◉</span><h2>แจ้งเตือนล่าสุด</h2><p>เหตุการณ์สำคัญของระบบ</p></div><a class="ghost" href="dashboard.php#alerts">ดูการแจ้งเตือน →</a></div><?php foreach($recent as $n):?><div class="perf-row"><div><b><?=h((string)($n['message']??'-'))?></b><small><?=h(date('d/m H:i',strtotime((string)($n['created_at']??'now'))))?></small></div><span class="badge2"><?=h((string)($n['role']??'-'))?></span></div><?php endforeach;?></article></section>
<section data-dash-section="ops" class="panel wide"><div class="panel-head"><div><span class="step">⌁</span><h2>คิวงานปัจจุบัน</h2><p>รายการที่ยังไม่จบ — Dashboard แสดงผลเท่านั้น</p></div><a class="ghost" href="dashboard.php">เปิด Staff Operations →</a></div><?php if(!$active):?><div class="empty">ไม่มีงานค้างในขณะนี้</div><?php endif;?><?php foreach(array_slice($active,0,10) as $c):?><div class="queue-row"><b><?=h((string)($c['ticket']??'-'))?></b><div><?=h((string)($c['guest_name']??'ลูกค้า'))?> · โต๊ะ <?=h(dash_table_name($d,(int)($c['table_id']??0)))?></div><span class="badge2"><?=h(op_status_label((string)($c['status']??'')))?></span></div><?php endforeach;?></section>
<footer>MR BAR Admin Dashboard · Update Pack v<?=$version?> · Dashboard แยกจาก Settings/Management แล้ว</footer></main><script src="assets/admin.js?v=1140"></script><script src="assets/dashboard-v14921.js?v=14921"></script></body></html>
