<?php
require __DIR__.'/app/bootstrap.php';require_once __DIR__.'/app/compat.php';$u=require_any_permission(['reports.view','shifts.view','notifications.view','tables.view']);$msg='';$err='';
if($_SERVER['REQUEST_METHOD']==='POST'){csrf_check();$a=(string)($_POST['action']??'');try{
 if($a==='shift'){ if(!user_can($u,'shifts.manage'))throw new RuntimeException('ไม่มี Permission: shifts.manage'); $pr=(int)$_POST['pr_id'];$date=(string)$_POST['date'];$start=(string)$_POST['start'];$end=(string)$_POST['end']; if(!$pr||!$date||!$start||!$end)throw new RuntimeException('กรอกข้อมูลกะให้ครบ'); db_mutate(function($d)use($pr,$date,$start,$end,$u){$d['shifts'][]=['id'=>next_id($d['shifts']),'pr_id'=>$pr,'date'=>$date,'start'=>$start,'end'=>$end,'status'=>'scheduled','created_at'=>date('c')];$d['audit'][]=['at'=>date('c'),'action'=>'shift_created','pr_id'=>$pr,'by'=>$u['id']];return $d;});$msg='เพิ่มกะ PR แล้ว'; }
 elseif($a==='read_all'){if(!user_can($u,'notifications.manage'))throw new RuntimeException('ไม่มี Permission: notifications.manage');db_mutate(function($d){foreach($d['notifications'] as &$n)$n['read_at']=$n['read_at']?:date('c');unset($n);return $d;});$msg='ทำเครื่องหมายแจ้งเตือนทั้งหมดแล้ว';}
}catch(Throwable $e){$err=$e->getMessage();}}
$d=db_load();$today=date('Y-m-d');$todayC=array_values(array_filter($d['checkins'],fn($c)=>str_starts_with((string)($c['created_at']??''),$today)));$completed=array_values(array_filter($todayC,fn($c)=>($c['status']??'')==='completed'));$active=array_values(array_filter($todayC,fn($c)=>!in_array(($c['status']??''),['completed','cancelled'],true)));$shifts=$d['shifts'];usort($shifts,fn($a,$b)=>strcmp(($b['date']??'').($b['start']??''),($a['date']??'').($a['start']??'')));
function prn($d,$id){foreach($d['prs'] as $p)if((int)$p['id']===(int)$id)return $p['name'];return '-';}
$base=(isset($_SERVER['HTTPS'])&&$_SERVER['HTTPS']!=='off'?'https':'http').'://'.($_SERVER['HTTP_HOST']??'localhost').rtrim(dirname($_SERVER['SCRIPT_NAME']??'/it/admin-tools.php'),'/');
?><!doctype html><html lang="th"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>MR BAR — Tools</title><link rel="stylesheet" href="assets/admin.css?v=1140"><style>.toolgrid{display:grid;grid-template-columns:1.1fr 1fr;gap:18px}.qrgrid{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:14px}.qrcard{text-align:center;padding:18px;border:1px solid #7c3cff55;border-radius:20px;background:#ffffff06}.qrcard img{width:150px;height:150px;background:white;padding:7px;border-radius:12px}.bigform{display:grid;grid-template-columns:2fr 1.4fr 1fr 1fr auto;gap:10px}.reportnum{font-size:42px;font-weight:900}.shift{display:flex;justify-content:space-between;padding:13px;border-bottom:1px solid #ffffff12}@media(max-width:850px){.toolgrid{grid-template-columns:1fr}.bigform{grid-template-columns:1fr}}</style><link rel="stylesheet" href="assets/admin-v14.css?v=1140"></head><body class="admin-v14-page"><?php require_once __DIR__.'/app/admin-nav.php'; echo admin_sidebar('tools',$u); ?><main style="max-width:1500px;margin:auto;padding:28px"><header class="topbar"><div><p class="eyebrow">ADMIN / OPERATIONS TOOLS</p><h1>เครื่องมือร้าน • QR • กะงาน • รายงาน</h1><p>เมนูเสริม v1.14.0 สำหรับงานประจำวัน</p></div><div style="display:flex;gap:8px"><a class="ghost" href="night-ops.php">Night Ops →</a><a class="ghost" href="admin.php">← Admin Control</a></div></header><?php if($msg):?><div class="notice ok">✓ <?=h($msg)?></div><?php endif;?><?php if($err):?><div class="notice err">⚠ <?=h($err)?></div><?php endif;?>
<section class="kpis"><article class="kpi pink"><span>Check-in วันนี้</span><b><?=count($todayC)?></b><small>รายการ</small></article><article class="kpi green"><span>จบงานวันนี้</span><b><?=count($completed)?></b><small>รายการ</small></article><article class="kpi blue"><span>กำลังดำเนินการ</span><b><?=count($active)?></b><small>รายการ</small></article><article class="kpi gold"><span>กะที่จัดไว้</span><b><?=count($shifts)?></b><small>กะ</small></article></section>
<section class="panel wide"><div class="panel-head"><div><span class="step">1</span><h2>QR ประจำโต๊ะ</h2><p>พิมพ์ QR แล้วติดโต๊ะ ลูกค้าสแกนเพื่อเปิด Check-in พร้อมเลขโต๊ะ</p></div><button class="ghost" onclick="print()">พิมพ์หน้านี้</button></div><div class="qrgrid"><?php foreach($d['tables'] as $t):$url=$base.'/custumers/?table='.urlencode((string)$t['code']);?><div class="qrcard"><b style="font-size:28px"><?=h($t['code'])?></b><p><?=h($t['zone']??'Main')?></p><img loading="lazy" src="https://api.qrserver.com/v1/create-qr-code/?size=180x180&data=<?=urlencode($url)?>" alt="QR <?=h($t['code'])?>"><small style="display:block;word-break:break-all"><?=h($url)?></small></div><?php endforeach;?></div></section>
<div class="toolgrid"><section class="panel"><div class="panel-head"><div><span class="step">2</span><h2>จัดกะ PR</h2><p>กำหนดวันและเวลาเข้าเวร</p></div></div><form method="post" class="bigform"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><input type="hidden" name="action" value="shift"><select name="pr_id" required><option value="">เลือก PR</option><?php foreach($d['prs'] as $p):?><option value="<?=$p['id']?>"><?=h($p['code'].' · '.$p['name'])?></option><?php endforeach;?></select><input type="date" name="date" value="<?=$today?>" required><input type="time" name="start" value="18:00" required><input type="time" name="end" value="02:00" required><button class="mini primary">เพิ่มกะ</button></form><div><?php foreach(array_slice($shifts,0,12) as $s):?><div class="shift"><b><?=h(prn($d,$s['pr_id']))?></b><span><?=h($s['date'].' · '.$s['start'].'–'.$s['end'])?></span></div><?php endforeach;?></div></section>
<section class="panel"><div class="panel-head"><div><span class="step">3</span><h2>Notification Center</h2><p>การแจ้งเตือนล่าสุดทุก Role</p></div><form method="post"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><input type="hidden" name="action" value="read_all"><button class="mini secondary">อ่านทั้งหมด</button></form></div><div class="audit-list"><?php foreach(array_slice(array_reverse($d['notifications']),0,20) as $n):?><div><span>◉</span><b><?=h($n['message']??'-')?></b><small><?=h(strtoupper($n['role']??'').' · '.date('d/m H:i',strtotime($n['created_at']??'now')))?></small></div><?php endforeach;?></div></section></div>
<section class="panel wide"><div class="panel-head"><div><span class="step">4</span><h2>รายงานวันนี้</h2><p>ภาพรวม Operations สำหรับผู้ดูแลร้าน</p></div></div><div class="kpis"><article class="kpi pink"><span>อัตราจบงาน</span><b class="reportnum"><?=count($todayC)?round(count($completed)/count($todayC)*100):0?>%</b></article><article class="kpi blue"><span>PR Online</span><b class="reportnum"><?=count(array_filter($d['prs'],fn($p)=>($p['status']??'')==='online'))?></b></article><article class="kpi green"><span>โต๊ะว่าง</span><b class="reportnum"><?=count(array_filter($d['tables'],fn($t)=>($t['status']??'')==='available'))?></b></article></div></section>
<footer>MR BAR Operations Tools · Update Pack v1.14.0</footer></main></body></html>
