<?php
require __DIR__.'/app/bootstrap.php';
$u=require_any_permission(['attendance.view','attendance.manage','workforce.view','payroll.view']);$d=db_load();
function ac_branch(array $d,$id): string {foreach($d['branches']??[] as $b)if((int)($b['id']??0)===(int)$id)return (string)($b['code']??'').' · '.(string)($b['name']??'');return 'ไม่ระบุสาขา';}
function ac_employee(array $d,$id): array {foreach($d['employees']??[] as $e)if((int)($e['id']??0)===(int)$id)return $e;return ['id'=>(int)$id,'code'=>'EMP#'.$id,'name'=>'ไม่พบ Employee','position'=>'other'];}
function ac_hm($value): string {if(!$value)return '—';$ts=strtotime((string)$value);return $ts?date('H:i:s',$ts):'—';}
$employeeId=(int)($_GET['employee_id']??0);$branchId=(int)($_GET['branch_id']??0);$position=(string)($_GET['position']??'');$from=(string)($_GET['from']??date('Y-m-01'));$to=(string)($_GET['to']??date('Y-m-d'));
if(!preg_match('/^\d{4}-\d{2}-\d{2}$/',$from))$from=date('Y-m-01');if(!preg_match('/^\d{4}-\d{2}-\d{2}$/',$to))$to=date('Y-m-d');if($from>$to){$t=$from;$from=$to;$to=$t;}
$rows=[];foreach($d['attendance']??[] as $a){if(empty($a['check_in']))continue;$dt=substr((string)$a['check_in'],0,10);if($dt<$from||$dt>$to)continue;$eid=(int)($a['employee_id']??0);if($employeeId&&$eid!==$employeeId)continue;if($branchId&&(int)($a['branch_id']??0)!==$branchId)continue;$emp=ac_employee($d,$eid);if($position!==''&&(string)($emp['position']??'')!==$position)continue;$a['_employee']=$emp;$rows[]=$a;}
usort($rows,function($a,$b){return strcmp((string)($b['check_in']??''),(string)($a['check_in']??''));});
$employees=array_values(array_filter($d['employees']??[],function($e){return !empty($e['active']);}));usort($employees,function($a,$b){return strcmp((string)$a['code'],(string)$b['code']);});
$positions=[];foreach($employees as $e){$p=(string)($e['position']??'staff');$positions[$p]=workforce_position_label($p);}asort($positions);
$total=count($rows);$withIn=count(array_filter($rows,function($a){return !empty($a['checkin_evidence']);}));$withOut=count(array_filter($rows,function($a){return !empty($a['checkout_evidence']);}));$open=count(array_filter($rows,function($a){return empty($a['check_out']);}));
?><!doctype html><html lang="th"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>MR BAR — Workforce Attendance Evidence</title><link rel="stylesheet" href="assets/admin.css?v=1180"><link rel="stylesheet" href="assets/admin-v14.css?v=1180"><style>
.evidence-shell{max-width:1480px;margin:0 auto;padding:28px}.evidence-hero{display:flex;justify-content:space-between;gap:20px;align-items:flex-end;margin-bottom:20px}.evidence-hero h1{font-size:clamp(28px,3vw,48px);margin:4px 0}.evidence-hero p{max-width:760px}.filter-card,.evidence-card,.evidence-kpi{border:1px solid var(--line,#ffffff1a);background:var(--card,#0e1222);border-radius:22px;box-shadow:0 18px 60px #00000018}.filter-card{padding:18px;margin-bottom:18px}.filters{display:grid;grid-template-columns:2fr 1.2fr 1.2fr 1fr 1fr auto;gap:12px;align-items:end}.filters label{display:grid;gap:6px;font-size:12px;font-weight:800}.filters select,.filters input{min-height:44px;border-radius:12px;border:1px solid #7a86a533;padding:0 12px;background:var(--input,#0a0e19);color:inherit}.filter-btn{min-height:44px;border:0;border-radius:12px;padding:0 22px;font-weight:900;color:#fff;background:linear-gradient(100deg,#9638ff,#2f7dff)}.kpi-row{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin-bottom:18px}.evidence-kpi{padding:18px}.evidence-kpi small{opacity:.65}.evidence-kpi b{display:block;font-size:30px;margin-top:5px}.report{display:grid;gap:12px}.evidence-card{display:grid;grid-template-columns:minmax(170px,1.1fr) minmax(200px,1.2fr) minmax(200px,1.2fr) 220px;gap:14px;align-items:center;padding:16px}.person b{font-size:17px}.person span,.time-col span{display:block;opacity:.65;font-size:12px;margin-top:4px}.time-col strong{font-size:18px}.shots{display:flex;gap:9px;justify-content:flex-end}.shot{display:block;width:100px;height:76px;border-radius:14px;overflow:hidden;border:1px solid #8792b033;background:#090d18;position:relative}.shot img{width:100%;height:100%;object-fit:cover}.shot em{position:absolute;left:6px;bottom:6px;padding:3px 6px;border-radius:7px;background:#050713c9;color:#fff;font-size:9px;font-style:normal}.no-shot{width:100px;height:76px;border:1px dashed #8792b044;border-radius:14px;display:grid;place-items:center;font-size:10px;opacity:.5}.empty-report{text-align:center;padding:60px 20px;border:1px dashed #8792b044;border-radius:24px;opacity:.7}.status-open{color:#52e6aa}.status-done{color:#7eb7ff}@media(max-width:1000px){.filters{grid-template-columns:1fr 1fr}.filter-btn{grid-column:1/-1}.kpi-row{grid-template-columns:1fr 1fr}.evidence-card{grid-template-columns:1fr 1fr}.shots{justify-content:flex-start}}@media(max-width:620px){.evidence-shell{padding:16px}.evidence-hero{display:block}.filters,.kpi-row,.evidence-card{grid-template-columns:1fr}.shots{justify-content:flex-start}}
</style></head><body class="admin-v14-page"><div class="ambient"><i></i><i></i><i></i></div><?php require_once __DIR__.'/app/admin-nav.php';echo admin_sidebar('payroll',$u);?><main class="evidence-shell"><header class="evidence-hero"><div><p class="eyebrow">WORKFORCE / ATTENDANCE / EVIDENCE</p><h1>หลักฐานการลงเวลาพนักงาน</h1><p>ตรวจเวลา GPS สาขา และรูป Check-In / Check-Out ของ Employee ทุกประเภท — PR, Staff, Manager, Office และพนักงานชั่วคราว</p></div><div><a class="logout" href="employees.php">Employees →</a></div></header>
<section class="filter-card"><form method="get" class="filters"><label>Employee<select name="employee_id"><option value="0">พนักงานทั้งหมด</option><?php foreach($employees as $e):?><option value="<?=(int)$e['id']?>" <?=$employeeId===(int)$e['id']?'selected':''?>><?=h(workforce_employee_label($e).' · '.workforce_position_label((string)$e['position']))?></option><?php endforeach;?></select></label><label>ตำแหน่ง<select name="position"><option value="">ทุกตำแหน่ง</option><?php foreach($positions as $k=>$v):?><option value="<?=h($k)?>" <?=$position===$k?'selected':''?>><?=h($v)?></option><?php endforeach;?></select></label><label>สาขา<select name="branch_id"><option value="0">ทุกสาขา</option><?php foreach($d['branches']??[] as $b):?><option value="<?=(int)$b['id']?>" <?=$branchId===(int)$b['id']?'selected':''?>><?=h((string)$b['code'].' · '.(string)$b['name'])?></option><?php endforeach;?></select></label><label>จาก<input type="date" name="from" value="<?=h($from)?>"></label><label>ถึง<input type="date" name="to" value="<?=h($to)?>"></label><button class="filter-btn">แสดงรายงาน</button></form></section>
<section class="kpi-row"><article class="evidence-kpi"><small>รายการลงเวลา</small><b><?=$total?></b></article><article class="evidence-kpi"><small>มีรูป Check-In</small><b><?=$withIn?></b></article><article class="evidence-kpi"><small>มีรูป Check-Out</small><b><?=$withOut?></b></article><article class="evidence-kpi"><small>กำลังทำงาน</small><b><?=$open?></b></article></section>
<section class="report"><?php if(!$rows):?><div class="empty-report"><b>ไม่พบข้อมูลในช่วงที่เลือก</b><p>ลองเปลี่ยน Employee / สาขา / วันที่</p></div><?php endif;?><?php foreach(array_slice($rows,0,300) as $a):$e=$a['_employee'];?><article class="evidence-card"><div class="person"><b><?=h(workforce_employee_label($e))?></b><span><?=h(workforce_position_label((string)($e['position']??'other')))?> · <?=h(substr((string)$a['check_in'],0,10))?></span><span class="<?=empty($a['check_out'])?'status-open':'status-done'?>"><?=empty($a['check_out'])?'● กำลังทำงาน':'✓ ปิดเวลาแล้ว'?></span></div><div class="time-col"><strong>IN <?=h(ac_hm($a['check_in']??null))?></strong><span><?=h(ac_branch($d,$a['branch_id']??0))?></span><span>GPS <?=isset($a['checkin_distance_m'])?round((float)$a['checkin_distance_m']).'m':'—'?> · ±<?=isset($a['checkin_accuracy_m'])?round((float)$a['checkin_accuracy_m']).'m':'—'?></span></div><div class="time-col"><strong>OUT <?=h(ac_hm($a['check_out']??null))?></strong><span><?=h(ac_branch($d,$a['branch_id']??0))?></span><span>GPS <?=isset($a['checkout_distance_m'])?round((float)$a['checkout_distance_m']).'m':'—'?> · ±<?=isset($a['checkout_accuracy_m'])?round((float)$a['checkout_accuracy_m']).'m':'—'?></span></div><div class="shots"><?php if(!empty($a['checkin_evidence'])):?><a class="shot" href="attendance-evidence.php?id=<?=(int)$a['id']?>&type=in" target="_blank"><img src="attendance-evidence.php?id=<?=(int)$a['id']?>&type=in" alt="Check-in"><em>CHECK-IN</em></a><?php else:?><div class="no-shot">NO IN PHOTO</div><?php endif;?><?php if(!empty($a['checkout_evidence'])):?><a class="shot" href="attendance-evidence.php?id=<?=(int)$a['id']?>&type=out" target="_blank"><img src="attendance-evidence.php?id=<?=(int)$a['id']?>&type=out" alt="Check-out"><em>CHECK-OUT</em></a><?php else:?><div class="no-shot">NO OUT PHOTO</div><?php endif;?></div></article><?php endforeach;?></section><footer style="padding:26px 0;opacity:.55">MR BAR Workforce Attendance · v1.18.0 · Schema v<?=h((string)($d['meta']['schema']??18))?></footer></main></body></html>
