<?php
header('Cache-Control: no-store, no-cache, must-revalidate, max-age=0');
header('Pragma: no-cache');
header('X-Robots-Tag: noindex, nofollow, noarchive');
header('Referrer-Policy: no-referrer');
require __DIR__.'/app/bootstrap.php';
require_once __DIR__.'/app/account-onboarding.php';
$token=trim((string)($_POST['token']??$_GET['token']??''));$d=db_load();$invite=account_find_invite($d,$token);$employee=$invite?workforce_employee_by_id($d,(int)($invite['employee_id']??0)):null;$err='';$valid=$invite&&account_invite_is_valid($invite)&&$employee&&!empty($employee['active'])&&empty($employee['user_id']);
if($_SERVER['REQUEST_METHOD']==='POST'){
    csrf_check();
    try{
        if(!$valid)throw new RuntimeException('Invite Link นี้หมดอายุ ถูกใช้แล้ว หรือไม่พร้อมใช้งาน กรุณาขอลิงก์ใหม่จาก Admin');
        $username=trim((string)($_POST['username']??''));$pw=(string)($_POST['password']??'');$confirm=(string)($_POST['password_confirm']??'');if($pw!==$confirm)throw new RuntimeException('ยืนยัน Password ไม่ตรงกัน');
        $hash=account_invite_hash($token);$inviteId=(int)($invite['id']??0);$employeeId=(int)$employee['id'];$createdUser=null;
        db_mutate(function($x)use($hash,$inviteId,$employeeId,$username,$pw,&$createdUser){
            $idx=null;foreach($x['account_invites']??[] as $i=>$row)if((int)($row['id']??0)===$inviteId&&hash_equals((string)($row['token_hash']??''),$hash)){$idx=$i;break;}if($idx===null||!account_invite_is_valid($x['account_invites'][$idx]))throw new RuntimeException('Invite Link ไม่พร้อมใช้งานแล้ว');
            $createdUser=account_create_and_link($x,$employeeId,$username,$pw);$x['account_invites'][$idx]['used_at']=date('c');$x['account_invites'][$idx]['used_by_user_id']=(int)$createdUser['id'];
            foreach($x['account_invites'] as $i=>&$other)if($i!==$idx&&(int)($other['employee_id']??0)===$employeeId&&account_invite_is_valid($other))$other['revoked_at']=date('c');unset($other);
            $x['audit'][]=['at'=>date('c'),'action'=>'employee_self_account_activated','employee_id'=>$employeeId,'user_id'=>(int)$createdUser['id'],'invite_id'=>$inviteId,'role'=>(string)$createdUser['role']];return $x;
        });
        if(!$createdUser)throw new RuntimeException('สร้างบัญชีไม่สำเร็จ');establish_session($createdUser);$_SESSION['needs_pin_setup']=1;header('Location:setup-pin.php?return_to=time');exit;
    }catch(Throwable $e){$err=$e->getMessage();$d=db_load();$invite=account_find_invite($d,$token);$employee=$invite?workforce_employee_by_id($d,(int)($invite['employee_id']??0)):null;$valid=$invite&&account_invite_is_valid($invite)&&$employee&&!empty($employee['active'])&&empty($employee['user_id']);}
}
$role=$employee?account_employee_role($employee):'';$expires=$invite&&!empty($invite['expires_at'])?date('d/m/Y H:i',strtotime((string)$invite['expires_at'])):'';
?><!doctype html><html lang="th"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover,interactive-widget=resizes-content"><meta name="theme-color" content="#080713"><title>MR BAR — เปิดใช้งานบัญชีพนักงาน</title><style>
*{box-sizing:border-box}body{margin:0;min-height:100vh;background:radial-gradient(circle at 10% 15%,#6b1b9c44,transparent 36%),radial-gradient(circle at 90% 80%,#0877a744,transparent 38%),#070711;color:#f7f5fb;font-family:MRBAR Thai,Noto Sans Thai,Tahoma,sans-serif;display:grid;place-items:center;padding:24px}.card{width:min(100%,520px);border:1px solid #ffffff18;border-radius:28px;background:#11111cea;box-shadow:0 30px 90px #0009;padding:28px}.brand{font-size:11px;letter-spacing:.22em;color:#9a92ac;font-weight:900}.card h1{font-size:31px;margin:9px 0 8px}.intro{color:#aaa4b7;line-height:1.7;margin:0 0 20px}.employee{padding:16px;border:1px solid #ffffff12;border-radius:18px;background:#ffffff05;margin:18px 0}.employee small,.employee span{display:block;color:#9790a4}.employee b{display:block;font-size:21px;margin:4px 0}.badge{display:inline-flex!important;margin-top:9px;padding:5px 9px;border-radius:999px;background:#7344ff22;border:1px solid #8f63ff55;color:#d6c8ff!important;font-size:10px;font-weight:900}.notice{padding:13px 14px;border-radius:14px;margin:14px 0;font-size:12px}.error{background:#ff456814;border:1px solid #ff456840;color:#ffb0c1}.expired{background:#ffad3312;border:1px solid #ffad3338;color:#ffd495}.field{display:grid;gap:7px;margin:13px 0}.field label{font-size:11px;color:#aaa5b7;font-weight:800}.field input{height:52px;border-radius:14px;border:1px solid #ffffff17;background:#080910;color:#fff;padding:0 14px;font:inherit;outline:none}.field input:focus{border-color:#6dafff88;box-shadow:0 0 0 4px #377fff14}.hint{font-size:10px;color:#777283}.submit{width:100%;height:55px;border:0;border-radius:14px;background:linear-gradient(100deg,#7b37ed,#2384ee);color:#fff;font:inherit;font-weight:950;margin-top:8px}.secure{margin-top:16px;color:#787284;font-size:10px;line-height:1.6}.login{display:block;text-align:center;margin-top:20px;color:#aaa3bb;text-decoration:none;font-size:11px}
</style><link rel="stylesheet" href="assets/staff-auth-v12721.css?v=12721"></head><body class="staff-activate-page"><main class="card"><div class="brand">MR BAR · EMPLOYEE ACCOUNT</div><h1>ตั้งค่าบัญชีเข้าสู่ระบบ</h1><p class="intro">ลิงก์นี้ออกโดย Admin สำหรับพนักงานที่ระบุเท่านั้น หลังตั้ง Username/Password ระบบจะพาไปตั้ง PIN 6 หลักและเข้าสู่ MR BAR TIME</p><?php if($employee):?><section class="employee"><small>พนักงาน</small><b><?=h((string)$employee['code'])?> · <?=h((string)$employee['name'])?></b><span><?=h(workforce_position_label((string)$employee['position']))?></span><span class="badge">สิทธิ์บัญชี <?=h(strtoupper($role))?></span><?php if($expires):?><span style="margin-top:8px;font-size:10px">ลิงก์หมดอายุ <?=h($expires)?> น.</span><?php endif;?></section><?php endif;?><?php if($err):?><div class="notice error">⚠ <?=h($err)?></div><?php endif;?><?php if($valid):?><form method="post"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><input type="hidden" name="token" value="<?=h($token)?>"><div class="field"><label>USERNAME</label><input name="username" minlength="3" maxlength="40" pattern="[A-Za-z0-9._-]{3,40}" autocomplete="username" autocapitalize="none" spellcheck="false" inputmode="text" placeholder="เช่น somchai01" required><span class="hint">ใช้ A-Z, 0-9, จุด, ขีดกลาง หรือ _</span></div><div class="field"><label>PASSWORD</label><input type="password" name="password" minlength="8" autocomplete="new-password" required></div><div class="field"><label>ยืนยัน PASSWORD</label><input type="password" name="password_confirm" minlength="8" autocomplete="new-password" required></div><button class="submit">สร้างบัญชีและเข้า MR BAR TIME →</button></form><p class="secure">🔐 Password จะถูกเก็บแบบ Hash เท่านั้น · Invite ใช้ได้ครั้งเดียว · หลังสร้างบัญชีลิงก์นี้จะใช้ซ้ำไม่ได้</p><?php else:?><div class="notice expired">ลิงก์นี้ไม่พร้อมใช้งาน อาจหมดอายุ ถูกยกเลิก ถูกใช้ไปแล้ว หรือพนักงานมีบัญชีอยู่แล้ว กรุณาติดต่อ Admin เพื่อสร้าง Invite ใหม่</div><?php endif;?><a class="login" href="login.php?return_to=time&pwa=1">มีบัญชีแล้ว? เข้าสู่ระบบ MR BAR TIME</a></main><script src="assets/staff-auth-v12721.js?v=12721"></script></body></html>
