<?php
require __DIR__.'/app/bootstrap.php';require_once __DIR__.'/app/branches.php';
$portalCanonical=branch_public_base().'/Portal';$portalCurrent=(string)(parse_url((string)($_SERVER['REQUEST_URI']??''),PHP_URL_PATH)??'');if($portalCurrent!==$portalCanonical){header('Location: '.$portalCanonical,true,302);exit;}
$raw=db_load_global();$s=array_replace(db_portal_defaults(),$raw['portal_settings']??[]);$admin=!empty($_SESSION['user']['super_admin']);
if($s['enabled']!=='1'&&!$admin){http_response_code(503);}
$branches=array_values(array_filter($raw['branches']??[],function($b)use($s){if(empty($b['published']))return false;if(!empty($b['active']))return true;return $s['show_closed_branches']==='1';}));
usort($branches,fn($a,$b)=>[(int)empty($a['portal_featured']),(int)($a['sort_order']??100),(string)$a['name']]<=>[(int)empty($b['portal_featured']),(int)($b['sort_order']??100),(string)$b['name']]);
$portalStats=['branches'=>0,'tables'=>0,'prs'=>0];foreach($branches as $portalBranch){$portalData=$raw['branch_data'][(string)(int)$portalBranch['id']]??[];if(!empty($portalBranch['active']))$portalStats['branches']++;$portalStats['tables']+=count(array_filter($portalData['tables']??[],fn($table)=>!empty($table['active'])&&($table['status']??'')==='available'));$portalStats['prs']+=count(array_filter($portalData['prs']??[],fn($pr)=>!empty($pr['active'])&&in_array((string)($pr['status']??''),['online','busy','break'],true)));}
$portalNow=new DateTimeImmutable('now',new DateTimeZone('Asia/Bangkok'));
function portal_asset(string $path): string {$path=trim($path);if($path===''||stripos($path,'javascript:')===0)return '';if(preg_match('#^https?://#i',$path)||strpos($path,'//')===0||strpos($path,'/')===0)return $path;return branch_public_base().'/'.ltrim($path,'/');}
?><!doctype html><html lang="th"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="theme-color" content="#070b17"><title><?=h((string)$s['brand_name'])?> · เลือกร้าน</title><meta name="description" content="<?=h((string)$s['subtitle'])?>"><?php if($portalFavicon=portal_asset((string)($s['favicon']??''))):?><link rel="icon" href="<?=h($portalFavicon)?>"><?php endif;?><link rel="stylesheet" href="assets/portal-v1300.css?v=1300"><link rel="stylesheet" href="assets/portal-showcase-v1304.css?v=1304"><link rel="stylesheet" href="assets/portal-themes-v1307.css?v=1307"><link rel="stylesheet" href="assets/portal-featured-image-v1308.css?v=1308"><link rel="stylesheet" href="assets/portal-brand-hero-v1330.css?v=1330"><link rel="stylesheet" href="assets/portal-logo-hotfix-v1331.css?v=1331"><link rel="stylesheet" href="assets/portal-directory-v14855.css?v=14855"><link rel="stylesheet" href="assets/portal-visual-refresh-v14856.css?v=14856"><script src="assets/portal-showcase-v1304.js?v=1304" defer></script></head><body class="portal-body"><div class="portal-bg"<?php if($hero=portal_asset((string)$s['hero_image'])):?> style="--portal-hero:url('<?=h($hero)?>')"<?php endif;?>></div><div class="portal-noise"></div>
<?php $portalLogo=portal_asset((string)($s['logo']??''));?><header class="portal-head"><a href="<?=h(branch_public_base().'/Portal')?>" class="portal-brand<?=$portalLogo!==''?' has-logo':''?>"><?php if($portalLogo!==''):?><img class="portal-brand-logo" src="<?=h($portalLogo)?>" alt="<?=h((string)$s['brand_name'])?>" width="64" height="64" style="display:block!important;flex:0 0 64px!important;width:64px!important;height:64px!important;min-width:64px!important;max-width:64px!important;min-height:64px!important;max-height:64px!important;object-fit:contain!important;margin:0!important;padding:0!important;border:0!important;background:transparent!important;box-shadow:none!important"><?php else:?><i>✦</i><?php endif;?><span><b><?=h((string)$s['brand_name'])?></b><small>MULTI EXPERIENCE PORTAL</small></span></a><nav><?php if((string)$s['contact_url']!==''):?><a href="<?=h((string)$s['contact_url'])?>" target="_blank" rel="noopener"><?=h((string)$s['contact_label'])?> ↗</a><?php endif;?><?php if($admin):?><a href="portal-config.php">Config Portal</a><?php endif;?></nav></header>
<main class="portal-shell"><section class="portal-hero"><span><?=h((string)$s['eyebrow'])?></span><h1><?=h((string)$s['title'])?></h1><p><?=h((string)$s['subtitle'])?></p><div><b><?=count($branches)?></b><small>ร้านในเครือที่พร้อมต้อนรับคุณ</small></div></section>
<section class="portal-snapshot" aria-label="ข้อมูลสาขาในเครือ"><article class="portal-snapshot-date"><span class="portal-snapshot-mark" aria-hidden="true">◷</span><div><small>TONIGHT · BANGKOK TIME</small><time datetime="<?=$portalNow->format(DATE_ATOM)?>" data-portal-clock><?=h($portalNow->format('d/m/Y'))?> · <?=h($portalNow->format('H:i'))?></time></div></article><article><span class="portal-snapshot-mark" aria-hidden="true">⌖</span><div><small>BRANCHES READY</small><b><?=number_format($portalStats['branches'])?> <span>สาขาพร้อมต้อนรับ</span></b></div></article><article><span class="portal-snapshot-mark" aria-hidden="true">▦</span><div><small>TABLES AVAILABLE</small><b><?=number_format($portalStats['tables'])?> <span>โต๊ะว่างในเครือ</span></b></div></article><article><span class="portal-snapshot-mark" aria-hidden="true">✦</span><div><small>PR TONIGHT</small><b><?=number_format($portalStats['prs'])?> <span>PR active</span></b></div></article></section>
<?php if($s['enabled']!=='1'):?><div class="portal-off">Portal ปิดอยู่ · Super Admin Preview</div><?php endif;?>
<section class="portal-directory" aria-labelledby="portal-directory-title">
<div class="portal-directory-heading"><div><span>01 / FIND YOUR BRANCH</span><h2 id="portal-directory-title">สำรวจร้านในเครือ</h2><p>ค้นหาจากชื่อร้าน ทำเล หรือรหัสสาขา แล้วเข้าไปดูบรรยากาศและบริการของแต่ละร้าน</p></div><div class="portal-directory-count"><b data-portal-visible><?=count($branches)?></b><span>จาก <?=count($branches)?> สาขา</span></div></div>
<div class="portal-directory-tools"><label class="portal-search"><span aria-hidden="true">⌕</span><input type="search" data-portal-search placeholder="ค้นหาชื่อร้าน ทำเล หรือรหัสสาขา" autocomplete="off"><button type="button" data-portal-clear aria-label="ล้างคำค้น" hidden>×</button></label><div class="portal-filters" role="group" aria-label="กรองสาขา"><button type="button" data-portal-filter="all" aria-pressed="true">ทั้งหมด <b><?=count($branches)?></b></button><button type="button" data-portal-filter="open" aria-pressed="false">พร้อมต้อนรับ</button><button type="button" data-portal-filter="available" aria-pressed="false">มีโต๊ะว่าง</button><button type="button" data-portal-filter="featured" aria-pressed="false">ร้านแนะนำ</button></div></div>
<p class="portal-search-status" data-portal-status aria-live="polite">แสดง <?=count($branches)?> สาขา</p>
</section>
<section class="portal-grid" data-portal-grid><?php foreach($branches as $branch):$id=(string)(int)$branch['id'];$bd=$raw['branch_data'][$id]??[];$settings=$bd['settings']??[];$available=count(array_filter($bd['tables']??[],fn($t)=>!empty($t['active'])&&($t['status']??'')==='available'));$live=count(array_filter($bd['prs']??[],fn($p)=>!empty($p['active'])&&in_array((string)($p['status']??''),['online','busy','break'],true)));$cover=portal_asset((string)($branch['cover_image']??''));if($cover==='')$cover=portal_asset((string)($settings['customer_web_hero_image']??''));$isOpen=!empty($branch['active']);$isFeatured=!empty($branch['portal_featured']);$searchText=implode(' ',[(string)($branch['name']??''),(string)($branch['code']??''),(string)($branch['address']??''),(string)($branch['description']??'')]);?>
<article class="portal-card<?= $isFeatured?' featured':''?><?= !$isOpen?' closed':''?>" data-portal-card data-open="<?=$isOpen?'1':'0'?>" data-featured="<?=$isFeatured?'1':'0'?>" data-available="<?=$available>0?'1':'0'?>" data-search="<?=h($searchText)?>"><a href="<?=h(branch_slug_path($branch))?>" aria-label="เข้าสู่ <?=h((string)$branch['name'])?>"><div class="portal-cover"<?php if($cover):?> style="background-image:url('<?=h($cover)?>')"<?php endif;?>><span><?= $isFeatured?'FEATURED SHOP':'MR BAR EXPERIENCE'?></span><?php if(!empty($branch['logo'])):?><img src="<?=h(portal_asset((string)$branch['logo']))?>" alt=""><?php else:?><b><?=h(mb_strtoupper(mb_substr((string)$branch['name'],0,2,'UTF-8'),'UTF-8'))?></b><?php endif;?><i class="portal-branch-signal<?=$isOpen?'':' is-closed'?>" aria-hidden="true"></i></div><div class="portal-copy"><header><div><small><?=h((string)($branch['code']??''))?> · <?=$isOpen?'พร้อมต้อนรับ':'ปิดชั่วคราว'?></small><h2><?=h((string)$branch['name'])?></h2></div><em aria-hidden="true">↗</em></header><p><?=h((string)($branch['description']??''))?></p><div class="portal-live"><span><i class="green"></i><?=$available?> โต๊ะว่าง</span><span><i class="pink"></i><?=$live?> PR คืนนี้</span></div><footer><span><?=h((string)($branch['address']??''))?></span><b>ดูร้านและจองโต๊ะ <i aria-hidden="true">→</i></b></footer></div></a></article><?php endforeach;?></section>
<section class="portal-empty portal-no-results" data-portal-empty hidden><b>ไม่พบสาขาที่ตรงกับการค้นหา</b><p>ลองเปลี่ยนคำค้นหรือเลือกตัวกรองอื่น</p><button type="button" data-portal-reset>แสดงทุกสาขา</button></section>
<?php if(!$branches):?><section class="portal-empty"><b>กำลังเตรียมร้านสำหรับคุณ</b><p>กรุณากลับมาใหม่อีกครั้ง หรือติดต่อทีมงาน</p></section><?php endif;?>
</main><footer class="portal-footer"><b><?=h((string)$s['footer_text'])?></b><span>© <?=date('Y')?> · Customer Portal</span></footer><script src="assets/portal-directory-v14855.js?v=14855" defer></script><script src="assets/portal-visual-refresh-v14856.js?v=14856" defer></script></body></html>
