<?php
require __DIR__.'/app/bootstrap.php';require_once __DIR__.'/app/admin-nav.php';
$u=current_user();if(!$u){header('Location:login.php');exit;}if(empty($u['super_admin'])){http_response_code(403);exit(permission_denied_page('Super Admin · Config Web Portal'));}
$msg='';$err='';
if(($_SERVER['REQUEST_METHOD']??'GET')==='POST'){csrf_check();try{$allowed=array_keys(db_portal_defaults());$values=[];foreach($allowed as $key){if(in_array($key,['enabled','show_closed_branches'],true))$values[$key]=!empty($_POST[$key])?'1':'0';else $values[$key]=trim((string)($_POST[$key]??''));}db_mutate_global(function($d)use($values,$u){$d['portal_settings']=array_replace(db_portal_defaults(),$values);$d['audit'][]=['at'=>date('c'),'action'=>'portal_settings_updated','branch_id'=>0,'by'=>(int)$u['id']];return $d;});$msg='บันทึก Web Portal กลางแล้ว';}catch(Throwable $e){$err=$e->getMessage();}}
$d=db_load_global();$s=array_replace(db_portal_defaults(),$d['portal_settings']??[]);
?><!doctype html><html lang="th"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Config Web Portal · MR BAR</title><link rel="stylesheet" href="assets/admin.css?v=1172"><link rel="stylesheet" href="assets/admin-v14.css?v=1172"><link rel="stylesheet" href="assets/multi-branch-admin-v1300.css?v=1300"><link rel="stylesheet" href="assets/multi-branch-admin-polish-v1306.css?v=1306"></head><body class="admin-v14-page mb-page"><div class="ambient"><i></i><i></i><i></i></div><?=admin_sidebar('portalconfig',$u)?>
<main class="mb-shell"><header class="mb-top"><div><p>PLATFORM / CUSTOMER GATEWAY</p><h1>Config Web Portal</h1><span>ตั้งค่าหน้าหลักที่ลูกค้าใช้เลือกร้าน ก่อนเข้าสู่หน้าเว็บของแต่ละสาขา</span></div><nav><a href="branch-manager.php">Branch Manager</a><a href="<?=h(branch_public_base().'/Portal')?>" target="_blank">Preview Portal ↗</a></nav></header>
<?php if($msg):?><div class="mb-notice ok">✓ <?=h($msg)?></div><?php endif;?><?php if($err):?><div class="mb-notice err">⚠ <?=h($err)?></div><?php endif;?>
<div class="mb-grid portal-config-grid"><section class="mb-panel"><header><div><small>PORTAL CONTENT</small><h2>ข้อความและภาพหลัก</h2></div></header><form method="post" class="mb-form"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>">
<div class="mb-switches"><label><input type="checkbox" name="enabled" <?=$s['enabled']==='1'?'checked':''?>><span>เปิด Portal กลาง</span></label><label><input type="checkbox" name="show_closed_branches" <?=$s['show_closed_branches']==='1'?'checked':''?>><span>แสดงร้านที่ปิดชั่วคราว</span></label></div>
<div class="mb-form-grid"><label><span>ชื่อกลุ่ม/แบรนด์</span><input name="brand_name" value="<?=h((string)$s['brand_name'])?>"></label><label><span>ข้อความเล็กเหนือหัวเรื่อง</span><input name="eyebrow" value="<?=h((string)$s['eyebrow'])?>"></label><label class="wide"><span>หัวเรื่องหลัก</span><input name="title" value="<?=h((string)$s['title'])?>"></label><label class="wide"><span>คำอธิบาย</span><textarea name="subtitle" rows="3"><?=h((string)$s['subtitle'])?></textarea></label><label class="wide"><span>Hero Image URL</span><input name="hero_image" value="<?=h((string)$s['hero_image'])?>" placeholder="https://... หรือ uploads/..."></label><label><span>ชื่อปุ่มติดต่อ</span><input name="contact_label" value="<?=h((string)$s['contact_label'])?>"></label><label><span>Contact URL</span><input name="contact_url" value="<?=h((string)$s['contact_url'])?>"></label><label class="wide"><span>ข้อความ Footer</span><input name="footer_text" value="<?=h((string)$s['footer_text'])?>"></label></div><button class="mb-save">บันทึก Portal</button></form></section>
<section class="mb-panel mb-preview"><header><div><small>LIVE STRUCTURE</small><h2>ร้านที่จะแสดง</h2></div><b><?=count(array_filter($d['branches']??[],fn($b)=>!empty($b['published'])&&!empty($b['active'])))?> ร้าน</b></header><?php foreach($d['branches']??[] as $b):?><article><span><?=!empty($b['published'])?'●':'○'?></span><div><b><?=h((string)$b['name'])?></b><small>/shop/<?=h((string)$b['slug'])?>/</small></div><a href="branch-manager.php?edit=<?=(int)$b['id']?>">ตั้งค่า</a></article><?php endforeach;?></section></div>
</main></body></html>
