<?php
require __DIR__.'/app/bootstrap.php';require_once __DIR__.'/app/admin-nav.php';
$u=current_user();if(!$u){header('Location:login.php');exit;}if(empty($u['super_admin'])){http_response_code(403);exit(permission_denied_page('Super Admin · Config Web Portal'));}
function pc_media_dir(): string {return __DIR__.'/storage/portal-media';}
function pc_media_upload(array $file,string $kind='logo'): string {
    $error=(int)($file['error']??UPLOAD_ERR_NO_FILE);
    if($error!==UPLOAD_ERR_OK){$messages=[UPLOAD_ERR_INI_SIZE=>'ไฟล์ใหญ่เกิน upload_max_filesize ของ Hosting',UPLOAD_ERR_FORM_SIZE=>'ไฟล์ใหญ่เกินขนาดที่ฟอร์มอนุญาต',UPLOAD_ERR_PARTIAL=>'ไฟล์อัปโหลดมาไม่ครบ',UPLOAD_ERR_NO_FILE=>'ไม่ได้เลือกไฟล์',UPLOAD_ERR_NO_TMP_DIR=>'Hosting ไม่มี Temporary Folder',UPLOAD_ERR_CANT_WRITE=>'Hosting เขียนไฟล์ไม่ได้',UPLOAD_ERR_EXTENSION=>'PHP Extension หยุดการ Upload'];throw new RuntimeException($messages[$error]??('อัปโหลด Logo ไม่สำเร็จ (code '.$error.')'));}
    $size=(int)($file['size']??0);if($size<=0||$size>5*1024*1024)throw new RuntimeException('Logo ต้องมีขนาดไม่เกิน 5MB');
    $tmp=(string)($file['tmp_name']??'');if($tmp===''||!is_uploaded_file($tmp))throw new RuntimeException('ไฟล์อัปโหลดไม่ถูกต้อง');
    $info=@getimagesize($tmp);if(!$info||empty($info[0])||empty($info[1]))throw new RuntimeException('ไฟล์นี้ไม่ใช่รูปภาพที่รองรับ');
    if((int)$info[0]>8000||(int)$info[1]>8000)throw new RuntimeException('มิติ Logo ต้องไม่เกิน 8,000 × 8,000 px');
    $allowed=['image/jpeg'=>'jpg','image/png'=>'png','image/webp'=>'webp'];$ext=$allowed[(string)($info['mime']??'')]??'';if($ext==='')throw new RuntimeException('รองรับเฉพาะ JPG / PNG / WEBP');
    $dir=pc_media_dir();if(!is_dir($dir))@mkdir($dir,0775,true);if(is_dir($dir)&&!is_writable($dir))@chmod($dir,0775);if(!is_dir($dir)||!is_writable($dir))throw new RuntimeException('Server ไม่อนุญาตให้เขียน storage/portal-media');
    $kind=$kind==='favicon'?'favicon':'logo';$name='portal-'.$kind.'-'.date('Ymd-His').'-'.bin2hex(random_bytes(5)).'.'.$ext;$dest=$dir.'/'.$name;
    if(!@move_uploaded_file($tmp,$dest))throw new RuntimeException('บันทึก Logo ลง Server ไม่สำเร็จ');@chmod($dest,0644);
    return 'portal-media.php?file='.rawurlencode($name);
}
function pc_asset(string $value): string {$value=trim($value);if($value==='')return '';if(preg_match('#^https?://#i',$value)||strpos($value,'//')===0||strpos($value,'/')===0)return $value;return branch_public_base().'/'.ltrim($value,'/');}
$msg='';$err='';
if(($_SERVER['REQUEST_METHOD']??'GET')==='POST'&&empty($_POST)&&empty($_FILES)&&(int)($_SERVER['CONTENT_LENGTH']??0)>0){$err='ไฟล์ใหญ่เกิน post_max_size ของ Hosting';}
elseif(($_SERVER['REQUEST_METHOD']??'GET')==='POST'){csrf_check();try{
    $current=db_load_global();$before=array_replace(db_portal_defaults(),$current['portal_settings']??[]);$values=[];
    foreach(array_keys(db_portal_defaults()) as $key){if(in_array($key,['logo','favicon'],true)){$values[$key]=(string)$before[$key];continue;}if(in_array($key,['enabled','show_closed_branches'],true))$values[$key]=!empty($_POST[$key])?'1':'0';else $values[$key]=trim((string)($_POST[$key]??''));}
    if(!empty($_POST['remove_logo']))$values['logo']='';
    if((int)($_FILES['logo_file']['error']??UPLOAD_ERR_NO_FILE)!==UPLOAD_ERR_NO_FILE)$values['logo']=pc_media_upload($_FILES['logo_file'],'logo');
    if(!empty($_POST['remove_favicon']))$values['favicon']='';
    if((int)($_FILES['favicon_file']['error']??UPLOAD_ERR_NO_FILE)!==UPLOAD_ERR_NO_FILE)$values['favicon']=pc_media_upload($_FILES['favicon_file'],'favicon');
    db_mutate_global(function($d)use($values,$u){$d['portal_settings']=array_replace(db_portal_defaults(),$values);$d['audit'][]=['at'=>date('c'),'action'=>'portal_settings_updated','branch_id'=>0,'by'=>(int)$u['id']];return $d;});$msg='บันทึก Web Portal กลางและ Logo แล้ว';
}catch(Throwable $e){$err=$e->getMessage();}}
$d=db_load_global();$s=array_replace(db_portal_defaults(),$d['portal_settings']??[]);$logoPreview=pc_asset((string)$s['logo']);$faviconPreview=pc_asset((string)$s['favicon']);
?><!doctype html><html lang="th"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Config Web Portal · MR BAR</title><link rel="stylesheet" href="assets/admin.css?v=1172"><link rel="stylesheet" href="assets/admin-v14.css?v=1172"><link rel="stylesheet" href="assets/multi-branch-admin-v1300.css?v=1300"><link rel="stylesheet" href="assets/multi-branch-admin-polish-v1306.css?v=1306"><link rel="stylesheet" href="assets/portal-config-v1330.css?v=1330"></head><body class="admin-v14-page mb-page"><div class="ambient"><i></i><i></i><i></i></div><?=admin_sidebar('portalconfig',$u)?>
<main class="mb-shell"><header class="mb-top"><div><p>PLATFORM / CUSTOMER GATEWAY</p><h1>Config Web Portal</h1><span>ตั้งค่าหน้าหลักที่ลูกค้าใช้เลือกร้าน ก่อนเข้าสู่หน้าเว็บของแต่ละสาขา</span></div><nav><a href="branch-manager.php">Branch Manager</a><a href="<?=h(branch_public_base().'/Portal')?>" target="_blank">Preview Portal ↗</a></nav></header>
<?php if($msg):?><div class="mb-notice ok">✓ <?=h($msg)?></div><?php endif;?><?php if($err):?><div class="mb-notice err">⚠ <?=h($err)?></div><?php endif;?>
<div class="mb-grid portal-config-grid"><section class="mb-panel"><header><div><small>PORTAL CONTENT</small><h2>ข้อความและภาพหลัก</h2></div></header><form method="post" enctype="multipart/form-data" class="mb-form"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>">
<div class="mb-switches"><label><input type="checkbox" name="enabled" <?=$s['enabled']==='1'?'checked':''?>><span>เปิด Portal กลาง</span></label><label><input type="checkbox" name="show_closed_branches" <?=$s['show_closed_branches']==='1'?'checked':''?>><span>แสดงร้านที่ปิดชั่วคราว</span></label></div>
<section class="pc-logo-field"><div class="pc-logo-preview"><?php if($logoPreview):?><img src="<?=h($logoPreview)?>" alt="Portal Logo"><?php else:?><b>✦</b><?php endif;?></div><div class="pc-logo-control"><strong>Logo Portal กลาง</strong><small>PNG พื้นโปร่งใสจะสวยที่สุด · JPG / PNG / WEBP · ไม่เกิน 5MB</small><label class="pc-upload"><input type="file" name="logo_file" accept="image/jpeg,image/png,image/webp"><span>เลือกรูป Logo จากเครื่อง</span></label><?php if($logoPreview):?><label class="pc-remove"><input type="checkbox" name="remove_logo" value="1"> ลบ Logo ปัจจุบัน</label><?php endif;?></div></section>
<section class="pc-logo-field pc-favicon-field"><div class="pc-logo-preview pc-favicon-preview"><?php if($faviconPreview):?><img src="<?=h($faviconPreview)?>" alt="Portal Favicon"><?php else:?><b>★</b><?php endif;?></div><div class="pc-logo-control"><strong>Favicon หน้า Portal</strong><small>ไอคอนบนแท็บ Browser · แนะนำรูปสี่เหลี่ยม 512 × 512 px · JPG / PNG / WEBP · ไม่เกิน 5MB</small><label class="pc-upload"><input type="file" name="favicon_file" accept="image/jpeg,image/png,image/webp"><span>เลือก Favicon จากเครื่อง</span></label><?php if($faviconPreview):?><label class="pc-remove"><input type="checkbox" name="remove_favicon" value="1"> ลบ Favicon ปัจจุบัน</label><?php endif;?></div></section>
<div class="mb-form-grid"><label><span>ชื่อกลุ่ม/แบรนด์</span><input name="brand_name" value="<?=h((string)$s['brand_name'])?>"></label><label><span>ข้อความเล็กเหนือหัวเรื่อง</span><input name="eyebrow" value="<?=h((string)$s['eyebrow'])?>"></label><label class="wide"><span>หัวเรื่องหลัก</span><input name="title" value="<?=h((string)$s['title'])?>"></label><label class="wide"><span>คำอธิบาย</span><textarea name="subtitle" rows="3"><?=h((string)$s['subtitle'])?></textarea></label><label class="wide"><span>Hero Image URL</span><input name="hero_image" value="<?=h((string)$s['hero_image'])?>" placeholder="https://... หรือ uploads/..."></label><label><span>ชื่อปุ่มติดต่อ</span><input name="contact_label" value="<?=h((string)$s['contact_label'])?>"></label><label><span>Contact URL</span><input name="contact_url" value="<?=h((string)$s['contact_url'])?>"></label><label class="wide"><span>ข้อความ Footer</span><input name="footer_text" value="<?=h((string)$s['footer_text'])?>"></label></div><button class="mb-save">บันทึก Portal</button></form></section>
<section class="mb-panel mb-preview"><header><div><small>LIVE STRUCTURE</small><h2>ร้านที่จะแสดง</h2></div><b><?=count(array_filter($d['branches']??[],fn($b)=>!empty($b['published'])&&!empty($b['active'])))?> ร้าน</b></header><?php foreach($d['branches']??[] as $b):?><article><span><?=!empty($b['published'])?'●':'○'?></span><div><b><?=h((string)$b['name'])?></b><small>/shop/<?=h((string)$b['slug'])?>/</small></div><a href="branch-manager.php?edit=<?=(int)$b['id']?>">ตั้งค่า</a></article><?php endforeach;?></section></div>
</main></body></html>