<?php
require __DIR__.'/app/bootstrap.php';
require_once __DIR__.'/app/compat.php';
require_once __DIR__.'/app/pos-incentive.php';
$u=require_permission('employees.manage');$msg='';$err='';$preview=null;$previewStage=null;$previewGuess=[];$previewType='';$previewStats=[];
$month=(string)($_GET['month']??$_POST['month']??date('Y-m'));if(!posi_month_valid($month))$month=date('Y-m');
[$monthFrom,$monthTo]=posi_month_bounds($month);$uid=(int)($u['id']??0);
if($_SERVER['REQUEST_METHOD']==='POST'){csrf_check();$action=(string)($_POST['action']??'');try{
    if($action==='save_rule'){
        $ruleMonth=(string)($_POST['rule_month']??$month);if(!posi_month_valid($ruleMonth))throw new RuntimeException('เดือนของ Rule ไม่ถูกต้อง');if(posi_closing(db_load(),$ruleMonth))throw new RuntimeException('เดือนนี้ Final แล้ว กรุณา Reopen ก่อนแก้ Rule');$scope=(string)($_POST['scope_type']??'store');if(!in_array($scope,['store','team','employee'],true))$scope='store';$scopeValue='';if($scope==='team'){$scopeValue=trim((string)($_POST['scope_team']??''));if($scopeValue==='')throw new RuntimeException('กรุณาระบุ Team Code');}elseif($scope==='employee'){$scopeValue=(string)max(0,(int)($_POST['scope_employee_id']??0));if($scopeValue==='0')throw new RuntimeException('กรุณาเลือกพนักงาน');}$payout=(string)($_POST['payout_type']??'per_drink');if(!in_array($payout,['per_drink','percent_sales','fixed_bonus'],true))$payout='per_drink';$rid=(int)($_POST['rule_id']??0);$rule=['id'=>$rid,'month'=>$ruleMonth,'name'=>trim((string)($_POST['rule_name']??'Monthly Incentive'))?:'Monthly Incentive','enabled'=>!empty($_POST['enabled'])?1:0,'scope_type'=>$scope,'scope_value'=>$scopeValue,'target_sales'=>(string)posi_money($_POST['target_sales']??0),'payout_type'=>$payout,'reward_rate'=>(string)posi_money($_POST['reward_rate']??0),'note'=>trim((string)($_POST['note']??'')),'updated_at'=>date('c'),'updated_by'=>$uid];
        db_mutate(function($d)use($rule,$rid,$uid){if(!isset($d['pos_incentive_rules'])||!is_array($d['pos_incentive_rules']))$d['pos_incentive_rules']=[];$r=$rule;if($rid>0){$found=false;foreach($d['pos_incentive_rules'] as &$x)if((int)($x['id']??0)===$rid){$r['created_at']=$x['created_at']??date('c');$r['created_by']=$x['created_by']??$uid;$x=posi_rule_defaults(array_replace($x,$r));$found=true;break;}unset($x);if(!$found)throw new RuntimeException('ไม่พบ Rule');}else{$r['id']=next_id($d['pos_incentive_rules']);$r['created_at']=date('c');$r['created_by']=$uid;$d['pos_incentive_rules'][]=posi_rule_defaults($r);} $d['audit'][]=['at'=>date('c'),'action'=>'pos_incentive_rule_saved','rule_id'=>(int)$r['id'],'month'=>(string)$r['month'],'by'=>$uid];return $d;});$month=$ruleMonth;[$monthFrom,$monthTo]=posi_month_bounds($month);$msg='บันทึกเงื่อนไข Incentive แล้ว';
    }elseif($action==='delete_rule'){$rid=(int)($_POST['rule_id']??0);$snap=db_load();foreach(posi_rules($snap) as $rr)if((int)$rr['id']===$rid&&posi_closing($snap,(string)$rr['month']))throw new RuntimeException('เดือนนี้ Final แล้ว กรุณา Reopen ก่อนลบ Rule');db_mutate(function($d)use($rid,$uid){$before=count($d['pos_incentive_rules']??[]);$d['pos_incentive_rules']=array_values(array_filter($d['pos_incentive_rules']??[],fn($r)=>(int)($r['id']??0)!==$rid));if(count($d['pos_incentive_rules'])===$before)throw new RuntimeException('ไม่พบ Rule');$d['audit'][]=['at'=>date('c'),'action'=>'pos_incentive_rule_deleted','rule_id'=>$rid,'by'=>$uid];return $d;});$msg='ลบ Rule แล้ว';
    }elseif($action==='upload_preview'){$previewStage=posi_stage_upload($_FILES['pos_file']??[]);$preview=posi_parse_file((string)$previewStage['path'],(string)$previewStage['ext'],0);$previewGuess=posi_guess_columns($preview['headers']);$previewType=posi_report_type($previewGuess);$previewStats=posi_preview_summary($preview,$previewGuess);$msg=$previewType==='product_summary'?'ตรวจพบรายงานยอดขายตามสินค้า · ระบบเลือกคอลัมน์และค่าดริ้ง D/M ให้อัตโนมัติ':'อ่านไฟล์สำเร็จ · กรุณาตรวจ Mapping ก่อน Import จริง';
    }elseif($action==='commit_import'){$token=(string)($_POST['stage_token']??'');$stage=posi_stage_get($token);$parsed=posi_parse_file((string)$stage['path'],(string)$stage['ext'],0);$map=['date'=>(int)($_POST['map_date']??-1),'item'=>(int)($_POST['map_item']??-1),'group'=>(int)($_POST['map_group']??-1),'category'=>(int)($_POST['map_category']??-1),'qty'=>(int)($_POST['map_qty']??-1),'sales'=>(int)($_POST['map_sales']??-1),'cost'=>(int)($_POST['map_cost']??-1),'profit'=>(int)($_POST['map_profit']??-1),'ref'=>(int)($_POST['map_ref']??-1)];$reportType=(string)($_POST['report_type']??'transaction');if($map['item']<0||$map['sales']<0||($reportType!=='product_summary'&&$map['date']<0))throw new RuntimeException($reportType==='product_summary'?'ต้อง Mapping ชื่อสินค้าและราคาสุทธิ':'ต้อง Mapping วันที่ ชื่อเมนู และยอดขาย');$meta=['source_name'=>trim((string)($_POST['source_name']??'POS')),'import_mode'=>(string)($_POST['import_mode']??'period'),'period_start'=>(string)($_POST['period_start']??''),'period_end'=>(string)($_POST['period_end']??''),'report_type'=>$reportType];$batch=null;db_mutate(function($d)use($stage,$parsed,$map,$meta,$uid,&$batch){$batch=posi_commit_import($d,$stage,$parsed,$map,$meta,$uid);return $d;});posi_stage_clear($token);$month=(string)($batch['month']??$month);[$monthFrom,$monthTo]=posi_month_bounds($month);$msg='Import สำเร็จ '.(int)$batch['rows_imported'].' รายการ · ยอดสุทธิ '.number_format((float)$batch['total_sales'],2).' · ค่าดริ้ง Match '.(int)$batch['matched_rows'].' · รอตั้ง Alias '.(int)$batch['unmatched_rows'];
    }elseif($action==='void_batch'){$bid=(int)($_POST['batch_id']??0);$voided=null;db_mutate(function($d)use($bid,$uid,&$voided){$voided=posi_void_batch($d,$bid,$uid);return $d;});$msg='Void Import Batch #'.$bid.' แล้ว · แถวข้อมูลของ Batch นี้ถูกตัดออกจากการคำนวณ';
    }elseif($action==='remap'){if(posi_closing(db_load(),$month))throw new RuntimeException('เดือนนี้ Final แล้ว กรุณา Reopen ก่อน Re-map');$changed=0;db_mutate(function($d)use($month,$uid,&$changed){$changed=posi_remap_rows($d,$month);$d['audit'][]=['at'=>date('c'),'action'=>'pos_incentive_remap','month'=>$month,'changed'=>$changed,'by'=>$uid];return $d;});$msg='คำนวณ POS Mapping ใหม่แล้ว · เปลี่ยน '.$changed.' แถว';
    }elseif($action==='finalize'){$closing=null;db_mutate(function($d)use($month,$uid,&$closing){$closing=posi_close_month($d,$month,$uid);return $d;});$msg='Final Incentive เดือน '.$month.' แล้ว · หลังจากนี้หน้า Employee จะใช้อ้างอิง Snapshot นี้';
    }elseif($action==='reopen'){$n=0;db_mutate(function($d)use($month,$uid,&$n){$n=posi_reopen_month($d,$month,$uid);return $d;});$msg=$n?'Reopen เดือน '.$month.' แล้ว สามารถ Import/แก้ Rule และ Final ใหม่ได้':'ไม่พบรอบ Final';
    }
}catch(Throwable $e){$err=$e->getMessage();}}
$d=db_load();$currency=(string)($d['settings']['currency']??'THB');$summary=posi_period_summary($d,$month);$rules=posi_rules($d,$month);$results=posi_month_results($d,$month);$closing=posi_closing($d,$month);$unmatched=posi_unmatched_items($d,$month,20);$employees=array_values(array_filter($d['employees']??[],fn($e)=>!empty($e['active'])&&in_array((string)($e['position']??''),['sales','pr'],true)));$batches=array_values(array_filter($d['pos_import_batches']??[],fn($b)=>(string)($b['month']??'')===$month));usort($batches,fn($a,$b)=>strcmp((string)($b['imported_at']??''),(string)($a['imported_at']??'')));
$primaryRule=null;foreach($rules as $r)if(!empty($r['enabled'])&&$r['scope_type']==='store'){$primaryRule=$r;break;}if(!$primaryRule)foreach($rules as $r)if(!empty($r['enabled'])){$primaryRule=$r;break;}$target=$primaryRule?(float)$primaryRule['target_sales']:0;$primaryActual=$primaryRule?posi_scope_sales($d,$month,$primaryRule):0.0;$progress=$target>0?min(999,$primaryActual/$target*100):0;$projectedUnlock=$target<=0||($primaryActual*(float)$summary['projection_factor'])>=$target;$defaultPeriodEnd=$month===date('Y-m')?date('Y-m-d'):$monthTo;
$prev=date('Y-m',strtotime($month.'-01 -1 month'));$next=date('Y-m',strtotime($month.'-01 +1 month'));
$step=max(1,min(4,(int)($_GET['step']??(($summary['rows']??0)>0?2:1))));
$groupFilter=trim((string)($_GET['group_filter']??'all'));$employeeFilter=max(0,(int)($_GET['employee_filter']??0));$calculateView=!empty($_GET['calculate']);
$groupOptions=['sales'=>'Sales','pr'=>'PR'];foreach($results as $rr){$team=trim((string)($rr['team_code']??''));if($team!=='')$groupOptions['team:'.$team]='ทีม '.$team;}
$resultView=array_values(array_filter($results,function($r)use($groupFilter,$employeeFilter){if($employeeFilter>0&&(int)$r['employee_id']!==$employeeFilter)return false;if($groupFilter==='all')return true;if(strpos($groupFilter,'team:')===0)return (string)($r['team_code']??'')===substr($groupFilter,5);return (string)($r['position']??'')===$groupFilter;}));
usort($resultView,fn($a,$b)=>[(string)($a['team_code']??''),(string)($a['position']??''),-(float)($a['recognized_pay']??0)]<=>[(string)($b['team_code']??''),(string)($b['position']??''),-(float)($b['recognized_pay']??0)]);
$viewUnits=array_sum(array_map(fn($r)=>(float)($r['units']??0),$resultView));$viewSales=array_sum(array_map(fn($r)=>(float)($r['sales']??0),$resultView));$viewPay=array_sum(array_map(fn($r)=>(float)($r['recognized_pay']??0),$resultView));
function posi_payout_label(string $p): string{return ['per_drink'=>'บาท / Drink','percent_sales'=>'% จากยอดขายรายบุคคล','fixed_bonus'=>'โบนัสคงที่'][$p]??$p;}
?><!doctype html><html lang="th"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>MR BAR — POS Incentive & Commission</title><link rel="stylesheet" href="assets/admin.css?v=1240"><link rel="stylesheet" href="assets/admin-v14.css?v=1240"><link rel="stylesheet" href="assets/pos-incentive-v1298.css?v=1298"><link rel="stylesheet" href="assets/pos-incentive-wizard-v1350.css?v=1350"></head><body class="admin-v14-page posi-page posi-wizard-step-<?=$step?>"><?php require_once __DIR__.'/app/admin-nav.php';echo admin_sidebar('incentive',$u);?><main class="posi-shell"><header class="posi-head"><div><p>PEOPLE / POS INCENTIVE</p><h1>POS Incentive & Commission</h1><span>Import Excel/CSV → Mapping เมนูเข้าพนักงาน → ประมาณการรายสัปดาห์ → Final รายเดือน</span></div><div><a href="employees.php">Employee Center</a><a href="payroll-attendance.php">Attendance & Payroll</a></div></header><?php if($msg):?><div class="posi-notice ok">✓ <?=h($msg)?></div><?php endif;?><?php if($err):?><div class="posi-notice err">⚠ <?=h($err)?></div><?php endif;?>
<section class="posi-month"><a href="?month=<?=h($prev)?>">‹</a><div><small>รอบคำนวณ</small><b><?=h($month)?></b><span><?=h(date('d/m/Y',strtotime($monthFrom)))?> – <?=h(date('d/m/Y',strtotime($monthTo)))?></span></div><a href="?month=<?=h($next)?>">›</a><em class="<?= $closing?'final':'estimate' ?>"><?= $closing?'FINAL':'ESTIMATE' ?></em></section>
<section class="posi-workflow posi-wizard-nav"><a href="?month=<?=h($month)?>&step=1" class="<?=$step===1?'active':(($summary['rows']??0)>0?'done':'')?>"><i>1</i><span><b>อัปโหลด POS</b><small>นำเข้าและตรวจข้อมูล</small></span></a><a href="?month=<?=h($month)?>&step=2" class="<?=$step===2?'active':(($summary['rows']??0)>0?'done':'')?>"><i>2</i><span><b>จัดกลุ่มและ Sort</b><small>เลือก Sales / PR / ทีม</small></span></a><a href="?month=<?=h($month)?>&step=3" class="<?=$step===3?'active':($rules?'done':'')?>"><i>3</i><span><b>คำนวณค่าคอม</b><small>ใช้กติกาประจำเดือน</small></span></a><a href="?month=<?=h($month)?>&step=4" class="<?=$step===4?'active':($closing?'done':'')?>"><i>4</i><span><b>ตรวจและปิดรอบ</b><small>Final รายเดือน</small></span></a></section>
<section class="posi-kpis"><article class="sales"><small>ยอดขายสุทธิจาก POS</small><b><?=number_format((float)$summary['actual_sales'],2)?></b><span><?=h($currency)?> · <?=number_format((int)$summary['rows'])?> รายการสินค้า</span></article><article class="drinks"><small>หน่วยค่าดริ้ง D + M</small><b><?=number_format((float)($summary['drink_units']??0),0)?></b><span><i>D <?=number_format((float)($summary['d_units']??0),0)?></i><i>M <?=number_format((float)($summary['m_units']??0),0)?></i></span></article><article class="<?=($summary['unmatched_rows']??0)>0?'warn':'good'?>"><small>จับคู่ชื่อพนักงาน</small><b><?=number_format((int)$summary['matched_rows'])?> / <?=number_format((int)$summary['matched_rows']+(int)$summary['unmatched_rows'])?></b><span><?=($summary['unmatched_rows']??0)>0?'รอตั้ง Alias '.number_format((int)$summary['unmatched_rows']).' รายการ':'รายการค่าดริ้งพร้อมคำนวณ'?></span></article><article class="<?=$target>0&&$projectedUnlock?'good':'target'?>"><small>เป้ายอดขายเดือนนี้</small><b><?=$target>0?number_format($target,0):'ยังไม่ตั้ง'?></b><span><?=$target>0?number_format($progress,1).'% · ประมาณปลายเดือน '.number_format((float)$summary['projected_sales'],0):'สร้าง Rule เพื่อเริ่มคำนวณค่าคอม'?></span></article></section>
<div class="posi-grid posi-setup-grid"><section class="posi-card"><div class="posi-card-head"><div><small>02 / COMMISSION RULE</small><h2>กติกาค่าคอมประจำเดือน</h2><p>กำหนดเป้ายอดร้าน เงื่อนไขปลดล็อก และอัตราจ่ายต่อหน่วย</p></div></div><form method="post" class="posi-rule-form"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><input type="hidden" name="action" value="save_rule"><label>เดือน<input type="month" name="rule_month" value="<?=h($month)?>" required></label><label>ชื่อ Rule<input name="rule_name" value="Monthly Drink Commission" required></label><label>Scope<select name="scope_type"><option value="store">ยอดรวมทั้งร้าน</option><option value="team">ยอดเฉพาะทีม</option><option value="employee">ยอดเฉพาะพนักงาน</option></select></label><label>Team Code<input name="scope_team" placeholder="เช่น TEAM-A"></label><label>พนักงาน<select name="scope_employee_id"><option value="0">— ใช้เมื่อ Scope = พนักงาน —</option><?php foreach($employees as $e):?><option value="<?=(int)$e['id']?>"><?=h(workforce_employee_label($e))?></option><?php endforeach;?></select></label><label>เป้ายอดขาย<input type="number" step="0.01" min="0" name="target_sales" placeholder="2500000" required></label><label>วิธีจ่าย<select name="payout_type"><option value="per_drink">บาท / Drink</option><option value="percent_sales">% ยอดขายรายบุคคล</option><option value="fixed_bonus">โบนัสคงที่</option></select></label><label>Rate / มูลค่า<input type="number" step="0.01" min="0" name="reward_rate" placeholder="80" required></label><label class="wide">หมายเหตุ<input name="note" placeholder="เช่น ถึงยอด 2.5M จ่าย 80 บาทต่อ Drink"></label><label class="check"><input type="checkbox" name="enabled" value="1" checked> เปิดใช้ Rule</label><button>บันทึก Rule</button></form><div class="posi-rule-list"><?php if(!$rules):?><div class="empty">ยังไม่มี Rule เดือนนี้</div><?php endif;?><?php foreach($rules as $r):?><article><div><b><?=h((string)$r['name'])?></b><span><?=h(strtoupper((string)$r['scope_type']))?> · Target <?=number_format((float)$r['target_sales'],0)?> · <?=number_format((float)$r['reward_rate'],2)?> <?=h(posi_payout_label((string)$r['payout_type']))?></span><?php if(!empty($r['note'])):?><small><?=h((string)$r['note'])?></small><?php endif;?></div><form method="post" onsubmit="return confirm('ลบ Rule นี้?')"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><input type="hidden" name="action" value="delete_rule"><input type="hidden" name="month" value="<?=h($month)?>"><input type="hidden" name="rule_id" value="<?=(int)$r['id']?>"><button>ลบ</button></form></article><?php endforeach;?></div></section>
<section class="posi-card posi-import-card"><div class="posi-card-head row"><div><small>01 / IMPORT POS</small><h2>นำเข้ารายงานยอดขายตามสินค้า</h2><p>รองรับไฟล์รูปแบบเดียวกับ “ยอดขายตามสินค้า เดือน 8 V2” · ตรวจหัวตารางและ D/M อัตโนมัติ</p></div><span class="posi-format-badge">XLSX / CSV</span></div>
<?php if(!$preview):?><form method="post" enctype="multipart/form-data" class="posi-upload posi-upload-new"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><input type="hidden" name="action" value="upload_preview"><input type="hidden" name="month" value="<?=h($month)?>"><label><span class="upload-icon">↑</span><b>ลากหรือเลือกไฟล์รายงาน POS</b><small>ระบบจะยังไม่บันทึก จนกว่าจะตรวจ Preview และกดยืนยัน</small><input type="file" name="pos_file" accept=".xlsx,.csv" required></label><button>อ่านไฟล์และตรวจสอบ</button></form>
<?php else:$previewType=$previewType?:posi_report_type($previewGuess);$previewStats=$previewStats?:posi_preview_summary($preview,$previewGuess);?><div class="preview-file"><div><b><?=h((string)$previewStage['name'])?></b><span>พบหัวตารางที่แถว <?=number_format((int)($preview['header_row']??1))?> · SHA <?=h(substr((string)$previewStage['sha256'],0,12))?>…</span></div><em><?=$previewType==='product_summary'?'รายงานยอดขายตามสินค้า':'รายละเอียดรายการขาย'?></em></div>
<div class="posi-preview-stats"><article><small>รายการสินค้า</small><b><?=number_format((int)$previewStats['rows'])?></b></article><article><small>ยอดขายสุทธิ</small><b><?=number_format((float)$previewStats['net_sales'],2)?></b></article><article><small>ค่าดริ้ง D</small><b><?=number_format((float)$previewStats['d_units'],0)?></b></article><article><small>ค่าดริ้ง M</small><b><?=number_format((float)$previewStats['m_units'],0)?></b></article><article class="accent"><small>D + M รวม</small><b><?=number_format((float)$previewStats['candidate_units'],0)?></b></article></div>
<div class="posi-detect-note"><b>ระบบตรวจพบและตั้งค่าให้แล้ว</b><span>ยอดสุทธิใช้เทียบ Target ทั้งร้าน · ค่าดริ้งนับเฉพาะสินค้า D/M ในกลุ่ม PR และ Sales · รายการอื่นเก็บเป็นยอดร้านแต่ไม่คิดค่าดริ้ง<?php if($previewType==='product_summary'):?> · ไฟล์ไม่มีวันที่ ระบบจะลงรอบ <strong><?=h($month)?></strong> ตามช่อง “ถึง” ด้านล่าง<?php endif;?></span></div>
<form method="post" class="posi-map-form"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><input type="hidden" name="action" value="commit_import"><input type="hidden" name="month" value="<?=h($month)?>"><input type="hidden" name="stage_token" value="<?=h((string)$previewStage['token'])?>"><input type="hidden" name="report_type" value="<?=h($previewType)?>">
<div class="posi-map-primary"><label>ชื่อแหล่งข้อมูล<input name="source_name" value="POS Product Summary" required></label><label>วิธีนำเข้า<select name="import_mode"><option value="mtd_snapshot" <?=$previewType==='product_summary'?'selected':''?>>Snapshot เดือนนี้ · แทนไฟล์เก่า</option><option value="period">เพิ่มข้อมูลเฉพาะช่วง</option></select></label><label>ตั้งแต่<input type="date" name="period_start" value="<?=h($monthFrom)?>" required></label><label>ถึง<input type="date" name="period_end" value="<?=h($defaultPeriodEnd)?>" required></label></div>
<details class="posi-mapping" <?=$previewType==='product_summary'?'':'open'?>><summary>ตรวจคอลัมน์ที่ระบบเลือก <small>เปิดเมื่อต้องการแก้ Mapping</small></summary><div><?php $mapLabels=['date'=>'วันที่ขาย (ไม่จำเป็นสำหรับรายงานสรุป)','item'=>'ชื่อสินค้า *','group'=>'กลุ่มสินค้า','category'=>'หมวดสินค้า','qty'=>'จำนวนการขาย','sales'=>'ราคาสุทธิ *','ref'=>'เลขที่บิล (ถ้ามี)'];foreach($mapLabels as $mk=>$ml):?><label><?=h($ml)?><select name="map_<?=h($mk)?>"><option value="-1">— ไม่ใช้ —</option><?php foreach($preview['headers'] as $i=>$hh):?><option value="<?=$i?>" <?=($previewGuess[$mk]??-1)===$i?'selected':''?>><?=h($hh)?></option><?php endforeach;?></select></label><?php endforeach;?></div></details><button class="posi-commit">ยืนยัน Import และคำนวณค่าดริ้ง</button></form>
<div class="posi-preview"><table><thead><tr><?php foreach($preview['headers'] as $hh):?><th><?=h($hh)?></th><?php endforeach;?></tr></thead><tbody><?php foreach(array_slice($preview['rows'],0,10) as $row):?><tr><?php foreach($preview['headers'] as $i=>$hh):?><td><?=h((string)($row[$i]??''))?></td><?php endforeach;?></tr><?php endforeach;?></tbody></table></div><?php endif;?>
<div class="import-help"><b>ป้องกันยอดซ้ำ</b><span>ไฟล์เดิมถูกตรวจด้วย SHA-256 · Snapshot ใหม่แทน Snapshot เก่าของเดือนเดียวกัน · ต้อง Reopen ก่อนแก้เดือนที่ Final แล้ว</span></div></section></div>
<section class="posi-sort-stage">
<div class="posi-step-title"><small>STEP 2–3 / SORT & CALCULATE</small><h2>เลือกกลุ่ม แล้วคำนวณค่าคอม</h2><p>เลือกกลุ่มหลักแบบเดียวกับ Filter ใน Excel จากนั้นเลือก Sales รายคนได้ และกดคำนวณเพื่อดูยอดตามกติกาค่าคอมประจำเดือน</p></div>
<form method="get" class="posi-sort-form"><input type="hidden" name="month" value="<?=h($month)?>"><input type="hidden" name="step" value="3">
<label><span>1. Sort ตามกลุ่ม</span><select name="group_filter"><option value="all">ทุกกลุ่ม</option><?php foreach($groupOptions as $gv=>$gl):?><option value="<?=h($gv)?>" <?=$groupFilter===$gv?'selected':''?>><?=h($gl)?></option><?php endforeach;?></select></label>
<label><span>2. เลือก Sales / พนักงาน</span><select name="employee_filter"><option value="0">ทุกคนในกลุ่ม</option><?php foreach($employees as $e):?><option value="<?=(int)$e['id']?>" <?=$employeeFilter===(int)$e['id']?'selected':''?>><?=h(workforce_employee_label($e))?> · <?=h(workforce_position_label((string)$e['position']))?></option><?php endforeach;?></select></label>
<button name="calculate" value="1">คำนวณตามกลุ่มที่เลือก →</button></form>
<?php if($calculateView):?><div class="posi-calc-summary"><article><small>พนักงานในผลลัพธ์</small><b><?=number_format(count($resultView))?></b><span>คน</span></article><article><small>ยอด D/M ที่จับคู่</small><b><?=number_format($viewUnits,0)?></b><span>หน่วย</span></article><article><small>ยอดขายที่ผูกกับกลุ่ม</small><b><?=number_format($viewSales,2)?></b><span><?=h($currency)?></span></article><article class="pay"><small>ค่าคอมตามกติกา</small><b><?=number_format($viewPay,2)?></b><span><?=h($currency)?></span></article></div><?php endif;?>
</section>
<section class="posi-card wide posi-results-stage"><div class="posi-card-head row"><div><small>03 / LIVE ESTIMATE</small><h2>สรุปค่าดริ้งและค่าคอมรายพนักงาน</h2><p>แสดง D/M ที่จับคู่ได้ ยอดสะสม อัตราจ่าย และยอดประมาณการก่อนปิดรอบ</p></div><div class="card-actions"><form method="post"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><input type="hidden" name="action" value="remap"><input type="hidden" name="month" value="<?=h($month)?>"><button>↻ Re-map จาก Alias ล่าสุด</button></form><?php if(!$closing):?><form method="post" onsubmit="return confirm('Final Incentive เดือน <?=h($month)?>? ระบบจะ Snapshot ยอดรายคน ณ ตอนนี้')"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><input type="hidden" name="action" value="finalize"><input type="hidden" name="month" value="<?=h($month)?>"><button class="final">Final เดือนนี้</button></form><?php else:?><form method="post" onsubmit="return confirm('Reopen รอบ Final เพื่อแก้ข้อมูล?')"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><input type="hidden" name="action" value="reopen"><input type="hidden" name="month" value="<?=h($month)?>"><button class="warn">Reopen</button></form><?php endif;?></div></div><div class="posi-results"><table><thead><tr><th>พนักงาน</th><th>ทีม</th><th>ค่าดริ้ง D / M</th><th>ยอด D/M ที่จับคู่</th><th>อัตราจ่าย</th><th>สถานะ</th><th>ยอดจ่ายปัจจุบัน</th><th>ประมาณการปลายเดือน</th></tr></thead><tbody><?php if(!$resultView):?><tr><td colspan="8" class="empty">ยังไม่มี Sales/PR ที่เปิด POS Incentive · ตั้ง Alias ที่ Employee Center ก่อน</td></tr><?php endif;?><?php foreach($resultView as $r):$e=posi_employee_by_id($d,(int)$r['employee_id']);?><tr><td><b><?=h($e?workforce_employee_label($e):'#'.$r['employee_id'])?></b><small><?=h(workforce_position_label((string)$r['position']))?><?=$r['team_lead']?' · หัวทีม':''?></small></td><td><?=h($r['team_code']?:'—')?></td><td><div class="drink-split"><span class="d">D <b><?=number_format((float)($r['d_units']??0),0)?></b></span><span class="m">M <b><?=number_format((float)($r['m_units']??0),0)?></b></span></div><small>รวม <?=number_format((float)$r['units'],0)?> หน่วย</small></td><td><b><?=number_format((float)$r['sales'],2)?></b></td><td><?=number_format((float)$r['rate'],2)?></td><td><span class="state <?=h((string)$r['status'])?>"><?=h(posi_status_label((string)$r['status']))?></span><?php if($r['rule_name']):?><small><?=h((string)$r['rule_name'])?></small><?php endif;?></td><td><b><?=number_format((float)$r['recognized_pay'],2)?></b><small><?=(float)$r['potential_pay']>(float)$r['recognized_pay']?'Potential '.number_format((float)$r['potential_pay'],2):h($currency)?></small></td><td><b><?=number_format((float)$r['projected_potential_pay'],2)?></b><small><?=number_format((float)$r['projected_units'],1)?> units · <?=$r['projected_unlock']?'มีแนวโน้มผ่าน':'ยังไม่ผ่าน Target'?></small></td></tr><?php endforeach;?></tbody></table></div></section>
<div class="posi-grid lower"><section class="posi-card"><div class="posi-card-head"><div><small>04 / UNMATCHED</small><h2>ชื่อ D/M ที่ยังไม่ตรงกับพนักงาน</h2><p>แสดงเฉพาะรายการค่าดริ้ง ไม่รวมอาหาร เครื่องดื่ม Member และสินค้าอื่น</p></div></div><div class="unmatched-list"><?php if(!$unmatched):?><div class="empty">ไม่มีรายการ Unmatched</div><?php endif;?><?php foreach($unmatched as $x):?><article><div><b><?=h((string)$x['item_name'])?></b><span><?=number_format((float)$x['qty'],2)?> units · <?=$x['rows']?> rows</span></div><strong><?=number_format((float)$x['sales'],2)?> <?=h($currency)?></strong></article><?php endforeach;?></div></section><section class="posi-card"><div class="posi-card-head"><div><small>05 / IMPORT HISTORY</small><h2>ประวัติ Batch เดือนนี้</h2><p>เก็บต้นทาง, Hash, ช่วงวันที่ และสถานะเพื่อ Audit ย้อนหลัง</p></div></div><div class="batch-list"><?php if(!$batches):?><div class="empty">ยังไม่มี Import เดือนนี้</div><?php endif;?><?php foreach($batches as $b):?><article class="<?=h((string)($b['status']??'active'))?>"><div><b>#<?=(int)$b['id']?> · <?=h((string)$b['source_name'])?></b><span><?=h((string)$b['filename'])?></span><small><?=h((string)$b['period_start'])?> → <?=h((string)$b['period_end'])?> · <?=h(strtoupper((string)$b['import_mode']))?></small></div><div><strong><?=number_format((float)$b['total_sales'],2)?></strong><span><?=(int)$b['rows_imported']?> สินค้า · D/M Match <?=(int)$b['matched_rows']?><?=isset($b['candidate_rows'])?' / '.(int)$b['candidate_rows']:''?></span><em><?=h(strtoupper((string)$b['status']))?></em><?php if(($b['status']??'active')==='active'&&!$closing):?><form method="post" class="batch-void" onsubmit="return confirm('Void Batch #<?=(int)$b['id']?>? ยอดจาก Batch นี้จะถูกตัดออกจากการคำนวณ')"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><input type="hidden" name="action" value="void_batch"><input type="hidden" name="month" value="<?=h($month)?>"><input type="hidden" name="batch_id" value="<?=(int)$b['id']?>"><button>Void</button></form><?php endif;?></div></article><?php endforeach;?></div></section></div>
<section class="posi-explain"><b>หลักการคำนวณ</b><p>ยอดสุทธิทุกสินค้าจาก POS ใช้ตรวจ Target ของร้าน ส่วนค่าดริ้งนับเฉพาะรายการ D/M ในกลุ่ม PR และ Sales ที่จับคู่ Alias สำเร็จ แล้วคูณอัตราจ่ายของพนักงานหรือ Rule รายเดือน ก่อน Final ระบบแสดงเป็นยอดประมาณการเท่านั้น</p></section><footer>MR BAR POS Incentive & Commission · <?=h((string)(app_config()['pack']??'MR BAR'))?> · Schema v<?=h((string)($d['meta']['schema']??24))?></footer></main></body></html>
