<?php
require __DIR__.'/app/bootstrap.php';
require_once __DIR__.'/app/pos-reports.php';
$u=require_permission('employees.manage');$uid=(int)$u['id'];$d=db_load();$err='';$msg='';
if($_SERVER['REQUEST_METHOD']==='POST'){csrf_check();try{
    $action=(string)($_POST['action']??'');$reason=(string)($_POST['reason']??'');
    if($action==='void_round'){
        if((string)($_POST['confirm']??'')!=='VOID')throw new RuntimeException('พิมพ์ VOID เพื่อยืนยัน');
        $core=(string)($_POST['core']??'');$id=(int)($_POST['round_id']??0);
        db_mutate(fn($x)=>posr_void_round($x,$core,$id,$uid,$reason));$msg='ยกเลิกรอบบันทึกแล้ว';
    }elseif($action==='clear_bill_report'){
        if((string)($_POST['confirm']??'')!=='CLEAR')throw new RuntimeException('พิมพ์ CLEAR เพื่อยืนยัน');
        $batchId=(int)($_POST['batch_id']??0);db_mutate(fn($x)=>posr_clear_bill_batch($x,$batchId,$uid,$reason));$msg='เคลียร์ Report รายละเอียดบิลและคืนสถานะการจับคู่แล้ว';
    }elseif($action==='clear_report'){
        if((string)($_POST['confirm']??'')!=='CLEAR')throw new RuntimeException('พิมพ์ CLEAR เพื่อยืนยัน');
        $batchId=(int)($_POST['batch_id']??0);
        db_mutate(fn($x)=>posr_clear_batch($x,$batchId,$uid,$reason));$msg='เคลียร์ Report แล้ว โดยยังเก็บประวัติการดำเนินการ';
    }else throw new RuntimeException('คำสั่งไม่ถูกต้อง');
    $d=db_load();
}catch(Throwable $e){$err=$e->getMessage();}}
$filters=['core'=>(string)($_GET['core']??'all'),'status'=>(string)($_GET['status']??'saved'),'from'=>(string)($_GET['from']??''),'to'=>(string)($_GET['to']??''),'q'=>(string)($_GET['q']??''),'sort'=>(string)($_GET['sort']??'saved_at'),'dir'=>(string)($_GET['dir']??'desc'),'employee_sort'=>(string)($_GET['employee_sort']??'total'),'employee_dir'=>(string)($_GET['employee_dir']??'desc')];
$allRounds=posr_rounds($d,true);$rounds=posr_filter_sort($allRounds,$filters);$employees=posr_employee_summary($allRounds,$filters);
$activeRounds=array_values(array_filter($rounds,fn($r)=>($r['status']??'saved')!=='void'));$total=array_sum(array_map(fn($r)=>(float)($r['total']??0),$activeRounds));
$drinkTotal=array_sum(array_map(fn($r)=>($r['core']??'')==='drinks'&&(($r['status']??'saved')!=='void')?(float)($r['total']??0):0,$rounds));
$commissionTotal=array_sum(array_map(fn($r)=>($r['core']??'')==='commission'&&(($r['status']??'saved')!=='void')?(float)($r['total']??0):0,$rounds));
if(($_GET['export']??'')==='csv'){
    header('Content-Type: text/csv; charset=UTF-8');header('Content-Disposition: attachment; filename="pos-payout-report-'.date('Ymd-His').'.csv"');echo "\xEF\xBB\xBF";
    $f=fopen('php://output','w');fputcsv($f,['พนักงาน','ตำแหน่ง','D','M','ค่าดื่ม','ค่าคอม','รวม']);
    foreach($employees as $r)fputcsv($f,[$r['name'],$r['role'],$r['d'],$r['m'],$r['drinks'],$r['commission'],$r['total']]);fclose($f);exit;
}
$sortLink=function(string $field,string $label)use($filters){$q=$filters;$q['sort']=$field;$q['dir']=$filters['sort']===$field&&$filters['dir']==='asc'?'desc':'asc';return '<a href="?'.h(http_build_query($q)).'">'.h($label).($filters['sort']===$field?($filters['dir']==='asc'?' ↑':' ↓'):'').'</a>';};
$empSort=function(string $field,string $label)use($filters){$q=$filters;$q['employee_sort']=$field;$q['employee_dir']=$filters['employee_sort']===$field&&$filters['employee_dir']==='asc'?'desc':'asc';return '<a href="?'.h(http_build_query($q)).'#employee">'.h($label).($filters['employee_sort']===$field?($filters['employee_dir']==='asc'?' ↑':' ↓'):'').'</a>';};
$batches=$d['pos_import_batches']??[];usort($batches,fn($a,$b)=>strcmp((string)($b['imported_at']??''),(string)($a['imported_at']??'')));
$billBatches=$d['pos_bill_batches']??[];usort($billBatches,fn($a,$b)=>strcmp((string)($b['imported_at']??''),(string)($a['imported_at']??'')));$activeBillBatches=array_values(array_filter($billBatches,fn($b)=>($b['status']??'active')==='active'));
?><!doctype html><html lang="th"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>POS Reports</title>
<link rel="stylesheet" href="assets/admin.css?v=1240"><link rel="stylesheet" href="assets/admin-v14.css?v=1240"><link rel="stylesheet" href="assets/pos-reports.css?v=1461"><link rel="stylesheet" href="assets/pos-suite.css?v=1470"></head>
<body class="admin-v14-page"><?php require_once __DIR__.'/app/admin-nav.php';echo admin_sidebar('incentive',$u);?>
<main class="report-shell"><header class="report-head"><div><small>POS / REPORT CENTER</small><h1>รายงานค่าดื่มและค่าคอม</h1><p>ค้นหา กรอง เรียง ตรวจย้อนหลัง และส่งออกข้อมูลจ่ายเงิน</p></div><nav><a href="employees.php">Employee Center</a><a href="payroll-attendance.php">Attendance & Payroll</a></nav></header>
<nav class="pos-suite-nav"><a href="pos-incentive-import.php"><span>1</span><div><b>Import POS</b><small>อัปโหลดไฟล์</small></div></a><a href="pos-incentive.php"><span>2</span><div><b>Process ข้อมูล</b><small>ระบบเดิม / Mapping / Sort</small></div></a><a href="pos-drinks.php"><span>3</span><div><b>ค่าดื่ม</b><small>PR / Sales</small></div></a><a href="pos-commission.php"><span>4</span><div><b>ค่าคอม</b><small>PR ในทีม Sales</small></div></a><a class="active" href="pos-reports.php"><span>5</span><div><b>Report</b><small>สรุป / Sort / เคลียร์</small></div></a></nav>
<?php if($msg):?><div class="notice ok">✓ <?=h($msg)?></div><?php endif;?><?php if($err):?><div class="notice err">⚠ <?=h($err)?></div><?php endif;?>
<section class="panel"><div class="panel-head"><div><small>BILL MATCHING</small><h2>Report รายละเอียดบิล</h2><p>ใช้เลขบิลจับคู่ยอดขายกับรอบเปิดโต๊ะของ Sales</p></div><a class="export" href="sales-table.php">ดูรอบโต๊ะ Sales</a></div><div class="table-wrap"><table><thead><tr><th>Batch</th><th>ช่วงวันที่</th><th>จำนวนบิล</th><th>ยอดขาย</th><th>รอบโต๊ะที่จับคู่</th><th>สถานะ</th><th>จัดการ</th></tr></thead><tbody><?php if(!$billBatches):?><tr><td colspan="7" class="empty">ยังไม่มี Report รายละเอียดบิล</td></tr><?php endif;foreach($billBatches as $b):?><tr class="<?=($b['status']??'active')==='void'?'void':''?>"><td>#<?=(int)$b['id']?> <?=h((string)($b['filename']??''))?></td><td><?=h((string)$b['period_start'].' – '.(string)$b['period_end'])?></td><td><?=number_format((int)($b['bill_count']??0))?></td><td class="money"><?=number_format((float)($b['total_sales']??0),2)?></td><td><?=number_format((int)($b['matched_sessions']??0))?></td><td><?=h((string)($b['status']??'active'))?></td><td><?php if(($b['status']??'active')==='active'):?><details><summary>เคลียร์</summary><form method="post" class="danger-form" onsubmit="return confirm('ยืนยันเคลียร์ Report รายละเอียดบิล?')"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><input type="hidden" name="action" value="clear_bill_report"><input type="hidden" name="batch_id" value="<?=(int)$b['id']?>"><input name="reason" placeholder="เหตุผล" required><input name="confirm" placeholder="พิมพ์ CLEAR" required><button>ยืนยัน</button></form></details><?php endif;?></td></tr><?php endforeach;?></tbody></table></div></section>
<section class="filters"><form method="get"><label>ประเภท<select name="core"><option value="all">ทั้งหมด</option><option value="drinks" <?=$filters['core']==='drinks'?'selected':''?>>ค่าดื่ม</option><option value="commission" <?=$filters['core']==='commission'?'selected':''?>>ค่าคอม</option></select></label><label>สถานะ<select name="status"><option value="saved" <?=$filters['status']==='saved'?'selected':''?>>ใช้งาน</option><option value="void" <?=$filters['status']==='void'?'selected':''?>>ยกเลิก</option><option value="all" <?=$filters['status']==='all'?'selected':''?>>ทั้งหมด</option></select></label><label>ตั้งแต่<input type="date" name="from" value="<?=h($filters['from'])?>"></label><label>ถึง<input type="date" name="to" value="<?=h($filters['to'])?>"></label><label class="wide">ค้นหา<input name="q" value="<?=h($filters['q'])?>" placeholder="ชื่อพนักงาน ทีม เลข Report"></label><button>แสดงผล</button><a class="reset" href="pos-reports.php">ล้างตัวกรอง</a></form></section>
<section class="kpis"><article><small>ยอดรวมที่แสดง</small><b><?=number_format($total,2)?></b><span>บาท</span></article><article><small>ค่าดื่ม</small><b><?=number_format($drinkTotal,2)?></b><span>บาท</span></article><article><small>ค่าคอม</small><b><?=number_format($commissionTotal,2)?></b><span>บาท</span></article><article><small>รอบใช้งาน</small><b><?=count($activeRounds)?></b><span>รอบ</span></article></section>
<section class="panel"><div class="panel-head"><div><small>PAYMENT ROUNDS</small><h2>รอบที่บันทึก</h2></div><a class="export" href="?<?=h(http_build_query(array_merge($filters,['export'=>'csv'])))?>">ดาวน์โหลด CSV</a></div>
<div class="table-wrap"><table><thead><tr><th><?=$sortLink('core_label','ประเภท')?></th><th><?=$sortLink('batch_id','Report')?></th><th><?=$sortLink('from','ช่วงวันที่')?></th><th>จำนวนคน</th><th><?=$sortLink('total','ยอดรวม')?></th><th>สถานะ</th><th>รายละเอียด</th></tr></thead><tbody>
<?php if(!$rounds):?><tr><td colspan="7" class="empty">ไม่พบข้อมูลตามตัวกรอง</td></tr><?php endif;foreach($rounds as $r):?><tr class="<?=($r['status']??'saved')==='void'?'void':''?>"><td><span class="badge <?=h($r['core'])?>"><?=h($r['core_label'])?></span></td><td>#<?=(int)$r['batch_id']?></td><td><?=h($r['from'].' – '.$r['to'])?></td><td><?=count($r['rows']??[])?></td><td class="money"><?=number_format((float)$r['total'],2)?></td><td><?=($r['status']??'saved')==='void'?'ยกเลิก':'ใช้งาน'?></td><td><details><summary>เปิดดู</summary><table class="inner"><tr><th>พนักงาน</th><th>ทีม/ตำแหน่ง</th><th>D</th><th>M</th><th>ยอด</th></tr><?php foreach($r['rows']??[] as $line):?><tr><td><?=h($line['name'])?></td><td><?=h(($line['role']??'').' '.($line['teams']??''))?></td><td><?=number_format((float)$line['d'],2)?></td><td><?=number_format((float)$line['m'],2)?></td><td><?=number_format((float)$line['amount'],2)?></td></tr><?php endforeach;?></table>
<?php if(($r['status']??'saved')!=='void'):?><form method="post" class="danger-form" onsubmit="return confirm('ยืนยันยกเลิกรอบนี้?')"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><input type="hidden" name="action" value="void_round"><input type="hidden" name="core" value="<?=h($r['core'])?>"><input type="hidden" name="round_id" value="<?=(int)$r['id']?>"><input name="reason" placeholder="เหตุผลที่ยกเลิก" required><input name="confirm" placeholder="พิมพ์ VOID" required><button>ยกเลิกรอบ</button></form><?php else:?><p>เหตุผล: <?=h((string)($r['void_reason']??'-'))?></p><?php endif;?></details></td></tr><?php endforeach;?></tbody></table></div></section>
<section class="panel" id="employee"><div class="panel-head"><div><small>EMPLOYEE SUMMARY</small><h2>สรุปตามพนักงาน</h2></div><span>กดหัวตารางเพื่อ Sort</span></div><div class="table-wrap"><table><thead><tr><th><?=$empSort('name','พนักงาน')?></th><th><?=$empSort('role','ตำแหน่ง')?></th><th><?=$empSort('d','D')?></th><th><?=$empSort('m','M')?></th><th><?=$empSort('drinks','ค่าดื่ม')?></th><th><?=$empSort('commission','ค่าคอม')?></th><th><?=$empSort('total','รวมรับ')?></th></tr></thead><tbody><?php foreach($employees as $r):?><tr><td><?=h($r['name'])?></td><td><?=h($r['role'])?></td><td><?=number_format($r['d'],2)?></td><td><?=number_format($r['m'],2)?></td><td><?=number_format($r['drinks'],2)?></td><td><?=number_format($r['commission'],2)?></td><td class="money"><?=number_format($r['total'],2)?></td></tr><?php endforeach;?></tbody></table></div></section>
<section class="panel danger-zone"><div class="panel-head"><div><small>REPORT MANAGEMENT</small><h2>เครื่องมือเคลียร์ Report</h2><p>เป็น Soft Delete เก็บประวัติไว้ และต้องยกเลิกรอบค่าดื่ม/ค่าคอมก่อน</p></div></div><div class="report-list"><?php foreach($batches as $b):?><article><div><b>#<?=(int)$b['id']?> <?=h((string)($b['source_name']??$b['filename']??'POS Report'))?></b><span><?=h((string)($b['period_start']??'').' – '.(string)($b['period_end']??''))?> · <?=h((string)($b['status']??'active'))?></span></div><?php if(($b['status']??'active')==='active'):?><details><summary>เคลียร์ Report</summary><form method="post" class="danger-form" onsubmit="return confirm('Report จะไม่สามารถนำไปคำนวณต่อ ยืนยันหรือไม่?')"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><input type="hidden" name="action" value="clear_report"><input type="hidden" name="batch_id" value="<?=(int)$b['id']?>"><input name="reason" placeholder="เหตุผลที่เคลียร์" required><input name="confirm" placeholder="พิมพ์ CLEAR" required><button>ยืนยันเคลียร์</button></form></details><?php else:?><span class="badge"><?=h((string)$b['status'])?></span><?php endif;?></article><?php endforeach;?></div></section>
</main></body></html>