<?php
require __DIR__.'/app/bootstrap.php';
require_once __DIR__.'/app/compat.php';
require_once __DIR__.'/app/pos-incentive.php';
require_once __DIR__.'/app/pos-r4.php';
$u=require_permission('employees.manage');$msg='';$err='';$action='';$preview=null;$previewStage=null;$previewGuess=[];$previewType='';$previewStats=[];
$month=(string)($_GET['month']??$_POST['month']??date('Y-m'));if(!posi_month_valid($month))$month=date('Y-m');
[$monthFrom,$monthTo]=posi_month_bounds($month);$periodMode=(string)($_GET['period_mode']??$_POST['period_mode']??'month');if(!in_array($periodMode,['month','week','cycle','custom'],true))$periodMode='month';
$periodFrom=(string)($_GET['date_from']??$_POST['date_from']??'');$periodTo=(string)($_GET['date_to']??$_POST['date_to']??'');$validDate=fn(string $date)=>(bool)preg_match('/^\d{4}-\d{2}-\d{2}$/',$date);
if(!$validDate($periodFrom)||!$validDate($periodTo)||$periodTo<$periodFrom){if($periodMode==='cycle'){$periodTo=$month.'-22';$periodFrom=date('Y-m-d',strtotime($periodTo.' -1 month'));}elseif($periodMode==='week'){$anchor=$month===date('Y-m')?date('Y-m-d'):$monthTo;$periodFrom=date('Y-m-d',strtotime('monday this week',strtotime($anchor)));$periodTo=date('Y-m-d',strtotime($periodFrom.' +6 days'));}else{$periodFrom=$monthFrom;$periodTo=$monthTo;}}
$month=substr($periodTo,0,7);[$monthFrom,$monthTo]=posi_month_bounds($month);$periodQuery=http_build_query(['month'=>$month,'period_mode'=>$periodMode,'date_from'=>$periodFrom,'date_to'=>$periodTo]);$uid=(int)($u['id']??0);
if($_SERVER['REQUEST_METHOD']==='POST'){csrf_check();$action=(string)($_POST['action']??'');try{
    if($action==='save_rule'){
        $ruleMonth=(string)($_POST['rule_month']??$month);if(!posi_month_valid($ruleMonth))throw new RuntimeException('เดือนของ Rule ไม่ถูกต้อง');if(posi_closing(db_load(),$ruleMonth))throw new RuntimeException('เดือนนี้ Final แล้ว กรุณา Reopen ก่อนแก้ Rule');$scope=(string)($_POST['scope_type']??'store');if(!in_array($scope,['store','team','employee'],true))$scope='store';$scopeValue='';if($scope==='team'){$scopeValue=trim((string)($_POST['scope_team']??''));if($scopeValue==='')throw new RuntimeException('กรุณาระบุ Team Code');}elseif($scope==='employee'){$scopeValue=(string)max(0,(int)($_POST['scope_employee_id']??0));if($scopeValue==='0')throw new RuntimeException('กรุณาเลือกพนักงาน');}$payout=(string)($_POST['payout_type']??'per_drink');if(!in_array($payout,['per_drink','percent_sales','fixed_bonus'],true))$payout='per_drink';$rid=(int)($_POST['rule_id']??0);$rule=['id'=>$rid,'month'=>$ruleMonth,'name'=>trim((string)($_POST['rule_name']??'Monthly Incentive'))?:'Monthly Incentive','enabled'=>!empty($_POST['enabled'])?1:0,'scope_type'=>$scope,'scope_value'=>$scopeValue,'target_sales'=>(string)posi_money($_POST['target_sales']??0),'payout_type'=>$payout,'reward_rate'=>(string)posi_money($_POST['reward_rate']??0),'note'=>trim((string)($_POST['note']??'')),'updated_at'=>date('c'),'updated_by'=>$uid];
        db_mutate(function($d)use($rule,$rid,$uid){if(!isset($d['pos_incentive_rules'])||!is_array($d['pos_incentive_rules']))$d['pos_incentive_rules']=[];$r=$rule;if($rid>0){$found=false;foreach($d['pos_incentive_rules'] as &$x)if((int)($x['id']??0)===$rid){$r['created_at']=$x['created_at']??date('c');$r['created_by']=$x['created_by']??$uid;$x=posi_rule_defaults(array_replace($x,$r));$found=true;break;}unset($x);if(!$found)throw new RuntimeException('ไม่พบ Rule');}else{$r['id']=next_id($d['pos_incentive_rules']);$r['created_at']=date('c');$r['created_by']=$uid;$d['pos_incentive_rules'][]=posi_rule_defaults($r);} $d['audit'][]=['at'=>date('c'),'action'=>'pos_incentive_rule_saved','rule_id'=>(int)$r['id'],'month'=>(string)$r['month'],'by'=>$uid];return $d;});$month=$ruleMonth;[$monthFrom,$monthTo]=posi_month_bounds($month);$msg='บันทึกเงื่อนไข Incentive แล้ว';
    }elseif($action==='delete_rule'){$rid=(int)($_POST['rule_id']??0);$snap=db_load();foreach(posi_rules($snap) as $rr)if((int)$rr['id']===$rid&&posi_closing($snap,(string)$rr['month']))throw new RuntimeException('เดือนนี้ Final แล้ว กรุณา Reopen ก่อนลบ Rule');db_mutate(function($d)use($rid,$uid){$before=count($d['pos_incentive_rules']??[]);$d['pos_incentive_rules']=array_values(array_filter($d['pos_incentive_rules']??[],fn($r)=>(int)($r['id']??0)!==$rid));if(count($d['pos_incentive_rules'])===$before)throw new RuntimeException('ไม่พบ Rule');$d['audit'][]=['at'=>date('c'),'action'=>'pos_incentive_rule_deleted','rule_id'=>$rid,'by'=>$uid];return $d;});$msg='ลบ Rule แล้ว';
    }elseif($action==='save_sales_commission_rule'){
        if(posi_closing(db_load(),$month))throw new RuntimeException('เดือนนี้ Final แล้ว กรุณา Reopen ก่อนแก้เงื่อนไข');
        $storeMinimum=(array)($_POST['store_minimum']??[]);$personalMinimum=(array)($_POST['personal_minimum']??[]);$minimumUnits=(array)($_POST['minimum_units']??[]);$ratePerUnit=(array)($_POST['rate_per_unit']??[]);$tiers=[];$tierCount=max(count($storeMinimum),count($personalMinimum),count($minimumUnits),count($ratePerUnit));
        for($i=0;$i<$tierCount;$i++){$tier=['id'=>$i+1,'store_minimum'=>posi_money($storeMinimum[$i]??0),'personal_minimum'=>posi_money($personalMinimum[$i]??0),'minimum_units'=>posi_money($minimumUnits[$i]??0),'rate_per_unit'=>posi_money($ratePerUnit[$i]??0)];if((float)$tier['rate_per_unit']<=0)continue;$tiers[]=$tier;}
        if(!$tiers)throw new RuntimeException('กรุณาเพิ่มอย่างน้อย 1 เงื่อนไข และระบุค่าคอมต่อบิลมากกว่า 0');$tiers=posi_sales_commission_tiers(['tiers'=>$tiers]);
        $rule=['month'=>$month,'period_from'=>$periodFrom,'period_to'=>$periodTo,'tiers'=>$tiers,'note'=>trim((string)($_POST['sales_rule_note']??'')),'updated_at'=>date('c'),'updated_by'=>$uid];
        db_mutate(function($d)use($rule,$month,$periodFrom,$periodTo,$uid){if(!isset($d['sales_commission_rules'])||!is_array($d['sales_commission_rules']))$d['sales_commission_rules']=[];$saved=false;foreach($d['sales_commission_rules'] as &$existing)if((string)($existing['period_from']??'')===$periodFrom&&(string)($existing['period_to']??'')===$periodTo){$existing=array_replace($existing,$rule);unset($existing['minimum_units'],$existing['rate_per_unit'],$existing['target_units'],$existing['target_bonus']);$saved=true;break;}unset($existing);if(!$saved)$d['sales_commission_rules'][]=$rule;$d['audit'][]=['at'=>date('c'),'action'=>'sales_commission_tiers_saved','month'=>$month,'period_from'=>$periodFrom,'period_to'=>$periodTo,'tier_count'=>count($rule['tiers']),'by'=>$uid];return $d;});$msg='บันทึก '.count($tiers).' ระดับเงื่อนไขและคำนวณค่าคอม Sales ใหม่แล้ว';
    }elseif($action==='upload_to_inbox'){
        $stored=posi_inbox_store_upload($_FILES['pos_file']??[]);$title=trim((string)($_POST['report_title']??''));if($title==='')$title=pathinfo((string)$stored['original_name'],PATHINFO_FILENAME);$detail=trim((string)($_POST['report_detail']??''));
        try{db_mutate(function($d)use($stored,$title,$detail,$periodMode,$periodFrom,$periodTo,$uid){if(!isset($d['pos_upload_inbox'])||!is_array($d['pos_upload_inbox']))$d['pos_upload_inbox']=[];foreach($d['pos_upload_inbox'] as $existing)if(($existing['sha256']??'')===$stored['sha256']&&(string)($existing['period_from']??'')===$periodFrom&&(string)($existing['period_to']??'')===$periodTo&&in_array((string)($existing['status']??''),['uploaded','processing','completed'],true))throw new RuntimeException('ไฟล์เดียวกันอยู่ในถังข้อมูลรอบนี้แล้ว · สถานะ '.posi_inbox_status_label((string)$existing['status']));$entry=array_replace($stored,['id'=>next_id($d['pos_upload_inbox']),'title'=>$title,'detail'=>$detail,'period_mode'=>$periodMode,'period_from'=>$periodFrom,'period_to'=>$periodTo,'status'=>'uploaded','uploaded_at'=>date('c'),'uploaded_by'=>$uid,'processed_at'=>'','processed_by'=>null,'batch_id'=>null,'error'=>'']);$d['pos_upload_inbox'][]=$entry;$d['audit'][]=['at'=>date('c'),'action'=>'pos_file_uploaded_to_inbox','inbox_id'=>$entry['id'],'period_from'=>$periodFrom,'period_to'=>$periodTo,'by'=>$uid];return $d;});}catch(Throwable $uploadError){$path=posi_inbox_dir().'/'.basename((string)$stored['stored_name']);if(is_file($path))@unlink($path);throw $uploadError;}$msg='เก็บไฟล์ไว้ในถังข้อมูล POS แล้ว · รอทีมฝ่ายจ่ายเงินเลือกไป Process';
    }elseif($action==='process_inbox'){
        $inboxId=max(0,(int)($_POST['inbox_id']??0));$snapshot=db_load();$entry=null;foreach($snapshot['pos_upload_inbox']??[] as $candidate)if((int)($candidate['id']??0)===$inboxId){$entry=$candidate;break;}if(!$entry)throw new RuntimeException('ไม่พบไฟล์ในถังข้อมูล');$entryStatus=(string)($entry['status']??'uploaded');if($entryStatus==='completed')throw new RuntimeException('ไฟล์นี้ Process สำเร็จแล้ว');if($entryStatus==='processing'&&strtotime((string)($entry['processing_at']??''))>=time()-900)throw new RuntimeException('ไฟล์นี้กำลังถูก Process โดยผู้ใช้อื่น กรุณารอให้เสร็จก่อน');
        db_mutate(function($d)use($inboxId,$uid){foreach($d['pos_upload_inbox']??[] as &$item)if((int)($item['id']??0)===$inboxId){$item['status']='processing';$item['processing_at']=date('c');$item['processed_by']=$uid;$item['error']='';break;}unset($item);return $d;});
        try{$path=posi_inbox_path($entry);$parsed=posi_parse_file($path,(string)$entry['ext'],0);$map=posi_guess_columns($parsed['headers']);$reportType=posi_report_type($map);if(($map['item']??-1)<0||($map['sales']??-1)<0||($reportType!=='product_summary'&&($map['date']??-1)<0))throw new RuntimeException('ระบบตรวจคอลัมน์ชื่อสินค้า/ยอดขายไม่ครบ');$from=(string)$entry['period_from'];$to=(string)$entry['period_to'];$stage=['name'=>(string)$entry['original_name'],'sha256'=>(string)$entry['sha256'],'ext'=>(string)$entry['ext'],'path'=>$path];$meta=['source_name'=>'POS Inbox '.$from.'_'.$to,'import_mode'=>'mtd_snapshot','period_start'=>$from,'period_end'=>$to,'report_type'=>$reportType];$batch=null;db_mutate(function($d)use($stage,$parsed,$map,$meta,$uid,$inboxId,&$batch){$batch=posi_commit_import($d,$stage,$parsed,$map,$meta,$uid);foreach($d['pos_upload_inbox']??[] as &$item)if((int)($item['id']??0)===$inboxId){$item['status']='completed';$item['processed_at']=date('c');$item['processed_by']=$uid;$item['batch_id']=(int)$batch['id'];$item['error']='';break;}unset($item);return $d;});$periodFrom=$from;$periodTo=$to;$month=substr($to,0,7);$msg='Process ไฟล์สำเร็จ '.(int)$batch['rows_imported'].' รายการ · พร้อม Sort และคำนวณ';}catch(Throwable $processError){db_mutate(function($d)use($inboxId,$processError,$uid){foreach($d['pos_upload_inbox']??[] as &$item)if((int)($item['id']??0)===$inboxId){$item['status']='failed';$item['error']=$processError->getMessage();$item['processed_at']=date('c');$item['processed_by']=$uid;break;}unset($item);return $d;});throw $processError;}
    }elseif($action==='commit_import'){$token=(string)($_POST['stage_token']??'');$stage=posi_stage_get($token);$parsed=posi_parse_file((string)$stage['path'],(string)$stage['ext'],0);$map=['date'=>(int)($_POST['map_date']??-1),'item'=>(int)($_POST['map_item']??-1),'group'=>(int)($_POST['map_group']??-1),'category'=>(int)($_POST['map_category']??-1),'qty'=>(int)($_POST['map_qty']??-1),'sales'=>(int)($_POST['map_sales']??-1),'cost'=>(int)($_POST['map_cost']??-1),'profit'=>(int)($_POST['map_profit']??-1),'ref'=>(int)($_POST['map_ref']??-1)];$reportType=(string)($_POST['report_type']??'transaction');if($map['item']<0||$map['sales']<0||($reportType!=='product_summary'&&$map['date']<0))throw new RuntimeException($reportType==='product_summary'?'ต้อง Mapping ชื่อสินค้าและราคาสุทธิ':'ต้อง Mapping วันที่ ชื่อเมนู และยอดขาย');$meta=['source_name'=>trim((string)($_POST['source_name']??'POS')),'import_mode'=>(string)($_POST['import_mode']??'period'),'period_start'=>(string)($_POST['period_start']??''),'period_end'=>(string)($_POST['period_end']??''),'report_type'=>$reportType];$batch=null;db_mutate(function($d)use($stage,$parsed,$map,$meta,$uid,&$batch){$batch=posi_commit_import($d,$stage,$parsed,$map,$meta,$uid);return $d;});posi_stage_clear($token);$month=(string)($batch['month']??$month);[$monthFrom,$monthTo]=posi_month_bounds($month);$msg='Import สำเร็จ '.(int)$batch['rows_imported'].' รายการ · ยอดสุทธิ '.number_format((float)$batch['total_sales'],2).' · ค่าดริ้ง Match '.(int)$batch['matched_rows'].' · รอตั้ง Alias '.(int)$batch['unmatched_rows'];
    }elseif($action==='void_batch'){$bid=(int)($_POST['batch_id']??0);$voided=null;db_mutate(function($d)use($bid,$uid,&$voided){$voided=posi_void_batch($d,$bid,$uid);return $d;});$msg='Void Import Batch #'.$bid.' แล้ว · แถวข้อมูลของ Batch นี้ถูกตัดออกจากการคำนวณ';
    }elseif($action==='remap'){if(posi_closing(db_load(),$month))throw new RuntimeException('เดือนนี้ Final แล้ว กรุณา Reopen ก่อน Re-map');$changed=0;db_mutate(function($d)use($month,$uid,&$changed){$changed=posi_remap_rows($d,$month);$d['audit'][]=['at'=>date('c'),'action'=>'pos_incentive_remap','month'=>$month,'changed'=>$changed,'by'=>$uid];return $d;});$msg='คำนวณ POS Mapping ใหม่แล้ว · เปลี่ยน '.$changed.' แถว';
    }elseif($action==='finalize'){if(empty($_POST['flow_ready']))throw new RuntimeException('กรุณาไปขั้นตอนสุดท้ายและตรวจข้อมูลก่อนบันทึก');$closing=null;db_mutate(function($d)use($month,$uid,&$closing){$closing=posi_close_month($d,$month,$uid);return $d;});$msg='Final Incentive เดือน '.$month.' แล้ว · หลังจากนี้หน้า Employee จะใช้อ้างอิง Snapshot นี้';
    }elseif($action==='reopen'){$n=0;db_mutate(function($d)use($month,$uid,&$n){$n=posi_reopen_month($d,$month,$uid);return $d;});$msg=$n?'Reopen เดือน '.$month.' แล้ว สามารถ Import/แก้ Rule และ Final ใหม่ได้':'ไม่พบรอบ Final';
    }
}catch(Throwable $e){$err=$e->getMessage();}}
$d=db_load();$inboxItems=array_values($d['pos_upload_inbox']??[]);usort($inboxItems,fn($a,$b)=>strcmp((string)($b['uploaded_at']??''),(string)($a['uploaded_at']??'')));$inboxItems=array_slice($inboxItems,0,30);$inboxWaiting=count(array_filter($inboxItems,fn($item)=>in_array((string)($item['status']??''),['uploaded','failed'],true)));$currency=(string)($d['settings']['currency']??'THB');$productRows=posi_active_rows_period($d,$periodFrom,$periodTo);$salesMode=!empty($_GET['sales_commission'])||$action==='save_sales_commission_rule';$salesRule=posi_sales_commission_rule($d,$month,$periodFrom,$periodTo);$salesCommissionRows=posi_sales_commission_results($d,$month,$salesRule,$periodFrom,$periodTo);$salesTotalUnits=array_sum(array_map(fn($row)=>(float)$row['units'],$salesCommissionRows));$salesTotalCommission=array_sum(array_map(fn($row)=>(float)$row['commission'],$salesCommissionRows));$summary=posi_period_summary_dates($d,$periodFrom,$periodTo);$rules=posi_rules($d,$month);$results=posi_month_results($d,$month);$closing=posi_closing($d,$month);$unmatched=posi_unmatched_items($d,$month,20);$employees=array_values(array_filter($d['employees']??[],fn($e)=>!empty($e['active'])&&in_array((string)($e['position']??''),['sales','pr'],true)));$batches=array_values(array_filter($d['pos_import_batches']??[],fn($b)=>(string)($b['month']??'')===$month));usort($batches,fn($a,$b)=>strcmp((string)($b['imported_at']??''),(string)($a['imported_at']??'')));
$primaryRule=null;foreach($rules as $r)if(!empty($r['enabled'])&&$r['scope_type']==='store'){$primaryRule=$r;break;}if(!$primaryRule)foreach($rules as $r)if(!empty($r['enabled'])){$primaryRule=$r;break;}$target=$primaryRule?(float)$primaryRule['target_sales']:0;$primaryActual=$primaryRule?posi_scope_sales($d,$month,$primaryRule):0.0;$progress=$target>0?min(999,$primaryActual/$target*100):0;$projectedUnlock=$target<=0||($primaryActual*(float)$summary['projection_factor'])>=$target;$defaultPeriodEnd=$month===date('Y-m')?date('Y-m-d'):$monthTo;
$prev=date('Y-m',strtotime($month.'-01 -1 month'));$next=date('Y-m',strtotime($month.'-01 +1 month'));
$sortConfirmed=!empty($_GET['sort_confirmed'])||!empty($_POST['sort_confirmed'])||$action==='save_sales_commission_rule';$r4Rule=posi_r4_rule($d,$month,$periodFrom,$periodTo);
$hasActiveRule=false;foreach($rules as $flowRule){if(!empty($flowRule['enabled'])){$hasActiveRule=true;break;}}
$step1Done=(int)($summary['rows']??0)>0;$step2Done=$step1Done&&$sortConfirmed&&count($salesCommissionRows)>0;$step3Done=$step2Done&&(!empty($r4Rule['enabled'])||!empty($salesRule['updated_at'])||$hasActiveRule);
$requestedStep=max(1,min(4,(int)($_GET['step']??$_POST['step']??($step1Done?2:1))));$maxStep=$step1Done?2:1;if($step2Done)$maxStep=3;if($step3Done)$maxStep=4;$step=min($requestedStep,$maxStep);if($requestedStep>$maxStep&&$err==='')$err='ยังไปขั้นตอนนั้นไม่ได้ กรุณาทำขั้นตอนปัจจุบันให้ครบก่อน';
$flowQuery=$periodQuery.($sortConfirmed?'&sort_confirmed=1':'');
function posi_payout_label(string $p): string{return ['per_drink'=>'บาท / Drink','percent_sales'=>'% จากยอดขายรายบุคคล','fixed_bonus'=>'โบนัสคงที่'][$p]??$p;}
?><!doctype html><html lang="th"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>MR BAR — POS Incentive & Commission</title><link rel="stylesheet" href="assets/admin.css?v=1240"><link rel="stylesheet" href="assets/admin-v14.css?v=1240"><link rel="stylesheet" href="assets/pos-incentive-v1298.css?v=1298"><link rel="stylesheet" href="assets/pos-incentive-wizard-v1351.css?v=1360"><link rel="stylesheet" href="assets/pos-incentive-product-sort-v1360.css?v=1370"><link rel="stylesheet" href="assets/pos-sales-commission-v1370.css?v=1380"><link rel="stylesheet" href="assets/pos-period-picker-v1380.css?v=1390"><link rel="stylesheet" href="assets/pos-upload-inbox-v1390.css?v=1390"><link rel="stylesheet" href="assets/pos-wizard-strict-v1410.css?v=1410"><link rel="stylesheet" href="assets/pos-sales-tiers-v1420.css?v=1420"></head><body class="admin-v14-page posi-page posi-wizard-step-<?=$step?> <?=$salesMode?'posi-sales-mode':''?>"><?php require_once __DIR__.'/app/admin-nav.php';echo admin_sidebar('incentive',$u);?><main class="posi-shell"><header class="posi-head"><div><p>PEOPLE / POS INCENTIVE</p><h1>POS Incentive & Commission</h1><span>Import Excel/CSV → Mapping เมนูเข้าพนักงาน → ประมาณการรายสัปดาห์ → Final รายเดือน</span></div><div><a href="employees.php">Employee Center</a><a href="payroll-attendance.php">Attendance & Payroll</a></div></header><?php if($msg):?><div class="posi-notice ok">✓ <?=h($msg)?></div><?php endif;?><?php if($err):?><div class="posi-notice err">⚠ <?=h($err)?></div><?php endif;?>
<section class="posi-period-picker" data-period-picker>
<div class="posi-period-title"><div><small>รอบข้อมูลที่กำลังคำนวณ</small><h2><?=h(date('d/m/Y',strtotime($periodFrom)))?> – <?=h(date('d/m/Y',strtotime($periodTo)))?></h2><p>เลือกได้ทั้งรายเดือน รายสัปดาห์ รอบตัดบัญชี 22–22 หรือช่วงวันที่กำหนดเอง</p></div><em class="<?= $closing?'final':'estimate' ?>"><?= $closing?'FINAL':'กำลังคำนวณ' ?></em></div>
<form method="get" class="posi-period-form"><input type="hidden" name="step" value="<?=$step?>"><?php if($salesMode):?><input type="hidden" name="sales_commission" value="1"><?php endif;?>
<label><span>รูปแบบรอบ</span><select name="period_mode" data-period-mode><option value="month" <?=$periodMode==='month'?'selected':''?>>รายเดือน</option><option value="week" <?=$periodMode==='week'?'selected':''?>>รายสัปดาห์</option><option value="cycle" <?=$periodMode==='cycle'?'selected':''?>>รอบวันที่ 22 – 22</option><option value="custom" <?=$periodMode==='custom'?'selected':''?>>กำหนดช่วงเอง</option></select></label>
<label><span>วันที่เริ่มต้น</span><input type="date" name="date_from" value="<?=h($periodFrom)?>" data-period-from required></label>
<label><span>วันที่สิ้นสุด / คำนวณถึงวันนี้</span><input type="date" name="date_to" value="<?=h($periodTo)?>" data-period-to required></label>
<button>แสดงข้อมูลรอบนี้ →</button></form>
<div class="posi-period-shortcuts"><button type="button" data-period-shortcut="month">เดือนนี้</button><button type="button" data-period-shortcut="week">สัปดาห์นี้</button><button type="button" data-period-shortcut="cycle">รอบ 22–22</button><button type="button" data-period-shortcut="today">ตั้งแต่ต้นรอบถึงวันนี้</button></div>
</section>
<?php if($step>1):?><section class="posi-period-locked"><div><small>รอบข้อมูลที่เลือกจากขั้นแรก</small><b><?=h(date('d/m/Y',strtotime($periodFrom)))?> – <?=h(date('d/m/Y',strtotime($periodTo)))?></b></div><span>ใช้รอบเดียวกันทุกขั้นตอน</span></section><?php endif;?>
<section class="posi-workflow posi-wizard-nav" aria-label="ขั้นตอนดำเนินงาน">
<div class="<?=$step===1?'active':($step1Done?'done':'locked')?>"><i><?=$step1Done?'✓':'1'?></i><span><b>1. ถังข้อมูล POS</b><small><?=$step===1?'กำลังทำขั้นตอนนี้':($step1Done?'เสร็จแล้ว':'รอดำเนินการ')?></small></span></div>
<div class="<?=$step===2?'active':($step2Done?'done':($maxStep<2?'locked':''))?>"><i><?=$step2Done?'✓':'2'?></i><span><b>2. Sort และตรวจข้อมูล</b><small><?=$step===2?'กำลังทำขั้นตอนนี้':($step2Done?'เสร็จแล้ว':'ต้องทำขั้นก่อนหน้า')?></small></span></div>
<div class="<?=$step===3?'active':($step3Done?'done':($maxStep<3?'locked':''))?>"><i><?=$step3Done?'✓':'3'?></i><span><b>3. คำนวณค่าคอม</b><small><?=$step===3?'กำลังทำขั้นตอนนี้':($step3Done?'เสร็จแล้ว':'ต้องทำขั้นก่อนหน้า')?></small></span></div>
<div class="<?=$step===4?'active':($closing?'done':'locked')?>"><i><?=$closing?'✓':'4'?></i><span><b>4. ตรวจและบันทึก</b><small><?=$step===4?'ขั้นตอนสุดท้าย':($closing?'บันทึกแล้ว':'ต้องทำขั้นก่อนหน้า')?></small></span></div>
</section>
<section class="posi-kpis"><article class="sales"><small>ยอดขายสุทธิจาก POS</small><b><?=number_format((float)$summary['actual_sales'],2)?></b><span><?=h($currency)?> · <?=number_format((int)$summary['rows'])?> รายการสินค้า</span></article><article class="drinks"><small>หน่วยค่าดริ้ง D + M</small><b><?=number_format((float)($summary['drink_units']??0),0)?></b><span><i>D <?=number_format((float)($summary['d_units']??0),0)?></i><i>M <?=number_format((float)($summary['m_units']??0),0)?></i></span></article><article class="<?=($summary['unmatched_rows']??0)>0?'warn':'good'?>"><small>จับคู่ชื่อพนักงาน</small><b><?=number_format((int)$summary['matched_rows'])?> / <?=number_format((int)$summary['matched_rows']+(int)$summary['unmatched_rows'])?></b><span><?=($summary['unmatched_rows']??0)>0?'รอตั้ง Alias '.number_format((int)$summary['unmatched_rows']).' รายการ':'รายการค่าดริ้งพร้อมคำนวณ'?></span></article><article class="<?=$target>0&&$projectedUnlock?'good':'target'?>"><small>เป้ายอดขายเดือนนี้</small><b><?=$target>0?number_format($target,0):'ยังไม่ตั้ง'?></b><span><?=$target>0?number_format($progress,1).'% · ประมาณปลายเดือน '.number_format((float)$summary['projected_sales'],0):'สร้าง Rule เพื่อเริ่มคำนวณค่าคอม'?></span></article></section>
<div class="posi-grid posi-setup-grid"><section class="posi-card"><div class="posi-card-head"><div><small>02 / COMMISSION RULE</small><h2>กติกาค่าคอมประจำเดือน</h2><p>กำหนดเป้ายอดร้าน เงื่อนไขปลดล็อก และอัตราจ่ายต่อหน่วย</p></div></div><form method="post" class="posi-rule-form"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><input type="hidden" name="action" value="save_rule"><label>เดือน<input type="month" name="rule_month" value="<?=h($month)?>" required></label><label>ชื่อ Rule<input name="rule_name" value="Monthly Drink Commission" required></label><label>Scope<select name="scope_type"><option value="store">ยอดรวมทั้งร้าน</option><option value="team">ยอดเฉพาะทีม</option><option value="employee">ยอดเฉพาะพนักงาน</option></select></label><label>Team Code<input name="scope_team" placeholder="เช่น TEAM-A"></label><label>พนักงาน<select name="scope_employee_id"><option value="0">— ใช้เมื่อ Scope = พนักงาน —</option><?php foreach($employees as $e):?><option value="<?=(int)$e['id']?>"><?=h(workforce_employee_label($e))?></option><?php endforeach;?></select></label><label>เป้ายอดขาย<input type="number" step="0.01" min="0" name="target_sales" placeholder="2500000" required></label><label>วิธีจ่าย<select name="payout_type"><option value="per_drink">บาท / Drink</option><option value="percent_sales">% ยอดขายรายบุคคล</option><option value="fixed_bonus">โบนัสคงที่</option></select></label><label>Rate / มูลค่า<input type="number" step="0.01" min="0" name="reward_rate" placeholder="80" required></label><label class="wide">หมายเหตุ<input name="note" placeholder="เช่น ถึงยอด 2.5M จ่าย 80 บาทต่อ Drink"></label><label class="check"><input type="checkbox" name="enabled" value="1" checked> เปิดใช้ Rule</label><button>บันทึก Rule</button></form><div class="posi-rule-list"><?php if(!$rules):?><div class="empty">ยังไม่มี Rule เดือนนี้</div><?php endif;?><?php foreach($rules as $r):?><article><div><b><?=h((string)$r['name'])?></b><span><?=h(strtoupper((string)$r['scope_type']))?> · Target <?=number_format((float)$r['target_sales'],0)?> · <?=number_format((float)$r['reward_rate'],2)?> <?=h(posi_payout_label((string)$r['payout_type']))?></span><?php if(!empty($r['note'])):?><small><?=h((string)$r['note'])?></small><?php endif;?></div><form method="post" onsubmit="return confirm('ลบ Rule นี้?')"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><input type="hidden" name="action" value="delete_rule"><input type="hidden" name="month" value="<?=h($month)?>"><input type="hidden" name="rule_id" value="<?=(int)$r['id']?>"><button>ลบ</button></form></article><?php endforeach;?></div></section>
<section class="posi-card posi-import-card"><div class="posi-card-head row"><div><small>01 / IMPORT POS</small><h2>ถังข้อมูลรายงาน POS</h2><p>ทีม IT อัปโหลดไฟล์พร้อมรายละเอียดไว้ก่อน · ทีมจ่ายเงินค่อยเลือกไฟล์ไป Process, Sort และคำนวณภายหลัง</p></div><span class="posi-format-badge">XLSX / CSV</span></div>
<?php if(!$preview):?><form method="post" enctype="multipart/form-data" class="posi-inbox-upload"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><input type="hidden" name="action" value="upload_to_inbox"><input type="hidden" name="month" value="<?=h($month)?>"><input type="hidden" name="period_mode" value="<?=h($periodMode)?>"><input type="hidden" name="date_from" value="<?=h($periodFrom)?>"><input type="hidden" name="date_to" value="<?=h($periodTo)?>">
<div class="posi-inbox-upload-head"><div><small>สำหรับทีมอัปโหลด / IT</small><h3>เพิ่มไฟล์เข้าถังข้อมูล POS</h3><p>ขั้นตอนนี้เก็บไฟล์และรายละเอียดไว้ก่อน ยังไม่คำนวณและไม่กระทบยอด</p></div><span>รอบ <?=h(date('d/m/Y',strtotime($periodFrom)))?> – <?=h(date('d/m/Y',strtotime($periodTo)))?></span></div>
<div class="posi-inbox-fields"><label><span>ชื่อรายงาน</span><input name="report_title" placeholder="เช่น ยอดขายตามสินค้า รอบ 22 ก.ค.–22 ส.ค."></label><label><span>รายละเอียดส่งต่อทีมจ่ายเงิน</span><input name="report_detail" placeholder="เช่น ไฟล์ปิดรอบจาก POS เครื่องหลัก"></label></div>
<label class="posi-inbox-file"><span class="upload-icon">↑</span><div><b>เลือกไฟล์ Excel / CSV</b><small>สูงสุด 20MB · ระบบเก็บไฟล์ต้นฉบับไว้ตรวจย้อนหลัง</small></div><input type="file" name="pos_file" accept=".xlsx,.csv" required></label><button>อัปโหลดเข้าถังข้อมูล →</button></form>
<section class="posi-inbox-list"><div class="posi-inbox-list-head"><div><small>สำหรับทีมตรวจและจ่ายเงิน</small><h3>ถังข้อมูลรอดำเนินการ</h3></div><span><?=$inboxWaiting?> งานรอ</span></div>
<?php if(!$inboxItems):?><div class="empty">ยังไม่มีไฟล์ในถังข้อมูล</div><?php endif;?>
<?php foreach($inboxItems as $item):$status=(string)($item['status']??'uploaded');$canProcess=in_array($status,['uploaded','failed'],true)||($status==='processing'&&strtotime((string)($item['processing_at']??''))<time()-900);?><article class="posi-inbox-item status-<?=h($status)?>"><div class="posi-inbox-icon"><?=strtoupper(h((string)($item['ext']??'POS')))?></div><div class="posi-inbox-info"><div><b><?=h((string)($item['title']??$item['original_name']??'POS Report'))?></b><em><?=h(posi_inbox_status_label($status))?></em></div><span><?=h((string)($item['original_name']??''))?> · <?=number_format((float)($item['size']??0)/1024,1)?> KB</span><p><?=h((string)($item['detail']??'ไม่มีรายละเอียด'))?></p><small>รอบ <?=h(date('d/m/Y',strtotime((string)$item['period_from'])))?> – <?=h(date('d/m/Y',strtotime((string)$item['period_to'])))?> · อัปโหลด <?=h((string)($item['uploaded_at']??''))?> · ผู้ส่ง #<?=(int)($item['uploaded_by']??0)?></small><?php if($status==='failed'&&!empty($item['error'])):?><strong><?=h((string)$item['error'])?></strong><?php endif;?></div><div class="posi-inbox-action"><?php if($canProcess):?><form method="post"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><input type="hidden" name="action" value="process_inbox"><input type="hidden" name="inbox_id" value="<?=(int)$item['id']?>"><input type="hidden" name="month" value="<?=h(substr((string)$item['period_to'],0,7))?>"><input type="hidden" name="period_mode" value="<?=h((string)($item['period_mode']??'custom'))?>"><input type="hidden" name="date_from" value="<?=h((string)$item['period_from'])?>"><input type="hidden" name="date_to" value="<?=h((string)$item['period_to'])?>"><button>เลือกไฟล์นี้ไป Process →</button></form><?php elseif($status==='processing'):?><span>กำลังประมวลผล…</span><?php else:?><span>Batch #<?=(int)($item['batch_id']??0)?> · เสร็จแล้ว</span><?php endif;?></div></article><?php endforeach;?></section>
<?php else:$previewType=$previewType?:posi_report_type($previewGuess);$previewStats=$previewStats?:posi_preview_summary($preview,$previewGuess);?><div class="preview-file"><div><b><?=h((string)$previewStage['name'])?></b><span>พบหัวตารางที่แถว <?=number_format((int)($preview['header_row']??1))?> · SHA <?=h(substr((string)$previewStage['sha256'],0,12))?>…</span></div><em><?=$previewType==='product_summary'?'รายงานยอดขายตามสินค้า':'รายละเอียดรายการขาย'?></em></div>
<div class="posi-preview-stats"><article><small>รายการสินค้า</small><b><?=number_format((int)$previewStats['rows'])?></b></article><article><small>ยอดขายสุทธิ</small><b><?=number_format((float)$previewStats['net_sales'],2)?></b></article><article><small>ค่าดริ้ง D</small><b><?=number_format((float)$previewStats['d_units'],0)?></b></article><article><small>ค่าดริ้ง M</small><b><?=number_format((float)$previewStats['m_units'],0)?></b></article><article class="accent"><small>D + M รวม</small><b><?=number_format((float)$previewStats['candidate_units'],0)?></b></article></div>
<div class="posi-detect-note"><b>ระบบตรวจพบและตั้งค่าให้แล้ว</b><span>ยอดสุทธิใช้เทียบ Target ทั้งร้าน · ค่าดริ้งนับเฉพาะสินค้า D/M ในกลุ่ม PR และ Sales · รายการอื่นเก็บเป็นยอดร้านแต่ไม่คิดค่าดริ้ง<?php if($previewType==='product_summary'):?> · ไฟล์ไม่มีวันที่ ระบบจะลงรอบ <strong><?=h($month)?></strong> ตามช่อง “ถึง” ด้านล่าง<?php endif;?></span></div>
<form method="post" class="posi-map-form"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><input type="hidden" name="action" value="commit_import"><input type="hidden" name="month" value="<?=h($month)?>"><input type="hidden" name="stage_token" value="<?=h((string)$previewStage['token'])?>"><input type="hidden" name="report_type" value="<?=h($previewType)?>">
<div class="posi-map-primary"><label>ชื่อแหล่งข้อมูล<input name="source_name" value="POS Product Summary" required></label><label>วิธีนำเข้า<select name="import_mode"><option value="mtd_snapshot" <?=$previewType==='product_summary'?'selected':''?>>Snapshot เดือนนี้ · แทนไฟล์เก่า</option><option value="period">เพิ่มข้อมูลเฉพาะช่วง</option></select></label><label>ตั้งแต่<input type="date" name="period_start" value="<?=h($monthFrom)?>" required></label><label>ถึง<input type="date" name="period_end" value="<?=h($defaultPeriodEnd)?>" required></label></div>
<details class="posi-mapping" <?=$previewType==='product_summary'?'':'open'?>><summary>ตรวจคอลัมน์ที่ระบบเลือก <small>เปิดเมื่อต้องการแก้ Mapping</small></summary><div><?php $mapLabels=['date'=>'วันที่ขาย (ไม่จำเป็นสำหรับรายงานสรุป)','item'=>'ชื่อสินค้า *','group'=>'กลุ่มสินค้า','category'=>'หมวดสินค้า','qty'=>'จำนวนการขาย','sales'=>'ราคาสุทธิ *','ref'=>'เลขที่บิล (ถ้ามี)'];foreach($mapLabels as $mk=>$ml):?><label><?=h($ml)?><select name="map_<?=h($mk)?>"><option value="-1">— ไม่ใช้ —</option><?php foreach($preview['headers'] as $i=>$hh):?><option value="<?=$i?>" <?=($previewGuess[$mk]??-1)===$i?'selected':''?>><?=h($hh)?></option><?php endforeach;?></select></label><?php endforeach;?></div></details><button class="posi-commit">ยืนยัน Import และคำนวณค่าดริ้ง</button></form>
<section class="posi-product-sort" data-posi-product-sort>
<div class="posi-product-sort-head"><div><small>STEP 2 / PRODUCT SORT</small><h2>เลือกกลุ่มสินค้า แล้วดูยอดเฉพาะที่ต้องการ</h2><p>เลือกหัวข้อหลักก่อน แล้วเลือกค่าภายในหัวข้อนั้น เช่น <b>กลุ่มสินค้า → Sales</b> ระบบจะแสดงเฉพาะรายการที่ตรงและคำนวณยอดให้ทันที</p></div><span>ไม่แก้ไขไฟล์ต้นฉบับ</span></div>
<div class="posi-product-sort-controls">
<div class="posi-axis" role="group" aria-label="หัวข้อหลัก"><button type="button" class="active" data-sort-axis="group">กลุ่มสินค้า</button><button type="button" data-sort-axis="category">หมวดหมู่สินค้า</button></div>
<label><span>เลือกค่าที่ต้องการ</span><select data-sort-value><option value="">ทั้งหมด</option></select></label>
<label class="posi-product-search"><span>ค้นหาในผลลัพธ์</span><input type="search" data-sort-search placeholder="ชื่อสินค้า / รหัสสินค้า"></label>
<button type="button" class="posi-sort-calculate" data-sort-calculate>คำนวณยอดที่เลือก →</button>
</div>
<div class="posi-product-sort-summary">
<article><small>รายการที่แสดง</small><b data-sort-rows>0</b><span>รายการ</span></article>
<article><small>จำนวนการขาย</small><b data-sort-qty>0</b><span>หน่วย</span></article>
<article><small>ยอดขายสุทธิ</small><b data-sort-sales>0.00</b><span><?=h($currency)?></span></article>
<article class="accent"><small>ยอดเฉลี่ยต่อรายการ</small><b data-sort-average>0.00</b><span><?=h($currency)?></span></article>
</div>
<div class="posi-sort-status" data-sort-status>กำลังเตรียมข้อมูลจากคอลัมน์ที่ Mapping…</div>
</section>
<div class="posi-preview posi-product-table"><table data-product-table data-group-index="<?=(int)($previewGuess['group']??-1)?>" data-category-index="<?=(int)($previewGuess['category']??-1)?>" data-qty-index="<?=(int)($previewGuess['qty']??-1)?>" data-sales-index="<?=(int)($previewGuess['sales']??-1)?>"><thead><tr><?php foreach($preview['headers'] as $hh):?><th><?=h($hh)?></th><?php endforeach;?></tr></thead><tbody><?php foreach($preview['rows'] as $row):?><tr><?php foreach($preview['headers'] as $i=>$hh):?><td><?=h((string)($row[$i]??''))?></td><?php endforeach;?></tr><?php endforeach;?></tbody></table></div><?php endif;?>
<div class="import-help"><b>ป้องกันยอดซ้ำ</b><span>ไฟล์เดิมถูกตรวจด้วย SHA-256 · Snapshot ใหม่แทน Snapshot เก่าของเดือนเดียวกัน · ต้อง Reopen ก่อนแก้เดือนที่ Final แล้ว</span></div></section></div>
<section class="posi-card wide posi-product-explorer">
<div class="posi-card-head row"><div><small>02 / SORT IMPORTED PRODUCTS</small><h2>ข้อมูลสินค้าที่นำเข้าแล้ว</h2><p>เลือกกลุ่มหรือหมวดหมู่ แล้วตรวจยอดเฉพาะชุดที่ต้องการก่อนเข้าสู่การคำนวณค่าคอม</p></div><span class="posi-format-badge"><?=number_format(count($productRows))?> รายการ</span></div>
<?php if(!$productRows):?><div class="empty">ยังไม่มีข้อมูลสินค้าในเดือนนี้ · กลับไปขั้นที่ 1 เพื่ออัปโหลดไฟล์ POS</div><?php else:?>
<section class="posi-product-sort" data-posi-product-sort>
<div class="posi-product-sort-head"><div><small>FILTER & CALCULATE</small><h2>เลือกหัวข้อหลักและค่าที่ต้องการ</h2><p>ตัวอย่าง: <b>กลุ่มสินค้า → Sales</b> ระบบจะแสดงเฉพาะรายการในกลุ่มและรวมยอดให้ทันที</p></div><span>ข้อมูลที่ Import แล้ว</span></div>
<div class="posi-product-sort-controls"><div class="posi-axis" role="group" aria-label="หัวข้อหลัก"><button type="button" class="active" data-sort-axis="group">กลุ่มสินค้า</button><button type="button" data-sort-axis="category">หมวดหมู่สินค้า</button></div><label><span>เลือกค่าที่ต้องการ</span><select data-sort-value><option value="">ทั้งหมด</option></select></label><label class="posi-product-search"><span>ค้นหาในผลลัพธ์</span><input type="search" data-sort-search placeholder="ชื่อสินค้า"></label><button type="button" class="posi-sort-calculate" data-sort-calculate>คำนวณยอดที่เลือก →</button></div>
<div class="posi-product-sort-summary"><article><small>รายการที่แสดง</small><b data-sort-rows>0</b><span>รายการ</span></article><article><small>จำนวนการขาย</small><b data-sort-qty>0</b><span>หน่วย</span></article><article><small>ยอดขายสุทธิ</small><b data-sort-sales>0.00</b><span><?=h($currency)?></span></article><article class="accent"><small>ยอดเฉลี่ยต่อรายการ</small><b data-sort-average>0.00</b><span><?=h($currency)?></span></article></div><div class="posi-sort-status" data-sort-status>กำลังเตรียมข้อมูล…</div><a class="posi-sales-commission-link" data-sales-commission-link hidden href="?<?=h($periodQuery)?>&step=3&sales_commission=1&sort_confirmed=1">ขั้นตอนต่อไป: คำนวณค่าคอม Sales →</a>
</section>
<div class="posi-preview posi-product-table"><table data-product-table data-group-index="1" data-category-index="2" data-qty-index="3" data-sales-index="4"><thead><tr><th>ชื่อสินค้า</th><th>กลุ่มสินค้า</th><th>หมวดหมู่สินค้า</th><th>จำนวนการขาย</th><th>ยอดขายสุทธิ</th><th>วันที่</th><th>สถานะค่าคอม</th></tr></thead><tbody><?php foreach($productRows as $row):?><tr><td><?=h((string)($row['item_name']??''))?></td><td><?=h((string)($row['item_group']??''))?></td><td><?=h((string)($row['item_category']??''))?></td><td><?=number_format((float)($row['qty']??0),2)?></td><td><?=number_format((float)($row['net_sales']??0),2)?></td><td><?=h((string)($row['sale_date']??''))?></td><td><?=!empty($row['incentive_candidate'])?'นำไปคำนวณ':'ยอดร้าน'?></td></tr><?php endforeach;?></tbody></table></div>
<?php endif;?></section>
<section class="posi-sales-commission-stage">
<div class="posi-sales-stage-head"><div><small>STEP 3 / SALES COMMISSION</small><h2>คำนวณค่าคอม Sales รายเดือน</h2><p>ระบบรวมรายการ D/M ของ Sales คนเดียวกัน และใช้จำนวนการขายเป็นจำนวนบิล/โต๊ะสำหรับคำนวณ</p></div><div><a href="pos-r4.php?<?=h($periodQuery)?>&sort_confirmed=1">เปิดกติกา R4 / Hold →</a></div></div>
<div class="posi-sales-source">
<div class="posi-sales-section-title"><div><small>ข้อมูลตั้งต้น</small><h3>Sales และจำนวนบิล/โต๊ะ</h3></div><span><?=number_format(count($salesCommissionRows))?> Sales</span></div>
<div class="posi-sales-two-column"><table><thead><tr><th>ชื่อ Sales</th><th>จำนวนการขาย (บิล/โต๊ะ)</th></tr></thead><tbody><?php if(!$salesCommissionRows):?><tr><td colspan="2" class="empty">ไม่พบสินค้าในกลุ่ม Sales เดือนนี้</td></tr><?php endif;?><?php foreach($salesCommissionRows as $row):?><tr><td><b><?=h((string)$row['sales_name'])?></b></td><td><strong><?=number_format((float)$row['units'],2)?></strong></td></tr><?php endforeach;?></tbody><tfoot><tr><th>รวมทั้งหมด</th><th><?=number_format($salesTotalUnits,2)?></th></tr></tfoot></table></div>
</div>
<div class="posi-sales-rule-panel">
<div class="posi-sales-section-title"><div><small>เงื่อนไขการคำนวณแบบหลายระดับ</small><h3>กำหนดเป้าค่าคอม Sales</h3><p>ระบบตรวจจากระดับเป้าสูงสุดลงมา และใช้ระดับแรกที่ผ่านครบทุกเงื่อนไข</p></div><span><?=h(date('d/m/Y',strtotime($periodFrom)))?> – <?=h(date('d/m/Y',strtotime($periodTo)))?></span></div>
<div class="posi-tier-store-summary"><div><small>ยอดขายรวมร้านจาก POS รอบนี้</small><b><?=number_format((float)$summary['actual_sales'],2)?> <?=h($currency)?></b></div><p>ยอดนี้ดึงอัตโนมัติจากไฟล์ POS ไม่ต้องกรอกซ้ำ · <a href="pos-r4.php?<?=h($periodQuery)?>">กรอกยอดขายรายบุคคลของ Sales →</a></p></div>
<form method="post" class="posi-sales-rule-form posi-tier-form" data-tier-form><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><input type="hidden" name="action" value="save_sales_commission_rule"><input type="hidden" name="month" value="<?=h($month)?>"><input type="hidden" name="period_mode" value="<?=h($periodMode)?>"><input type="hidden" name="date_from" value="<?=h($periodFrom)?>"><input type="hidden" name="date_to" value="<?=h($periodTo)?>">
<div class="posi-tier-head"><b>ระดับ</b><b>ยอดรวมร้านขั้นต่ำ</b><b>ยอดรายบุคคลขั้นต่ำ</b><b>จำนวนบิลขั้นต่ำ</b><b>ค่าคอม/บิล</b><b></b></div>
<div class="posi-tier-rows" data-tier-rows>
<?php $tierRows=$salesRule['tiers']?:[['store_minimum'=>0,'personal_minimum'=>0,'minimum_units'=>0,'rate_per_unit'=>0]];foreach($tierRows as $tierIndex=>$tier):?>
<div class="posi-tier-row"><strong data-tier-number>ระดับ <?=$tierIndex+1?></strong><label><span>ยอดรวมร้านขั้นต่ำ</span><div><input type="number" min="0" step="0.01" name="store_minimum[]" value="<?=h((string)$tier['store_minimum'])?>" required><em><?=h($currency)?></em></div></label><label><span>ยอดรายบุคคลขั้นต่ำ</span><div><input type="number" min="0" step="0.01" name="personal_minimum[]" value="<?=h((string)$tier['personal_minimum'])?>" required><em><?=h($currency)?></em></div></label><label><span>จำนวนบิลขั้นต่ำ</span><div><input type="number" min="0" step="1" name="minimum_units[]" value="<?=h((string)$tier['minimum_units'])?>" required><em>บิล/โต๊ะ</em></div></label><label><span>ค่าคอมต่อบิล</span><div><input type="number" min="0.01" step="0.01" name="rate_per_unit[]" value="<?=h((string)$tier['rate_per_unit'])?>" required><em><?=h($currency)?></em></div></label><button type="button" class="posi-tier-remove" data-remove-tier aria-label="ลบเงื่อนไข">ลบ</button></div>
<?php endforeach;?>
</div>
<button type="button" class="posi-tier-add" data-add-tier>＋ เพิ่มเงื่อนไขอีกระดับ</button>
<label class="wide"><span>หมายเหตุสำหรับฝ่ายจ่ายเงิน</span><input name="sales_rule_note" value="<?=h((string)$salesRule['note'])?>" placeholder="เช่น ใช้อัตราสูงสุดที่ผ่านครบทั้ง 3 เงื่อนไข"></label>
<button class="posi-tier-save">บันทึกทุกเงื่อนไขและคำนวณใหม่ →</button></form>
<div class="posi-sales-formula">สูตร: ตรวจ <b>ยอดร้าน + ยอดรายบุคคล + จำนวนบิล</b> จากระดับสูงลงต่ำ แล้วคำนวณ <b>จำนวนบิล × อัตราของระดับที่ผ่าน</b></div>
</div>
<div class="posi-sales-payout">
<div class="posi-sales-section-title"><div><small>ผลการคำนวณ</small><h3>ตารางจ่ายค่าคอม Sales</h3></div><button type="button" data-copy-sales-table>คัดลอกตารางสำหรับจ่ายเงิน</button></div>
<div class="posi-sales-payout-kpis"><article><small>Sales ทั้งหมด</small><b><?=number_format(count($salesCommissionRows))?></b><span>คน</span></article><article><small>จำนวนการขายรวม</small><b><?=number_format($salesTotalUnits,2)?></b><span>บิล/โต๊ะ</span></article><article class="pay"><small>ค่าคอมรวม</small><b><?=number_format($salesTotalCommission,2)?></b><span><?=h($currency)?></span></article></div>
<div class="posi-sales-result-table"><table data-sales-payout-table><thead><tr><th>ชื่อ Sales</th><th>ยอดขายส่วนตัว</th><th>บิล/โต๊ะ</th><th>ระดับที่ผ่าน</th><th>อัตรา/บิล</th><th>ยอดจ่ายรวม</th><th>สถานะ</th></tr></thead><tbody><?php foreach($salesCommissionRows as $row):$matched=$row['matched_tier'];?><tr><td><?=h((string)$row['sales_name'])?></td><td><?=number_format((float)$row['personal_sales'],2)?></td><td><?=number_format((float)$row['units'],2)?></td><td><?=$matched?'ร้าน ≥ '.number_format((float)$matched['store_minimum'],0).' / คน ≥ '.number_format((float)$matched['personal_minimum'],0).' / บิล ≥ '.number_format((float)$matched['minimum_units'],0):'—'?></td><td><?=number_format((float)$row['rate_per_unit'],2)?></td><td><b><?=number_format((float)$row['commission'],2)?></b></td><td><?=$row['eligible']?'ผ่านเงื่อนไข':'ไม่ผ่านทุกระดับ'?></td></tr><?php endforeach;?></tbody><tfoot><tr><th>รวม</th><th></th><th><?=number_format($salesTotalUnits,2)?></th><th></th><th></th><th><?=number_format($salesTotalCommission,2)?></th><th></th></tr></tfoot></table></div>
<p class="posi-copy-feedback" data-copy-feedback></p>
</div>
</section>
<section class="posi-card wide posi-results-stage"><div class="posi-card-head row"><div><small>03 / LIVE ESTIMATE</small><h2>สรุปค่าดริ้งและค่าคอมรายพนักงาน</h2><p>แสดง D/M ที่จับคู่ได้ ยอดสะสม อัตราจ่าย และยอดประมาณการก่อนปิดรอบ</p></div><div class="card-actions"><form method="post"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><input type="hidden" name="action" value="remap"><input type="hidden" name="month" value="<?=h($month)?>"><button>↻ Re-map จาก Alias ล่าสุด</button></form><?php if(!$closing):?><form method="post" onsubmit="return confirm('Final Incentive เดือน <?=h($month)?>? ระบบจะ Snapshot ยอดรายคน ณ ตอนนี้')"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><input type="hidden" name="action" value="finalize"><input type="hidden" name="month" value="<?=h($month)?>"><button class="final">Final เดือนนี้</button></form><?php else:?><form method="post" onsubmit="return confirm('Reopen รอบ Final เพื่อแก้ข้อมูล?')"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><input type="hidden" name="action" value="reopen"><input type="hidden" name="month" value="<?=h($month)?>"><button class="warn">Reopen</button></form><?php endif;?></div></div><div class="posi-results"><table><thead><tr><th>พนักงาน</th><th>ทีม</th><th>ค่าดริ้ง D / M</th><th>ยอด D/M ที่จับคู่</th><th>อัตราจ่าย</th><th>สถานะ</th><th>ยอดจ่ายปัจจุบัน</th><th>ประมาณการปลายเดือน</th></tr></thead><tbody><?php if(!$results):?><tr><td colspan="8" class="empty">ยังไม่มี Sales/PR ที่เปิด POS Incentive · ตั้ง Alias ที่ Employee Center ก่อน</td></tr><?php endif;?><?php foreach($results as $r):$e=posi_employee_by_id($d,(int)$r['employee_id']);?><tr><td><b><?=h($e?workforce_employee_label($e):'#'.$r['employee_id'])?></b><small><?=h(workforce_position_label((string)$r['position']))?><?=$r['team_lead']?' · หัวทีม':''?></small></td><td><?=h($r['team_code']?:'—')?></td><td><div class="drink-split"><span class="d">D <b><?=number_format((float)($r['d_units']??0),0)?></b></span><span class="m">M <b><?=number_format((float)($r['m_units']??0),0)?></b></span></div><small>รวม <?=number_format((float)$r['units'],0)?> หน่วย</small></td><td><b><?=number_format((float)$r['sales'],2)?></b></td><td><?=number_format((float)$r['rate'],2)?></td><td><span class="state <?=h((string)$r['status'])?>"><?=h(posi_status_label((string)$r['status']))?></span><?php if($r['rule_name']):?><small><?=h((string)$r['rule_name'])?></small><?php endif;?></td><td><b><?=number_format((float)$r['recognized_pay'],2)?></b><small><?=(float)$r['potential_pay']>(float)$r['recognized_pay']?'Potential '.number_format((float)$r['potential_pay'],2):h($currency)?></small></td><td><b><?=number_format((float)$r['projected_potential_pay'],2)?></b><small><?=number_format((float)$r['projected_units'],1)?> units · <?=$r['projected_unlock']?'มีแนวโน้มผ่าน':'ยังไม่ผ่าน Target'?></small></td></tr><?php endforeach;?></tbody></table></div></section>
<div class="posi-grid lower"><section class="posi-card"><div class="posi-card-head"><div><small>04 / UNMATCHED</small><h2>ชื่อ D/M ที่ยังไม่ตรงกับพนักงาน</h2><p>แสดงเฉพาะรายการค่าดริ้ง ไม่รวมอาหาร เครื่องดื่ม Member และสินค้าอื่น</p></div></div><div class="unmatched-list"><?php if(!$unmatched):?><div class="empty">ไม่มีรายการ Unmatched</div><?php endif;?><?php foreach($unmatched as $x):?><article><div><b><?=h((string)$x['item_name'])?></b><span><?=number_format((float)$x['qty'],2)?> units · <?=$x['rows']?> rows</span></div><strong><?=number_format((float)$x['sales'],2)?> <?=h($currency)?></strong></article><?php endforeach;?></div></section><section class="posi-card"><div class="posi-card-head"><div><small>05 / IMPORT HISTORY</small><h2>ประวัติ Batch เดือนนี้</h2><p>เก็บต้นทาง, Hash, ช่วงวันที่ และสถานะเพื่อ Audit ย้อนหลัง</p></div></div><div class="batch-list"><?php if(!$batches):?><div class="empty">ยังไม่มี Import เดือนนี้</div><?php endif;?><?php foreach($batches as $b):?><article class="<?=h((string)($b['status']??'active'))?>"><div><b>#<?=(int)$b['id']?> · <?=h((string)$b['source_name'])?></b><span><?=h((string)$b['filename'])?></span><small><?=h((string)$b['period_start'])?> → <?=h((string)$b['period_end'])?> · <?=h(strtoupper((string)$b['import_mode']))?></small></div><div><strong><?=number_format((float)$b['total_sales'],2)?></strong><span><?=(int)$b['rows_imported']?> สินค้า · D/M Match <?=(int)$b['matched_rows']?><?=isset($b['candidate_rows'])?' / '.(int)$b['candidate_rows']:''?></span><em><?=h(strtoupper((string)$b['status']))?></em><?php if(($b['status']??'active')==='active'&&!$closing):?><form method="post" class="batch-void" onsubmit="return confirm('Void Batch #<?=(int)$b['id']?>? ยอดจาก Batch นี้จะถูกตัดออกจากการคำนวณ')"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><input type="hidden" name="action" value="void_batch"><input type="hidden" name="month" value="<?=h($month)?>"><input type="hidden" name="batch_id" value="<?=(int)$b['id']?>"><button>Void</button></form><?php endif;?></div></article><?php endforeach;?></div></section></div>
<nav class="posi-flow-actions" aria-label="ไปขั้นตอนก่อนหน้าหรือถัดไป">
<?php if($step>1):?><a class="prev" href="?<?=h($flowQuery)?>&step=<?=$step-1?>">← ขั้นตอนก่อนหน้า</a><?php else:?><span></span><?php endif;?>
<div><b>ขั้นตอน <?=$step?> จาก 4</b><small><?=['','อัปโหลดและเลือกช่วงข้อมูล','Sort และตรวจรายการ','ตั้งกติกาและคำนวณ','ตรวจสอบก่อนบันทึก'][$step]?></small></div>
<?php if($step===1):?><?php if($step1Done):?><a class="next" href="?<?=h($flowQuery)?>&step=2">ขั้นตอนต่อไป →</a><?php else:?><button disabled>ต้อง Process ไฟล์ก่อน</button><?php endif;?>
<?php elseif($step===2):?><button disabled>เลือกกลุ่ม Sales และกด “ขั้นตอนต่อไป” ด้านบน</button>
<?php elseif($step===3):?><?php if($step3Done):?><a class="next" href="?<?=h($flowQuery)?>&step=4">ขั้นตอนต่อไป: ตรวจข้อมูล →</a><?php else:?><button disabled>ต้องบันทึกกติกาค่าคอมก่อน</button><?php endif;?>
<?php else:?><?php if(!$closing):?><form method="post" onsubmit="return confirm('ตรวจข้อมูลครบแล้วและต้องการบันทึก Final รอบนี้ใช่หรือไม่?')"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><input type="hidden" name="action" value="finalize"><input type="hidden" name="flow_ready" value="1"><input type="hidden" name="step" value="4"><input type="hidden" name="month" value="<?=h($month)?>"><input type="hidden" name="period_mode" value="<?=h($periodMode)?>"><input type="hidden" name="date_from" value="<?=h($periodFrom)?>"><input type="hidden" name="date_to" value="<?=h($periodTo)?>"><button class="save">บันทึกข้อมูลและ Final รอบนี้ ✓</button></form><?php else:?><strong class="saved">✓ บันทึก Final แล้ว</strong><?php endif;?><?php endif;?>
</nav>
<section class="posi-explain"><b>หลักการคำนวณ</b><p>ยอดสุทธิทุกสินค้าจาก POS ใช้ตรวจ Target ของร้าน ส่วนค่าดริ้งนับเฉพาะรายการ D/M ในกลุ่ม PR และ Sales ที่จับคู่ Alias สำเร็จ แล้วคูณอัตราจ่ายของพนักงานหรือ Rule รายเดือน ก่อน Final ระบบแสดงเป็นยอดประมาณการเท่านั้น</p></section><footer>MR BAR POS Incentive & Commission · <?=h((string)(app_config()['pack']??'MR BAR'))?> · Schema v<?=h((string)($d['meta']['schema']??24))?></footer></main><script src="assets/pos-incentive-product-sort-v1360.js?v=1380" defer></script><script src="assets/pos-period-picker-v1380.js?v=1380" defer></script><script src="assets/pos-sales-tiers-v1420.js?v=1420" defer></script></body></html>
