<?php
require __DIR__.'/app/bootstrap.php';
require_once __DIR__.'/app/compat.php';
require_once __DIR__.'/app/pos-incentive.php';
require_once __DIR__.'/app/pos-r4.php';
$u=require_permission('employees.manage');$uid=(int)($u['id']??0);$msg='';$err='';
$month=(string)($_GET['month']??$_POST['month']??date('Y-m'));if(!posi_month_valid($month))$month=date('Y-m');
[$monthFrom,$monthTo]=posi_month_bounds($month);$from=(string)($_GET['date_from']??$_POST['date_from']??$monthFrom);$to=(string)($_GET['date_to']??$_POST['date_to']??$monthTo);
if(!preg_match('/^\d{4}-\d{2}-\d{2}$/',$from)||!preg_match('/^\d{4}-\d{2}-\d{2}$/',$to)||$to<$from){$from=$monthFrom;$to=$monthTo;}
if($_SERVER['REQUEST_METHOD']==='POST'){csrf_check();$action=(string)($_POST['action']??'');try{
 if($action==='save_r4_rule'){
  $mode=in_array((string)($_POST['sales_rate_mode']??''),['amount_per_unit','percent_normal'],true)?(string)$_POST['sales_rate_mode']:'amount_per_unit';
  $tierMins=[600000,500000,400000,300000,200000,0];$tiers=[];foreach($tierMins as $min)$tiers[]=['min_sales'=>$min,'rate'=>max(0,(float)($_POST['tier_'.$min]??0))];
  $rule=['enabled'=>!empty($_POST['enabled'])?1:0,'month'=>$month,'period_from'=>$from,'period_to'=>$to,'store_target'=>max(0,(float)($_POST['store_target']??0)),'waive_reduction'=>!empty($_POST['waive_reduction'])?1:0,'sales_normal_rate'=>max(0,(float)($_POST['sales_normal_rate']??0)),'sales_rate_mode'=>$mode,'sales_tiers'=>$tiers,'pr_normal_rate'=>max(0,(float)($_POST['pr_normal_rate']??5)),'pr_reduced_rate'=>max(0,(float)($_POST['pr_reduced_rate']??4)),'hold_enabled'=>!empty($_POST['hold_enabled'])?1:0,'release_month'=>(string)($_POST['release_month']??''),'release_store_target'=>max(0,(float)($_POST['release_store_target']??0)),'release_personal_target'=>max(0,(float)($_POST['release_personal_target']??0)),'release_deadline'=>(string)($_POST['release_deadline']??''),'online_exception_enabled'=>!empty($_POST['online_exception_enabled'])?1:0,'online_required_days'=>max(0,(int)($_POST['online_required_days']??0)),'online_required_tables'=>max(0,(int)($_POST['online_required_tables']??4)),'note'=>trim((string)($_POST['note']??'')),'updated_at'=>date('c'),'updated_by'=>$uid];
  db_mutate(function($d)use($rule,$from,$to,$uid){if(!isset($d['pos_r4_rules'])||!is_array($d['pos_r4_rules']))$d['pos_r4_rules']=[];$saved=false;foreach($d['pos_r4_rules'] as &$x)if((string)($x['period_from']??'')===$from&&(string)($x['period_to']??'')===$to){$x=array_replace($x,$rule);$saved=true;break;}unset($x);if(!$saved)$d['pos_r4_rules'][]=$rule;$d['audit'][]=['at'=>date('c'),'action'=>'pos_r4_rule_saved','period_from'=>$from,'period_to'=>$to,'by'=>$uid];return $d;});$msg='บันทึกกติกา R4 และคำนวณใหม่แล้ว';
 }elseif($action==='save_employee_input'){
  $eid=max(0,(int)($_POST['employee_id']??0));if($eid<=0)throw new RuntimeException('กรุณาเลือกพนักงาน');
  $input=['period_from'=>$from,'period_to'=>$to,'employee_id'=>$eid,'personal_sales'=>max(0,(float)($_POST['personal_sales']??0)),'online_post_days'=>max(0,(int)($_POST['online_post_days']??0)),'online_required_days'=>max(0,(int)($_POST['online_required_days']??0)),'online_tables'=>max(0,(int)($_POST['online_tables']??0)),'exception_approved'=>!empty($_POST['exception_approved'])?1:0,'exception_approved_by'=>!empty($_POST['exception_approved'])?$uid:null,'note'=>trim((string)($_POST['input_note']??'')),'updated_at'=>date('c'),'updated_by'=>$uid];
  db_mutate(function($d)use($input,$eid,$from,$to,$uid){if(!isset($d['pos_r4_employee_inputs'])||!is_array($d['pos_r4_employee_inputs']))$d['pos_r4_employee_inputs']=[];$saved=false;foreach($d['pos_r4_employee_inputs'] as &$x)if((int)($x['employee_id']??0)===$eid&&(string)($x['period_from']??'')===$from&&(string)($x['period_to']??'')===$to){$x=array_replace($x,$input);$saved=true;break;}unset($x);if(!$saved)$d['pos_r4_employee_inputs'][]=$input;$d['audit'][]=['at'=>date('c'),'action'=>'pos_r4_employee_input_saved','employee_id'=>$eid,'period_from'=>$from,'period_to'=>$to,'by'=>$uid];return $d;});$msg='บันทึกยอดส่วนตัวและหลักฐานออนไลน์แล้ว';
 }elseif($action==='map_menu_alias'){
  $eid=max(0,(int)($_POST['employee_id']??0));$alias=trim((string)($_POST['menu_alias']??''));if($eid<=0||$alias==='')throw new RuntimeException('กรุณาเลือกพนักงานและชื่อเมนู');
  db_mutate(function($d)use($eid,$alias,$from,$to,$uid){$found=false;foreach($d['employees']??[] as &$employee){$cfg=posi_employee_cfg($employee);$aliases=$cfg['aliases'];$aliases=array_values(array_filter($aliases,fn($x)=>posi_norm((string)$x)!==posi_norm($alias)));if((int)($employee['id']??0)===$eid){if(empty($employee['active'])||!in_array((string)($employee['position']??''),['sales','pr'],true))throw new RuntimeException('เลือกได้เฉพาะ Sales/PR ที่ใช้งาน');$aliases[]=$alias;$cfg['enabled']=1;$found=true;}$cfg['aliases']=array_values(array_unique($aliases));$employee['pos_incentive']=$cfg;}unset($employee);if(!$found)throw new RuntimeException('ไม่พบพนักงาน');$changed=posi_remap_rows_period($d,$from,$to);$d['audit'][]=['at'=>date('c'),'action'=>'pos_menu_alias_mapped','alias'=>$alias,'employee_id'=>$eid,'rows_changed'=>$changed,'by'=>$uid];return $d;});$msg='ผูกชื่อเมนูกับ Card พนักงานและ Re-map รอบนี้แล้ว';
 }elseif($action==='snapshot_holds'){
  $snapshot=db_load();$rule=posi_r4_rule($snapshot,$month,$from,$to);if(empty($rule['enabled']))throw new RuntimeException('กรุณาเปิดและบันทึกกติกา R4 ก่อน');$rows=posi_r4_sales_results($snapshot,$month,$rule,$from,$to);
  db_mutate(function($d)use($rows,$from,$to,$uid){if(!isset($d['pos_commission_holds'])||!is_array($d['pos_commission_holds']))$d['pos_commission_holds']=[];foreach($rows as $row){$eid=(int)($row['employee_id']??0);$amount=(float)($row['held_amount']??0);if($eid<=0||$amount<=0)continue;$found=false;foreach($d['pos_commission_holds'] as &$hold)if((int)($hold['employee_id']??0)===$eid&&(string)($hold['source_period_from']??'')===$from&&(string)($hold['source_period_to']??'')===$to){if(($hold['status']??'held')!=='released'){$hold['amount']=$amount;$hold['updated_at']=date('c');}$found=true;break;}unset($hold);if(!$found)$d['pos_commission_holds'][]=['id'=>next_id($d['pos_commission_holds']),'employee_id'=>$eid,'source_period_from'=>$from,'source_period_to'=>$to,'amount'=>$amount,'status'=>'held','created_at'=>date('c'),'created_by'=>$uid,'released_at'=>'','released_by'=>null];}$d['audit'][]=['at'=>date('c'),'action'=>'pos_r4_holds_snapshotted','period_from'=>$from,'period_to'=>$to,'by'=>$uid];return $d;});$msg='บันทึกรายการเงิน Hold แล้ว';
 }elseif($action==='release_hold'){
  $hid=max(0,(int)($_POST['hold_id']??0));db_mutate(function($d)use($hid,$uid){foreach($d['pos_commission_holds']??[] as &$hold)if((int)($hold['id']??0)===$hid){$hold['status']='released';$hold['released_at']=date('c');$hold['released_by']=$uid;break;}unset($hold);return $d;});$msg='ยืนยันคืนเงิน Hold แล้ว';
 }
}catch(Throwable $e){$err=$e->getMessage();}}
$d=db_load();$rule=posi_r4_rule($d,$month,$from,$to);$results=posi_r4_sales_results($d,$month,$rule,$from,$to);$storeSales=posi_r4_store_sales($d,$from,$to);
$employees=array_values(array_filter($d['employees']??[],fn($e)=>!empty($e['active'])&&in_array((string)($e['position']??''),['sales','pr'],true)));
$unmapped=[];foreach($results as $row)if(empty($row['employee_id']))$unmapped[]=$row;
$holds=array_values(array_filter($d['pos_commission_holds']??[],fn($h)=>(string)($h['source_period_from']??'')===$from&&(string)($h['source_period_to']??'')===$to));
$q=h(http_build_query(['month'=>$month,'date_from'=>$from,'date_to'=>$to]));
?><!doctype html><html lang="th"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>MR BAR — R4 Commission</title><link rel="stylesheet" href="assets/admin.css?v=1240"><link rel="stylesheet" href="assets/admin-v14.css?v=1240"><link rel="stylesheet" href="assets/pos-incentive-v1298.css?v=1298"><link rel="stylesheet" href="assets/pos-r4-v1400.css?v=1400"></head><body class="admin-v14-page r4-page"><?php require_once __DIR__.'/app/admin-nav.php';echo admin_sidebar('incentive',$u);?><main class="r4-shell">
<header class="r4-head"><div><small>POS / R4 COMMISSION ENGINE</small><h1>กติกาค่าคอม Sales & PR</h1><p><?=h(date('d/m/Y',strtotime($from)))?> – <?=h(date('d/m/Y',strtotime($to)))?> · Mapping เมนู → Card พนักงาน → คำนวณ → Hold/คืนเงิน</p></div><a href="pos-incentive.php?<?=$q?>&step=3&sales_commission=1">← POS Incentive</a></header>
<?php if($msg):?><div class="r4-notice ok">✓ <?=h($msg)?></div><?php endif;?><?php if($err):?><div class="r4-notice err">⚠ <?=h($err)?></div><?php endif;?>
<section class="r4-kpis"><article><small>ยอดรวมร้าน</small><b><?=number_format($storeSales,2)?></b><span>เป้า <?=number_format((float)$rule['store_target'],0)?> บาท</span></article><article class="<?=$storeSales>=(float)$rule['store_target']?'good':'warn'?>"><small>สถานะยอดร้าน</small><b><?=$storeSales>=(float)$rule['store_target']?'ถึงเป้า':'ไม่ถึงเป้า'?></b><span><?=$rule['waive_reduction']?'ยกเว้นการลดเดือนนี้':'ใช้เงื่อนไข R4'?></span></article><article><small>จับคู่ Card แล้ว</small><b><?=count($results)-count($unmapped)?> / <?=count($results)?></b><span>ต้องครบก่อนบันทึก Hold</span></article><article><small>เงิน Hold รอบนี้</small><b><?=number_format(array_sum(array_map(fn($r)=>(float)$r['held_amount'],$results)),2)?></b><span>บาท</span></article></section>
<section class="r4-card"><div class="r4-title"><div><small>1 / RULE SETTINGS</small><h2>ตั้งกติกา R4 สำหรับรอบนี้</h2></div><em><?=$rule['enabled']?'เปิดใช้งาน':'ยังไม่เปิด'?></em></div>
<form method="post" class="r4-rule-grid"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><input type="hidden" name="action" value="save_r4_rule"><input type="hidden" name="month" value="<?=h($month)?>"><input type="hidden" name="date_from" value="<?=h($from)?>"><input type="hidden" name="date_to" value="<?=h($to)?>">
<label>เป้ายอดรวมร้าน<input type="number" name="store_target" value="<?=h((string)$rule['store_target'])?>"></label><label>อัตราปกติ Sales<input type="number" name="sales_normal_rate" value="<?=h((string)$rule['sales_normal_rate'])?>"></label><label>รูปแบบอัตรา<select name="sales_rate_mode"><option value="amount_per_unit" <?=$rule['sales_rate_mode']==='amount_per_unit'?'selected':''?>>บาทต่อบิล/โต๊ะ</option><option value="percent_normal" <?=$rule['sales_rate_mode']==='percent_normal'?'selected':''?>>เปอร์เซ็นต์ของค่าคอมปกติ</option></select></label><label>PR ปกติ/ดื่ม<input type="number" name="pr_normal_rate" value="<?=h((string)$rule['pr_normal_rate'])?>"></label><label>PR เมื่อยอดร้านไม่ถึง<input type="number" name="pr_reduced_rate" value="<?=h((string)$rule['pr_reduced_rate'])?>"></label>
<?php foreach($rule['sales_tiers'] as $tier):?><label>ยอดส่วนตัว ≥ <?=number_format((float)$tier['min_sales'],0)?> <input type="number" name="tier_<?=(int)$tier['min_sales']?>" value="<?=h((string)$tier['rate'])?>"></label><?php endforeach;?>
<label>เดือนตรวจคืน Hold<input type="month" name="release_month" value="<?=h((string)$rule['release_month'])?>"></label><label>เป้ายอดร้านเพื่อคืนทั้งทีม<input type="number" name="release_store_target" value="<?=h((string)$rule['release_store_target'])?>"></label><label>เป้าส่วนตัวเพื่อคืนรายคน<input type="number" name="release_personal_target" value="<?=h((string)$rule['release_personal_target'])?>"></label><label>กำหนดคืนภายใน<input type="date" name="release_deadline" value="<?=h((string)$rule['release_deadline'])?>"></label><label>จำนวนวันโพสต์ที่ต้องครบ<input type="number" name="online_required_days" value="<?=h((string)$rule['online_required_days'])?>"></label><label>โต๊ะจากออนไลน์ขั้นต่ำ<input type="number" name="online_required_tables" value="<?=h((string)$rule['online_required_tables'])?>"></label>
<label class="check"><input type="checkbox" name="enabled" value="1" <?=$rule['enabled']?'checked':''?>> เปิดใช้ R4</label><label class="check"><input type="checkbox" name="waive_reduction" value="1" <?=$rule['waive_reduction']?'checked':''?>> ยกเว้นการลดทั้งหมด</label><label class="check"><input type="checkbox" name="hold_enabled" value="1" <?=$rule['hold_enabled']?'checked':''?>> เก็บส่วนต่างเป็น Hold</label><label class="check"><input type="checkbox" name="online_exception_enabled" value="1" <?=$rule['online_exception_enabled']?'checked':''?>> เปิดข้อยกเว้นออนไลน์</label><label class="wide">หมายเหตุ<input name="note" value="<?=h((string)$rule['note'])?>"></label><button class="wide">บันทึกกติกาและคำนวณใหม่</button></form></section>
<section class="r4-card"><div class="r4-title"><div><small>2 / MENU MAPPING</small><h2>ผูกชื่อเมนูจาก POS กับ Card พนักงาน</h2><p>Alias ที่บันทึกจะติดกับพนักงานและใช้จับคู่อัตโนมัติในไฟล์รอบต่อไป</p></div><em><?=count($unmapped)?> ยังไม่ผูก</em></div>
<?php if(!$unmapped):?><div class="r4-empty">รายการทั้งหมดถูกผูกกับ Card พนักงานแล้ว</div><?php endif;?><?php foreach($unmapped as $row):?><form method="post" class="r4-map-row"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><input type="hidden" name="action" value="map_menu_alias"><input type="hidden" name="month" value="<?=h($month)?>"><input type="hidden" name="date_from" value="<?=h($from)?>"><input type="hidden" name="date_to" value="<?=h($to)?>"><input type="hidden" name="menu_alias" value="<?=h((string)$row['sales_name'])?>"><div><b><?=h((string)$row['sales_name'])?></b><span><?=number_format((float)$row['units'],2)?> บิล/โต๊ะ</span></div><select name="employee_id" required><option value="">— เลือก Card พนักงาน —</option><?php foreach($employees as $e):?><option value="<?=(int)$e['id']?>"><?=h((string)$e['code'].' · '.workforce_employee_label($e).' · '.workforce_position_label((string)$e['position']))?></option><?php endforeach;?></select><button>ผูกและ Re-map</button></form><?php endforeach;?></section>
<section class="r4-card"><div class="r4-title"><div><small>3 / EMPLOYEE INPUT</small><h2>ยอดส่วนตัวและเงื่อนไขออนไลน์</h2><p>ยอดส่วนตัว 600k ไม่ได้อยู่ในไฟล์ค่าคอม D/M จึงต้องกรอกหรือนำเข้าจากรายงานยอด Sales อีกชุด</p></div></div>
<div class="r4-input-list"><?php foreach($results as $row):if(empty($row['employee_id']))continue;$e=posi_employee_by_id($d,(int)$row['employee_id']);$input=$row['employee_input'];?><form method="post" class="r4-employee-row"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><input type="hidden" name="action" value="save_employee_input"><input type="hidden" name="month" value="<?=h($month)?>"><input type="hidden" name="date_from" value="<?=h($from)?>"><input type="hidden" name="date_to" value="<?=h($to)?>"><input type="hidden" name="employee_id" value="<?=(int)$row['employee_id']?>"><div class="person"><b><?=h($e?workforce_employee_label($e):(string)$row['sales_name'])?></b><span><?=h($e?(string)$e['code']:'')?> · <?=number_format((float)$row['units'],2)?> บิล/โต๊ะ</span></div><label>ยอดขายส่วนตัว<input type="number" name="personal_sales" value="<?=h((string)$input['personal_sales'])?>"></label><label>โพสต์แล้ว/วัน<input type="number" name="online_post_days" value="<?=h((string)$input['online_post_days'])?>"></label><label>จำนวนวันที่ต้องโพสต์<input type="number" name="online_required_days" value="<?=h((string)$input['online_required_days'])?>"></label><label>ลูกค้าออนไลน์/โต๊ะ<input type="number" name="online_tables" value="<?=h((string)$input['online_tables'])?>"></label><label class="check"><input type="checkbox" name="exception_approved" value="1" <?=$input['exception_approved']?'checked':''?>> ผู้จัดการอนุมัติยกเว้น</label><label>หมายเหตุ<input name="input_note" value="<?=h((string)$input['note'])?>"></label><button>บันทึก</button></form><?php endforeach;?></div></section>
<section class="r4-card"><div class="r4-title"><div><small>4 / CALCULATION</small><h2>ผลคำนวณพร้อมจ่ายและเงิน Hold</h2></div><form method="post"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><input type="hidden" name="action" value="snapshot_holds"><input type="hidden" name="month" value="<?=h($month)?>"><input type="hidden" name="date_from" value="<?=h($from)?>"><input type="hidden" name="date_to" value="<?=h($to)?>"><button>บันทึกรายการ Hold</button></form></div>
<div class="r4-table"><table><thead><tr><th>Card พนักงาน</th><th>เมนู/Alias</th><th>บิล/โต๊ะ</th><th>ยอดส่วนตัว</th><th>Rate ปกติ</th><th>Rate ใช้จริง</th><th>ยอดปกติ</th><th>จ่ายรอบนี้</th><th>Hold</th><th>เหตุผล</th></tr></thead><tbody><?php foreach($results as $row):$e=!empty($row['employee_id'])?posi_employee_by_id($d,(int)$row['employee_id']):null;?><tr class="<?=h((string)$row['mapping_status'])?>"><td><?php if($e):?><b><a href="employees.php?employee_id=<?=(int)$e['id']?>"><?=h(workforce_employee_label($e))?></a></b><small><?=h((string)$e['code'])?> · ผูกแล้ว · เปิด Card ได้</small><?php else:?><b>ยังไม่ผูก Card</b><?php endif;?></td><td><?=h((string)$row['sales_name'])?></td><td><?=number_format((float)$row['units'],2)?></td><td><?=number_format((float)$row['employee_input']['personal_sales'],2)?></td><td><?=number_format((float)$row['normal_rate'],2)?></td><td><?=number_format((float)$row['applied_rate'],2)?></td><td><?=number_format((float)$row['normal_commission'],2)?></td><td><b><?=number_format((float)$row['commission'],2)?></b></td><td><?=number_format((float)$row['held_amount'],2)?></td><td><?=h((string)$row['reason'])?></td></tr><?php endforeach;?></tbody></table></div></section>
<section class="r4-card"><div class="r4-title"><div><small>5 / HOLD LEDGER</small><h2>บัญชีเงิน Hold และการคืนเงิน</h2></div></div><div class="r4-holds"><?php if(!$holds):?><div class="r4-empty">ยังไม่มีรายการ Hold ที่บันทึก</div><?php endif;?><?php foreach($holds as $hold):$e=posi_employee_by_id($d,(int)$hold['employee_id']);$release=posi_r4_release_state($d,$rule,(int)$hold['employee_id']);?><article><div><b><?=h($e?workforce_employee_label($e):'#'.$hold['employee_id'])?></b><span><?=number_format((float)$hold['amount'],2)?> บาท · <?=h((string)$hold['status'])?></span><small><?=h((string)$release['reason'])?></small></div><?php if(($hold['status']??'held')==='held'&&!empty($release['eligible'])):?><form method="post"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><input type="hidden" name="action" value="release_hold"><input type="hidden" name="hold_id" value="<?=(int)$hold['id']?>"><input type="hidden" name="month" value="<?=h($month)?>"><input type="hidden" name="date_from" value="<?=h($from)?>"><input type="hidden" name="date_to" value="<?=h($to)?>"><button>ยืนยันคืนเงิน</button></form><?php endif;?></article><?php endforeach;?></div></section>
</main></body></html>