<?php
require __DIR__.'/app/bootstrap.php';
require_once __DIR__.'/app/compat.php';
require_once __DIR__.'/app/pos-incentive.php';
require_once __DIR__.'/app/pos-r4.php';
$u=require_permission('employees.manage');$msg='';$err='';$action='';$preview=null;$previewStage=null;$previewGuess=[];$previewType='';$previewStats=[];
$month=(string)($_GET['month']??$_POST['month']??date('Y-m'));if(!posi_month_valid($month))$month=date('Y-m');
[$monthFrom,$monthTo]=posi_month_bounds($month);$periodMode=(string)($_GET['period_mode']??$_POST['period_mode']??'month');if(!in_array($periodMode,['month','week','cycle','custom'],true))$periodMode='month';
$periodFrom=(string)($_GET['date_from']??$_POST['date_from']??'');$periodTo=(string)($_GET['date_to']??$_POST['date_to']??'');$validDate=fn(string $date)=>(bool)preg_match('/^\d{4}-\d{2}-\d{2}$/',$date);
if(!$validDate($periodFrom)||!$validDate($periodTo)||$periodTo<$periodFrom){if($periodMode==='cycle'){$periodTo=$month.'-22';$periodFrom=date('Y-m-d',strtotime($periodTo.' -1 month'));}elseif($periodMode==='week'){$anchor=$month===date('Y-m')?date('Y-m-d'):$monthTo;$periodFrom=date('Y-m-d',strtotime('monday this week',strtotime($anchor)));$periodTo=date('Y-m-d',strtotime($periodFrom.' +6 days'));}else{$periodFrom=$monthFrom;$periodTo=$monthTo;}}
$month=substr($periodTo,0,7);[$monthFrom,$monthTo]=posi_month_bounds($month);$periodQuery=http_build_query(['month'=>$month,'period_mode'=>$periodMode,'date_from'=>$periodFrom,'date_to'=>$periodTo]);$uid=(int)($u['id']??0);
if($_SERVER['REQUEST_METHOD']==='POST'){csrf_check();$action=(string)($_POST['action']??'');try{
    if($action==='save_rule'){
        $ruleMonth=(string)($_POST['rule_month']??$month);if(!posi_month_valid($ruleMonth))throw new RuntimeException('เดือนของ Rule ไม่ถูกต้อง');if(posi_closing(db_load(),$ruleMonth))throw new RuntimeException('เดือนนี้ Final แล้ว กรุณา Reopen ก่อนแก้ Rule');$scope=(string)($_POST['scope_type']??'store');if(!in_array($scope,['store','team','employee'],true))$scope='store';$scopeValue='';if($scope==='team'){$scopeValue=trim((string)($_POST['scope_team']??''));if($scopeValue==='')throw new RuntimeException('กรุณาระบุ Team Code');}elseif($scope==='employee'){$scopeValue=(string)max(0,(int)($_POST['scope_employee_id']??0));if($scopeValue==='0')throw new RuntimeException('กรุณาเลือกพนักงาน');}$payout=(string)($_POST['payout_type']??'per_drink');if(!in_array($payout,['per_drink','percent_sales','fixed_bonus'],true))$payout='per_drink';$rid=(int)($_POST['rule_id']??0);$rule=['id'=>$rid,'month'=>$ruleMonth,'name'=>trim((string)($_POST['rule_name']??'Monthly Incentive'))?:'Monthly Incentive','enabled'=>!empty($_POST['enabled'])?1:0,'scope_type'=>$scope,'scope_value'=>$scopeValue,'target_sales'=>(string)posi_money($_POST['target_sales']??0),'payout_type'=>$payout,'reward_rate'=>(string)posi_money($_POST['reward_rate']??0),'note'=>trim((string)($_POST['note']??'')),'updated_at'=>date('c'),'updated_by'=>$uid];
        db_mutate(function($d)use($rule,$rid,$uid){if(!isset($d['pos_incentive_rules'])||!is_array($d['pos_incentive_rules']))$d['pos_incentive_rules']=[];$r=$rule;if($rid>0){$found=false;foreach($d['pos_incentive_rules'] as &$x)if((int)($x['id']??0)===$rid){$r['created_at']=$x['created_at']??date('c');$r['created_by']=$x['created_by']??$uid;$x=posi_rule_defaults(array_replace($x,$r));$found=true;break;}unset($x);if(!$found)throw new RuntimeException('ไม่พบ Rule');}else{$r['id']=next_id($d['pos_incentive_rules']);$r['created_at']=date('c');$r['created_by']=$uid;$d['pos_incentive_rules'][]=posi_rule_defaults($r);} $d['audit'][]=['at'=>date('c'),'action'=>'pos_incentive_rule_saved','rule_id'=>(int)$r['id'],'month'=>(string)$r['month'],'by'=>$uid];return $d;});$month=$ruleMonth;[$monthFrom,$monthTo]=posi_month_bounds($month);$msg='บันทึกเงื่อนไข Incentive แล้ว';
    }elseif($action==='delete_rule'){$rid=(int)($_POST['rule_id']??0);$snap=db_load();foreach(posi_rules($snap) as $rr)if((int)$rr['id']===$rid&&posi_closing($snap,(string)$rr['month']))throw new RuntimeException('เดือนนี้ Final แล้ว กรุณา Reopen ก่อนลบ Rule');db_mutate(function($d)use($rid,$uid){$before=count($d['pos_incentive_rules']??[]);$d['pos_incentive_rules']=array_values(array_filter($d['pos_incentive_rules']??[],fn($r)=>(int)($r['id']??0)!==$rid));if(count($d['pos_incentive_rules'])===$before)throw new RuntimeException('ไม่พบ Rule');$d['audit'][]=['at'=>date('c'),'action'=>'pos_incentive_rule_deleted','rule_id'=>$rid,'by'=>$uid];return $d;});$msg='ลบ Rule แล้ว';
    }elseif($action==='save_sales_commission_rule'){
        if(posi_closing(db_load(),$month))throw new RuntimeException('เดือนนี้ Final แล้ว กรุณา Reopen ก่อนแก้เงื่อนไข');
        $storeMinimum=(array)($_POST['store_minimum']??[]);$personalMinimum=(array)($_POST['personal_minimum']??[]);$minimumUnits=(array)($_POST['minimum_units']??[]);$ratePerUnit=(array)($_POST['rate_per_unit']??[]);$tiers=[];$tierCount=max(count($storeMinimum),count($personalMinimum),count($minimumUnits),count($ratePerUnit));
        for($i=0;$i<$tierCount;$i++){$tier=['id'=>$i+1,'store_minimum'=>posi_money($storeMinimum[$i]??0),'personal_minimum'=>posi_money($personalMinimum[$i]??0),'minimum_units'=>posi_money($minimumUnits[$i]??0),'rate_per_unit'=>posi_money($ratePerUnit[$i]??0)];if((float)$tier['rate_per_unit']<=0)continue;$tiers[]=$tier;}
        if(!$tiers)throw new RuntimeException('กรุณาเพิ่มอย่างน้อย 1 เงื่อนไข และระบุค่าคอมต่อบิลมากกว่า 0');$tiers=posi_sales_commission_tiers(['tiers'=>$tiers]);
        $personalKeys=(array)($_POST['sales_key']??[]);$personalValues=(array)($_POST['personal_sales']??[]);$personalSales=[];foreach($personalKeys as $i=>$key){$key=trim((string)$key);if($key==='')continue;$personalSales[$key]=posi_money($personalValues[$i]??0);}
        $rule=['month'=>$month,'period_from'=>$periodFrom,'period_to'=>$periodTo,'tiers'=>$tiers,'personal_sales_by_key'=>$personalSales,'note'=>trim((string)($_POST['sales_rule_note']??'')),'updated_at'=>date('c'),'updated_by'=>$uid];
        db_mutate(function($d)use($rule,$month,$periodFrom,$periodTo,$uid){if(!isset($d['sales_commission_rules'])||!is_array($d['sales_commission_rules']))$d['sales_commission_rules']=[];$saved=false;foreach($d['sales_commission_rules'] as &$existing)if((string)($existing['period_from']??'')===$periodFrom&&(string)($existing['period_to']??'')===$periodTo){$existing=array_replace($existing,$rule);unset($existing['minimum_units'],$existing['rate_per_unit'],$existing['target_units'],$existing['target_bonus']);$saved=true;break;}unset($existing);if(!$saved)$d['sales_commission_rules'][]=$rule;$d['audit'][]=['at'=>date('c'),'action'=>'sales_commission_tiers_saved','month'=>$month,'period_from'=>$periodFrom,'period_to'=>$periodTo,'tier_count'=>count($rule['tiers']),'by'=>$uid];return $d;});$msg='บันทึก '.count($tiers).' ระดับเงื่อนไขและคำนวณค่าคอม Sales ใหม่แล้ว';
    }elseif($action==='save_role_commission_rule'){
        if(posi_closing(db_load(),$month))throw new RuntimeException('รอบนี้ Final แล้ว กรุณา Reopen ก่อนแก้เงื่อนไข');
        $teamKeys=(array)($_POST['team_key']??[]);$teamSales=(array)($_POST['team_sales_id']??[]);$teamSalesMap=[];foreach($teamKeys as $i=>$teamKey){$teamKey=trim((string)$teamKey);$salesId=max(0,(int)($teamSales[$i]??0));if($teamKey!==''&&$salesId>0)$teamSalesMap[$teamKey]=$salesId;}
        $rule=['period_from'=>$periodFrom,'period_to'=>$periodTo,'pr_rate_d'=>posi_money($_POST['pr_rate_d']??0),'pr_rate_m'=>posi_money($_POST['pr_rate_m']??0),'sales_own_rate_d'=>posi_money($_POST['sales_own_rate_d']??0),'sales_own_rate_m'=>posi_money($_POST['sales_own_rate_m']??0),'sales_team_rate_d'=>posi_money($_POST['sales_team_rate_d']??0),'sales_team_rate_m'=>posi_money($_POST['sales_team_rate_m']??0),'team_sales_map'=>$teamSalesMap,'updated_at'=>date('c'),'updated_by'=>$uid];
        db_mutate(function($d)use($rule,$periodFrom,$periodTo,$uid){if(!isset($d['role_commission_rules'])||!is_array($d['role_commission_rules']))$d['role_commission_rules']=[];$saved=false;foreach($d['role_commission_rules'] as &$existing)if((string)($existing['period_from']??'')===$periodFrom&&(string)($existing['period_to']??'')===$periodTo){$existing=array_replace($existing,$rule);$saved=true;break;}unset($existing);if(!$saved)$d['role_commission_rules'][]=$rule;$d['audit'][]=['at'=>date('c'),'action'=>'role_team_commission_rule_saved','period_from'=>$periodFrom,'period_to'=>$periodTo,'by'=>$uid];return $d;});$msg='บันทึกอัตรา PR/Sales และคำนวณค่าคอมทีมใหม่แล้ว';
    }elseif($action==='upload_to_inbox'){
        $stored=posi_inbox_store_upload($_FILES['pos_file']??[]);$title=trim((string)($_POST['report_title']??''));if($title==='')$title=pathinfo((string)$stored['original_name'],PATHINFO_FILENAME);$detail=trim((string)($_POST['report_detail']??''));
        try{db_mutate(function($d)use($stored,$title,$detail,$periodMode,$periodFrom,$periodTo,$uid){if(!isset($d['pos_upload_inbox'])||!is_array($d['pos_upload_inbox']))$d['pos_upload_inbox']=[];foreach($d['pos_upload_inbox'] as $existing)if(($existing['sha256']??'')===$stored['sha256']&&(string)($existing['period_from']??'')===$periodFrom&&(string)($existing['period_to']??'')===$periodTo&&in_array((string)($existing['status']??''),['uploaded','processing','completed'],true))throw new RuntimeException('ไฟล์เดียวกันอยู่ในถังข้อมูลรอบนี้แล้ว · สถานะ '.posi_inbox_status_label((string)$existing['status']));$entry=array_replace($stored,['id'=>next_id($d['pos_upload_inbox']),'title'=>$title,'detail'=>$detail,'period_mode'=>$periodMode,'period_from'=>$periodFrom,'period_to'=>$periodTo,'status'=>'uploaded','uploaded_at'=>date('c'),'uploaded_by'=>$uid,'processed_at'=>'','processed_by'=>null,'batch_id'=>null,'error'=>'']);$d['pos_upload_inbox'][]=$entry;$d['audit'][]=['at'=>date('c'),'action'=>'pos_file_uploaded_to_inbox','inbox_id'=>$entry['id'],'period_from'=>$periodFrom,'period_to'=>$periodTo,'by'=>$uid];return $d;});}catch(Throwable $uploadError){$path=posi_inbox_dir().'/'.basename((string)$stored['stored_name']);if(is_file($path))@unlink($path);throw $uploadError;}$msg='เก็บไฟล์ไว้ในถังข้อมูล POS แล้ว · รอทีมฝ่ายจ่ายเงินเลือกไป Process';
    }elseif($action==='delete_inbox_file'){
        $inboxId=max(0,(int)($_POST['inbox_id']??0));if($inboxId<1)throw new RuntimeException('ไม่พบไฟล์ที่ต้องการลบ');$deletedFile='';$deletedName='';
        db_mutate(function($d)use($inboxId,$uid,&$deletedFile,&$deletedName){$entryIndex=null;$entry=null;foreach($d['pos_upload_inbox']??[] as $i=>$candidate)if((int)($candidate['id']??0)===$inboxId){$entryIndex=$i;$entry=$candidate;break;}if($entryIndex===null||!$entry)throw new RuntimeException('ไม่พบไฟล์ Import ที่เลือก');$status=(string)($entry['status']??'uploaded');if(!in_array($status,['uploaded','failed'],true)||!empty($entry['batch_id']))throw new RuntimeException('ไฟล์นี้ถูก Process แล้ว กรุณาเคลียร์ Report หรือเคลียร์ Process ก่อนลบ');$deletedFile=posi_inbox_path($entry);$deletedName=(string)($entry['original_name']??$entry['title']??'POS Report');array_splice($d['pos_upload_inbox'],$entryIndex,1);$d['audit'][]=['at'=>date('c'),'action'=>'pos_inbox_file_deleted','inbox_id'=>$inboxId,'file_name'=>$deletedName,'status'=>$status,'by'=>$uid];return $d;});if($deletedFile!==''&&is_file($deletedFile)&&!@unlink($deletedFile))throw new RuntimeException('นำรายการออกแล้ว แต่ลบไฟล์ต้นฉบับบน Server ไม่สำเร็จ กรุณาแจ้งผู้ดูแลระบบ');$msg='ลบไฟล์ Import “'.$deletedName.'” แล้ว';
    }elseif($action==='clear_inbox_process'){
        $inboxId=max(0,(int)($_POST['inbox_id']??0));if($inboxId<1)throw new RuntimeException('กรุณาติ๊กเลือกไฟล์ที่ต้องการเคลียร์ Process');$clearedBatches=0;
        db_mutate(function($d)use($inboxId,$uid,&$clearedBatches){$entryIndex=null;$entry=null;foreach($d['pos_upload_inbox']??[] as $i=>$candidate)if((int)($candidate['id']??0)===$inboxId){$entryIndex=$i;$entry=$candidate;break;}if($entryIndex===null||!$entry)throw new RuntimeException('ไม่พบไฟล์ที่เลือก');if((string)($entry['report_kind']??'menu_sales')==='bill_detail'&&(int)($entry['batch_id']??0)>0){posi_void_bill_batch($d,(int)$entry['batch_id'],$uid);$clearedBatches++;}$batchIds=[];foreach($d['pos_import_batches']??[] as $batch)if((string)($batch['sha256']??'')===(string)($entry['sha256']??'')&&(string)($batch['period_start']??'')===(string)($entry['period_from']??'')&&(string)($batch['period_end']??'')===(string)($entry['period_to']??'')&&(string)($batch['status']??'active')==='active')$batchIds[]=(int)$batch['id'];foreach($batchIds as $batchId){posi_void_batch($d,$batchId,$uid);$clearedBatches++;}$d['pos_upload_inbox'][$entryIndex]['status']='uploaded';$d['pos_upload_inbox'][$entryIndex]['processing_at']='';$d['pos_upload_inbox'][$entryIndex]['processed_at']='';$d['pos_upload_inbox'][$entryIndex]['processed_by']=null;$d['pos_upload_inbox'][$entryIndex]['batch_id']=null;$d['pos_upload_inbox'][$entryIndex]['error']='';$d['audit'][]=['at'=>date('c'),'action'=>'pos_inbox_process_cleared','inbox_id'=>$inboxId,'voided_batches'=>$clearedBatches,'by'=>$uid];return $d;});$msg='เคลียร์ Process แล้ว'.($clearedBatches?' · ยกเลิก Batch เดิม '.$clearedBatches.' รายการ':' · ไฟล์พร้อมเลือกใหม่');
    }elseif($action==='process_inbox'){
        $inboxId=max(0,(int)($_POST['inbox_id']??0));$snapshot=db_load();$entry=null;foreach($snapshot['pos_upload_inbox']??[] as $candidate)if((int)($candidate['id']??0)===$inboxId){$entry=$candidate;break;}if(!$entry)throw new RuntimeException('ไม่พบไฟล์ในถังข้อมูล');$entryStatus=(string)($entry['status']??'uploaded');if($entryStatus==='completed'){$from=(string)$entry['period_from'];$to=(string)$entry['period_to'];$isBill=(string)($entry['report_kind']??'menu_sales')==='bill_detail';$redirect='pos-incentive.php?'.http_build_query(['month'=>substr($to,0,7),'period_mode'=>(string)($entry['period_mode']??'custom'),'date_from'=>$from,'date_to'=>$to,'step'=>$isBill?1:2,$isBill?'bill_processed':'processed'=>1]);header('Location: '.$redirect);exit;}if($entryStatus==='processing'&&strtotime((string)($entry['processing_at']??''))>=time()-900)throw new RuntimeException('ไฟล์นี้กำลังถูก Process โดยผู้ใช้อื่น กรุณารอให้เสร็จก่อน');
        db_mutate(function($d)use($inboxId,$uid){foreach($d['pos_upload_inbox']??[] as &$item)if((int)($item['id']??0)===$inboxId){$item['status']='processing';$item['processing_at']=date('c');$item['processed_by']=$uid;$item['error']='';break;}unset($item);return $d;});
        try{$path=posi_inbox_path($entry);$parsed=posi_parse_file($path,(string)$entry['ext'],0);$map=posi_guess_columns($parsed['headers']);$reportKind=(string)($entry['report_kind']??'menu_sales');if($reportKind==='bill_detail'){$billBatch=null;db_mutate(function($d)use($entry,$parsed,$map,$uid,$inboxId,&$billBatch){[$d,$billBatch]=posi_commit_bill_import($d,$entry,$parsed,$map,$uid);foreach($d['pos_upload_inbox']??[] as &$item)if((int)($item['id']??0)===$inboxId){$item['status']='completed';$item['processed_at']=date('c');$item['processed_by']=$uid;$item['batch_id']=(int)$billBatch['id'];$item['error']='';break;}unset($item);return $d;});$redirect='pos-incentive.php?'.http_build_query(['period_mode'=>(string)($entry['period_mode']??'custom'),'date_from'=>(string)$entry['period_from'],'date_to'=>(string)$entry['period_to'],'step'=>1,'bill_processed'=>1]);header('Location: '.$redirect);exit;}$reportType=posi_report_type($map);if(($map['item']??-1)<0||($map['sales']??-1)<0||($reportType!=='product_summary'&&($map['date']??-1)<0))throw new RuntimeException('ระบบตรวจคอลัมน์ชื่อสินค้า/ยอดขายไม่ครบ');$from=(string)$entry['period_from'];$to=(string)$entry['period_to'];$stage=['name'=>(string)$entry['original_name'],'sha256'=>(string)$entry['sha256'],'ext'=>(string)$entry['ext'],'path'=>$path];$meta=['source_name'=>'POS Inbox '.$from.'_'.$to,'import_mode'=>'mtd_snapshot','period_start'=>$from,'period_end'=>$to,'report_type'=>$reportType];$batch=null;db_mutate(function($d)use($stage,$parsed,$map,$meta,$uid,$inboxId,&$batch){$batch=posi_commit_import($d,$stage,$parsed,$map,$meta,$uid);foreach($d['pos_upload_inbox']??[] as &$item)if((int)($item['id']??0)===$inboxId){$item['status']='completed';$item['processed_at']=date('c');$item['processed_by']=$uid;$item['batch_id']=(int)$batch['id'];$item['error']='';break;}unset($item);return $d;});$periodFrom=$from;$periodTo=$to;$month=substr($to,0,7);$redirect='pos-incentive.php?'.http_build_query(['month'=>$month,'period_mode'=>(string)($entry['period_mode']??'custom'),'date_from'=>$from,'date_to'=>$to,'step'=>2,'processed'=>1]);header('Location: '.$redirect);exit;}catch(Throwable $processError){db_mutate(function($d)use($inboxId,$processError,$uid){foreach($d['pos_upload_inbox']??[] as &$item)if((int)($item['id']??0)===$inboxId){$item['status']='failed';$item['error']=$processError->getMessage();$item['processed_at']=date('c');$item['processed_by']=$uid;break;}unset($item);return $d;});throw $processError;}
    }elseif($action==='commit_import'){$token=(string)($_POST['stage_token']??'');$stage=posi_stage_get($token);$parsed=posi_parse_file((string)$stage['path'],(string)$stage['ext'],0);$map=['date'=>(int)($_POST['map_date']??-1),'item'=>(int)($_POST['map_item']??-1),'group'=>(int)($_POST['map_group']??-1),'category'=>(int)($_POST['map_category']??-1),'qty'=>(int)($_POST['map_qty']??-1),'sales'=>(int)($_POST['map_sales']??-1),'cost'=>(int)($_POST['map_cost']??-1),'profit'=>(int)($_POST['map_profit']??-1),'ref'=>(int)($_POST['map_ref']??-1)];$reportType=(string)($_POST['report_type']??'transaction');if($map['item']<0||$map['sales']<0||($reportType!=='product_summary'&&$map['date']<0))throw new RuntimeException($reportType==='product_summary'?'ต้อง Mapping ชื่อสินค้าและราคาสุทธิ':'ต้อง Mapping วันที่ ชื่อเมนู และยอดขาย');$meta=['source_name'=>trim((string)($_POST['source_name']??'POS')),'import_mode'=>(string)($_POST['import_mode']??'period'),'period_start'=>(string)($_POST['period_start']??''),'period_end'=>(string)($_POST['period_end']??''),'report_type'=>$reportType];$batch=null;db_mutate(function($d)use($stage,$parsed,$map,$meta,$uid,&$batch){$batch=posi_commit_import($d,$stage,$parsed,$map,$meta,$uid);return $d;});posi_stage_clear($token);$month=(string)($batch['month']??$month);[$monthFrom,$monthTo]=posi_month_bounds($month);$msg='Import สำเร็จ '.(int)$batch['rows_imported'].' รายการ · ยอดสุทธิ '.number_format((float)$batch['total_sales'],2).' · ค่าดริ้ง Match '.(int)$batch['matched_rows'].' · รอตั้ง Alias '.(int)$batch['unmatched_rows'];
    }elseif($action==='void_batch'){$bid=(int)($_POST['batch_id']??0);$voided=null;db_mutate(function($d)use($bid,$uid,&$voided){$voided=posi_void_batch($d,$bid,$uid);return $d;});$msg='Void Import Batch #'.$bid.' แล้ว · แถวข้อมูลของ Batch นี้ถูกตัดออกจากการคำนวณ';
    }elseif($action==='remap'){if(posi_closing(db_load(),$month))throw new RuntimeException('เดือนนี้ Final แล้ว กรุณา Reopen ก่อน Re-map');$changed=0;db_mutate(function($d)use($month,$uid,&$changed){$changed=posi_remap_rows($d,$month);$d['audit'][]=['at'=>date('c'),'action'=>'pos_incentive_remap','month'=>$month,'changed'=>$changed,'by'=>$uid];return $d;});$msg='คำนวณ POS Mapping ใหม่แล้ว · เปลี่ยน '.$changed.' แถว';
    }elseif($action==='finalize'){if(empty($_POST['flow_ready']))throw new RuntimeException('กรุณาไปขั้นตอนสุดท้ายและตรวจข้อมูลก่อนบันทึก');$closing=null;db_mutate(function($d)use($month,$uid,&$closing){$closing=posi_close_month($d,$month,$uid);return $d;});$msg='Final Incentive เดือน '.$month.' แล้ว · หลังจากนี้หน้า Employee จะใช้อ้างอิง Snapshot นี้';
    }elseif($action==='reopen'){$n=0;db_mutate(function($d)use($month,$uid,&$n){$n=posi_reopen_month($d,$month,$uid);return $d;});$msg=$n?'Reopen เดือน '.$month.' แล้ว สามารถ Import/แก้ Rule และ Final ใหม่ได้':'ไม่พบรอบ Final';
    }
}catch(Throwable $e){$err=$e->getMessage();}}
if(!$msg&&!empty($_GET['processed']))$msg='Report การขายตามเมนูพร้อมใช้งานแล้ว · ดำเนินการ Sort และตรวจข้อมูลต่อได้เลย';
if(!$msg&&!empty($_GET['bill_processed']))$msg='Report รายละเอียดบิลพร้อมใช้เทียบเลขบิลกับรอบเปิดโต๊ะ Sales แล้ว';
$d=db_load();$inboxItems=array_values($d['pos_upload_inbox']??[]);usort($inboxItems,fn($a,$b)=>strcmp((string)($b['uploaded_at']??''),(string)($a['uploaded_at']??'')));$inboxItems=array_slice($inboxItems,0,30);$inboxWaiting=count(array_filter($inboxItems,fn($item)=>in_array((string)($item['status']??''),['uploaded','failed'],true)));$currency=(string)($d['settings']['currency']??'THB');$productRows=posi_active_rows_period($d,$periodFrom,$periodTo);$salesMode=!empty($_GET['sales_commission'])||in_array($action,['save_sales_commission_rule','save_role_commission_rule'],true);$salesRule=posi_sales_commission_rule($d,$month,$periodFrom,$periodTo);$salesCommissionRows=posi_sales_commission_results($d,$month,$salesRule,$periodFrom,$periodTo);$salesTotalUnits=array_sum(array_map(fn($row)=>(float)$row['units'],$salesCommissionRows));$salesTotalCommission=array_sum(array_map(fn($row)=>(float)$row['commission'],$salesCommissionRows));$salesMissingPersonal=count(array_filter($salesCommissionRows,fn($row)=>(float)($row['personal_sales']??0)<=0));$roleRule=posi_role_commission_rule($d,$periodFrom,$periodTo);$roleResults=posi_role_commission_results($d,$roleRule,$periodFrom,$periodTo);$normalizedTeamSalesMap=$roleResults['team_sales_map'];$roleRows=$roleResults['rows'];$salesRoleRows=array_values(array_filter($roleRows,fn($row)=>(string)($row['role']??'')==='sales'));$roleTotalCommission=array_sum(array_map(fn($row)=>(float)$row['total_commission'],$roleRows));$summary=posi_period_summary_dates($d,$periodFrom,$periodTo);$rules=posi_rules($d,$month);$results=posi_month_results($d,$month);$closing=posi_closing($d,$month);$unmatched=posi_unmatched_items($d,$month,20);$employees=array_values(array_filter($d['employees']??[],fn($e)=>!empty($e['active'])&&in_array((string)($e['position']??''),['sales','pr'],true)));$salesEmployees=array_values(array_filter($employees,fn($e)=>(string)($e['position']??'')==='sales'));$batches=array_values(array_filter($d['pos_import_batches']??[],fn($b)=>(string)($b['month']??'')===$month));usort($batches,fn($a,$b)=>strcmp((string)($b['imported_at']??''),(string)($a['imported_at']??'')));
$primaryRule=null;foreach($rules as $r)if(!empty($r['enabled'])&&$r['scope_type']==='store'){$primaryRule=$r;break;}if(!$primaryRule)foreach($rules as $r)if(!empty($r['enabled'])){$primaryRule=$r;break;}$target=$primaryRule?(float)$primaryRule['target_sales']:0;$primaryActual=$primaryRule?posi_scope_sales($d,$month,$primaryRule):0.0;$progress=$target>0?min(999,$primaryActual/$target*100):0;$projectedUnlock=$target<=0||($primaryActual*(float)$summary['projection_factor'])>=$target;$defaultPeriodEnd=$month===date('Y-m')?date('Y-m-d'):$monthTo;
$prev=date('Y-m',strtotime($month.'-01 -1 month'));$next=date('Y-m',strtotime($month.'-01 +1 month'));
$sortConfirmed=!empty($_GET['sort_confirmed'])||!empty($_POST['sort_confirmed'])||in_array($action,['save_sales_commission_rule','save_role_commission_rule'],true);$calcMode=(string)($_GET['calc_mode']??$_POST['calc_mode']??'');if(!in_array($calcMode,['pr','sales'],true))$calcMode='';$r4Rule=posi_r4_rule($d,$month,$periodFrom,$periodTo);
$hasActiveRule=false;foreach($rules as $flowRule){if(!empty($flowRule['enabled'])){$hasActiveRule=true;break;}}
$step1Done=(int)($summary['rows']??0)>0;$step2Done=$step1Done&&$sortConfirmed&&$calcMode!=='';$step3Done=$step2Done&&!empty($roleRule['updated_at']);
$requestedStep=max(1,min(4,(int)($_GET['step']??$_POST['step']??($step1Done?2:1))));$maxStep=$step1Done?2:1;if($step2Done)$maxStep=3;if($step3Done)$maxStep=4;$step=min($requestedStep,$maxStep);if($requestedStep>$maxStep&&$err==='')$err='ยังไปขั้นตอนนั้นไม่ได้ กรุณาทำขั้นตอนปัจจุบันให้ครบก่อน';
$flowQuery=$periodQuery.($sortConfirmed?'&sort_confirmed=1':'').($calcMode!==''?'&calc_mode='.rawurlencode($calcMode):'');
function posi_payout_label(string $p): string{return ['per_drink'=>'บาท / Drink','percent_sales'=>'% จากยอดขายรายบุคคล','fixed_bonus'=>'โบนัสคงที่'][$p]??$p;}
?><!doctype html><html lang="th"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>MR BAR — POS Incentive & Commission</title><link rel="stylesheet" href="assets/admin.css?v=1240"><link rel="stylesheet" href="assets/admin-v14.css?v=1240"><link rel="stylesheet" href="assets/pos-incentive-v1298.css?v=1298"><link rel="stylesheet" href="assets/pos-incentive-wizard-v1351.css?v=1360"><link rel="stylesheet" href="assets/pos-incentive-product-sort-v1360.css?v=1370"><link rel="stylesheet" href="assets/pos-sales-commission-v1370.css?v=1380"><link rel="stylesheet" href="assets/pos-period-picker-v1380.css?v=1390"><link rel="stylesheet" href="assets/pos-upload-inbox-v1390.css?v=1435"><link rel="stylesheet" href="assets/pos-wizard-strict-v1410.css?v=1410"><link rel="stylesheet" href="assets/pos-sales-tiers-v1420.css?v=1431"><link rel="stylesheet" href="assets/pos-role-team-v1430.css?v=1430"><link rel="stylesheet" href="assets/pos-suite.css?v=1481"></head><body class="admin-v14-page posi-page posi-wizard-step-<?=$step?> <?=$salesMode?'posi-sales-mode':''?>"><?php require_once __DIR__.'/app/admin-nav.php';echo admin_sidebar('incentive',$u);?><main class="posi-shell"><header class="posi-head"><div><p>PEOPLE / POS INCENTIVE</p><h1>POS Incentive & Commission</h1><span>Import Excel/CSV → Mapping เมนูเข้าพนักงาน → ประมาณการรายสัปดาห์ → Final รายเดือน</span></div><div><a href="employees.php">Employee Center</a><a href="payroll-attendance.php">Attendance & Payroll</a></div></header><nav class="pos-suite-nav"><a href="pos-incentive-import.php"><span>1</span><div><b>Import POS</b><small>อัปโหลดไฟล์</small></div></a><a class="active" href="pos-incentive.php"><span>2</span><div><b>Process ข้อมูล</b><small>ระบบเดิม / Mapping / Sort</small></div></a><a href="pos-drinks.php"><span>3</span><div><b>ค่าดื่ม</b><small>PR / Sales</small></div></a><a href="pos-commission.php"><span>4</span><div><b>ค่าคอม</b><small>PR ในทีม Sales</small></div></a><a href="pos-reports.php"><span>5</span><div><b>Report</b><small>สรุป / Sort / เคลียร์</small></div></a></nav><?php if($msg):?><div class="posi-notice ok">✓ <?=h($msg)?></div><?php endif;?><?php if($err):?><div class="posi-notice err">⚠ <?=h($err)?></div><?php endif;?>
<?php if($step>1):?><section class="posi-period-picker" data-period-picker>
<div class="posi-period-title"><div><small>รอบข้อมูลที่กำลังคำนวณ</small><h2><?=h(date('d/m/Y',strtotime($periodFrom)))?> – <?=h(date('d/m/Y',strtotime($periodTo)))?></h2><p>เลือกได้ทั้งรายเดือน รายสัปดาห์ รอบตัดบัญชี 22–22 หรือช่วงวันที่กำหนดเอง</p></div><em class="<?= $closing?'final':'estimate' ?>"><?= $closing?'FINAL':'กำลังคำนวณ' ?></em></div>
<form method="get" class="posi-period-form"><input type="hidden" name="step" value="<?=$step?>"><?php if($salesMode):?><input type="hidden" name="sales_commission" value="1"><?php endif;?>
<label><span>รูปแบบรอบ</span><select name="period_mode" data-period-mode><option value="month" <?=$periodMode==='month'?'selected':''?>>รายเดือน</option><option value="week" <?=$periodMode==='week'?'selected':''?>>รายสัปดาห์</option><option value="cycle" <?=$periodMode==='cycle'?'selected':''?>>รอบวันที่ 22 – 22</option><option value="custom" <?=$periodMode==='custom'?'selected':''?>>กำหนดช่วงเอง</option></select></label>
<label><span>วันที่เริ่มต้น</span><input type="date" name="date_from" value="<?=h($periodFrom)?>" data-period-from required></label>
<label><span>วันที่สิ้นสุด / คำนวณถึงวันนี้</span><input type="date" name="date_to" value="<?=h($periodTo)?>" data-period-to required></label>
<button>แสดงข้อมูลรอบนี้ →</button></form>
<div class="posi-period-shortcuts"><button type="button" data-period-shortcut="month">เดือนนี้</button><button type="button" data-period-shortcut="week">สัปดาห์นี้</button><button type="button" data-period-shortcut="cycle">รอบ 22–22</button><button type="button" data-period-shortcut="today">ตั้งแต่ต้นรอบถึงวันนี้</button></div>
</section><?php endif;?>
<?php if($step>1):?><section class="posi-period-locked"><div><small>รอบข้อมูลที่เลือกจากขั้นแรก</small><b><?=h(date('d/m/Y',strtotime($periodFrom)))?> – <?=h(date('d/m/Y',strtotime($periodTo)))?></b></div><span>ใช้รอบเดียวกันทุกขั้นตอน</span></section><?php endif;?>
<section class="posi-workflow posi-wizard-nav" aria-label="ขั้นตอนดำเนินงาน">
<div class="<?=$step===1?'active':($step1Done?'done':'locked')?>"><i><?=$step1Done?'✓':'1'?></i><span><b>1. เลือกไฟล์ Report</b><small><?=$step===1?'กำลังทำขั้นตอนนี้':($step1Done?'เสร็จแล้ว':'รอดำเนินการ')?></small></span></div>
<div class="<?=$step===2?'active':($step2Done?'done':($maxStep<2?'locked':''))?>"><i><?=$step2Done?'✓':'2'?></i><span><b>2. Sort และตรวจข้อมูล</b><small><?=$step===2?'กำลังทำขั้นตอนนี้':($step2Done?'เสร็จแล้ว':'ต้องทำขั้นก่อนหน้า')?></small></span></div>
<div class="<?=$step===3?'active':($step3Done?'done':($maxStep<3?'locked':''))?>"><i><?=$step3Done?'✓':'3'?></i><span><b>3. คำนวณค่าคอม</b><small><?=$step===3?'กำลังทำขั้นตอนนี้':($step3Done?'เสร็จแล้ว':'ต้องทำขั้นก่อนหน้า')?></small></span></div>
<div class="<?=$step===4?'active':($closing?'done':'locked')?>"><i><?=$closing?'✓':'4'?></i><span><b>4. ตรวจและบันทึก</b><small><?=$step===4?'ขั้นตอนสุดท้าย':($closing?'บันทึกแล้ว':'ต้องทำขั้นก่อนหน้า')?></small></span></div>
</section>
<?php if($step>1):?><section class="posi-kpis"><article class="sales"><small>ยอดขายสุทธิจาก POS</small><b><?=number_format((float)$summary['actual_sales'],2)?></b><span><?=h($currency)?> · <?=number_format((int)$summary['rows'])?> รายการสินค้า</span></article><article class="drinks"><small>หน่วยค่าดริ้ง D + M</small><b><?=number_format((float)($summary['drink_units']??0),0)?></b><span><i>D <?=number_format((float)($summary['d_units']??0),0)?></i><i>M <?=number_format((float)($summary['m_units']??0),0)?></i></span></article><article class="<?=($summary['unmatched_rows']??0)>0?'warn':'good'?>"><small>จับคู่ชื่อพนักงาน</small><b><?=number_format((int)$summary['matched_rows'])?> / <?=number_format((int)$summary['matched_rows']+(int)$summary['unmatched_rows'])?></b><span><?=($summary['unmatched_rows']??0)>0?'รอตั้ง Alias '.number_format((int)$summary['unmatched_rows']).' รายการ':'รายการค่าดริ้งพร้อมคำนวณ'?></span></article><article class="<?=$target>0&&$projectedUnlock?'good':'target'?>"><small>เป้ายอดขายเดือนนี้</small><b><?=$target>0?number_format($target,0):'ยังไม่ตั้ง'?></b><span><?=$target>0?number_format($progress,1).'% · ประมาณปลายเดือน '.number_format((float)$summary['projected_sales'],0):'สร้าง Rule เพื่อเริ่มคำนวณค่าคอม'?></span></article></section><?php endif;?>
<div class="posi-grid posi-setup-grid"><section class="posi-card"><div class="posi-card-head"><div><small>02 / COMMISSION RULE</small><h2>กติกาค่าคอมประจำเดือน</h2><p>กำหนดเป้ายอดร้าน เงื่อนไขปลดล็อก และอัตราจ่ายต่อหน่วย</p></div></div><form method="post" class="posi-rule-form"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><input type="hidden" name="action" value="save_rule"><label>เดือน<input type="month" name="rule_month" value="<?=h($month)?>" required></label><label>ชื่อ Rule<input name="rule_name" value="Monthly Drink Commission" required></label><label>Scope<select name="scope_type"><option value="store">ยอดรวมทั้งร้าน</option><option value="team">ยอดเฉพาะทีม</option><option value="employee">ยอดเฉพาะพนักงาน</option></select></label><label>Team Code<input name="scope_team" placeholder="เช่น TEAM-A"></label><label>พนักงาน<select name="scope_employee_id"><option value="0">— ใช้เมื่อ Scope = พนักงาน —</option><?php foreach($employees as $e):?><option value="<?=(int)$e['id']?>"><?=h(workforce_employee_label($e))?></option><?php endforeach;?></select></label><label>เป้ายอดขาย<input type="number" step="0.01" min="0" name="target_sales" placeholder="2500000" required></label><label>วิธีจ่าย<select name="payout_type"><option value="per_drink">บาท / Drink</option><option value="percent_sales">% ยอดขายรายบุคคล</option><option value="fixed_bonus">โบนัสคงที่</option></select></label><label>Rate / มูลค่า<input type="number" step="0.01" min="0" name="reward_rate" placeholder="80" required></label><label class="wide">หมายเหตุ<input name="note" placeholder="เช่น ถึงยอด 2.5M จ่าย 80 บาทต่อ Drink"></label><label class="check"><input type="checkbox" name="enabled" value="1" checked> เปิดใช้ Rule</label><button>บันทึก Rule</button></form><div class="posi-rule-list"><?php if(!$rules):?><div class="empty">ยังไม่มี Rule เดือนนี้</div><?php endif;?><?php foreach($rules as $r):?><article><div><b><?=h((string)$r['name'])?></b><span><?=h(strtoupper((string)$r['scope_type']))?> · Target <?=number_format((float)$r['target_sales'],0)?> · <?=number_format((float)$r['reward_rate'],2)?> <?=h(posi_payout_label((string)$r['payout_type']))?></span><?php if(!empty($r['note'])):?><small><?=h((string)$r['note'])?></small><?php endif;?></div><form method="post" onsubmit="return confirm('ลบ Rule นี้?')"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><input type="hidden" name="action" value="delete_rule"><input type="hidden" name="month" value="<?=h($month)?>"><input type="hidden" name="rule_id" value="<?=(int)$r['id']?>"><button>ลบ</button></form></article><?php endforeach;?></div></section>
<section class="posi-card posi-import-card"><div class="posi-card-head row"><div><small>01 / SELECT POS FILE</small><h2>เลือกไฟล์ Report เพื่อคำนวณ</h2><p>หน้านี้ใช้เลือกไฟล์ที่ Import เข้า Server แล้วเท่านั้น จากนั้นจึงเริ่ม Process และไปตรวจข้อมูลในขั้นถัดไป</p></div><a class="posi-format-badge" href="pos-incentive-import.php">+ Import File จาก POS</a></div>
<?php if(!$preview):?><section class="posi-inbox-list"><div class="posi-inbox-list-head"><div><small>ขั้นตอนที่ 2 · สำหรับทีมตรวจและจ่ายเงิน</small><h3>เลือกไฟล์มาใช้งาน</h3></div><span><?=$inboxWaiting?> ไฟล์รอเลือก</span></div>
<?php if(!$inboxItems):?><div class="empty">ยังไม่มีไฟล์ POS ที่ Import เข้า Server</div><?php endif;?>
<form method="post" id="posi-inbox-process-form"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>">
<?php foreach($inboxItems as $item):$status=(string)($item['status']??'uploaded');$canProcess=in_array($status,['uploaded','failed'],true)||($status==='processing'&&strtotime((string)($item['processing_at']??''))<time()-900);$canDelete=in_array($status,['uploaded','failed'],true)&&empty($item['batch_id']);?><article class="posi-inbox-item status-<?=h($status)?>"><div class="posi-inbox-icon"><?=strtoupper(h((string)($item['ext']??'POS')))?></div><div class="posi-inbox-info"><div><b><?=h(posi_bill_report_label((string)($item['report_kind']??'menu_sales')).' · '.(string)($item['title']??$item['original_name']??'POS Report'))?></b><em><?=h(posi_inbox_status_label($status))?></em></div><span><?=h((string)($item['original_name']??''))?> · <?=number_format((float)($item['size']??0)/1024,1)?> KB</span><p><?=h((string)($item['detail']??'ไม่มีรายละเอียด'))?></p><small>รอบ <?=h(date('d/m/Y',strtotime((string)$item['period_from'])))?> – <?=h(date('d/m/Y',strtotime((string)$item['period_to'])))?> · อัปโหลด <?=h((string)($item['uploaded_at']??''))?> · ผู้ส่ง #<?=(int)($item['uploaded_by']??0)?></small><?php if($status==='failed'&&!empty($item['error'])):?><strong><?=h((string)$item['error'])?></strong><?php endif;?></div><div class="posi-inbox-action"><?php if($canProcess):?><label class="posi-inbox-select"><input type="radio" name="inbox_id" value="<?=(int)$item['id']?>" required><span aria-hidden="true">✓</span><b>เลือกไฟล์นี้</b></label><?php elseif($status==='processing'):?><span>กำลังประมวลผล…</span><?php else:?><span>Batch #<?=(int)($item['batch_id']??0)?> · เสร็จแล้ว</span><?php endif;?><?php if($canDelete):?><button type="submit" class="posi-inbox-delete" form="posi-delete-inbox-<?=(int)$item['id']?>">ลบไฟล์</button><?php endif;?></div></article><?php endforeach;?></form><?php foreach($inboxItems as $item):$status=(string)($item['status']??'uploaded');if(!in_array($status,['uploaded','failed'],true)||!empty($item['batch_id']))continue;?><form method="post" id="posi-delete-inbox-<?=(int)$item['id']?>" class="posi-hidden-delete-form" onsubmit="return confirm('ลบไฟล์ Import นี้ออกจาก Server ใช่หรือไม่? การลบไม่สามารถย้อนกลับได้')"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><input type="hidden" name="action" value="delete_inbox_file"><input type="hidden" name="inbox_id" value="<?=(int)$item['id']?>"></form><?php endforeach;?></section>
<?php else:$previewType=$previewType?:posi_report_type($previewGuess);$previewStats=$previewStats?:posi_preview_summary($preview,$previewGuess);?><div class="preview-file"><div><b><?=h((string)$previewStage['name'])?></b><span>พบหัวตารางที่แถว <?=number_format((int)($preview['header_row']??1))?> · SHA <?=h(substr((string)$previewStage['sha256'],0,12))?>…</span></div><em><?=$previewType==='product_summary'?'รายงานยอดขายตามสินค้า':'รายละเอียดรายการขาย'?></em></div>
<div class="posi-preview-stats"><article><small>รายการสินค้า</small><b><?=number_format((int)$previewStats['rows'])?></b></article><article><small>ยอดขายสุทธิ</small><b><?=number_format((float)$previewStats['net_sales'],2)?></b></article><article><small>ค่าดริ้ง D</small><b><?=number_format((float)$previewStats['d_units'],0)?></b></article><article><small>ค่าดริ้ง M</small><b><?=number_format((float)$previewStats['m_units'],0)?></b></article><article class="accent"><small>D + M รวม</small><b><?=number_format((float)$previewStats['candidate_units'],0)?></b></article></div>
<div class="posi-detect-note"><b>ระบบตรวจพบและตั้งค่าให้แล้ว</b><span>ยอดสุทธิใช้เทียบ Target ทั้งร้าน · ค่าดริ้งนับเฉพาะสินค้า D/M ในกลุ่ม PR และ Sales · รายการอื่นเก็บเป็นยอดร้านแต่ไม่คิดค่าดริ้ง<?php if($previewType==='product_summary'):?> · ไฟล์ไม่มีวันที่ ระบบจะลงรอบ <strong><?=h($month)?></strong> ตามช่อง “ถึง” ด้านล่าง<?php endif;?></span></div>
<form method="post" class="posi-map-form"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><input type="hidden" name="action" value="commit_import"><input type="hidden" name="month" value="<?=h($month)?>"><input type="hidden" name="stage_token" value="<?=h((string)$previewStage['token'])?>"><input type="hidden" name="report_type" value="<?=h($previewType)?>">
<div class="posi-map-primary"><label>ชื่อแหล่งข้อมูล<input name="source_name" value="POS Product Summary" required></label><label>วิธีนำเข้า<select name="import_mode"><option value="mtd_snapshot" <?=$previewType==='product_summary'?'selected':''?>>Snapshot เดือนนี้ · แทนไฟล์เก่า</option><option value="period">เพิ่มข้อมูลเฉพาะช่วง</option></select></label><label>ตั้งแต่<input type="date" name="period_start" value="<?=h($monthFrom)?>" required></label><label>ถึง<input type="date" name="period_end" value="<?=h($defaultPeriodEnd)?>" required></label></div>
<details class="posi-mapping" <?=$previewType==='product_summary'?'':'open'?>><summary>ตรวจคอลัมน์ที่ระบบเลือก <small>เปิดเมื่อต้องการแก้ Mapping</small></summary><div><?php $mapLabels=['date'=>'วันที่ขาย (ไม่จำเป็นสำหรับรายงานสรุป)','item'=>'ชื่อสินค้า *','group'=>'กลุ่มสินค้า','category'=>'หมวดสินค้า','qty'=>'จำนวนการขาย','sales'=>'ราคาสุทธิ *','ref'=>'เลขที่บิล (ถ้ามี)'];foreach($mapLabels as $mk=>$ml):?><label><?=h($ml)?><select name="map_<?=h($mk)?>"><option value="-1">— ไม่ใช้ —</option><?php foreach($preview['headers'] as $i=>$hh):?><option value="<?=$i?>" <?=($previewGuess[$mk]??-1)===$i?'selected':''?>><?=h($hh)?></option><?php endforeach;?></select></label><?php endforeach;?></div></details><button class="posi-commit">ยืนยัน Import และคำนวณค่าดริ้ง</button></form>
<section class="posi-product-sort" data-posi-product-sort>
<div class="posi-product-sort-head"><div><small>STEP 2 / PRODUCT SORT</small><h2>เลือกกลุ่มสินค้า แล้วดูยอดเฉพาะที่ต้องการ</h2><p>เลือกหัวข้อหลักก่อน แล้วเลือกค่าภายในหัวข้อนั้น เช่น <b>กลุ่มสินค้า → Sales</b> ระบบจะแสดงเฉพาะรายการที่ตรงและคำนวณยอดให้ทันที</p></div><span>ไม่แก้ไขไฟล์ต้นฉบับ</span></div>
<div class="posi-product-sort-controls">
<div class="posi-axis" role="group" aria-label="หัวข้อหลัก"><button type="button" class="active" data-sort-axis="group">กลุ่มสินค้า</button><button type="button" data-sort-axis="category">หมวดหมู่สินค้า</button></div>
<label><span>เลือกค่าที่ต้องการ</span><select data-sort-value><option value="">ทั้งหมด</option></select></label>
<label class="posi-product-search"><span>ค้นหาในผลลัพธ์</span><input type="search" data-sort-search placeholder="ชื่อสินค้า / รหัสสินค้า"></label>
<label class="posi-calc-function"><span>เลือกฟังก์ชันที่จะทำต่อ</span><select data-calc-function><option value="">— เลือกฟังก์ชัน —</option><option value="pr">คำนวณค่าดื่ม PR</option><option value="sales">คำนวณค่าคอม Sales</option></select></label>
</div>
<div class="posi-product-sort-summary">
<article><small>รายการที่แสดง</small><b data-sort-rows>0</b><span>รายการ</span></article>
<article><small>จำนวนการขาย</small><b data-sort-qty>0</b><span>หน่วย</span></article>
<article><small>ยอดขายสุทธิ</small><b data-sort-sales>0.00</b><span><?=h($currency)?></span></article>
<article class="accent"><small>ยอดเฉลี่ยต่อรายการ</small><b data-sort-average>0.00</b><span><?=h($currency)?></span></article>
</div>
<div class="posi-sort-status" data-sort-status>กำลังเตรียมข้อมูลจากคอลัมน์ที่ Mapping…</div>
</section>
<div class="posi-preview posi-product-table"><table data-product-table data-group-index="<?=(int)($previewGuess['group']??-1)?>" data-category-index="<?=(int)($previewGuess['category']??-1)?>" data-qty-index="<?=(int)($previewGuess['qty']??-1)?>" data-sales-index="<?=(int)($previewGuess['sales']??-1)?>"><thead><tr><?php foreach($preview['headers'] as $hh):?><th><?=h($hh)?></th><?php endforeach;?></tr></thead><tbody><?php foreach($preview['rows'] as $row):?><tr><?php foreach($preview['headers'] as $i=>$hh):?><td><?=h((string)($row[$i]??''))?></td><?php endforeach;?></tr><?php endforeach;?></tbody></table></div><?php endif;?>
<div class="import-help"><b>ป้องกันยอดซ้ำ</b><span>ไฟล์เดิมถูกตรวจด้วย SHA-256 · Snapshot ใหม่แทน Snapshot เก่าของเดือนเดียวกัน · ต้อง Reopen ก่อนแก้เดือนที่ Final แล้ว</span></div></section></div>
<section class="posi-card wide posi-product-explorer">
<div class="posi-card-head row"><div><small>02 / SORT IMPORTED PRODUCTS</small><h2>ข้อมูลสินค้าที่นำเข้าแล้ว</h2><p>เลือกกลุ่มหรือหมวดหมู่ แล้วตรวจยอดเฉพาะชุดที่ต้องการก่อนเข้าสู่การคำนวณค่าคอม</p></div><span class="posi-format-badge"><?=number_format(count($productRows))?> รายการ</span></div>
<?php if(!$productRows):?><div class="empty">ยังไม่มีข้อมูลสินค้าในเดือนนี้ · กลับไปขั้นที่ 1 เพื่ออัปโหลดไฟล์ POS</div><?php else:?>
<section class="posi-product-sort" data-posi-product-sort>
<div class="posi-product-sort-head"><div><small>FILTER & CALCULATE</small><h2>เลือกหัวข้อหลักและค่าที่ต้องการ</h2><p>ตัวอย่าง: <b>กลุ่มสินค้า → Sales</b> ระบบจะแสดงเฉพาะรายการในกลุ่มและรวมยอดให้ทันที</p></div><span>ข้อมูลที่ Import แล้ว</span></div>
<div class="posi-product-sort-controls"><div class="posi-axis" role="group" aria-label="หัวข้อหลัก"><button type="button" class="active" data-sort-axis="group">กลุ่มสินค้า</button><button type="button" data-sort-axis="category">หมวดหมู่สินค้า</button></div><label><span>เลือกค่าที่ต้องการ</span><select data-sort-value><option value="">ทั้งหมด</option></select></label><label class="posi-product-search"><span>ค้นหาในผลลัพธ์</span><input type="search" data-sort-search placeholder="ชื่อสินค้า"></label><label class="posi-calc-function"><span>เลือกฟังก์ชันที่จะทำต่อ</span><select data-calc-function><option value="">— เลือกฟังก์ชัน —</option><option value="pr">คำนวณค่าดื่ม PR</option><option value="sales">คำนวณค่าคอม Sales</option></select></label></div>
<div class="posi-product-sort-summary"><article><small>รายการที่แสดง</small><b data-sort-rows>0</b><span>รายการ</span></article><article><small>จำนวนการขาย</small><b data-sort-qty>0</b><span>หน่วย</span></article><article><small>ยอดขายสุทธิ</small><b data-sort-sales>0.00</b><span><?=h($currency)?></span></article><article class="accent"><small>ยอดเฉลี่ยต่อรายการ</small><b data-sort-average>0.00</b><span><?=h($currency)?></span></article></div><div class="posi-sort-status" data-sort-status>กำลังเตรียมข้อมูล…</div><a class="posi-sales-commission-link" data-sales-commission-link hidden href="?<?=h($periodQuery)?>&step=3&sales_commission=1&sort_confirmed=1">ขั้นตอนต่อไป: คำนวณค่าคอม Sales →</a>
</section>
<div class="posi-preview posi-product-table"><table data-product-table data-group-index="1" data-category-index="2" data-qty-index="3" data-sales-index="4"><thead><tr><th>ชื่อสินค้า</th><th>กลุ่มสินค้า</th><th>หมวดหมู่สินค้า</th><th>จำนวนการขาย</th><th>ยอดขายสุทธิ</th><th>วันที่</th><th>สถานะค่าคอม</th></tr></thead><tbody><?php foreach($productRows as $row):?><tr><td><?=h((string)($row['item_name']??''))?></td><td><?=h((string)($row['item_group']??''))?></td><td><?=h((string)($row['item_category']??''))?></td><td><?=number_format((float)($row['qty']??0),2)?></td><td><?=number_format((float)($row['net_sales']??0),2)?></td><td><?=h((string)($row['sale_date']??''))?></td><td><?=!empty($row['incentive_candidate'])?'นำไปคำนวณ':'ยอดร้าน'?></td></tr><?php endforeach;?></tbody></table></div>
<?php endif;?></section>
<?php if(in_array($step,[3,4],true)):?><section class="posi-sales-commission-stage posi-role-stage">
<div class="posi-sales-stage-head"><div><small>STEP 3 / PR + SALES COMMISSION</small><h2><?=$calcMode==='pr'?'คำนวณค่าดื่ม PR':'คำนวณค่าคอม/ดื่ม Sales'?></h2><p><?=$calcMode==='pr'?'ตรวจรายการดื่มของ PR และกำหนดอัตราจ่าย':'Sales ได้รายได้ 2 ทาง: ค่าดื่มของตัวเอง และค่าคอมจากดื่ม PR ในทีม'?></p></div></div>
<?php if($step===3&&$calcMode==='sales'):?>
<section class="posi-role-rule-panel"><div class="posi-sales-section-title"><div><small>เงื่อนไขรอบนี้</small><h3>กำหนดอัตรารายได้ Sales</h3><p>กรอกอัตราต่อดื่ม แล้วจับคู่ทีมจากไฟล์ POS กับ Sales ผู้ดูแล · Sales คนเดิมสามารถเลือกดูแลซ้ำได้หลายทีม</p></div><span><?=h(date('d/m/Y',strtotime($periodFrom)))?> – <?=h(date('d/m/Y',strtotime($periodTo)))?></span></div>
<form method="post" class="posi-role-rate-form"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><input type="hidden" name="action" value="save_role_commission_rule"><input type="hidden" name="month" value="<?=h($month)?>"><input type="hidden" name="period_mode" value="<?=h($periodMode)?>"><input type="hidden" name="date_from" value="<?=h($periodFrom)?>"><input type="hidden" name="date_to" value="<?=h($periodTo)?>"><input type="hidden" name="step" value="3"><input type="hidden" name="sort_confirmed" value="1"><input type="hidden" name="calc_mode" value="sales"><input type="hidden" name="sales_commission" value="1"><input type="hidden" name="pr_rate_d" value="<?=h((string)$roleRule['pr_rate_d'])?>"><input type="hidden" name="pr_rate_m" value="<?=h((string)$roleRule['pr_rate_m'])?>">
<fieldset><legend>รายได้ทางที่ 1 · ค่าดื่มของ Sales เอง</legend><label><span>D บาท/ดื่ม</span><input type="number" step="0.01" min="0" name="sales_own_rate_d" value="<?=h((string)$roleRule['sales_own_rate_d'])?>" required></label><label><span>M บาท/ดื่ม</span><input type="number" step="0.01" min="0" name="sales_own_rate_m" value="<?=h((string)$roleRule['sales_own_rate_m'])?>" required></label></fieldset>
<fieldset><legend>รายได้ทางที่ 2 · ค่าคอมจาก PR ในทีม</legend><label><span>D บาท/ดื่มของทีม</span><input type="number" step="0.01" min="0" name="sales_team_rate_d" value="<?=h((string)$roleRule['sales_team_rate_d'])?>" required></label><label><span>M บาท/ดื่มของทีม</span><input type="number" step="0.01" min="0" name="sales_team_rate_m" value="<?=h((string)$roleRule['sales_team_rate_m'])?>" required></label></fieldset>
<fieldset class="posi-team-discovery"><legend>ทีมที่พบจริงจากไฟล์ POS</legend><?php if(!$roleResults['team_pr_units']):?><p>ยังไม่พบรายการ PR ที่มีรหัสทีมในไฟล์นี้</p><?php endif;?><?php foreach($roleResults['team_pr_units'] as $teamCode=>$teamUnits):?><label><span><b><?=h((string)$teamCode)?></b> · ยอดขายทีม <?=number_format((float)($roleResults['team_pr_sales'][$teamCode]??0),2)?> <?=h($currency)?> · PR D <?=number_format((float)($teamUnits['D']??0),0)?> / M <?=number_format((float)($teamUnits['M']??0),0)?></span><input type="hidden" name="team_key[]" value="<?=h((string)$teamCode)?>"><select name="team_sales_id[]"><option value="0">— เลือก Sales ผู้ดูแลทีม —</option><?php foreach($salesEmployees as $salesEmployee):?><option value="<?=(int)$salesEmployee['id']?>" <?=((int)($normalizedTeamSalesMap[$teamCode]??0)===(int)$salesEmployee['id'])?'selected':''?>><?=h(workforce_employee_label($salesEmployee))?></option><?php endforeach;?></select></label><?php endforeach;?></fieldset>
<button>บันทึกอัตราและคำนวณรายได้ Sales ใหม่ →</button></form></section>
<section class="posi-role-payout"><div class="posi-sales-section-title"><div><small>ตัวอย่างผลคำนวณ</small><h3>รายได้ Sales สองทาง</h3></div><span><?=number_format(count($salesRoleRows))?> Sales</span></div>
<div class="posi-sales-result-table"><table><thead><tr><th>Sales</th><th>ทีม PR ที่ดูแล</th><th>ยอดขาย Sales</th><th>ดื่มตัวเอง D / M</th><th>ค่าดื่มตัวเอง</th><th>ยอดขายทีม PR</th><th>ดื่ม PR ในทีม D / M</th><th>ค่าคอมจากทีม</th><th>รวมรายได้</th></tr></thead><tbody><?php if(!$salesRoleRows):?><tr><td colspan="9" class="empty">ยังไม่มี Sales ที่ผูกกับข้อมูล POS · ตรวจ Alias และเลือก Sales ผู้ดูแลทีมด้านบน</td></tr><?php endif;?><?php foreach($salesRoleRows as $row):?><tr><td><b><?=h((string)$row['name'])?></b></td><td><?=h((string)($row['team_code']?:'—'))?></td><td><?=number_format((float)($row['own_sales']??0),2)?></td><td>D <?=number_format((float)$row['own_d'],0)?> / M <?=number_format((float)$row['own_m'],0)?></td><td><?=number_format((float)$row['own_commission'],2)?></td><td><?=number_format((float)($row['team_pr_sales']??0),2)?></td><td>D <?=number_format((float)$row['team_pr_d'],0)?> / M <?=number_format((float)$row['team_pr_m'],0)?></td><td><?=number_format((float)$row['team_commission'],2)?></td><td><b><?=number_format((float)$row['total_commission'],2)?></b></td></tr><?php endforeach;?></tbody><tfoot><tr><th colspan="8">รวมรายได้ Sales</th><th><?=number_format(array_sum(array_map(fn($row)=>(float)$row['total_commission'],$salesRoleRows)),2)?></th></tr></tfoot></table></div></section>
<?php elseif($step===3&&$calcMode==='pr'):?><section class="posi-role-rule-panel"><div class="posi-sales-section-title"><div><small>PR DRINK COMMISSION</small><h3>ตารางคำนวณค่าดื่ม PR</h3><p>ส่วนคำนวณ PR จะใช้รายการดื่มตรงของ PR เท่านั้น</p></div></div></section><?php endif;?>
<?php if($step===4):?><div class="posi-sales-payout posi-role-payout">
<div class="posi-sales-section-title"><div><small>ผลการคำนวณ</small><h3>ตารางจ่าย PR / Sales</h3></div><button type="button" data-copy-sales-table>คัดลอกตารางสำหรับจ่ายเงิน</button></div>
<div class="posi-sales-payout-kpis"><article><small>พนักงานที่คำนวณ</small><b><?=number_format(count($roleRows))?></b><span>คน</span></article><article><small>รายการยังไม่ผูก Card</small><b><?=number_format(count($roleResults['unmapped']))?></b><span>ชื่อเมนู</span></article><article class="pay"><small>ยอดจ่ายรวม</small><b><?=number_format($roleTotalCommission,2)?></b><span><?=h($currency)?></span></article></div>
<?php if($roleResults['unmapped']):?><div class="posi-personal-warning">⚠ มีชื่อเมนู <?=count($roleResults['unmapped'])?> รายการที่ยังไม่ผูก Employee Card — ตั้ง Alias ก่อนบันทึกรอบ</div><?php endif;?>
<div class="posi-sales-result-table"><table data-sales-payout-table><thead><tr><th>พนักงาน</th><th>ตำแหน่ง</th><th>ทีม</th><th>ดื่มตัวเอง D / M</th><th>รายได้ตัวเอง</th><th>ดื่ม PR ในทีม D / M</th><th>ค่าคอมทีม</th><th>รวมจ่าย</th></tr></thead><tbody><?php if(!$roleRows):?><tr><td colspan="8" class="empty">ยังไม่มีรายการ PR/Sales ที่ผูกกับ Employee Card ในรอบนี้</td></tr><?php endif;?><?php foreach($roleRows as $row):?><tr><td><b><?=h((string)$row['name'])?></b></td><td><?=strtoupper(h((string)$row['role']))?><?=$row['team_lead']?' · หัวหน้าทีม':''?></td><td><?=h((string)($row['team_code']?:'—'))?></td><td>D <?=number_format((float)$row['own_d'],0)?> / M <?=number_format((float)$row['own_m'],0)?></td><td><?=number_format((float)$row['own_commission'],2)?></td><td><?=$row['role']==='sales'?'D '.number_format((float)$row['team_pr_d'],0).' / M '.number_format((float)$row['team_pr_m'],0):'—'?></td><td><?=number_format((float)$row['team_commission'],2)?></td><td><b><?=number_format((float)$row['total_commission'],2)?></b></td></tr><?php endforeach;?></tbody><tfoot><tr><th colspan="7">รวมจ่ายทั้งรอบ</th><th><?=number_format($roleTotalCommission,2)?></th></tr></tfoot></table></div><p class="posi-copy-feedback" data-copy-feedback></p>
</div><?php endif;?>
</section><?php endif;?>
<section class="posi-card wide posi-results-stage"><div class="posi-card-head row"><div><small>03 / LIVE ESTIMATE</small><h2>สรุปค่าดริ้งและค่าคอมรายพนักงาน</h2><p>แสดง D/M ที่จับคู่ได้ ยอดสะสม อัตราจ่าย และยอดประมาณการก่อนปิดรอบ</p></div><div class="card-actions"><form method="post"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><input type="hidden" name="action" value="remap"><input type="hidden" name="month" value="<?=h($month)?>"><button>↻ Re-map จาก Alias ล่าสุด</button></form><?php if(!$closing):?><form method="post" onsubmit="return confirm('Final Incentive เดือน <?=h($month)?>? ระบบจะ Snapshot ยอดรายคน ณ ตอนนี้')"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><input type="hidden" name="action" value="finalize"><input type="hidden" name="month" value="<?=h($month)?>"><button class="final">Final เดือนนี้</button></form><?php else:?><form method="post" onsubmit="return confirm('Reopen รอบ Final เพื่อแก้ข้อมูล?')"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><input type="hidden" name="action" value="reopen"><input type="hidden" name="month" value="<?=h($month)?>"><button class="warn">Reopen</button></form><?php endif;?></div></div><div class="posi-results"><table><thead><tr><th>พนักงาน</th><th>ทีม</th><th>ค่าดริ้ง D / M</th><th>ยอด D/M ที่จับคู่</th><th>อัตราจ่าย</th><th>สถานะ</th><th>ยอดจ่ายปัจจุบัน</th><th>ประมาณการปลายเดือน</th></tr></thead><tbody><?php if(!$results):?><tr><td colspan="8" class="empty">ยังไม่มี Sales/PR ที่เปิด POS Incentive · ตั้ง Alias ที่ Employee Center ก่อน</td></tr><?php endif;?><?php foreach($results as $r):$e=posi_employee_by_id($d,(int)$r['employee_id']);?><tr><td><b><?=h($e?workforce_employee_label($e):'#'.$r['employee_id'])?></b><small><?=h(workforce_position_label((string)$r['position']))?><?=$r['team_lead']?' · หัวทีม':''?></small></td><td><?=h($r['team_code']?:'—')?></td><td><div class="drink-split"><span class="d">D <b><?=number_format((float)($r['d_units']??0),0)?></b></span><span class="m">M <b><?=number_format((float)($r['m_units']??0),0)?></b></span></div><small>รวม <?=number_format((float)$r['units'],0)?> หน่วย</small></td><td><b><?=number_format((float)$r['sales'],2)?></b></td><td><?=number_format((float)$r['rate'],2)?></td><td><span class="state <?=h((string)$r['status'])?>"><?=h(posi_status_label((string)$r['status']))?></span><?php if($r['rule_name']):?><small><?=h((string)$r['rule_name'])?></small><?php endif;?></td><td><b><?=number_format((float)$r['recognized_pay'],2)?></b><small><?=(float)$r['potential_pay']>(float)$r['recognized_pay']?'Potential '.number_format((float)$r['potential_pay'],2):h($currency)?></small></td><td><b><?=number_format((float)$r['projected_potential_pay'],2)?></b><small><?=number_format((float)$r['projected_units'],1)?> units · <?=$r['projected_unlock']?'มีแนวโน้มผ่าน':'ยังไม่ผ่าน Target'?></small></td></tr><?php endforeach;?></tbody></table></div></section>
<div class="posi-grid lower"><section class="posi-card"><div class="posi-card-head"><div><small>04 / UNMATCHED</small><h2>ชื่อ D/M ที่ยังไม่ตรงกับพนักงาน</h2><p>แสดงเฉพาะรายการค่าดริ้ง ไม่รวมอาหาร เครื่องดื่ม Member และสินค้าอื่น</p></div></div><div class="unmatched-list"><?php if(!$unmatched):?><div class="empty">ไม่มีรายการ Unmatched</div><?php endif;?><?php foreach($unmatched as $x):?><article><div><b><?=h((string)$x['item_name'])?></b><span><?=number_format((float)$x['qty'],2)?> units · <?=$x['rows']?> rows</span></div><strong><?=number_format((float)$x['sales'],2)?> <?=h($currency)?></strong></article><?php endforeach;?></div></section><section class="posi-card"><div class="posi-card-head"><div><small>05 / IMPORT HISTORY</small><h2>ประวัติ Batch เดือนนี้</h2><p>เก็บต้นทาง, Hash, ช่วงวันที่ และสถานะเพื่อ Audit ย้อนหลัง</p></div></div><div class="batch-list"><?php if(!$batches):?><div class="empty">ยังไม่มี Import เดือนนี้</div><?php endif;?><?php foreach($batches as $b):?><article class="<?=h((string)($b['status']??'active'))?>"><div><b>#<?=(int)$b['id']?> · <?=h((string)$b['source_name'])?></b><span><?=h((string)$b['filename'])?></span><small><?=h((string)$b['period_start'])?> → <?=h((string)$b['period_end'])?> · <?=h(strtoupper((string)$b['import_mode']))?></small></div><div><strong><?=number_format((float)$b['total_sales'],2)?></strong><span><?=(int)$b['rows_imported']?> สินค้า · D/M Match <?=(int)$b['matched_rows']?><?=isset($b['candidate_rows'])?' / '.(int)$b['candidate_rows']:''?></span><em><?=h(strtoupper((string)$b['status']))?></em><?php if(($b['status']??'active')==='active'&&!$closing):?><form method="post" class="batch-void" onsubmit="return confirm('Void Batch #<?=(int)$b['id']?>? ยอดจาก Batch นี้จะถูกตัดออกจากการคำนวณ')"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><input type="hidden" name="action" value="void_batch"><input type="hidden" name="month" value="<?=h($month)?>"><input type="hidden" name="batch_id" value="<?=(int)$b['id']?>"><button>Void</button></form><?php endif;?></div></article><?php endforeach;?></div></section></div>
<nav class="posi-flow-actions" aria-label="ไปขั้นตอนก่อนหน้าหรือถัดไป">
<?php if($step>1):?><a class="prev" href="?<?=h($flowQuery)?>&step=<?=$step-1?>">← ขั้นตอนก่อนหน้า</a><?php elseif($inboxWaiting>0):?><button type="submit" name="action" value="clear_inbox_process" class="prev" form="posi-inbox-process-form" onclick="return confirm('เคลียร์ Process ของไฟล์ที่เลือกและยกเลิก Batch เดิมใช่หรือไม่? ไฟล์ต้นฉบับจะไม่ถูกลบ')">เคลียร์ Process ไฟล์ที่เลือก</button><?php else:?><span></span><?php endif;?>
<div><b>ขั้นตอน <?=$step?> จาก 4</b><small><?=['','อัปโหลดและเลือกช่วงข้อมูล','Sort และตรวจรายการ','ตั้งกติกาและคำนวณ','ตรวจสอบก่อนบันทึก'][$step]?></small></div>
<?php if($step===1):?><?php if($inboxWaiting>0):?><button type="submit" name="action" value="process_inbox" class="next" form="posi-inbox-process-form">ขั้นตอนต่อไป: Process ไฟล์ที่เลือก →</button><?php elseif($step1Done):?><a class="next" href="?<?=h($flowQuery)?>&step=2">ขั้นตอนต่อไป →</a><?php else:?><button disabled>Import และเลือกไฟล์ก่อน</button><?php endif;?>
<?php elseif($step===2):?><a class="next" data-calc-next href="#" aria-disabled="true">เลือกฟังก์ชันก่อน →</a>
<?php elseif($step===3):?><?php if($step3Done):?><a class="next" href="?<?=h($flowQuery)?>&step=4">ขั้นตอนต่อไป: ตรวจข้อมูล →</a><?php else:?><button disabled>ต้องบันทึกกติกาค่าคอมก่อน</button><?php endif;?>
<?php else:?><?php if(!$closing):?><form method="post" onsubmit="return confirm('ตรวจข้อมูลครบแล้วและต้องการบันทึก Final รอบนี้ใช่หรือไม่?')"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><input type="hidden" name="action" value="finalize"><input type="hidden" name="flow_ready" value="1"><input type="hidden" name="step" value="4"><input type="hidden" name="month" value="<?=h($month)?>"><input type="hidden" name="period_mode" value="<?=h($periodMode)?>"><input type="hidden" name="date_from" value="<?=h($periodFrom)?>"><input type="hidden" name="date_to" value="<?=h($periodTo)?>"><button class="save">บันทึกข้อมูลและ Final รอบนี้ ✓</button></form><?php else:?><strong class="saved">✓ บันทึก Final แล้ว</strong><?php endif;?><?php endif;?>
</nav>
<section class="posi-explain"><b>หลักการคำนวณ</b><p>ยอดสุทธิทุกสินค้าจาก POS ใช้ตรวจ Target ของร้าน ส่วนค่าดริ้งนับเฉพาะรายการ D/M ในกลุ่ม PR และ Sales ที่จับคู่ Alias สำเร็จ แล้วคูณอัตราจ่ายของพนักงานหรือ Rule รายเดือน ก่อน Final ระบบแสดงเป็นยอดประมาณการเท่านั้น</p></section><footer>MR BAR POS Incentive & Commission · <?=h((string)(app_config()['pack']??'MR BAR'))?> · Schema v<?=h((string)($d['meta']['schema']??24))?></footer></main><script src="assets/pos-incentive-product-sort-v1360.js?v=1439" defer></script><script src="assets/pos-period-picker-v1380.js?v=1380" defer></script><script src="assets/pos-sales-tiers-v1420.js?v=1420" defer></script></body></html>
