<?php
header('Cache-Control: no-store, no-cache, must-revalidate, max-age=0');
header('Pragma: no-cache');
require __DIR__.'/app/bootstrap.php';
require_once __DIR__.'/app/pr-preview.php';
$previewCtx=pr_preview_context();$isAdminPreview=(bool)$previewCtx;$msg='';$err='';
if($previewCtx){$u=$previewCtx['user'];$d=$previewCtx['data'];$pr=$previewCtx['pr'];}
else{$u=require_roles('pr');$d=db_load();$pr=user_pr($d,(int)$u['id']);if(!$pr){$pr=try_auto_link_pr_account((int)$u['id']);if($pr)$d=db_load();}}
if(!$pr){header('Location: pr.php');exit;}
$prId=(int)$pr['id'];$uid=(int)$u['id'];
function pj_media_url(array $pr,string $key): string{$rel=(string)($pr['profile'][$key]??'');if($rel==='')return '';if(strpos($rel,'storage/pr-media/')===0)return 'pr-media.php?pr_id='.(int)$pr['id'].'&field='.rawurlencode($key);return $rel;}
function pj_shift_status(string $s): string{return ['scheduled'=>'มีกะงาน','confirmed'=>'ยืนยันกะแล้ว','working'=>'กำลังทำงาน','completed'=>'จบกะ','off'=>'วันหยุด','cancelled'=>'ยกเลิก'][$s]??$s;}
function pj_fmt_time($v): string{if(!$v)return '—';$ts=strtotime((string)$v);return $ts?date('H:i',$ts):'—';}
function pj_job_step(string $status): int{return ['assigned'=>1,'accepted'=>2,'in_service'=>3,'completed'=>4,'rejected'=>0][$status]??0;}
if($_SERVER['REQUEST_METHOD']==='POST'){
 pr_preview_block_post();
 csrf_check();$action=(string)($_POST['action']??'');
 try{
  if($action==='status'){
   $st=(string)($_POST['status']??'');if(!in_array($st,['online','break'],true))throw new RuntimeException('สถานะไม่ถูกต้อง');
   db_mutate(function($x)use($prId,$st,$uid){if(!attendance_open($x,$prId))throw new RuntimeException('ต้อง Check-in เข้าเวรก่อนเปลี่ยนสถานะ');foreach($x['checkins'] as $c)if((int)($c['pr_id']??0)===$prId&&in_array((string)($c['status']??''),['assigned','accepted','in_service'],true))throw new RuntimeException('กำลังมีงานอยู่ ไม่สามารถเปลี่ยนสถานะเองได้');foreach($x['prs'] as &$p)if((int)$p['id']===$prId)$p['status']=$st;unset($p);$x['audit'][]=['at'=>date('c'),'action'=>'pr_status','pr_id'=>$prId,'status'=>$st,'by'=>$uid];return $x;});$msg='เปลี่ยนสถานะเรียบร้อย';
  }elseif(in_array($action,['accept_job','reject_job','start_service','complete_job'],true)){
   $cid=(int)($_POST['checkin_id']??0);
   if($action==='accept_job')db_mutate(function($x)use($cid,$prId,$uid){foreach($x['checkins'] as &$c)if((int)$c['id']===$cid){if((int)($c['pr_id']??0)!==$prId||($c['status']??'')!=='assigned')throw new RuntimeException('งานนี้ไม่พร้อมให้รับ');$c['status']='accepted';$c['accepted_at']=date('c');$c['updated_at']=date('c');foreach($x['prs'] as &$p)if((int)$p['id']===$prId){$p['status']='busy';$p['current_checkin_id']=$cid;}unset($p);$x['audit'][]=['at'=>date('c'),'action'=>'pr_accept_job','checkin_id'=>$cid,'pr_id'=>$prId,'by'=>$uid];return $x;}unset($c);throw new RuntimeException('ไม่พบงาน');});
   if($action==='reject_job')db_mutate(function($x)use($cid,$prId,$uid){foreach($x['checkins'] as &$c)if((int)$c['id']===$cid){if((int)($c['pr_id']??0)!==$prId||($c['status']??'')!=='assigned')throw new RuntimeException('งานนี้ไม่พร้อมให้ปฏิเสธ');$c['status']='rejected';$c['rejected_at']=date('c');$c['updated_at']=date('c');$c['pr_id']=null;foreach($x['prs'] as &$p)if((int)$p['id']===$prId){$p['status']=attendance_open($x,$prId)?'online':'offline';$p['current_checkin_id']=null;}unset($p);$x['audit'][]=['at'=>date('c'),'action'=>'pr_reject_job','checkin_id'=>$cid,'pr_id'=>$prId,'by'=>$uid];return $x;}unset($c);throw new RuntimeException('ไม่พบงาน');});
   if($action==='start_service')db_mutate(function($x)use($cid,$prId,$uid){foreach($x['checkins'] as &$c)if((int)$c['id']===$cid){if((int)($c['pr_id']??0)!==$prId||($c['status']??'')!=='accepted')throw new RuntimeException('งานนี้ยังไม่พร้อมเริ่มบริการ');$c['status']='in_service';$c['started_at']=date('c');$c['updated_at']=date('c');$x['audit'][]=['at'=>date('c'),'action'=>'pr_start_service','checkin_id'=>$cid,'pr_id'=>$prId,'by'=>$uid];return $x;}unset($c);throw new RuntimeException('ไม่พบงาน');});
   if($action==='complete_job')db_mutate(function($x)use($cid,$prId,$uid){foreach($x['checkins'] as &$c)if((int)$c['id']===$cid){if((int)($c['pr_id']??0)!==$prId||!in_array((string)$c['status'],['accepted','in_service'],true))throw new RuntimeException('งานนี้ไม่พร้อมปิด');$tableId=(int)($c['table_id']??0);$c['status']='completed';$c['completed_at']=date('c');$c['updated_at']=date('c');foreach($x['prs'] as &$p)if((int)$p['id']===$prId){$p['status']=attendance_open($x,$prId)?'online':'offline';$p['current_checkin_id']=null;}unset($p);foreach($x['tables'] as &$t)if((int)$t['id']===$tableId)$t['status']='available';unset($t);$x['audit'][]=['at'=>date('c'),'action'=>'pr_complete_job','checkin_id'=>$cid,'pr_id'=>$prId,'by'=>$uid];return $x;}unset($c);throw new RuntimeException('ไม่พบงาน');});
   $msg='อัปเดตงานเรียบร้อย';
  }elseif($action==='read_notifications'){
   db_mutate(function($x)use($uid){foreach($x['notifications'] as &$n)if(empty($n['read_at'])&&(int)($n['user_id']??0)===$uid)$n['read_at']=date('c');unset($n);return $x;});$msg='อ่านการแจ้งเตือนทั้งหมดแล้ว';
  }
 }catch(Throwable $e){$err=$e->getMessage();}
 $d=db_load();$pr=user_pr($d,(int)$u['id']);
}
$open=attendance_open($d,$prId);
$activeJobs=array_values(array_filter($d['checkins']??[],function($c)use($prId){return (int)($c['pr_id']??0)===$prId&&in_array((string)($c['status']??''),['assigned','accepted','in_service'],true);}));
usort($activeJobs,function($a,$b){return strcmp((string)($b['updated_at']??''),(string)($a['updated_at']??''));});
$rejectedIds=[];foreach($d['audit']??[] as $a)if(($a['action']??'')==='pr_reject_job'&&(int)($a['pr_id']??0)===$prId)$rejectedIds[(int)($a['checkin_id']??0)]=1;
$history=[];foreach($d['checkins']??[] as $c){$id=(int)($c['id']??0);$mine=(int)($c['pr_id']??0)===$prId||isset($rejectedIds[$id]);if(!$mine)continue;if(!in_array((string)($c['status']??''),['completed','rejected'],true))continue;$history[]=$c;}
usort($history,function($a,$b){return strcmp((string)($b['updated_at']??$b['completed_at']??''),(string)($a['updated_at']??$a['completed_at']??''));});$history=array_slice($history,0,12);
$today=date('Y-m-d');$limit=date('Y-m-d',strtotime('+14 days'));$shifts=[];foreach($d['shifts']??[] as $s){if((int)($s['pr_id']??0)!==$prId)continue;$date=(string)($s['date']??'');$st=(string)($s['status']??'scheduled');if($date<$today||$date>$limit||in_array($st,['cancelled','off'],true))continue;$shifts[]=$s;}usort($shifts,function($a,$b){$ka=(string)($a['date']??'').' '.(string)($a['start']??'');$kb=(string)($b['date']??'').' '.(string)($b['start']??'');return strcmp($ka,$kb);});
$notifications=op_unread_notifications($d,$u);$avatar=pj_media_url($pr,'profile_photo');$canChangeStatus=$open&&count($activeJobs)===0;
?><!doctype html><html lang="th"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="theme-color" content="#090617"><title>MR BAR — งาน PR</title><link rel="stylesheet" href="assets/pr.css?v=1250"><link rel="stylesheet" href="assets/pr-jobs.css?v=1131"><?php if($isAdminPreview):?><link rel="stylesheet" href="assets/pr-preview-v1173.css?v=1173"><?php endif;?></head><body class="attendance-home-body jobs-hub-body" data-auto-refresh="<?=h((string)($d['settings']['pr_auto_refresh']??'1'))?>"><div class="aurora a1"></div><div class="aurora a2"></div><div class="gridfx"></div><?php if($isAdminPreview)echo pr_preview_banner();?>
<div id="prDrawerBackdrop" class="pr-drawer-backdrop" hidden></div><aside id="prDrawer" class="pr-drawer" aria-hidden="true"><div class="drawer-head"><div class="drawer-avatar"><?php if($avatar!==''):?><img src="<?=h($avatar)?>" alt=""><?php else:?><span>♛</span><?php endif;?></div><div><small>MR BAR / PR</small><strong><?=h((string)($pr['profile']['nickname']??'')?:$pr['name'])?></strong><span><?=h((string)$pr['code'])?> · <?=h(strtoupper((string)$pr['status']))?></span></div><button type="button" id="drawerClose">×</button></div><nav class="drawer-nav"><a href="pr.php">◷ <span>ลงเวลา</span></a><a href="pr-calendar.php">▦ <span>ปฏิทิน / ประวัติ / ลา</span></a><a href="employee-income.php">฿ <span>รายได้ของฉัน</span></a><a class="drawer-active" href="pr-jobs.php">✦ <span>งาน / ตารางกะ / Track</span><b><?=count($activeJobs)?></b></a><a href="pr.php?profile=1">♙ <span>โปรไฟล์ส่วนตัว</span></a></nav><a class="drawer-logout" href="logout.php">ออกจากระบบ ↗</a></aside>
<main class="pr-mobile-shell jobs-shell"><header class="pr-appbar"><button type="button" class="hamburger" id="drawerOpen"><span></span><span></span><span></span></button><div class="appbar-brand"><small>MR BAR</small><strong>PR WORK</strong></div><div class="appbar-right"><span class="work-status <?=h((string)$pr['status'])?>"><?=h(strtoupper((string)$pr['status']))?></span><div class="mini-avatar"><?php if($avatar!==''):?><img src="<?=h($avatar)?>" alt=""><?php else:?><span>♛</span><?php endif;?></div></div></header>
<?php if($msg):?><div class="alert ok home-alert">✓ <?=h($msg)?></div><?php endif;?><?php if($err):?><div class="alert error home-alert">! <?=h($err)?></div><?php endif;?>
<section class="jobs-hero"><div><small>WORK CENTER</small><h1>งานของฉัน</h1><p>งานที่ Staff Assign · ตารางกะ · Track งานย้อนหลัง</p></div><div class="jobs-kpis"><span><b><?=count($activeJobs)?></b><small>กำลังดำเนินการ</small></span><span><b><?=count($shifts)?></b><small>กะ 14 วัน</small></span><span><b><?=count($notifications)?></b><small>แจ้งเตือนใหม่</small></span></div></section>
<section class="work-card" id="availability"><div class="section-title-row"><div><small>AVAILABILITY</small><h2>สถานะรับงาน</h2></div><span class="attendance-state <?=$open?'on':'off'?>"><?=$open?'เข้าเวรแล้ว':'ยังไม่เข้าเวร'?></span></div><form method="post" class="availability-inline"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><input type="hidden" name="action" value="status"><button name="status" value="online" class="status-btn online" <?=$canChangeStatus?'':'disabled'?>>ONLINE<small>พร้อมรับงาน</small></button><button name="status" value="break" class="status-btn break" <?=$canChangeStatus?'':'disabled'?>>BREAK<small>พักชั่วคราว</small></button></form></section>
<section class="work-card" id="assigned"><div class="section-title-row"><div><small>ASSIGNED JOBS</small><h2>งานที่ได้รับมอบหมาย</h2></div><span class="count"><?=count($activeJobs)?> JOBS</span></div><?php if(!$activeJobs):?><div class="empty compact"><b>ยังไม่มีงานใหม่ ✦</b><p>เมื่อ Staff Assign งาน งานจะขึ้นตรงนี้ทันที</p></div><?php endif;?>
<?php foreach($activeJobs as $c):$t=op_find_table($d,(int)($c['table_id']??0));$step=pj_job_step((string)$c['status']);?><article class="job-hub-card status-<?=h((string)$c['status'])?>"><div class="job-top"><div><span class="ticket"><?=h((string)($c['ticket']??('#'.$c['id'])))?></span><h3><?=h((string)($c['guest_name']??'ลูกค้า'))?></h3><p>โต๊ะ <b><?=h((string)($t['code']??'-'))?></b> · <?=h(op_status_label((string)$c['status']))?></p></div><span class="job-state"><?=h(strtoupper((string)$c['status']))?></span></div><div class="job-track" aria-label="ขั้นตอนงาน"><i class="<?=$step>=1?'done':''?>">1<small>ASSIGN</small></i><span class="<?=$step>=2?'done':''?>"></span><i class="<?=$step>=2?'done':''?>">2<small>ACCEPT</small></i><span class="<?=$step>=3?'done':''?>"></span><i class="<?=$step>=3?'done':''?>">3<small>SERVICE</small></i><span class="<?=$step>=4?'done':''?>"></span><i class="<?=$step>=4?'done':''?>">4<small>DONE</small></i></div><div class="job-times"><span>Assign <b><?=pj_fmt_time($c['assigned_at']??$c['created_at']??null)?></b></span><span>Accept <b><?=pj_fmt_time($c['accepted_at']??null)?></b></span><span>Start <b><?=pj_fmt_time($c['started_at']??null)?></b></span></div><form method="post" class="job-action-row"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><input type="hidden" name="checkin_id" value="<?=$c['id']?>"><?php if(($c['status']??'')==='assigned'):?><button class="accept" name="action" value="accept_job">✓ รับงาน</button><button class="reject" name="action" value="reject_job">× ปฏิเสธ</button><?php elseif(($c['status']??'')==='accepted'):?><button class="start" name="action" value="start_service">⚡ เริ่มบริการ</button><button class="complete" name="action" value="complete_job">✓ จบงาน</button><?php else:?><button class="complete big" name="action" value="complete_job">✓ จบบริการและคืนโต๊ะ</button><?php endif;?></form></article><?php endforeach;?></section>
<section class="work-card" id="shifts"><div class="section-title-row"><div><small>SHIFT SCHEDULE</small><h2>ตารางกะ 14 วัน</h2></div><a class="count" href="pr-calendar.php" style="text-decoration:none">เปิดปฏิทิน →</a></div><div class="shift-list"><?php if(!$shifts):?><div class="empty compact"><b>ยังไม่มีกะที่กำหนด</b><p>เมื่อ Admin/Staff จัดกะ จะปรากฏที่นี่</p></div><?php endif;?><?php foreach($shifts as $s):$date=(string)($s['date']??'');$isToday=$date===$today;?><article class="shift-row <?=$isToday?'today':''?>"><div class="shift-date"><b><?=h(date('d',strtotime($date)))?></b><span><?=h(date('m/Y',strtotime($date)))?></span></div><div><strong><?=$isToday?'วันนี้ · ':''?><?=h(date('D',strtotime($date)))?></strong><p><?=h((string)($s['start']??'--:--'))?> → <?=h((string)($s['end']??'--:--'))?></p></div><em><?=h(pj_shift_status((string)($s['status']??'scheduled')))?></em></article><?php endforeach;?></div></section>
<section class="work-card" id="tracker"><div class="section-title-row"><div><small>JOB TRACKER</small><h2>Track งานย้อนหลัง</h2></div><span class="count"><?=count($history)?> RECENT</span></div><div class="tracker-list"><?php if(!$history):?><div class="empty compact"><b>ยังไม่มีประวัติงาน</b></div><?php endif;?><?php foreach($history as $c):$t=op_find_table($d,(int)($c['table_id']??0));?><article class="track-row"><span class="track-icon <?=h((string)$c['status'])?>"><?=($c['status']??'')==='completed'?'✓':'×'?></span><div><strong><?=h((string)($c['ticket']??('#'.$c['id'])))?> · โต๊ะ <?=h((string)($t['code']??'-'))?></strong><p><?=h((string)($c['guest_name']??'ลูกค้า'))?> · <?=h(op_status_label((string)$c['status']))?></p><small>Assign <?=pj_fmt_time($c['assigned_at']??$c['created_at']??null)?> · Accept <?=pj_fmt_time($c['accepted_at']??null)?> · Start <?=pj_fmt_time($c['started_at']??null)?> · End <?=pj_fmt_time($c['completed_at']??$c['rejected_at']??null)?></small></div></article><?php endforeach;?></div></section>
<section class="work-card" id="updates"><div class="section-title-row"><div><small>UPDATES</small><h2>การแจ้งเตือนงาน</h2></div><?php if($notifications):?><form method="post"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><button class="read-all" name="action" value="read_notifications">อ่านทั้งหมด</button></form><?php endif;?></div><div class="work-notifies"><?php if(!$notifications):?><div class="empty compact"><b>ไม่มีแจ้งเตือนใหม่</b></div><?php endif;?><?php foreach(array_slice(array_reverse($notifications),0,8) as $n):?><article><span>◉</span><div><b><?=h((string)$n['message'])?></b><small><?=h(date('d/m H:i',strtotime((string)$n['created_at'])))?></small></div></article><?php endforeach;?></div></section>
<footer class="attendance-footer">✦ MR BAR PR Work · v1.13.1</footer></main>
<nav class="mobile-dock jobs-dock income-dock"><a href="pr.php"><span>◷</span><small>ลงเวลา</small></a><a href="pr-calendar.php"><span>▦</span><small>ปฏิทิน</small></a><a href="employee-income.php"><span>฿</span><small>รายได้</small></a><a class="active" href="pr-jobs.php"><span>✦</span><small>งาน</small><?php if(count($activeJobs)):?><b><?=count($activeJobs)?></b><?php endif;?></a></nav>
<script src="assets/pr-jobs.js?v=1131"></script><?php if($isAdminPreview):?><script src="assets/pr-preview-v1173.js?v=1173"></script><?php endif;?></body></html>
