<?php
// v1.11.3: mobile secure-context / permissions hardening
$https = (!empty($_SERVER['HTTPS']) && strtolower((string)$_SERVER['HTTPS']) !== 'off') || strtolower((string)($_SERVER['HTTP_X_FORWARDED_PROTO'] ?? '')) === 'https';
if (!$https) {
    $host = (string)($_SERVER['HTTP_HOST'] ?? 'nigiwaigroup.com');
    $uri = (string)($_SERVER['REQUEST_URI'] ?? '/it/pr.php');
    header('Location: https://'.$host.$uri, true, 302);
    exit;
}
header('Permissions-Policy: geolocation=(self), camera=(self)');
header('Cache-Control: no-store, no-cache, must-revalidate, max-age=0');
header('Pragma: no-cache');
require __DIR__.'/app/bootstrap.php';
require_once __DIR__.'/app/pr-preview.php';
$previewCtx=pr_preview_context();$isAdminPreview=(bool)$previewCtx;$msg='';$err='';
if($previewCtx){$u=$previewCtx['user'];$d=$previewCtx['data'];$pr=$previewCtx['pr'];}
else{$u=require_roles('pr');$d=db_load();$pr=user_pr($d,(int)$u['id']);if(!$pr){$pr=try_auto_link_pr_account((int)$u['id']);if($pr)$d=db_load();}}
if(!$pr){http_response_code(403);?><!doctype html><html lang="th"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#080713"><title>MR BAR — PR Account Link</title><link rel="stylesheet" href="assets/pr.css?v=1250"></head><body class="link-guard"><main class="link-card"><span class="beta">⚠ PR PROFILE NOT LINKED</span><div class="guard-icon">♛</div><h1>บัญชี PR ยังไม่ได้เชื่อมกับโปรไฟล์</h1><p>บัญชีนี้ยังไม่มี PR Profile ที่เชื่อมโยง จึงยังไม่สามารถ Check-in หรือแก้ไข Profile ได้</p><div class="guard-account"><b><?=h((string)$u['display_name'])?></b><small>@<?=h((string)$u['username'])?></small></div><p class="guard-hint">ให้ Admin เข้า Management → PR Management → Account Link แล้วเลือกบัญชีนี้ จากนั้นกด Reload</p><div class="guard-actions"><a class="primary" href="pr.php">↻ ตรวจอีกครั้ง</a><a class="logout" href="logout.php">ออกจากระบบ</a></div></main></body></html><?php exit;}

$employee=workforce_employee_by_pr($d,(int)$pr['id']);
if(!$employee){
    // Defensive fallback: schema v18 migration normally creates this automatically.
    $employee=['id'=>(int)($pr['employee_id']??0),'code'=>(string)($pr['code']??''),'name'=>(string)($pr['name']??''),'user_id'=>(int)($u['id']??0),'pr_id'=>(int)$pr['id'],'branch_id'=>$pr['branch_id']??null,'attendance_required'=>1,'attendance_policy'=>[]];
}
$employeeId=(int)($employee['id']??0);
$attendancePolicy=workforce_policy($d,$employee);

function pr_ensure_media_dir(string $dir): bool{
    if(is_dir($dir)&&is_writable($dir))return true;
    if(!is_dir($dir)){@mkdir($dir,0775,true);clearstatcache(true,$dir);}
    if(is_dir($dir)&&!is_writable($dir)){@chmod($dir,0775);clearstatcache(true,$dir);}
    if(is_dir($dir)&&!is_writable($dir)){@chmod($dir,0777);clearstatcache(true,$dir);}
    return is_dir($dir)&&is_writable($dir);
}
function pr_profile_upload(int $prId,string $field): ?string{
    if(empty($_FILES[$field])||($_FILES[$field]['error']??UPLOAD_ERR_NO_FILE)===UPLOAD_ERR_NO_FILE)return null;
    $f=$_FILES[$field];if(($f['error']??UPLOAD_ERR_OK)!==UPLOAD_ERR_OK)throw new RuntimeException('อัปโหลดรูปไม่สำเร็จ (Upload error '.(int)($f['error']??-1).')');
    if((int)$f['size']>5*1024*1024)throw new RuntimeException('รูปต้องมีขนาดไม่เกิน 5MB');
    $fi=new finfo(FILEINFO_MIME_TYPE);$mime=$fi->file($f['tmp_name']);$ext=['image/jpeg'=>'jpg','image/png'=>'png','image/webp'=>'webp'][$mime]??null;
    if(!$ext)throw new RuntimeException('รองรับรูป JPG, PNG หรือ WEBP เท่านั้น');

    // Prefer public uploads for backward compatibility. If shared hosting blocks it,
    // automatically fall back to private storage and serve through pr-media.php.
    $publicDir=__DIR__.'/uploads/pr/'.$prId;
    $privateDir=__DIR__.'/storage/pr-media/'.$prId;
    $isPrivate=false;
    if(pr_ensure_media_dir($publicDir)){$dir=$publicDir;}
    elseif(pr_ensure_media_dir($privateDir)){$dir=$privateDir;$isPrivate=true;}
    else{throw new RuntimeException('Server ไม่อนุญาตให้เขียนโฟลเดอร์รูป ทั้ง uploads/pr และ storage/pr-media กรุณาตรวจ FileZilla Permission ของโฟลเดอร์ storage');}

    $name=$field.'-'.date('YmdHis').'-'.bin2hex(random_bytes(4)).'.'.$ext;$dest=$dir.'/'.$name;
    if(!move_uploaded_file($f['tmp_name'],$dest))throw new RuntimeException('ไม่สามารถบันทึกรูปบน Server ได้ แม้โฟลเดอร์ปลายทางเขียนได้');
    @chmod($dest,0664);
    return $isPrivate?'storage/pr-media/'.$prId.'/'.$name:'uploads/pr/'.$prId.'/'.$name;
}
function pr_profile_value(array $pr,string $key): string{return (string)($pr['profile'][$key]??'');}
function pr_profile_media_url(array $pr,string $key): string{
    $rel=pr_profile_value($pr,$key);if($rel==='')return '';
    if(strpos($rel,'storage/pr-media/')===0)return 'pr-media.php?pr_id='.(int)$pr['id'].'&field='.rawurlencode($key);
    return $rel;
}

function pr_attendance_evidence_save(int $prId,string $mode,string $dataUrl): string{
    if(!preg_match('#^data:image/(jpeg|jpg|png|webp);base64,([A-Za-z0-9+/=]+)$#',$dataUrl,$m)) throw new RuntimeException('ไม่พบภาพยืนยันจากกล้อง');
    $bin=base64_decode($m[2],true); if($bin===false||strlen($bin)<500)throw new RuntimeException('ภาพยืนยันไม่สมบูรณ์');
    if(strlen($bin)>3*1024*1024)throw new RuntimeException('ภาพยืนยันมีขนาดใหญ่เกินไป');
    $fi=new finfo(FILEINFO_MIME_TYPE);$mime=$fi->buffer($bin);$ext=['image/jpeg'=>'jpg','image/png'=>'png','image/webp'=>'webp'][$mime]??null;if(!$ext)throw new RuntimeException('รูปแบบภาพยืนยันไม่ถูกต้อง');
    $dir=__DIR__.'/storage/attendance-evidence/'.date('Y/m').'/'.$prId;if(!is_dir($dir)&&!@mkdir($dir,0775,true)&&!is_dir($dir))throw new RuntimeException('Server ไม่สามารถสร้างโฟลเดอร์หลักฐาน Attendance ได้');
    $name=$mode.'-'.date('Ymd-His').'-'.bin2hex(random_bytes(4)).'.'.$ext;$dest=$dir.'/'.$name;if(file_put_contents($dest,$bin,LOCK_EX)===false)throw new RuntimeException('บันทึกภาพยืนยันไม่สำเร็จ');@chmod($dest,0664);
    return 'storage/attendance-evidence/'.date('Y/m').'/'.$prId.'/'.$name;
}
function pr_distance_m(float $lat1,float $lon1,float $lat2,float $lon2): float{$r=6371000;$p1=deg2rad($lat1);$p2=deg2rad($lat2);$dp=deg2rad($lat2-$lat1);$dl=deg2rad($lon2-$lon1);$a=sin($dp/2)**2+cos($p1)*cos($p2)*sin($dl/2)**2;return 2*$r*atan2(sqrt($a),sqrt(1-$a));}
function pr_resolve_branch(array $d,array $pr,float $lat,float $lng): array{
    $list=array_values(array_filter($d['branches']??[],fn($b)=>!empty($b['active'])&&is_numeric($b['lat']??null)&&is_numeric($b['lng']??null)));
    if(!$list)throw new RuntimeException('ยังไม่ได้ตั้งค่าพิกัดสาขา กรุณาแจ้ง Admin ตั้งค่า Branch GPS ก่อน');
    $assigned=(int)($pr['branch_id']??0);if($assigned){foreach($list as $b)if((int)$b['id']===$assigned){$b['_distance']=pr_distance_m($lat,$lng,(float)$b['lat'],(float)$b['lng']);return $b;}}
    foreach($list as &$b)$b['_distance']=pr_distance_m($lat,$lng,(float)$b['lat'],(float)$b['lng']);unset($b);usort($list,fn($a,$b)=>($a['_distance']<=>$b['_distance']));return $list[0];
}


if($_SERVER['REQUEST_METHOD']==='POST'){
    pr_preview_block_post();
    csrf_check();$action=(string)($_POST['action']??'');$face=(string)($_POST['face_verified']??'0')==='1';$prId=(int)$pr['id'];$uid=(int)$u['id'];
    $gpsLat=is_numeric($_POST['gps_lat']??null)?(float)$_POST['gps_lat']:null;$gpsLng=is_numeric($_POST['gps_lng']??null)?(float)$_POST['gps_lng']:null;$gpsAcc=is_numeric($_POST['gps_accuracy']??null)?(float)$_POST['gps_accuracy']:null;$evidenceData=(string)($_POST['evidence_image']??'');
    try{
        $faceRequired=!empty($attendancePolicy['camera_required']);
        if(in_array($action,['checkin','checkout'],true)&&$faceRequired&&!$face)throw new RuntimeException('กรุณาเปิดกล้องและแตะหน้าจอเพื่อยืนยันก่อนบันทึกเวลา');
        if(in_array($action,['checkin','checkout'],true)){
            if(empty($employee['attendance_required']))throw new RuntimeException('โปรไฟล์พนักงานนี้ถูกตั้งค่าเป็นไม่บังคับลงเวลา กรุณาติดต่อ Admin หากต้องการเปิดใช้งาน');
            $gpsRequired=!empty($attendancePolicy['gps_required']);$evidenceRequired=!empty($attendancePolicy['evidence_required']);
            if($gpsRequired&&($gpsLat===null||$gpsLng===null||$gpsAcc===null))throw new RuntimeException('กรุณาอนุญาต Location/GPS ก่อนบันทึกเวลา');
            $branch=null;$distance=null;$radius=(float)$attendancePolicy['radius_m'];
            if($gpsLat!==null&&$gpsLng!==null){
                try{$branch=workforce_resolve_branch($d,$employee,$gpsLat,$gpsLng);$distance=(float)$branch['_distance'];$override=$employee['attendance_policy']['radius_m']??null;$radius=is_numeric($override)?(float)$override:(float)($branch['radius_m']??$attendancePolicy['radius_m']);if($gpsAcc!==null&&$gpsAcc>(float)$attendancePolicy['max_accuracy_m']&&$gpsRequired)throw new RuntimeException('สัญญาณ GPS ยังไม่แม่นยำ (±'.round($gpsAcc).'m) กรุณารอสักครู่แล้วลองใหม่');if(($attendancePolicy['geofence_mode']??'strict')==='strict'&&$distance>$radius)throw new RuntimeException('อยู่นอกรัศมีสาขา '.($branch['name']??'').' ประมาณ '.round($distance).' เมตร (อนุญาต '.round($radius).' เมตร)');}
                catch(Throwable $be){if($gpsRequired)throw $be;}
            }
            if($evidenceRequired&&$evidenceData==='')throw new RuntimeException('กรุณาถ่ายภาพยืนยันก่อนบันทึกเวลา');
            $evidence=$evidenceData!==''?pr_attendance_evidence_save($prId,$action,$evidenceData):'';
            $snapshot=['gps_required'=>$gpsRequired?1:0,'camera_required'=>$faceRequired?1:0,'evidence_required'=>$evidenceRequired?1:0,'geofence_mode'=>(string)($attendancePolicy['geofence_mode']??'strict'),'radius_m'=>$radius,'max_accuracy_m'=>(float)($attendancePolicy['max_accuracy_m']??120)];
            if($action==='checkin'){
                db_mutate(function($d)use($prId,$employeeId,$uid,$face,$gpsLat,$gpsLng,$gpsAcc,$branch,$distance,$evidence,$snapshot){if(attendance_open($d,$prId))throw new RuntimeException('คุณ Check-in เข้าเวรอยู่แล้ว');$d['attendance'][]=['id'=>next_id($d['attendance']),'employee_id'=>$employeeId?:null,'pr_id'=>$prId,'user_id'=>$uid,'check_in'=>date('c'),'check_out'=>null,'method'=>$face?'fullscreen-camera-gps':'pr-time','device'=>substr((string)($_SERVER['HTTP_USER_AGENT']??''),0,180),'branch_id'=>$branch['id']??null,'checkin_lat'=>$gpsLat,'checkin_lng'=>$gpsLng,'checkin_accuracy_m'=>$gpsAcc,'checkin_distance_m'=>$distance,'checkin_evidence'=>$evidence,'policy_snapshot'=>$snapshot,'attendance_state'=>'open','payroll_status'=>'pending','missing_checkout_marked_at'=>null,'planned_checkout_at'=>null,'checkout_source'=>null,'checkout_reason'=>'','checkout_note'=>'','checkout_corrected_by'=>null,'checkout_corrected_at'=>null,'provisional_checkout'=>0];foreach($d['prs'] as &$p)if((int)$p['id']===$prId)$p['status']='online';unset($p);$d['audit'][]=['at'=>date('c'),'action'=>'pr_attendance_checkin','employee_id'=>$employeeId?:null,'pr_id'=>$prId,'by'=>$uid,'branch_id'=>$branch['id']??null,'distance_m'=>$distance,'evidence'=>basename($evidence)];return $d;});$msg='Check-in สำเร็จ'.($branch?' — '.h((string)($branch['name']??'')):'').' · '.date('H:i').' น.';
            }else{
                db_mutate(function($d)use($prId,$employeeId,$uid,$face,$gpsLat,$gpsLng,$gpsAcc,$branch,$distance,$evidence){foreach($d['checkins'] as $c)if((int)($c['pr_id']??0)===$prId&&in_array((string)$c['status'],['assigned','accepted','in_service'],true))throw new RuntimeException('ยังมีงานที่กำลังดำเนินอยู่ กรุณาจบงานก่อน Check-out');$found=false;for($i=count($d['attendance'])-1;$i>=0;$i--){$same=((int)($d['attendance'][$i]['pr_id']??0)===$prId)||($employeeId>0&&(int)($d['attendance'][$i]['employee_id']??0)===$employeeId);if($same&&empty($d['attendance'][$i]['check_out'])){$d['attendance'][$i]['employee_id']=$employeeId?:($d['attendance'][$i]['employee_id']??null);$d['attendance'][$i]['check_out']=date('c');$d['attendance'][$i]['checkout_method']=$face?'fullscreen-camera-gps':'pr-time';$d['attendance'][$i]['checkout_lat']=$gpsLat;$d['attendance'][$i]['checkout_lng']=$gpsLng;$d['attendance'][$i]['checkout_accuracy_m']=$gpsAcc;$d['attendance'][$i]['checkout_distance_m']=$distance;$d['attendance'][$i]['checkout_evidence']=$evidence;$d['attendance'][$i]['attendance_state']='complete';$d['attendance'][$i]['payroll_status']='final';$d['attendance'][$i]['provisional_checkout']=0;$d['attendance'][$i]['checkout_source']='employee';$d['attendance'][$i]['checkout_reason']='';$d['attendance'][$i]['checkout_note']='';if(empty($d['attendance'][$i]['branch_id']))$d['attendance'][$i]['branch_id']=$branch['id']??null;$found=true;break;}}if(!$found)throw new RuntimeException('ไม่พบกะงานที่กำลังเปิดอยู่');foreach($d['prs'] as &$p)if((int)$p['id']===$prId){$p['status']='offline';$p['current_checkin_id']=null;}unset($p);$d['audit'][]=['at'=>date('c'),'action'=>'pr_attendance_checkout','employee_id'=>$employeeId?:null,'pr_id'=>$prId,'by'=>$uid,'branch_id'=>$branch['id']??null,'distance_m'=>$distance,'evidence'=>basename($evidence)];return $d;});$msg='Check-out สำเร็จ'.($branch?' — '.h((string)($branch['name']??'')):'').' · '.date('H:i').' น.';
            }
        }elseif($action==='save_profile'){
            $keys=['nickname','phone','email','line_id','birthday','gender','address','emergency_name','emergency_relation','emergency_phone','bio','languages','specialties','facebook','instagram','tiktok'];$incoming=[];foreach($keys as $k)$incoming[$k]=trim((string)($_POST[$k]??''));
            if($incoming['email']!==''&&!filter_var($incoming['email'],FILTER_VALIDATE_EMAIL))throw new RuntimeException('รูปแบบ Email ไม่ถูกต้อง');
            if(mb_strlen($incoming['bio'])>1000)throw new RuntimeException('แนะนำตัวต้องไม่เกิน 1,000 ตัวอักษร');
            $profilePhoto=pr_profile_upload($prId,'profile_photo');$coverPhoto=pr_profile_upload($prId,'cover_photo');
            db_mutate(function($d)use($prId,$uid,$incoming,$profilePhoto,$coverPhoto){$changed=[];$linkedEmployeeId=null;foreach($d['prs'] as &$p){if((int)$p['id']!==$prId)continue;$before=$p['profile']??[];foreach($incoming as $k=>$v){if((string)($before[$k]??'')!==$v)$changed[]=$k;$p['profile'][$k]=$v;}if($profilePhoto){$p['profile']['profile_photo']=$profilePhoto;$changed[]='profile_photo';}if($coverPhoto){$p['profile']['cover_photo']=$coverPhoto;$changed[]='cover_photo';}$p['profile']['updated_at']=date('c');$p['profile']['updated_by']=$uid;break;}unset($p);foreach($d['employees'] as &$e){if((int)($e['pr_id']??0)!==$prId)continue;$linkedEmployeeId=(int)($e['id']??0);foreach(['nickname','phone','email','line_id','birthday','gender','address','emergency_name','emergency_relation','emergency_phone'] as $k)$e['profile'][$k]=(string)($incoming[$k]??$e['profile'][$k]??'');if($profilePhoto)$e['profile']['profile_photo']=$profilePhoto;$e['updated_at']=date('c');break;}unset($e);$changed=array_values(array_unique($changed));$d['audit'][]=['at'=>date('c'),'action'=>'pr_profile_updated','employee_id'=>$linkedEmployeeId,'pr_id'=>$prId,'by'=>$uid,'changed_fields'=>$changed,'field_count'=>count($changed)];return $d;});$msg='บันทึก Profile เรียบร้อยแล้ว';
        }elseif($action==='status'){
            $st=(string)($_POST['status']??'');if(!in_array($st,['online','break'],true))throw new RuntimeException('สถานะไม่ถูกต้อง');db_mutate(function($d)use($prId,$st,$uid){if(!attendance_open($d,$prId))throw new RuntimeException('ต้อง Check-in เข้าเวรก่อนเปลี่ยนสถานะ');foreach($d['checkins'] as $c)if((int)($c['pr_id']??0)===$prId&&in_array((string)$c['status'],['assigned','accepted','in_service'],true))throw new RuntimeException('กำลังมีงานอยู่ ไม่สามารถเปลี่ยนสถานะเองได้');foreach($d['prs'] as &$p)if((int)$p['id']===$prId)$p['status']=$st;unset($p);$d['audit'][]=['at'=>date('c'),'action'=>'pr_status','pr_id'=>$prId,'status'=>$st,'by'=>$uid];return $d;});$msg='เปลี่ยนสถานะแล้ว';
        }elseif(in_array($action,['accept_job','reject_job','start_service','complete_job'],true)){
            $cid=(int)($_POST['checkin_id']??0);
            if($action==='accept_job')db_mutate(function($d)use($cid,$prId,$uid){foreach($d['checkins'] as &$c)if((int)$c['id']===$cid){if((int)($c['pr_id']??0)!==$prId||($c['status']??'')!=='assigned')throw new RuntimeException('งานนี้ไม่พร้อมให้รับ');$c['status']='accepted';$c['accepted_at']=date('c');$c['updated_at']=date('c');foreach($d['prs'] as &$p)if((int)$p['id']===$prId){$p['status']='busy';$p['current_checkin_id']=$cid;}unset($p);$d['audit'][]=['at'=>date('c'),'action'=>'pr_accept_job','checkin_id'=>$cid,'pr_id'=>$prId,'by'=>$uid];return $d;}unset($c);throw new RuntimeException('ไม่พบงาน');});
            if($action==='reject_job')db_mutate(function($d)use($cid,$prId,$uid){foreach($d['checkins'] as &$c)if((int)$c['id']===$cid){if((int)($c['pr_id']??0)!==$prId||($c['status']??'')!=='assigned')throw new RuntimeException('งานนี้ไม่พร้อมให้ปฏิเสธ');$c['status']='rejected';$c['rejected_at']=date('c');$c['updated_at']=date('c');$c['pr_id']=null;foreach($d['prs'] as &$p)if((int)$p['id']===$prId){$p['status']='online';$p['current_checkin_id']=null;}unset($p);$d['audit'][]=['at'=>date('c'),'action'=>'pr_reject_job','checkin_id'=>$cid,'pr_id'=>$prId,'by'=>$uid];return $d;}unset($c);throw new RuntimeException('ไม่พบงาน');});
            if($action==='start_service')db_mutate(function($d)use($cid,$prId,$uid){foreach($d['checkins'] as &$c)if((int)$c['id']===$cid){if((int)($c['pr_id']??0)!==$prId||($c['status']??'')!=='accepted')throw new RuntimeException('งานนี้ยังไม่พร้อมเริ่มบริการ');$c['status']='in_service';$c['started_at']=date('c');$c['updated_at']=date('c');$d['audit'][]=['at'=>date('c'),'action'=>'pr_start_service','checkin_id'=>$cid,'pr_id'=>$prId,'by'=>$uid];return $d;}unset($c);throw new RuntimeException('ไม่พบงาน');});
            if($action==='complete_job')db_mutate(function($d)use($cid,$prId,$uid){foreach($d['checkins'] as &$c)if((int)$c['id']===$cid){if((int)($c['pr_id']??0)!==$prId||!in_array((string)$c['status'],['accepted','in_service'],true))throw new RuntimeException('งานนี้ไม่พร้อมปิด');$tableId=(int)$c['table_id'];$c['status']='completed';$c['completed_at']=date('c');$c['updated_at']=date('c');foreach($d['prs'] as &$p)if((int)$p['id']===$prId){$p['status']=attendance_open($d,$prId)?'online':'offline';$p['current_checkin_id']=null;}unset($p);foreach($d['tables'] as &$t)if((int)$t['id']===$tableId)$t['status']='available';unset($t);$d['audit'][]=['at'=>date('c'),'action'=>'pr_complete_job','checkin_id'=>$cid,'pr_id'=>$prId,'by'=>$uid];return $d;}unset($c);throw new RuntimeException('ไม่พบงาน');});
            $msg='อัปเดตงานเรียบร้อย';
        }elseif($action==='read_notifications'){db_mutate(function($d)use($uid){foreach($d['notifications'] as &$n)if(empty($n['read_at'])&&(int)($n['user_id']??0)===$uid)$n['read_at']=date('c');unset($n);return $d;});$msg='อ่านการแจ้งเตือนทั้งหมดแล้ว';}
    }catch(Throwable $e){$err=$e->getMessage();}
    $d=db_load();$pr=user_pr($d,(int)$u['id']);$employee=workforce_employee_by_pr($d,(int)$pr['id'])?:$employee;$employeeId=(int)($employee['id']??0);$attendancePolicy=workforce_policy($d,$employee);
}
$open=attendance_open($d,(int)$pr['id']);$notifications=op_unread_notifications($d,$u);$jobs=array_values(array_filter($d['checkins'],fn($c)=>(int)($c['pr_id']??0)===(int)$pr['id']&&in_array((string)$c['status'],['assigned','accepted','in_service'],true)));usort($jobs,fn($a,$b)=>strcmp((string)($b['updated_at']??''),(string)($a['updated_at']??'')));
$cover=pr_profile_media_url($pr,'cover_photo');$avatar=pr_profile_media_url($pr,'profile_photo');
$branchClient=[];foreach(($d['branches']??[]) as $b){if(empty($b['active'])||!is_numeric($b['lat']??null)||!is_numeric($b['lng']??null))continue;$branchClient[]=['id'=>(int)($b['id']??0),'code'=>(string)($b['code']??''),'name'=>(string)($b['name']??''),'lat'=>(float)$b['lat'],'lng'=>(float)$b['lng'],'radius_m'=>(float)($b['radius_m']??$d['settings']['attendance_default_radius_m']??200)];}
$todayAttendance=null;$todayKey=date('Y-m-d');foreach(array_reverse($d['attendance']) as $ta){if((int)($ta['pr_id']??0)!==(int)$pr['id'])continue;if(empty($ta['check_in']))continue;if(date('Y-m-d',strtotime((string)$ta['check_in']))===$todayKey){$todayAttendance=$ta;break;}}
?><!doctype html><html lang="th"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="theme-color" content="#090617"><title>MR BAR — ลงเวลา PR</title><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/leaflet@1.9.4/dist/leaflet.css"><link rel="stylesheet" href="assets/pr.css?v=1250"><link rel="stylesheet" href="assets/pr-gps-icons-v1174.css?v=1180"><?php if($isAdminPreview):?><link rel="stylesheet" href="assets/staff-preview-v12718.css?v=12718"><?php endif;?></head><body class="attendance-home-body" data-auto-refresh="<?=h((string)($d['settings']['pr_auto_refresh']??'1'))?>" data-gps-required="<?=$attendancePolicy['gps_required']?'1':'0'?>" data-camera-required="<?=$attendancePolicy['camera_required']?'1':'0'?>" data-evidence-required="<?=$attendancePolicy['evidence_required']?'1':'0'?>"><div class="aurora a1"></div><div class="aurora a2"></div><div class="gridfx"></div><?php if($isAdminPreview)echo pr_preview_banner();?>
<div id="attendanceOverlay" class="attendance-overlay" hidden data-mode="<?=$open?'checkout':'checkin'?>"><video id="fullCam" autoplay playsinline muted></video><div class="attendance-shade"></div><div class="attendance-scan"></div><button type="button" id="closeAttendance" class="attendance-close">×</button><div class="attendance-float"><span id="attendanceModeLabel"><?=$open?'CHECK-OUT':'CHECK-IN'?></span><h2 id="attendancePrompt">กำลังเปิดกล้อง...</h2><p id="attendanceClock">--:--:--</p><small id="attendanceGpsStatus">กำลังเตรียม Camera + GPS…</small></div><div id="attendanceResult" class="attendance-result"></div></div>

<div id="prDrawerBackdrop" class="pr-drawer-backdrop" hidden></div>
<aside id="prDrawer" class="pr-drawer" aria-hidden="true"><div class="drawer-head"><div class="drawer-avatar"><?php if($avatar!==''):?><img src="<?=h($avatar)?>" alt="PR Profile"><?php else:?><span>♛</span><?php endif;?></div><div><small>MR BAR / PR</small><strong><?=h(pr_profile_value($pr,'nickname')?:$pr['name'])?></strong><span><?=h((string)$pr['code'])?> · <?=h(strtoupper((string)$pr['status']))?></span></div><button type="button" id="drawerClose" aria-label="ปิดเมนู">×</button></div><nav class="drawer-nav"><a href="#attendanceHome" data-drawer-nav>◷ <span>ลงเวลาเข้า / ออกงาน</span></a><a href="pr-jobs.php">✦ <span>งาน / ตารางกะ / Track</span><b><?=count($jobs)?></b></a><a href="employee-income.php">฿ <span>รายได้ของฉัน</span></a><button type="button" id="drawerProfileEdit">♙ <span>โปรไฟล์ส่วนตัว</span></button><a href="pr-jobs.php#availability">● <span>สถานะรับงาน</span></a><a href="pr-jobs.php#updates">◉ <span>การแจ้งเตือน</span><b><?=count($notifications)?></b></a><a href="pr-calendar.php">▦ <span>ปฏิทิน / ประวัติลงเวลา / ขอลา</span></a></nav><details class="drawer-diagnostics"><summary>Device / Security Check</summary><div id="deviceDiag" class="device-diag"><p id="deviceDiagSummary">กำลังตรวจ HTTPS, Origin, GPS และ Camera…</p><div class="device-diag-grid"><span id="diagHttps" class="diag-pill unknown">HTTPS · ตรวจสอบ</span><span id="diagSecure" class="diag-pill unknown">SECURE · ตรวจสอบ</span><span id="diagGeo" class="diag-pill unknown">GPS · ตรวจสอบ</span><span id="diagCam" class="diag-pill unknown">CAMERA · ตรวจสอบ</span></div><small id="deviceOrigin" class="device-origin"></small></div></details><a class="drawer-logout" href="logout.php">ออกจากระบบ ↗</a></aside>

<main class="pr-mobile-shell"><header class="pr-appbar"><button type="button" class="hamburger" id="drawerOpen" aria-label="เปิดเมนู"><span></span><span></span><span></span></button><div class="appbar-brand"><small>MR BAR</small><strong>PR TIME</strong></div><div class="appbar-right"><a id="newJob" class="appbar-bell" href="pr-jobs.php" <?=count($jobs)?'':'hidden'?>><?=count($jobs)?:''?></a><div class="mini-avatar"><?php if($avatar!==''):?><img src="<?=h($avatar)?>" alt=""><?php else:?><span>♛</span><?php endif;?></div></div></header>
<?php if($msg):?><div class="alert ok home-alert">✓ <?=h($msg)?></div><?php endif;?><?php if($err):?><div class="alert error home-alert">! <?=h($err)?></div><?php endif;?>

<section class="time-home" id="attendanceHome"><div class="live-map-wrap"><div id="liveMap" class="live-map"><div id="mapLoading" class="map-loading"><span class="map-pulse"></span><b>กำลังค้นหา GPS</b><small>ระบบจะขอ Location เพื่อแสดงตำแหน่งจริง</small></div></div><div class="map-time"><strong id="homeClock">--:--</strong><span id="homeDate">กำลังโหลดวันที่…</span></div><button type="button" id="mapCenterBtn" class="map-center-btn map-locate-btn" aria-label="จัดตำแหน่งแผนที่กลับมาที่ GPS ปัจจุบัน" title="กลับมาตำแหน่ง GPS ปัจจุบัน"><svg viewBox="0 0 24 24" aria-hidden="true" focusable="false"><circle cx="12" cy="12" r="4.25"></circle><path d="M12 2.4v3M12 18.6v3M2.4 12h3M18.6 12h3"></path><circle class="locate-ring" cx="12" cy="12" r="8"></circle></svg></button><div class="map-provider">LIVE GPS MAP</div></div>
<div class="branch-strip"><span class="branch-icon branch-location-icon" aria-hidden="true"><svg viewBox="0 0 24 24" focusable="false"><path d="M12 21s6.25-5.08 6.25-11.25A6.25 6.25 0 1 0 5.75 9.75C5.75 15.92 12 21 12 21Z"></path><circle cx="12" cy="9.75" r="2.25"></circle></svg></span><div><small>ตำแหน่ง / สาขาปัจจุบัน</small><strong id="gpsHomeState">กำลังเตรียม GPS…</strong><span id="gpsHomeDetail">กำลังค้นหาสาขาที่ใกล้ที่สุด</span></div><button type="button" id="gpsRequestBtn" class="branch-refresh" aria-label="อัปเดต GPS">↻</button></div>
<script id="prBranchData" type="application/json"><?=json_encode($branchClient,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)?></script>
<div class="clock-actions"><button type="button" id="checkinLaunch" class="clock-btn clock-in" <?=$open?'disabled':''?>><small>CHECK-IN</small><b>เข้างาน</b></button><button type="button" id="checkoutLaunch" class="clock-btn clock-out" <?=$open?'':'disabled'?>><small>CHECK-OUT</small><b>ออกงาน</b></button></div>
<form method="post" id="attendanceForm" class="hidden-form"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><input type="hidden" name="face_verified" id="faceVerified" value="0"><input type="hidden" name="action" id="attendanceAction" value="<?=$open?'checkout':'checkin'?>"><input type="hidden" name="gps_lat" id="gpsLat"><input type="hidden" name="gps_lng" id="gpsLng"><input type="hidden" name="gps_accuracy" id="gpsAccuracy"><input type="hidden" name="evidence_image" id="evidenceImage"></form>
<div class="permission-line" id="permissionPreflight"><span class="perm-pill unknown" id="gpsPermPill">GPS · กำลังตรวจ</span><span class="perm-pill unknown" id="cameraPermPill">CAMERA · ขอเมื่อกดลงเวลา</span><button type="button" class="perm-recheck" id="permissionRecheck">ตรวจสิทธิ์</button></div></section>

<section class="today-card"><div class="section-title-row"><div><small>เวลาวันนี้</small><h2>เวลาเข้าออกงาน</h2></div><span class="status-dot <?=h((string)$pr['status'])?>">● <?=h(strtoupper((string)$pr['status']))?></span></div><div class="today-times"><article><small>เข้างาน</small><strong><?=!empty($todayAttendance['check_in'])?h(date('H:i',strtotime((string)$todayAttendance['check_in']))):'--:--'?></strong><span><?=!empty($todayAttendance['check_in'])?h(date('d/m/Y',strtotime((string)$todayAttendance['check_in']))):'ยังไม่ได้ลงเวลา'?></span></article><article><small>ออกงาน</small><strong><?=!empty($todayAttendance['check_out'])?h(date('H:i',strtotime((string)$todayAttendance['check_out']))):'--:--'?></strong><span><?=!empty($todayAttendance['check_out'])?h(date('d/m/Y',strtotime((string)$todayAttendance['check_out']))):($open?'กำลังทำงาน':'ยังไม่มีข้อมูล')?></span></article></div></section>

<footer class="attendance-footer">✦ MR BAR PR Time · v1.20.0</footer></main>

<nav class="mobile-dock pr-main-dock income-dock"><a class="active" href="pr.php"><span>◷</span><small>ลงเวลา</small></a><a href="pr-calendar.php"><span>▦</span><small>ปฏิทิน</small></a><a href="employee-income.php"><span>฿</span><small>รายได้</small></a><a href="pr-jobs.php"><span>✦</span><small>งาน</small><?php if(count($jobs)):?><b><?=count($jobs)?></b><?php endif;?></a></nav>

<div id="profileModal" class="profile-modal" hidden><div class="profile-dialog"><button type="button" id="profileClose" class="modal-close">×</button><div class="profile-preview"><div class="avatar"><?php if($avatar!==''):?><img src="<?=h($avatar)?>" alt="PR Profile"><?php else:?><span>♛</span><?php endif;?></div><div><div class="eyebrow">MY PROFILE</div><h2><?=h(pr_profile_value($pr,'nickname')?:$pr['name'])?></h2><p><?=h(pr_profile_value($pr,'bio')?:'แก้ไขข้อมูลส่วนตัวและรูปโปรไฟล์ได้ที่นี่')?></p></div></div><p class="muted">การเปลี่ยนแปลงทุกครั้งจะบันทึก Activity Log ให้ Admin ตรวจสอบได้</p><form method="post" enctype="multipart/form-data" class="profile-form"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><input type="hidden" name="action" value="save_profile"><div class="upload-grid"><label>รูปโปรไฟล์<input type="file" name="profile_photo" accept="image/jpeg,image/png,image/webp"><small>JPG/PNG/WEBP ≤ 5MB</small></label><label>รูปหน้าปก<input type="file" name="cover_photo" accept="image/jpeg,image/png,image/webp"><small>JPG/PNG/WEBP ≤ 5MB</small></label></div><div class="form-grid"><label>ชื่อเล่น<input name="nickname" value="<?=h(pr_profile_value($pr,'nickname'))?>"></label><label>เบอร์โทร<input name="phone" value="<?=h(pr_profile_value($pr,'phone'))?>"></label><label>Email<input type="email" name="email" value="<?=h(pr_profile_value($pr,'email'))?>"></label><label>LINE ID<input name="line_id" value="<?=h(pr_profile_value($pr,'line_id'))?>"></label><label>วันเกิด<input type="date" name="birthday" value="<?=h(pr_profile_value($pr,'birthday'))?>"></label><label>เพศ/คำเรียก<input name="gender" value="<?=h(pr_profile_value($pr,'gender'))?>"></label><label class="full">ที่อยู่<textarea name="address"><?=h(pr_profile_value($pr,'address'))?></textarea></label><label>ผู้ติดต่อฉุกเฉิน<input name="emergency_name" value="<?=h(pr_profile_value($pr,'emergency_name'))?>"></label><label>ความสัมพันธ์<input name="emergency_relation" value="<?=h(pr_profile_value($pr,'emergency_relation'))?>" placeholder="เช่น มารดา / คู่สมรส"></label><label>เบอร์ฉุกเฉิน<input name="emergency_phone" value="<?=h(pr_profile_value($pr,'emergency_phone'))?>"></label><label class="full">แนะนำตัว<textarea name="bio" maxlength="1000"><?=h(pr_profile_value($pr,'bio'))?></textarea></label><label>ภาษา<input name="languages" value="<?=h(pr_profile_value($pr,'languages'))?>" placeholder="ไทย, English, 中文"></label><label>ความถนัด/สไตล์งาน<input name="specialties" value="<?=h(pr_profile_value($pr,'specialties'))?>"></label><label>Facebook<input name="facebook" value="<?=h(pr_profile_value($pr,'facebook'))?>"></label><label>Instagram<input name="instagram" value="<?=h(pr_profile_value($pr,'instagram'))?>"></label><label>TikTok<input name="tiktok" value="<?=h(pr_profile_value($pr,'tiktok'))?>"></label></div><button class="primary wide" type="submit">SAVE PROFILE CHANGES →</button></form></div></div>
<script src="https://cdn.jsdelivr.net/npm/leaflet@1.9.4/dist/leaflet.js"></script><script src="assets/pr.js?v=1131"></script><?php if($isAdminPreview):?><script src="assets/staff-preview-v12718.js?v=12718"></script><?php endif;?></body></html>
