<?php
declare(strict_types=1);
require __DIR__.'/app/bootstrap.php';
require_once __DIR__.'/app/reservation-payments.php';
$u=require_permission('settings.view');
$d=db_load();
$canManage=user_can($u,'settings.manage',$d);
$message='';$error='';
if($_SERVER['REQUEST_METHOD']==='POST'){
    csrf_check();
    if(!$canManage){http_response_code(403);exit(permission_denied_page('settings.manage'));}
    try{
        $values=mrbar_reservation_payment_settings_from_input($_POST);
        db_mutate(function(array $data)use($values,$u):array{
            foreach($values as $key=>$value)$data['settings'][$key]=$value;
            audit_permission($data,$u,'reservation_payment_settings_updated',['payment_mode'=>$values['reservation_payment_mode'],'deposit_enabled'=>$values['reservation_deposit_enabled']]);
            return $data;
        });
        $message='บันทึกเงื่อนไขการจองแล้ว';
        $d=db_load();
    }catch(Throwable $exception){$error=$exception->getMessage();}
}
$s=$d['settings']??[];
$payment=mrbar_reservation_payment_config($d);
$integrations=mrbar_customer_integrations_status();
$branch=branch_current($d);
$branchLabel=trim((string)($branch['code']??'').' · '.(string)($branch['name']??''),' ·');
function reservation_setting_checked(array $settings,string $key,string $fallback='0'): string {return (string)($settings[$key]??$fallback)==='1'?'checked':'';}
?><!doctype html><html lang="th"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>เงื่อนไขจองและมัดจำ · MR BAR</title><link rel="stylesheet" href="assets/admin.css?v=1140"><link rel="stylesheet" href="assets/admin-v14.css?v=1140"><style>
.booking-settings-main{margin-left:var(--sidebar-w,250px);padding:32px clamp(18px,3vw,48px);min-height:100vh;color:#edf4ff}.booking-settings-header{display:flex;align-items:flex-end;justify-content:space-between;gap:24px;padding-bottom:22px;border-bottom:1px solid #26384d}.booking-settings-header .eyebrow{color:#48d6bc;font-size:11px;font-weight:850;letter-spacing:.08em}.booking-settings-header h1{margin:7px 0;font-size:30px}.booking-settings-header p{margin:0;color:#9cabc1}.booking-settings-header a,.booking-settings-save{border:1px solid #405873;border-radius:7px;padding:11px 15px;background:#122033;color:#e7f1ff;text-decoration:none;font-weight:800}.booking-settings-flash{margin:18px 0;padding:13px 16px;border:1px solid #2b806a;border-radius:8px;background:#0d2828}.booking-settings-flash.is-error{border-color:#963f5a;background:#301923}.booking-settings-layout{display:grid;grid-template-columns:minmax(0,1.45fr) minmax(280px,.8fr);gap:16px;margin-top:20px}.booking-settings-panel{background:#101b2a;border:1px solid #293d54;border-radius:8px;padding:22px}.booking-settings-panel h2{font-size:18px;margin:0 0 6px}.booking-settings-panel>p{font-size:13px;color:#9cabc1;margin:0 0 18px;line-height:1.65}.booking-settings-fields{display:grid;grid-template-columns:1fr 1fr;gap:15px}.booking-settings-fields label{display:grid;gap:7px;font-size:12px;font-weight:750;color:#c3d3e5}.booking-settings-fields label.wide{grid-column:1/-1}.booking-settings-fields input:not([type=checkbox]),.booking-settings-fields select,.booking-settings-fields textarea{width:100%;box-sizing:border-box;border:1px solid #344b66;border-radius:6px;background:#0b1422;color:#eff5ff;padding:11px 12px;font:inherit}.booking-settings-fields textarea{min-height:108px;resize:vertical;line-height:1.6}.booking-setting-help{display:block;color:#8597b0;font-size:11px;line-height:1.55;font-weight:450}.booking-setting-switch{grid-column:1/-1;display:flex!important;align-items:center;justify-content:space-between;gap:20px;padding:14px;border:1px solid #2a3d54;border-radius:7px;background:#0b1523}.booking-setting-switch>span{display:grid;gap:4px}.booking-setting-switch input{width:21px;height:21px;accent-color:#13b98c;flex:0 0 auto}.booking-settings-save{margin-top:18px;background:#0b9f76;border-color:#0b9f76;color:white;cursor:pointer}.booking-settings-save:hover{background:#13b98c}.booking-settings-readiness{display:grid;gap:10px;margin-top:18px}.booking-settings-readiness div{display:flex;justify-content:space-between;gap:10px;padding:11px 12px;border:1px solid #2c3f55;border-radius:6px;background:#0b1422;font-size:12px}.booking-settings-readiness b{color:#63ddb4}.booking-settings-readiness b.is-pending{color:#f5ca74}.booking-settings-flow{margin-top:16px;padding:13px 14px;border-left:3px solid #40cdb3;background:#0b1824;color:#bfccdc;font-size:12px;line-height:1.7}.booking-settings-flow strong{color:#f3f6fa}.booking-settings-foot{margin-top:17px;color:#7f91aa;font-size:11px;line-height:1.7}
@media(max-width:900px){.booking-settings-main{margin-left:0;padding:74px 16px 30px}.booking-settings-layout{grid-template-columns:1fr}.booking-settings-header{align-items:flex-start;flex-direction:column}.booking-settings-header h1{font-size:25px}}
@media(max-width:520px){.booking-settings-panel{padding:16px}.booking-settings-fields{grid-template-columns:1fr}.booking-settings-fields label.wide,.booking-setting-switch{grid-column:auto}.booking-settings-readiness div{align-items:flex-start;flex-direction:column}}
</style></head><body class="admin-v14-page booking-settings-page">
<?php require_once __DIR__.'/app/admin-nav.php';echo admin_sidebar('reservation_settings',$u);?>
<main class="booking-settings-main"><header class="booking-settings-header"><div><p class="eyebrow">CUSTOMER EXPERIENCE / RESERVATION POLICY<?=$branchLabel!==''?' · '.h($branchLabel):''?></p><h1>เงื่อนไขการจองและมัดจำ</h1><p>ตั้งช่องทางรับคำขอ วิธีตรวจการชำระ และข้อความที่ลูกค้าเห็น</p></div><a href="reservations.php">กลับหน้าจัดการจอง <span aria-hidden="true">→</span></a></header>
<?php if($message!==''):?><div class="booking-settings-flash" role="status">✓ <?=h($message)?></div><?php endif;?><?php if($error!==''):?><div class="booking-settings-flash is-error" role="alert">⚠ <?=h($error)?></div><?php endif;?>
<form method="post"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><div class="booking-settings-layout"><section class="booking-settings-panel"><h2>นโยบายรับจอง</h2><p>ปิดมัดจำได้ทันทีเมื่อระบบชำระเงินมีปัญหา โดยยังรับคำขอจองแบบเดิม</p><div class="booking-settings-fields">
<label class="booking-setting-switch"><span><b>เปิดรับจองออนไลน์</b><small class="booking-setting-help">ปิดแล้วลูกค้าจะส่งคำขอจองไม่ได้</small></span><input type="checkbox" name="reservation_enabled" <?=reservation_setting_checked($s,'reservation_enabled','1')?> <?=$canManage?'':'disabled'?>></label>
<label class="booking-setting-switch"><span><b>บังคับชำระมัดจำ</b><small class="booking-setting-help">ปิดสวิตช์นี้เพื่อข้ามการจ่ายและแนบสลิปชั่วคราว โหมดด้านล่างจะยังถูกจำไว้</small></span><input type="checkbox" name="reservation_deposit_enabled" <?=reservation_setting_checked($s,'reservation_deposit_enabled')?> <?=$canManage?'':'disabled'?>></label>
<label class="wide">ช่องทางชำระเงิน<select name="reservation_payment_mode" <?=$canManage?'':'disabled'?>><option value="none" <?=($s['reservation_payment_mode']??'none')==='none'?'selected':''?>>ไม่ต้องชำระ</option><option value="slip_manual" <?=($s['reservation_payment_mode']??'none')==='slip_manual'?'selected':''?>>สแกนจ่ายและแนบสลิป · พนักงานตรวจ</option><option value="slip_api" <?=($s['reservation_payment_mode']??'none')==='slip_api'?'selected':''?>>สแกนจ่ายและแนบสลิป · ตรวจด้วย API</option></select><small class="booking-setting-help">เมื่อปิด “บังคับชำระมัดจำ” ระบบจะใช้โหมดไม่ต้องชำระโดยไม่ลบค่าที่ตั้งไว้</small></label>
<label>วิธียืนยันการจอง<select name="reservation_confirmation_mode" <?=$canManage?'':'disabled'?>><option value="staff" <?=($s['reservation_confirmation_mode']??'staff')==='staff'?'selected':''?>>ให้พนักงานตรวจและยืนยัน</option><option value="api_auto" <?=($s['reservation_confirmation_mode']??'staff')==='api_auto'?'selected':''?>>ยืนยันอัตโนมัติเมื่อ API ตรวจผ่าน</option></select><small class="booking-setting-help">ถ้า API ยังไม่พร้อม จะไม่ยืนยันอัตโนมัติและส่งเข้าคิวตรวจโดยพนักงาน</small></label>
<label>มัดจำ (บาท)<input type="number" name="reservation_deposit_amount" min="0" max="1000000" step="1" value="<?=h((string)($s['reservation_deposit_amount']??'0'))?>" <?=$canManage?'':'disabled'?>><small class="booking-setting-help">กำหนดเป็นจำนวนเต็มบาท ไม่ตั้งจำนวนให้เอง</small></label>
<label>วิธีคำนวณมัดจำ<select name="reservation_deposit_calculation" <?=$canManage?'':'disabled'?>><option value="per_booking" <?=($s['reservation_deposit_calculation']??'per_booking')==='per_booking'?'selected':''?>>ต่อรายการจอง</option><option value="per_person" <?=($s['reservation_deposit_calculation']??'per_booking')==='per_person'?'selected':''?>>ต่อคน</option></select></label>
<label class="wide">QR Code สำหรับชำระเงิน (URL)<input type="text" name="reservation_payment_qr_url" maxlength="500" value="<?=h((string)($s['reservation_payment_qr_url']??''))?>" placeholder="https://... หรือ /assets/payment-qr.png" <?=$canManage?'':'disabled'?>><small class="booking-setting-help">โหมดชำระเงินต้องมี QR ที่เปิดผ่าน HTTPS หรือ public path ในเว็บ (ห้ามใช้ /storage เพราะเป็นพื้นที่ปิด); ระบบยังไม่สร้าง PromptPay QR แบบยอดเงินเฉพาะรายการ</small></label>
<label class="wide">บัญชี / PromptPay ผู้รับ<input type="text" name="reservation_payment_receiver" maxlength="120" value="<?=h((string)($s['reservation_payment_receiver']??''))?>" placeholder="เลขบัญชีหรือหมายเลข PromptPay สำหรับตรวจปลายทาง" <?=$canManage?'':'disabled'?>><small class="booking-setting-help">ข้อมูลนี้ส่งให้ Provider adapter ใช้เทียบผู้รับเมื่อเชื่อม API แล้ว</small></label>
<label class="wide">รายละเอียดบัญชี / วิธีชำระ<textarea name="reservation_payment_instructions" maxlength="2000" placeholder="ชื่อบัญชี · ธนาคาร · เลขบัญชี · วิธีตรวจยอด" <?=$canManage?'':'disabled'?>><?=h((string)($s['reservation_payment_instructions']??''))?></textarea><small class="booking-setting-help">ลูกค้าจะเห็นข้อมูลนี้เมื่อเปิดรับมัดจำ</small></label>
<label class="wide">เงื่อนไขการจอง<textarea name="reservation_terms" maxlength="3000" placeholder="เช่น เวลาถือโต๊ะ / การคืนมัดจำ / การยกเลิก" <?=$canManage?'':'disabled'?>><?=h((string)($s['reservation_terms']??''))?></textarea><small class="booking-setting-help">แสดงให้ลูกค้าอ่านและยอมรับก่อนส่งจอง</small></label>
</div><?php if($canManage):?><button class="booking-settings-save" type="submit">บันทึกเงื่อนไขการจอง</button><?php else:?><p class="booking-settings-foot">ต้องมีสิทธิ์ `settings.manage` เพื่อแก้ไขการตั้งค่านี้</p><?php endif;?></section>
<aside><section class="booking-settings-panel"><h2>สถานะระบบ</h2><p>การตั้งค่าการยืนยันไม่สามารถข้ามการตรวจ API ที่ยังไม่พร้อมได้</p><div class="booking-settings-readiness"><div><span>รับจองออนไลน์</span><b class="<?=$payment['shop_reservations_enabled']?'':'is-pending'?>"><?=$payment['shop_reservations_enabled']?'เปิด':'ปิด'?></b></div><div><span>การบังคับมัดจำ</span><b class="<?=$payment['required']?'is-pending':''?>"><?=$payment['required']?'เปิด':'ปิด · จองได้โดยไม่จ่าย'?></b></div><div><span>รูปแบบที่ใช้งาน</span><b><?=h(mrbar_reservation_payment_mode_label($payment['mode']))?></b></div><div><span>ตัวตรวจสลิป API</span><b class="<?=!empty($integrations['slip_verifier']['ready'])?'':'is-pending'?>"><?=!empty($integrations['slip_verifier']['ready'])?'พร้อม':'ยังไม่เชื่อม Provider / API Key'?></b></div><div><span>ค่าชำระครบถ้วน</span><b class="<?=$payment['ready']?'':'is-pending'?>"><?=$payment['ready']?'พร้อม':'ยังขาดยอดหรือรายละเอียดชำระ'?></b></div></div><div class="booking-settings-flow"><strong>ลำดับทำงาน</strong><br>ลูกค้าล็อกอิน LINE → ส่งคำขอและสลิป → สถานะ “รอตรวจมัดจำ” → พนักงานตรวจ หรือ API ตรวจ → ยืนยันโต๊ะตามนโยบาย</div><p class="booking-settings-foot">โหมด API ยังเป็นโครงเชื่อมต่อ: ต้องติดตั้ง Provider adapter และตั้ง `MRBAR_SLIP_PROVIDER` กับ `MRBAR_SLIP_API_KEY` ใน Environment Variables ของ PHP-FPM ก่อนทดสอบตรวจจริง</p></section><section class="booking-settings-panel" style="margin-top:16px"><h2>ความปลอดภัยสลิป</h2><p>ไฟล์รับเฉพาะ JPG, PNG, WEBP ขนาดไม่เกิน 5 MB ตั้งชื่อสุ่ม และเก็บใต้ `storage/` ซึ่งปิดการเรียกดูโดยตรงไว้ สลิปเปิดดูได้จากหลังบ้านตามสิทธิ์สาขา</p></section></aside></div></form>
</main></body></html>
