<?php
require __DIR__.'/app/bootstrap.php';
require_once __DIR__.'/app/account-onboarding.php';
$u=require_any_permission(['employees.view','pr.manage']);
$d=db_load();
require_once __DIR__.'/app/admin-nav.php';

function pv_find_user(array $d,int $id): ?array {if($id<=0)return null;foreach($d['users']??[] as $x)if((int)($x['id']??0)===$id)return $x;return null;}
function pv_find_pr(array $d,int $id): ?array {if($id<=0)return null;foreach($d['prs']??[] as $p)if((int)($p['id']??0)===$id)return $p;return null;}
function pv_branch(array $d,$id): string {if(!$id)return 'AUTO / ใกล้ที่สุด';foreach($d['branches']??[] as $b)if((int)($b['id']??0)===(int)$id)return (string)($b['name']??$b['code']??'สาขา');return 'ไม่พบสาขา';}
function pv_position(array $e): string {return function_exists('workforce_position_label')?workforce_position_label((string)($e['position']??'staff')):(string)($e['position']??'Staff');}
function pv_account_mismatch(array $e,?array $user): bool {if(!$user)return false;$role=(string)($user['role']??'');$position=(string)($e['position']??'staff');if($position==='pr'||!empty($e['pr_id']))return $role!=='pr';if($position==='sales')return $role!=='sales';return in_array($role,['pr','sales'],true);}
function pv_expected_role(array $e): string {$p=(string)($e['position']??'staff');return ($p==='pr'||!empty($e['pr_id']))?'PR':($p==='sales'?'SALES':'STAFF / ADMIN');}
function pv_app_route(array $e): string {return (($e['position']??'')==='pr'||!empty($e['pr_id']))?'pr.php':'employee-time.php';}
function pv_app_label(array $e): string {return (($e['position']??'')==='pr'||!empty($e['pr_id']))?'PR TIME':'MR BAR TIME';}
function pv_avatar(array $d,array $e): string {return function_exists('workforce_employee_avatar_url')?workforce_employee_avatar_url($d,$e):'';}

$employees=array_values($d['employees']??[]);
usort($employees,function($a,$b){$aa=!empty($a['active'])?0:1;$bb=!empty($b['active'])?0:1;if($aa!==$bb)return $aa-$bb;return strcasecmp((string)($a['code']??''),(string)($b['code']??''));});
$employeeId=(int)($_GET['employee_id']??0);
if($employeeId<=0 && (int)($_GET['pr_id']??0)>0){$legacy=(int)$_GET['pr_id'];foreach($employees as $e)if((int)($e['pr_id']??0)===$legacy){$employeeId=(int)$e['id'];break;}}
$employee=null;foreach($employees as $e)if((int)($e['id']??0)===$employeeId){$employee=$e;break;}
if(!$employee&&$employees){$employee=$employees[0];$employeeId=(int)$employee['id'];}
$link=$employee?pv_find_user($d,(int)($employee['user_id']??0)):null;
$pr=$employee?pv_find_pr($d,(int)($employee['pr_id']??0)):null;
$isPr=$employee&&(($employee['position']??'')==='pr'||!empty($employee['pr_id']));
$isSales=$employee&&(($employee['position']??'')==='sales');
$avatar=$employee?pv_avatar($d,$employee):'';
$open=$employee&&function_exists('workforce_attendance_open')?workforce_attendance_open($d,(int)$employee['id']):null;
$jobs=0;$shiftCount=0;
if($employee){$eid=(int)$employee['id'];$pid=(int)($employee['pr_id']??0);if($pid>0)foreach($d['checkins']??[] as $c)if((int)($c['pr_id']??0)===$pid&&in_array((string)($c['status']??''),['assigned','accepted','in_service'],true))$jobs++;$today=date('Y-m-d');$limit=date('Y-m-d',strtotime('+14 days'));foreach($d['shifts']??[] as $s){if((int)($s['employee_id']??0)!==$eid&&(!empty($pid)&&(int)($s['employee_id']??0)<=0&&(int)($s['pr_id']??0)===$pid)===false)continue;$dt=(string)($s['date']??'');if($dt<$today||$dt>$limit)continue;if(in_array((string)($s['status']??'scheduled'),['cancelled','off'],true))continue;$shiftCount++;}}
$accountRole=$link?(string)($link['role']??''):'';$accountMismatch=$employee?pv_account_mismatch($employee,$link):false;
$route=$employee?pv_app_route($employee):'';$appLabel=$employee?pv_app_label($employee):'';
$params=$employee?['admin_staff_preview'=>'1','employee_id'=>$employeeId,'preview_token'=>csrf_token(),'v'=>time()]:[];
if($isPr&&$pr){$params['admin_pr_preview']='1';$params['pr_id']=(int)$pr['id'];}
$previewSrc=$route?$route.'?'.http_build_query($params):'';
$app=app_config();$version=(string)($app['version']??'');
?><!doctype html><html lang="th"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>MR BAR — MR BAR TIME Preview</title><link rel="stylesheet" href="assets/admin.css?v=12718"><link rel="stylesheet" href="assets/admin-v14.css?v=12718"><link rel="stylesheet" href="assets/pr-view-v1173.css?v=12718"><link rel="stylesheet" href="assets/pr-view-v12717.css?v=12718"></head><body class="admin-v14-page pr-view-page"><div class="ambient"><i></i><i></i><i></i></div><?=admin_sidebar('prview',$u)?><main class="pv-shell">
<header class="pv-topbar"><button class="menu-btn" id="menuBtn">☰</button><div><p class="eyebrow">ทีมงาน & บุคลากร / MR BAR TIME PREVIEW</p><h1>ทดสอบหน้าจอพนักงาน <span>· อ่านอย่างเดียว</span></h1><p>ดูหน้าจอจริงตามประเภทพนักงานจาก Employee Center โดยไม่สลับบัญชีและไม่บันทึกข้อมูลลง Production</p></div><a class="pv-back" href="employees.php">← Employee Center</a></header>
<section class="pv-process"><div><span>1</span><b>เลือกพนักงาน</b><small>PR / Sales / Staff / Manager</small></div><i>→</i><div><span>2</span><b>ระบบเลือก App</b><small>PR TIME หรือ MR BAR TIME</small></div><i>→</i><div><span>3</span><b>ทดสอบแบบ Read-only</b><small>ทุกคำสั่งเขียนข้อมูลถูก Block</small></div></section>
<?php if(!$employee):?><section class="pv-empty"><span>♙</span><h2>ยังไม่มีข้อมูลพนักงาน</h2><p>เพิ่มพนักงานที่ Employee Center ก่อน แล้วจึงกลับมาทดสอบ MR BAR TIME</p><a class="pv-empty-link" href="employees.php">เปิด Employee Center →</a></section><?php else:?>
<section class="pv-control-card"><div class="pv-selector"><label><span>พนักงานที่ต้องการ Preview</span><select id="employeeSelect"><?php foreach($employees as $e):?><option value="<?=(int)$e['id']?>" <?=(int)$e['id']===$employeeId?'selected':''?>><?=h((string)($e['code']??''))?> · <?=h((string)($e['name']??''))?> · <?=h(pv_position($e))?><?=empty($e['active'])?' · ปิดใช้งาน':''?></option><?php endforeach;?></select></label><div class="pv-profile"><?php if($avatar!==''):?><img src="<?=h($avatar)?>" alt=""><?php else:?><span>♙</span><?php endif;?><div><small><?=h((string)($employee['code']??''))?></small><b><?=h((string)($employee['name']??''))?></b><em class="<?=!empty($employee['active'])?'online':'offline'?>"><?=!empty($employee['active'])?'ใช้งาน':'ปิดใช้งาน'?></em></div></div></div>
<div class="pv-meta"><span><small>ตำแหน่งงาน</small><b><?=h(pv_position($employee))?></b></span><span><small>App ที่ใช้งาน</small><b><?=h($appLabel)?></b></span><span><small>บัญชี / สิทธิ์</small><b><?=$link?'@'.h((string)$link['username']).' · '.h(strtoupper($accountRole)):'ยังไม่มีบัญชี'?></b></span><span><small>สาขาประจำ</small><b><?=h(pv_branch($d,$employee['branch_id']??null))?></b></span><span><small>การลงเวลา</small><b><?=$open?'กำลังเข้าเวร':'ยังไม่เข้าเวร'?></b></span><span><small><?=$isPr?'งาน PR ที่กำลังทำ':'กะ 14 วันข้างหน้า'?></small><b><?=$isPr?$jobs:$shiftCount?></b></span></div>
<div class="pv-health"><span class="<?=!empty($employee['active'])?'ok':'warn'?>">Employee: <?=!empty($employee['active'])?'ใช้งาน':'ปิดใช้งาน'?></span><span class="<?=$link&&!empty($link['active'])?'ok':($link?'warn':'muted')?>">บัญชี: <?=$link?(!empty($link['active'])?'ใช้งาน':'ปิดใช้งาน'):'ยังไม่มี'?></span><span class="<?=$accountMismatch?'bad':'ok'?>">สิทธิ์บัญชี: <?=$accountMismatch?'ไม่ตรงตำแหน่ง':'ปกติ'?></span><span class="ok">Preview Route: <?=h($appLabel)?></span></div>
<?php if($accountMismatch):?><div class="pv-warning"><b>บัญชีและตำแหน่งไม่สอดคล้องกัน</b><span>ตำแหน่ง <?=h(pv_position($employee))?> ควรใช้สิทธิ์ <?=h(pv_expected_role($employee))?> แต่บัญชีปัจจุบันเป็น <?=h(strtoupper($accountRole))?> · แก้ที่ Employee Center / บัญชีผู้ใช้ก่อนใช้งานจริง</span></div><?php endif;?>
<?php if(!$link):?><div class="pv-warning"><b>ยังไม่มีบัญชี Login</b><span>Preview ใช้ Virtual Identity เพื่อให้ Admin ตรวจหน้าจอได้ แต่พนักงานจริงต้องมีบัญชีจึงจะเข้า MR BAR TIME ได้</span></div><?php endif;?></section>
<section class="pv-preview-card"><div class="pv-toolbar"><div class="pv-tabs"><button class="active" data-pv-device="mobile"><span>▯</span><b>Mobile</b><small>390 × 844</small></button><button data-pv-device="tablet"><span>▯</span><b>Tablet</b><small>768 × 1024</small></button><button data-pv-device="desktop"><span>▱</span><b>Desktop</b><small>1280 × 900</small></button></div><div class="pv-actions"><button type="button" data-pv-refresh>↻ โหลดใหม่</button><a href="<?=h($previewSrc)?>" target="_blank" rel="noopener">เปิด Preview เต็มจอ ↗</a></div></div><div class="pv-notice"><i></i><div><b>MR BAR TIME PREVIEW · READ ONLY</b><span>GPS / Camera / ปฏิทิน / รายได้ / เมนูเฉพาะตำแหน่งสามารถทดลองได้ โดยคำสั่งที่เขียนข้อมูลจริงถูก Block</span></div><strong><?=h((string)$employee['code'])?> · <?=h((string)$employee['name'])?> · <?=h($appLabel)?></strong></div><div class="pv-stage" data-pv-stage data-device="mobile"><div class="pv-device"><div class="pv-device-top"><span></span><b>MR BAR · <?=h($appLabel)?> PREVIEW</b><em>READ ONLY</em></div><iframe id="prPreviewFrame" title="MR BAR TIME Preview" allow="camera; geolocation; fullscreen" src="<?=h($previewSrc)?>"></iframe></div></div><div class="pv-foot"><div><b>Preview ใช้ Employee Center เป็นข้อมูลหลัก</b><p>ชื่อ · ตำแหน่ง · บัญชี · สาขา · Attendance · กะ และ Profile เฉพาะตำแหน่ง อ้างอิงข้อมูล Production จริง แต่ไม่อนุญาตให้เขียนข้อมูล</p></div><div class="pv-foot-actions"><a href="employees.php?employee_id=<?=(int)$employee['id']?>">แก้ข้อมูลพนักงาน →</a><a href="workforce-schedule.php?employee_id=<?=(int)$employee['id']?>">เปิดกะ & ปฏิทิน →</a></div></div></section>
<?php endif;?><footer>MR BAR · MR BAR TIME Staff Preview<?= $version!==''?' · v'.h($version):''?> · Schema v<?=h((string)($d['meta']['schema']??24))?></footer></main><script src="assets/admin.js?v=12718"></script><script src="assets/staff-view-v12718.js?v=12718"></script></body></html>
