<?php
declare(strict_types=1);
require __DIR__.'/app/bootstrap.php';require_once __DIR__.'/app/compat.php';
$u=current_user();if(!$u){header('Location:login.php');exit;}$d=db_load();
$canView=(($u['role']??'')==='admin')||user_can($u,'workforce.exceptions.view',$d)||user_can($u,'attendance.view',$d)||user_can($u,'substitute.manage',$d);
$canManage=(($u['role']??'')==='admin')||user_can($u,'workforce.exceptions.manage',$d)||user_can($u,'attendance.manage',$d)||user_can($u,'substitute.manage',$d);
if(!$canView){http_response_code(403);exit('Permission denied');}
function wx_emp(array $d,int $id): array {$e=workforce_employee_by_id($d,$id);return $e?:['id'=>$id,'code'=>'EMP'.$id,'name'=>'Unknown','position'=>'other'];}
function wx_pr(array $d,int $id): ?array {foreach($d['prs']??[] as $p)if((int)($p['id']??0)===$id)return $p;return null;}
function wx_reason(string $r): string {return ['forgot'=>'ลืมกดออก','unable'=>'ไม่สามารถลงเวลาเอง','sick'=>'เจ็บป่วย/เมา/ไม่พร้อม','device'=>'อุปกรณ์/อินเทอร์เน็ตมีปัญหา','manager'=>'Manager ลงแทน','other'=>'อื่น ๆ','shift_end'=>'ใช้เวลาจบกะ'][$r]??$r;}
function wx_state(array $a): string {return ['open'=>'กำลังทำงาน','missing_checkout'=>'ขาด Check-out','provisional'=>'เวลาชั่วคราว','complete'=>'สมบูรณ์'][workforce_attendance_state($a)]??workforce_attendance_state($a);}
function wx_local_dt(string $v): string {$t=strtotime($v);return $t?date('Y-m-d\TH:i',$t):'';}
$msg='';$err='';
if($_SERVER['REQUEST_METHOD']==='POST'){
    if(!$canManage){http_response_code(403);exit('Permission denied');}
    csrf_check();$action=(string)($_POST['action']??'');
    try{
        if($action==='save_policy'){
            $grace=max(0,min(720,(int)($_POST['grace_minutes']??120)));$auto=!empty($_POST['auto_offline'])?'1':'0';$prov=!empty($_POST['provisional_enabled'])?'1':'0';$corr=!empty($_POST['correction_enabled'])?'1':'0';$sub=!empty($_POST['substitute_enabled'])?'1':'0';$ext=!empty($_POST['external_allowed'])?'1':'0';
            db_mutate(function($x)use($u,$grace,$auto,$prov,$corr,$sub,$ext){$x['settings']['attendance_missing_checkout_grace_minutes']=(string)$grace;$x['settings']['attendance_auto_offline_missing']=$auto;$x['settings']['attendance_provisional_close_enabled']=$prov;$x['settings']['attendance_correction_request_enabled']=$corr;$x['settings']['substitute_request_enabled']=$sub;$x['settings']['substitute_external_allowed']=$ext;audit_permission($x,$u,'workforce_exception_policy_updated',['grace_minutes'=>$grace]);return $x;});$msg='บันทึกนโยบาย Exception แล้ว';
        }elseif(in_array($action,['manual_checkout','provisional_checkout','finalize_provisional'],true)){
            $aid=(int)($_POST['attendance_id']??0);$reason=(string)($_POST['reason']??'manager');$note=trim((string)($_POST['note']??''));$checkoutRaw=(string)($_POST['checkout_at']??'');
            db_mutate(function($x)use($u,$aid,$action,$reason,$note,$checkoutRaw){
                foreach($x['attendance'] as &$a){if((int)($a['id']??0)!==$aid)continue;
                    if($action==='manual_checkout'){
                        if($checkoutRaw==='')throw new RuntimeException('กรุณาระบุเวลาออกจริง');$ts=strtotime($checkoutRaw);$in=strtotime((string)($a['check_in']??''));if(!$ts||!$in||$ts<=$in)throw new RuntimeException('เวลาออกต้องหลังเวลาเข้า');if($ts>time()+300)throw new RuntimeException('เวลาออกไม่ควรอยู่ในอนาคต');
                        $a['check_out']=date('c',$ts);$a['attendance_state']='complete';$a['payroll_status']='final';$a['provisional_checkout']=0;$a['checkout_source']='supervisor';$a['checkout_reason']=$reason;$a['checkout_note']=$note;$a['checkout_corrected_by']=(int)$u['id'];$a['checkout_corrected_at']=date('c');
                    }elseif($action==='provisional_checkout'){
                        if(($x['settings']['attendance_provisional_close_enabled']??'1')!=='1')throw new RuntimeException('ระบบปิดเวลาแบบชั่วคราวถูกปิดใช้งาน');$planned=workforce_planned_checkout($x,$a);if(!$planned)throw new RuntimeException('ไม่สามารถหาเวลาจบกะได้');
                        $a['check_out']=$planned->format('c');$a['attendance_state']='provisional';$a['payroll_status']='pending_review';$a['provisional_checkout']=1;$a['checkout_source']='auto_provisional';$a['checkout_reason']='shift_end';$a['checkout_note']=$note;$a['checkout_corrected_by']=(int)$u['id'];$a['checkout_corrected_at']=date('c');
                    }else{
                        if(workforce_attendance_state($a)!=='provisional')throw new RuntimeException('รายการนี้ไม่ใช่เวลา Provisional');$a['attendance_state']='complete';$a['payroll_status']='final';$a['provisional_checkout']=0;$a['checkout_source']='supervisor_confirmed';$a['checkout_corrected_by']=(int)$u['id'];$a['checkout_corrected_at']=date('c');
                    }
                    $pid=(int)($a['pr_id']??0);if($pid){foreach($x['prs'] as &$p)if((int)($p['id']??0)===$pid){$p['status']='offline';$p['current_checkin_id']=null;break;}unset($p);}
                    audit_permission($x,$u,'attendance_exception_resolved',['attendance_id'=>$aid,'action_type'=>$action,'employee_id'=>(int)($a['employee_id']??0),'pr_id'=>$pid]);return $x;
                }unset($a);throw new RuntimeException('ไม่พบ Attendance');
            });$msg='อัปเดต Attendance เรียบร้อยแล้ว';
        }elseif($action==='review_correction'){
            $rid=(int)($_POST['request_id']??0);$decision=(string)($_POST['decision']??'rejected');$note=trim((string)($_POST['admin_note']??''));if(!in_array($decision,['approved','rejected'],true))throw new RuntimeException('สถานะไม่ถูกต้อง');
            db_mutate(function($x)use($u,$rid,$decision,$note){foreach($x['time_correction_requests'] as &$r){if((int)($r['id']??0)!==$rid)continue;if(($r['status']??'')!=='pending')throw new RuntimeException('คำขอนี้ถูกดำเนินการแล้ว');$r['status']=$decision;$r['reviewed_by']=(int)$u['id'];$r['reviewed_at']=date('c');$r['updated_at']=date('c');$r['admin_note']=$note;if($decision==='approved'){foreach($x['attendance'] as &$a)if((int)($a['id']??0)===(int)$r['attendance_id']){$ts=strtotime((string)$r['requested_checkout']);$in=strtotime((string)($a['check_in']??''));if(!$ts||!$in||$ts<=$in)throw new RuntimeException('เวลาแก้ไขไม่ถูกต้อง');$a['check_out']=date('c',$ts);$a['attendance_state']='complete';$a['payroll_status']='final';$a['provisional_checkout']=0;$a['checkout_source']='employee_correction';$a['checkout_reason']='correction';$a['checkout_note']=$note;$a['checkout_corrected_by']=(int)$u['id'];$a['checkout_corrected_at']=date('c');$pid=(int)($a['pr_id']??0);if($pid){foreach($x['prs'] as &$p)if((int)$p['id']===$pid){$p['status']='offline';$p['current_checkin_id']=null;break;}unset($p);}break;}unset($a);}audit_permission($x,$u,'time_correction_reviewed',['request_id'=>$rid,'decision'=>$decision,'attendance_id'=>(int)$r['attendance_id']]);return $x;}unset($r);throw new RuntimeException('ไม่พบคำขอแก้เวลา');});$msg='ดำเนินการคำขอแก้เวลาแล้ว';
        }elseif($action==='review_substitute'){
            $rid=(int)($_POST['request_id']??0);$decision=(string)($_POST['decision']??'rejected');$note=trim((string)($_POST['admin_note']??''));if(!in_array($decision,['approved','rejected'],true))throw new RuntimeException('สถานะไม่ถูกต้อง');
            db_mutate(function($x)use($u,$rid,$decision,$note){foreach($x['substitute_requests'] as &$r){if((int)($r['id']??0)!==$rid)continue;if(($r['status']??'')!=='pending')throw new RuntimeException('คำขอนี้ถูกดำเนินการแล้ว');if($decision==='approved')workforce_apply_substitute_approval($x,$r,(int)$u['id']);$r['status']=$decision;$r['reviewed_by']=(int)$u['id'];$r['reviewed_at']=date('c');$r['updated_at']=date('c');$r['admin_note']=$note;audit_permission($x,$u,'substitute_request_reviewed',['request_id'=>$rid,'decision'=>$decision,'created_shift_id'=>(int)($r['created_shift_id']??0)]);return $x;}unset($r);throw new RuntimeException('ไม่พบคำขอคนมาแทน');});$msg='ดำเนินการคำขอคนมาแทนแล้ว';
        }elseif(in_array($action,['external_checkin','external_checkout'],true)){
            $rid=(int)($_POST['request_id']??0);db_mutate(function($x)use($u,$rid,$action){foreach($x['substitute_requests'] as &$r){if((int)($r['id']??0)!==$rid)continue;if(($r['status']??'')!=='approved'||($r['substitute_type']??'')!=='external')throw new RuntimeException('รายการนี้ไม่ใช่ PR คนนอกที่อนุมัติแล้ว');if($action==='external_checkin'){if(!empty($r['external_check_in']))throw new RuntimeException('ลงเวลาเข้าแล้ว');$r['external_check_in']=date('c');}else{if(empty($r['external_check_in']))throw new RuntimeException('ต้องลงเวลาเข้าก่อน');if(!empty($r['external_check_out']))throw new RuntimeException('ลงเวลาออกแล้ว');$r['external_check_out']=date('c');}$r['updated_at']=date('c');audit_permission($x,$u,'external_substitute_attendance',['request_id'=>$rid,'mode'=>$action]);return $x;}unset($r);throw new RuntimeException('ไม่พบรายการ');});$msg='บันทึกเวลาของ PR คนนอกแล้ว';
        }
    }catch(Throwable $e){$err=$e->getMessage();}
    $d=db_load();
}
$missing=[];foreach($d['attendance']??[] as $a){$st=workforce_attendance_state($a);if(in_array($st,['missing_checkout','provisional'],true))$missing[]=$a;}usort($missing,function($a,$b){return strcmp((string)($b['check_in']??''),(string)($a['check_in']??''));});
$corrections=array_values(array_filter($d['time_correction_requests']??[],function($r){return ($r['status']??'')==='pending';}));usort($corrections,function($a,$b){return strcmp((string)($b['requested_at']??''),(string)($a['requested_at']??''));});
$subs=$d['substitute_requests']??[];usort($subs,function($a,$b){return strcmp((string)($b['requested_at']??''),(string)($a['requested_at']??''));});
$pendingSubs=count(array_filter($subs,function($r){return ($r['status']??'')==='pending';}));
?><!doctype html><html lang="th"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>MR BAR — Workforce Exceptions</title><link rel="stylesheet" href="assets/admin.css?v=1200"><link rel="stylesheet" href="assets/admin-v14.css?v=1200"><link rel="stylesheet" href="assets/workforce-exceptions-v120.css?v=1200"></head><body class="admin-v14-page"><?php require_once __DIR__.'/app/admin-nav.php';echo admin_sidebar('exceptions',$u);?><main class="wx-shell"><header class="wx-head"><div><p>WORKFORCE / EXCEPTION CONTROL</p><h1>Attendance Exceptions & PR Substitute</h1><span>จัดการ Missing Check-out, คำขอแก้เวลา และ PR ที่มาแทนจากจุดเดียว</span></div><a href="workforce-schedule.php">← Workforce Schedule</a></header><?php if($msg):?><div class="notice ok">✓ <?=h($msg)?></div><?php endif;?><?php if($err):?><div class="notice err">⚠ <?=h($err)?></div><?php endif;?>
<section class="wx-kpis"><article><small>ขาด Check-out / ชั่วคราว</small><b><?=count($missing)?></b><span>Payroll ยังไม่ Final</span></article><article><small>คำขอแก้เวลา</small><b><?=count($corrections)?></b><span>รอ Manager ตรวจ</span></article><article><small>คำขอ PR มาแทน</small><b><?=$pendingSubs?></b><span>รออนุมัติ</span></article><article class="gold"><small>Grace Period</small><b><?=h((string)($d['settings']['attendance_missing_checkout_grace_minutes']??120))?></b><span>นาทีหลังจบกะ</span></article></section>
<section class="wx-panel policy"><div class="wx-title"><div><small>POLICY</small><h2>นโยบายเหตุผิดปกติ</h2></div></div><form method="post" class="policy-grid"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><input type="hidden" name="action" value="save_policy"><label>Grace Period (นาที)<input type="number" min="0" max="720" name="grace_minutes" value="<?=h((string)($d['settings']['attendance_missing_checkout_grace_minutes']??120))?>"></label><label class="switch"><input type="checkbox" name="auto_offline" value="1" <?=($d['settings']['attendance_auto_offline_missing']??'1')==='1'?'checked':''?>><span>PR Offline อัตโนมัติเมื่อ Missing</span></label><label class="switch"><input type="checkbox" name="provisional_enabled" value="1" <?=($d['settings']['attendance_provisional_close_enabled']??'1')==='1'?'checked':''?>><span>อนุญาตใช้เวลาจบกะแบบ Provisional</span></label><label class="switch"><input type="checkbox" name="correction_enabled" value="1" <?=($d['settings']['attendance_correction_request_enabled']??'1')==='1'?'checked':''?>><span>ให้พนักงานส่งคำขอแก้เวลา</span></label><label class="switch"><input type="checkbox" name="substitute_enabled" value="1" <?=($d['settings']['substitute_request_enabled']??'1')==='1'?'checked':''?>><span>เปิดระบบขอ PR มาแทน</span></label><label class="switch"><input type="checkbox" name="external_allowed" value="1" <?=($d['settings']['substitute_external_allowed']??'1')==='1'?'checked':''?>><span>อนุญาต PR คนนอก</span></label><button>บันทึก Policy</button></form></section>
<section class="wx-panel"><div class="wx-title"><div><small>MISSING CHECK-OUT</small><h2>Attendance ต้องตรวจสอบ</h2></div><span><?=count($missing)?> รายการ</span></div><?php if(!$missing):?><div class="wx-empty">ไม่มี Missing Check-out 🎉</div><?php endif;?><?php foreach($missing as $a):$e=wx_emp($d,(int)($a['employee_id']??0));$planned=workforce_planned_checkout($d,$a);?><article class="exception-card state-<?=h(workforce_attendance_state($a))?>"><div class="person"><span><?=h(workforce_initial((string)$e['name']))?></span><div><small><?=h((string)$e['code'].' · '.workforce_position_label((string)$e['position']))?></small><h3><?=h((string)$e['name'])?></h3><em><?=h(wx_state($a))?></em></div></div><div class="facts"><div><small>CHECK-IN</small><b><?=h(date('d/m/Y H:i',strtotime((string)$a['check_in'])))?></b></div><div><small>คาดว่าจบกะ</small><b><?=$planned?h($planned->format('d/m/Y H:i')):'—'?></b></div><div><small>CHECK-OUT</small><b><?=empty($a['check_out'])?'—':h(date('d/m/Y H:i',strtotime((string)$a['check_out'])))?></b></div><div><small>PAYROLL</small><b><?=h((string)($a['payroll_status']??'pending_review'))?></b></div></div><?php if($canManage):?><div class="exception-actions"><form method="post" class="manual-form"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><input type="hidden" name="action" value="manual_checkout"><input type="hidden" name="attendance_id" value="<?=(int)$a['id']?>"><label>เวลาออกจริง<input type="datetime-local" name="checkout_at" value="<?=h(wx_local_dt((string)($a['check_out']?:($a['planned_checkout_at']??''))))?>" required></label><label>เหตุผล<select name="reason"><option value="forgot">ลืมกดออก</option><option value="unable">ไม่สามารถลงเวลาเอง</option><option value="sick">เจ็บป่วย / เมา / ไม่พร้อม</option><option value="device">อุปกรณ์มีปัญหา</option><option value="manager">Manager ลงแทน</option><option value="other">อื่น ๆ</option></select></label><label>หมายเหตุ<input name="note" placeholder="รายละเอียดเพิ่มเติม"></label><button class="primary">บันทึก Check-out แทน</button></form><div class="quick-actions"><?php if(workforce_attendance_state($a)==='missing_checkout'&&($d['settings']['attendance_provisional_close_enabled']??'1')==='1'):?><form method="post"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><input type="hidden" name="action" value="provisional_checkout"><input type="hidden" name="attendance_id" value="<?=(int)$a['id']?>"><button class="ghost">ใช้เวลาจบกะ · รอตรวจ</button></form><?php elseif(workforce_attendance_state($a)==='provisional'):?><form method="post"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><input type="hidden" name="action" value="finalize_provisional"><input type="hidden" name="attendance_id" value="<?=(int)$a['id']?>"><button class="gold">✓ ยืนยันเวลา Provisional</button></form><?php endif;?></div></div><?php endif;?></article><?php endforeach;?></section>
<section class="wx-panel"><div class="wx-title"><div><small>TIME CORRECTION</small><h2>คำขอแก้เวลาออกจากพนักงาน</h2></div><span><?=count($corrections)?> รอ</span></div><?php if(!$corrections):?><div class="wx-empty">ไม่มีคำขอแก้เวลาที่รออนุมัติ</div><?php endif;?><?php foreach($corrections as $r):$e=wx_emp($d,(int)$r['employee_id']);?><article class="request-card"><div><small><?=h((string)$e['code'])?></small><h3><?=h((string)$e['name'])?></h3><p><?=h((string)$r['reason'])?></p></div><div><small>เวลาที่ขอแก้</small><b><?=h(date('d/m/Y H:i',strtotime((string)$r['requested_checkout'])))?></b></div><?php if($canManage):?><form method="post"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><input type="hidden" name="action" value="review_correction"><input type="hidden" name="request_id" value="<?=(int)$r['id']?>"><input name="admin_note" placeholder="หมายเหตุ Admin"><button name="decision" value="approved" class="approve">อนุมัติ</button><button name="decision" value="rejected" class="reject">ไม่อนุมัติ</button></form><?php endif;?></article><?php endforeach;?></section>
<section class="wx-panel"><div class="wx-title"><div><small>PR SUBSTITUTE</small><h2>คำขอ PR มาแทน</h2></div><span><?=$pendingSubs?> รออนุมัติ</span></div><?php if(!$subs):?><div class="wx-empty">ยังไม่มีคำขอ PR มาแทน</div><?php endif;?><?php foreach(array_slice($subs,0,80) as $r):$orig=wx_emp($d,(int)$r['original_employee_id']);?><article class="sub-card status-<?=h((string)$r['status'])?>"><div class="sub-main"><small><?=h((string)$orig['code'])?> · <?=h(date('d/m/Y',strtotime((string)$r['date'])))?></small><h3><?=h((string)$orig['name'])?> → <?=h(workforce_substitute_label($d,$r))?></h3><p><?=h((string)$r['reason'])?></p><div class="chips"><span><?=($r['substitute_type']??'')==='external'?'คนนอก':'PR ในระบบ'?></span><span><?=h(strtoupper((string)$r['status']))?></span><?php if(!empty($r['external_phone'])):?><span><?=h((string)$r['external_phone'])?></span><?php endif;?></div></div><?php if(($r['status']??'')==='pending'&&$canManage):?><form method="post" class="review-form"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><input type="hidden" name="action" value="review_substitute"><input type="hidden" name="request_id" value="<?=(int)$r['id']?>"><input name="admin_note" placeholder="หมายเหตุ Admin"><button name="decision" value="approved" class="approve">✓ อนุมัติ</button><button name="decision" value="rejected" class="reject">× ไม่อนุมัติ</button></form><?php elseif(($r['status']??'')==='approved'&&($r['substitute_type']??'')==='external'&&$canManage):?><div class="external-clock"><small>เวลาคนนอก</small><b>IN <?=empty($r['external_check_in'])?'—':h(date('H:i',strtotime((string)$r['external_check_in'])))?> · OUT <?=empty($r['external_check_out'])?'—':h(date('H:i',strtotime((string)$r['external_check_out'])))?></b><div><?php if(empty($r['external_check_in'])):?><form method="post"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><input type="hidden" name="action" value="external_checkin"><input type="hidden" name="request_id" value="<?=(int)$r['id']?>"><button class="approve">ลงเวลาเข้าแทน</button></form><?php elseif(empty($r['external_check_out'])):?><form method="post"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><input type="hidden" name="action" value="external_checkout"><input type="hidden" name="request_id" value="<?=(int)$r['id']?>"><button class="gold">ลงเวลาออกแทน</button></form><?php endif;?></div></div><?php else:?><div class="final-state"><?=h(strtoupper((string)$r['status']))?></div><?php endif;?></article><?php endforeach;?></section><footer>MR BAR Workforce Exceptions · v1.20.0 · Schema v<?=h((string)($d['meta']['schema']??19))?></footer></main></body></html>