<?php
require __DIR__.'/app/bootstrap.php';
require_once __DIR__.'/app/customer-media.php';
require_once __DIR__.'/app/floor-plan.php';
$u=require_permission('tables.view');$d=db_load();$canManage=user_can($u,'tables.manage',$d);$msg=isset($_GET['deleted'])?'ลบ Layout เรียบร้อยแล้ว':'';$err='';
function zs_map_index(array $d,int $id): ?int {foreach($d['floor_plans']??[] as $i=>$m)if((int)($m['id']??0)===$id)return $i;return null;}
function zs_active_branches(array $d): array {return array_values(array_filter($d['branches']??[],fn($b)=>!empty($b['active'])&&empty($b['deleted_at'])));}
if($_SERVER['REQUEST_METHOD']==='POST'){
 csrf_check();$action=(string)($_POST['action']??'');$postedMapId=(int)($_POST['map_id']??0);
 try{
  if(!$canManage)throw new RuntimeException('ไม่มี Permission: tables.manage');
  if($action==='create'||$action==='seed_mockup'){
   $name=trim((string)($_POST['name']??($action==='seed_mockup'?'Mockup ร้าน 3 ไร่':'Floor Plan ใหม่')));if($name==='')$name='Floor Plan ใหม่';$branchId=(int)($_POST['branch_id']??0);$newId=0;
   db_mutate(function($x)use($name,$branchId,$u,$action,&$newId){$x['floor_plans']=$x['floor_plans']??[];$x['floor_plan_items']=$x['floor_plan_items']??[];$newId=fp_next_id($x['floor_plans']);$map=fp_map_defaults(['id'=>$newId,'branch_id'=>$branchId?:null,'name'=>$name,'canvas_width'=>1200,'canvas_height'=>900,'created_by'=>(int)$u['id'],'updated_by'=>(int)$u['id']]);$x['floor_plans'][]=$map;if($action==='seed_mockup'){$items=fp_mockup_items($newId,$x['tables']??[]);$next=fp_next_id($x['floor_plan_items']);foreach($items as $item){$item['id']=$next++;$x['floor_plan_items'][]=$item;}}$x['audit'][]=['at'=>date('c'),'action'=>$action==='seed_mockup'?'floor_plan_mockup_created':'floor_plan_created','map_id'=>$newId,'by'=>(int)$u['id']];return $x;});
   header('Location:zone-studio.php?map_id='.$newId.'&created=1');exit;
  }
  if($postedMapId<=0||!fp_map($d,$postedMapId))throw new RuntimeException('ไม่พบ Floor Plan ที่ต้องการจัดการ');
  if($action==='delete_layout'){
   $nextMapId=0;db_mutate(function($x)use($postedMapId,$u,&$nextMapId){$target=fp_map($x,$postedMapId);if(!$target)throw new RuntimeException('ไม่พบ Layout ที่ต้องการลบ');$itemCount=0;foreach($x['floor_plan_items']??[] as $row)if((int)($row['map_id']??0)===$postedMapId)$itemCount++;$versionCount=0;foreach($x['floor_plan_versions']??[] as $row)if((int)($row['map_id']??0)===$postedMapId)$versionCount++;$x['floor_plans']=array_values(array_filter($x['floor_plans']??[],fn($row)=>(int)($row['id']??0)!==$postedMapId));$x['floor_plan_items']=array_values(array_filter($x['floor_plan_items']??[],fn($row)=>(int)($row['map_id']??0)!==$postedMapId));$x['floor_plan_versions']=array_values(array_filter($x['floor_plan_versions']??[],fn($row)=>(int)($row['map_id']??0)!==$postedMapId));foreach($x['floor_plans'] as $row){$nextMapId=(int)($row['id']??0);if($nextMapId>0)break;}$x['audit'][]=['at'=>date('c'),'action'=>'floor_plan_deleted','map_id'=>$postedMapId,'name'=>(string)($target['name']??''),'status'=>(string)($target['status']??'draft'),'items_deleted'=>$itemCount,'versions_deleted'=>$versionCount,'background_media_preserved'=>(int)($target['background_media_id']??0),'by'=>(int)$u['id']];return $x;});$url='zone-studio.php?deleted=1';if($nextMapId>0)$url.='&map_id='.$nextMapId;header('Location:'.$url);exit;
  }elseif($action==='save'){
   $name=trim((string)($_POST['name']??''));if($name==='')throw new RuntimeException('กรุณาตั้งชื่อ Layout');$branchId=(int)($_POST['branch_id']??0);$cw=max(600,min(4000,(int)($_POST['canvas_width']??1200)));$ch=max(500,min(4000,(int)($_POST['canvas_height']??900)));$grid=max(5,min(100,(int)($_POST['grid_size']??20)));$view=in_array((string)($_POST['view_mode']??'2d'),['2d','2.5d'],true)?(string)$_POST['view_mode']:'2d';$layoutMode=in_array((string)($_POST['layout_mode']??'objects'),['objects','image_hotspot'],true)?(string)$_POST['layout_mode']:'objects';$snap=isset($_POST['snap_enabled'])?1:0;$customer=isset($_POST['customer_enabled'])?1:0;$bgOpacity=max(0,min(100,(int)($_POST['background_opacity']??35)));$bgLocked=isset($_POST['background_locked'])?1:0;$itemsJson=(string)($_POST['items_json']??'[]');
   db_mutate(function($x)use($postedMapId,$name,$branchId,$cw,$ch,$grid,$view,$layoutMode,$snap,$customer,$bgOpacity,$bgLocked,$itemsJson,$u){$idx=zs_map_index($x,$postedMapId);if($idx===null)throw new RuntimeException('Floor Plan ถูกลบหรือเปลี่ยนแปลงแล้ว');$map=fp_map_defaults($x['floor_plans'][$idx]);$map['name']=$name;$map['branch_id']=$branchId?:null;$map['canvas_width']=$cw;$map['canvas_height']=$ch;$map['grid_size']=$grid;$map['view_mode']=$view;$map['layout_mode']=$layoutMode;$map['snap_enabled']=$snap;$map['customer_enabled']=$customer;$map['background_opacity']=$bgOpacity;$map['background_locked']=$bgLocked;$map['updated_at']=date('c');$map['updated_by']=(int)$u['id'];$items=fp_sanitize_items_json($itemsJson,$postedMapId,$map,$x);$x['floor_plans'][$idx]=$map;$x['floor_plan_items']=array_values(array_filter($x['floor_plan_items']??[],fn($i)=>(int)($i['map_id']??0)!==$postedMapId));foreach($items as $i)$x['floor_plan_items'][]=$i;$x['audit'][]=['at'=>date('c'),'action'=>'floor_plan_saved','map_id'=>$postedMapId,'items'=>count($items),'by'=>(int)$u['id']];return $x;});$msg='บันทึก Draft และตำแหน่งวัตถุแล้ว';
  }elseif($action==='publish'){
   db_mutate(function($x)use($postedMapId,$u){$idx=zs_map_index($x,$postedMapId);if($idx===null)throw new RuntimeException('ไม่พบ Floor Plan');$map=fp_map_defaults($x['floor_plans'][$idx]);$items=fp_items($x,$postedMapId);if(!$items)throw new RuntimeException('ยังไม่มีวัตถุใน Layout กรุณาจัดวางก่อน Publish');if($map['layout_mode']==='image_hotspot'){if(empty($map['background_media_id']))throw new RuntimeException('โหมด Hotspot ต้องอัปโหลดรูป Layout ก่อน Publish');$linked=0;foreach($items as $item)if(($item['type']??'')==='table'&&!empty($item['table_id'])&&!empty($item['customer_visible'])&&!empty($item['reservable']))$linked++;if($linked===0)throw new RuntimeException('กรุณาวาง Hotspot และเชื่อม Table Directory อย่างน้อย 1 โต๊ะก่อน Publish');}$branch=$map['branch_id'];foreach($x['floor_plans'] as &$other)if((int)($other['id']??0)!==$postedMapId&&($other['status']??'draft')==='published'&&($other['branch_id']??null)===$branch)$other['status']='draft';unset($other);$map['status']='published';$map['published_at']=date('c');$map['published_by']=(int)$u['id'];$map['updated_at']=date('c');$versions=$x['floor_plan_versions']??[];$verNo=1;foreach($versions as $v)if((int)($v['map_id']??0)===$postedMapId)$verNo=max($verNo,(int)($v['version_no']??0)+1);$versionId=fp_next_id($versions);$map['published_version_id']=$versionId;$versions[]=['id'=>$versionId,'map_id'=>$postedMapId,'version_no'=>$verNo,'map'=>$map,'items'=>$items,'created_at'=>date('c'),'created_by'=>(int)$u['id']];$x['floor_plan_versions']=$versions;$x['floor_plans'][$idx]=$map;$x['audit'][]=['at'=>date('c'),'action'=>'floor_plan_published','map_id'=>$postedMapId,'version'=>$verNo,'by'=>(int)$u['id']];return $x;});$msg='Publish แผนผังให้ Customer Web แล้ว';
  }elseif($action==='rollback'){
   $versionId=(int)($_POST['version_id']??0);db_mutate(function($x)use($postedMapId,$versionId,$u){$target=null;foreach($x['floor_plan_versions']??[] as $v)if((int)($v['id']??0)===$versionId&&(int)($v['map_id']??0)===$postedMapId){$target=$v;break;}if(!$target)throw new RuntimeException('ไม่พบ Version ที่เลือก');$idx=zs_map_index($x,$postedMapId);if($idx===null)throw new RuntimeException('ไม่พบ Floor Plan');$current=fp_map_defaults($x['floor_plans'][$idx]);$map=fp_map_defaults((array)($target['map']??[]));$map['id']=$postedMapId;$map['status']=$current['status'];$map['published_at']=$current['published_at'];$map['published_by']=$current['published_by'];$map['published_version_id']=$current['published_version_id'];$map['updated_at']=date('c');$map['updated_by']=(int)$u['id'];$x['floor_plans'][$idx]=$map;$x['floor_plan_items']=array_values(array_filter($x['floor_plan_items']??[],fn($i)=>(int)($i['map_id']??0)!==$postedMapId));$next=fp_next_id($x['floor_plan_items']);foreach((array)($target['items']??[]) as $i){$i=fp_item_defaults((array)$i);$i['id']=$next++;$i['map_id']=$postedMapId;$x['floor_plan_items'][]=$i;}$x['audit'][]=['at'=>date('c'),'action'=>'floor_plan_rollback','map_id'=>$postedMapId,'version_id'=>$versionId,'by'=>(int)$u['id']];return $x;});$msg='ย้อน Working Layout ไปยัง Version ที่เลือกแล้ว · Customer ยังเห็น Published Version เดิมจนกว่าจะ Publish ใหม่';
  }elseif($action==='clone'){
   $newId=0;db_mutate(function($x)use($postedMapId,$u,&$newId){$src=fp_map($x,$postedMapId);if(!$src)throw new RuntimeException('ไม่พบ Floor Plan');$newId=fp_next_id($x['floor_plans']??[]);$copy=$src;$copy['id']=$newId;$copy['name']=$src['name'].' — Copy';$copy['status']='draft';$copy['published_at']=null;$copy['published_by']=null;$copy['published_version_id']=0;$copy['created_at']=date('c');$copy['updated_at']=date('c');$copy['created_by']=(int)$u['id'];$copy['updated_by']=(int)$u['id'];$x['floor_plans'][]=$copy;$next=fp_next_id($x['floor_plan_items']??[]);foreach(fp_items($x,$postedMapId) as $i){$i['id']=$next++;$i['map_id']=$newId;$i['created_at']=date('c');$i['updated_at']=date('c');$x['floor_plan_items'][]=$i;}$x['audit'][]=['at'=>date('c'),'action'=>'floor_plan_cloned','from_map_id'=>$postedMapId,'map_id'=>$newId,'by'=>(int)$u['id']];return $x;});header('Location:zone-studio.php?map_id='.$newId.'&cloned=1');exit;
  }elseif($action==='background_upload'){
   if(!isset($_FILES['background']))throw new RuntimeException('กรุณาเลือกรูปผังร้าน');$useAsLayout=isset($_POST['use_as_layout']);$fitCanvas=isset($_POST['fit_canvas']);$uploaded=cm_upload_image($_FILES['background'],(int)$u['id'],$d);try{db_mutate(function($x)use($postedMapId,$uploaded,$u,$useAsLayout,$fitCanvas){$idx=zs_map_index($x,$postedMapId);if($idx===null)throw new RuntimeException('ไม่พบ Floor Plan');$map=fp_map_defaults($x['floor_plans'][$idx]);$oldW=max(1,(int)$map['canvas_width']);$oldH=max(1,(int)$map['canvas_height']);$uploaded['slot']='library';$x['customer_media'][]=$uploaded;$map['background_media_id']=(int)$uploaded['id'];if($useAsLayout){$map['layout_mode']='image_hotspot';$map['background_opacity']=100;$map['background_locked']=1;}if($fitCanvas&&!empty($uploaded['width'])&&!empty($uploaded['height'])){$iw=(int)$uploaded['width'];$ih=(int)$uploaded['height'];$scale=min(1,4000/max(1,$iw),4000/max(1,$ih));$newW=max(600,(int)round($iw*$scale));$newH=max(500,(int)round($ih*$scale));if($newW>4000||$newH>4000){$scale=min(4000/$newW,4000/$newH);$newW=(int)round($newW*$scale);$newH=(int)round($newH*$scale);}$sx=$newW/$oldW;$sy=$newH/$oldH;foreach($x['floor_plan_items']??[] as &$item)if((int)($item['map_id']??0)===$postedMapId){$item['x']=(int)round(((int)($item['x']??0))*$sx);$item['y']=(int)round(((int)($item['y']??0))*$sy);$item['w']=max(24,(int)round(((int)($item['w']??80))*$sx));$item['h']=max(24,(int)round(((int)($item['h']??60))*$sy));}unset($item);$map['canvas_width']=$newW;$map['canvas_height']=$newH;}$map['updated_at']=date('c');$map['updated_by']=(int)$u['id'];$x['floor_plans'][$idx]=$map;$x['audit'][]=['at'=>date('c'),'action'=>'floor_plan_background_uploaded','map_id'=>$postedMapId,'media_id'=>(int)$uploaded['id'],'layout_mode'=>$map['layout_mode'],'by'=>(int)$u['id']];return $x;});}catch(Throwable $e){cm_delete_file($uploaded);throw $e;}$msg=$useAsLayout?'ตั้งรูปเป็น Layout หลักแล้ว · วาง Hotspot โต๊ะได้ทันที':'อัปโหลด Reference Background แล้ว';
  }elseif($action==='background_remove'){
   db_mutate(function($x)use($postedMapId,$u){$idx=zs_map_index($x,$postedMapId);if($idx===null)throw new RuntimeException('ไม่พบ Floor Plan');$x['floor_plans'][$idx]['background_media_id']=0;$x['floor_plans'][$idx]['updated_at']=date('c');$x['audit'][]=['at'=>date('c'),'action'=>'floor_plan_background_detached','map_id'=>$postedMapId,'by'=>(int)$u['id']];return $x;});$msg='เอา Reference Background ออกจาก Layout แล้ว (ไฟล์ยังอยู่ใน Media Library)';
  }else throw new RuntimeException('คำสั่ง Zone Studio ไม่ถูกต้อง');
 }catch(Throwable $e){$err=$e->getMessage();}
 $d=db_load();
}
$maps=fp_maps($d);$mapId=(int)($_GET['map_id']??$_POST['map_id']??0);if($mapId<=0&&$maps)$mapId=(int)$maps[0]['id'];$map=$mapId?fp_map($d,$mapId):null;$items=$map?fp_items($d,$mapId):[];$versions=$map?fp_versions($d,$mapId):[];$branches=zs_active_branches($d);$tables=array_values(array_filter($d['tables']??[],fn($t)=>!empty($t['active'])));$bgUrl=$map?fp_media_url($d,(int)$map['background_media_id'],'custumers/'):'';
$state=['map'=>$map,'items'=>$items,'tables'=>array_map(fn($t)=>['id'=>(int)$t['id'],'code'=>(string)$t['code'],'zone'=>(string)($t['zone']??'Main'),'capacity'=>(int)($t['capacity']??4),'status'=>(string)($t['status']??'available')],$tables),'canManage'=>$canManage];
?><!doctype html><html lang="th"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>MR BAR — Zone Studio</title><link rel="stylesheet" href="assets/admin.css?v=1182"><link rel="stylesheet" href="assets/admin-v14.css?v=1182"><link rel="stylesheet" href="assets/zone-studio-v1280.css?v=1280"><link rel="stylesheet" href="assets/zone-studio-v1281.css?v=1281"><link rel="stylesheet" href="assets/zone-studio-v1282.css?v=1282"><link rel="stylesheet" href="assets/zone-studio-v1283.css?v=1283"><link rel="stylesheet" href="assets/zone-studio-hotspot-v12910.css?v=12910"><link rel="stylesheet" href="assets/zone-studio-usability-v12911.css?v=12911"><link rel="stylesheet" href="assets/zone-studio-layout-delete-v12912.css?v=12912"></head><body class="admin-v14-page zs-page"><div class="ambient"><i></i><i></i><i></i></div><?php require_once __DIR__.'/app/admin-nav.php';echo admin_sidebar('zonestudio',$u);?><main class="zs-shell"><header class="zs-top"><button class="menu-btn" id="menuBtn">☰</button><div><p class="eyebrow">CUSTOMER / FLOOR PLAN / BOOKING MAP</p><h1>Zone Studio</h1><p>จัดผังร้าน 2D + 2.5D จากมุมบน · Zone Thumbnail · Preset โต๊ะ/เก้าอี้/อุปกรณ์สำเร็จ · ลากวางบน Desktop/Tablet · เชื่อม Booking จริง</p></div><div class="zs-top-actions" data-theme-slot><a href="custumers/#zones" target="_blank" rel="noopener">Customer Preview ↗</a></div></header>
<?php if($msg):?><div class="notice ok">✓ <?=h($msg)?></div><?php endif;?><?php if($err):?><div class="notice err">⚠ <?=h($err)?></div><?php endif;?>
<section class="zs-summary"><div><span>LAYOUTS</span><b><?=count($maps)?></b><small>Draft / Published</small></div><div><span>TABLE DIRECTORY</span><b><?=count($tables)?></b><small>โต๊ะ Active</small></div><div><span>CURRENT</span><b><?=h($map?(string)$map['status']:'—')?></b><small><?=h($map?fp_branch_name($d,$map['branch_id']):'ยังไม่มี Layout')?></small></div><div class="zs-view-badge"><span>EDITOR</span><b>2D + 2.5D</b><small>Drag · Resize · Rotate · Snap · Version</small></div></section>
<section class="zs-layout-picker"><div class="zs-layout-list"><?php foreach($maps as $m):$isCurrent=(int)$m['id']===$mapId;$isPublished=(string)$m['status']==='published';?><article class="zs-layout-card <?=$isCurrent?'active':''?> <?=$isPublished?'is-published':''?>"><a href="zone-studio.php?map_id=<?=(int)$m['id']?>" class="zs-layout-card-open"><span><?=h((string)$m['name'])?></span><small><?=h(fp_branch_name($d,$m['branch_id']))?> · <?=h(strtoupper((string)$m['status']))?></small></a><?php if($canManage):?><form method="post" class="zs-layout-delete-form" data-layout-delete-form data-layout-name="<?=h((string)$m['name'])?>" data-layout-published="<?=$isPublished?'1':'0'?>"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><input type="hidden" name="action" value="delete_layout"><input type="hidden" name="map_id" value="<?=(int)$m['id']?>"><button type="submit" class="zs-layout-delete" title="ลบ Layout <?=h((string)$m['name'])?>" aria-label="ลบ Layout <?=h((string)$m['name'])?>">ลบ</button></form><?php endif;?></article><?php endforeach;?></div><?php if($canManage):?><details class="zs-create"><summary>＋ Layout ใหม่</summary><form method="post"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><input type="hidden" name="action" value="create"><input name="name" placeholder="เช่น Main Floor / Event Layout" required><select name="branch_id"><option value="0">ทุกสาขา / Default</option><?php foreach($branches as $b):?><option value="<?=(int)$b['id']?>"><?=h((string)$b['code'].' · '.(string)$b['name'])?></option><?php endforeach;?></select><button>สร้าง Blank Layout</button></form><form method="post" class="mockup-form"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><input type="hidden" name="action" value="seed_mockup"><input type="hidden" name="name" value="Mockup ร้าน 3 ไร่"><select name="branch_id"><option value="0">ทุกสาขา / Default</option><?php foreach($branches as $b):?><option value="<?=(int)$b['id']?>"><?=h((string)$b['code'].' · '.(string)$b['name'])?></option><?php endforeach;?></select><button class="mockup">✦ สร้าง Mockup คล้ายภาพตัวอย่าง</button></form></details><?php endif;?></section>
<?php if(!$map):?><section class="zs-empty"><span>▦</span><h2>เริ่มสร้างแผนผังร้าน</h2><p>เลือก “สร้าง Mockup คล้ายภาพตัวอย่าง” เพื่อได้ Stage / Pool / Entrance / K Zone / โต๊ะตัวอย่างทันที แล้วลากปรับตามร้านจริง</p></section><?php else:?>
<section class="zs-layout-command-center">
 <header><div><span>LAYOUT SETUP</span><h2>เลือกวิธีทำผังร้าน</h2><p>เลือกได้ทันทีจากตรงนี้ ไม่ต้องเข้าเมนู Map</p></div><strong>STEP 1</strong></header>
 <div class="zs-layout-mode-cards">
  <label class="zs-layout-mode-card <?=$map['layout_mode']==='objects'?'active':''?>" data-zs-mode-card="objects"><input type="radio" name="layout_mode" value="objects" form="zoneStudioSave" <?=$map['layout_mode']==='objects'?'checked':''?> data-zs-layout-mode><i>▦</i><span><b>จัด Layout ด้วยวัตถุ</b><small>วางโต๊ะ เก้าอี้ เวที และอุปกรณ์แบบเดิม</small></span><em>เลือก</em></label>
  <label class="zs-layout-mode-card <?=$map['layout_mode']==='image_hotspot'?'active':''?>" data-zs-mode-card="image_hotspot"><input type="radio" name="layout_mode" value="image_hotspot" form="zoneStudioSave" <?=$map['layout_mode']==='image_hotspot'?'checked':''?> data-zs-layout-mode><i>⌖</i><span><b>ใช้รูป Upload เป็น Layout</b><small>นำภาพผังสำเร็จมาใช้ แล้ววางกล่องโปร่งใสครอบตำแหน่งโต๊ะ</small></span><em>เลือก</em></label>
 </div>
 <div class="zs-image-layout-setup" data-zs-image-setup>
  <div class="zs-image-layout-status"><span>STEP 2 · FLOOR IMAGE</span><b><?=$bgUrl!==''?'มีรูป Layout แล้ว':'ยังไม่มีรูป Layout'?></b><small><?=$bgUrl!==''?'เปลี่ยนรูปใหม่ได้ โดยตำแหน่งเดิมจะปรับตามสัดส่วนเมื่อเลือก Fit Canvas':'รองรับ JPG / PNG / WEBP — แนะนำภาพแนวนอนความละเอียดสูง'?></small></div>
  <form method="post" enctype="multipart/form-data" class="zs-main-upload"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><input type="hidden" name="action" value="background_upload"><input type="hidden" name="map_id" value="<?=$mapId?>"><input type="hidden" name="use_as_layout" value="1"><label class="zs-file-drop"><span>เลือกรูป Layout ร้าน</span><input type="file" name="background" accept="image/jpeg,image/png,image/webp" required></label><label class="zs-fit-check"><input type="checkbox" name="fit_canvas" checked> ปรับขนาดพื้นที่ให้ตรงสัดส่วนรูป</label><button type="submit">อัปโหลดและใช้แทน Layout เดิม ↗</button></form>
  <button type="button" class="zs-main-hotspot" data-zs-quick-hotspot>＋ เพิ่มกล่องจุดโต๊ะ</button>
 </div>
</section>
<form method="post" id="zoneStudioSave" class="zs-editor-wrap"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><input type="hidden" name="action" value="save"><input type="hidden" name="map_id" value="<?=$mapId?>"><input type="hidden" name="items_json" id="zsItemsJson" value="">
<div class="zs-hotspot-guide <?=$map['layout_mode']==='image_hotspot'?'is-active':''?>" data-zs-hotspot-guide><div><span>IMAGE HOTSPOT MODE</span><b>ใช้ภาพ Layout จริง แล้ววางกรอบโต๊ะโปร่งใสด้านบน</b><small>ขั้นตอน: อัปโหลดรูป → เพิ่ม Hotspot → ลากครอบโต๊ะ → ดับเบิลคลิกเชื่อม Table Directory → บันทึกและ Publish</small></div><button type="button" data-zs-quick-hotspot>＋ เพิ่ม Hotspot โต๊ะ</button></div><div class="zs-toolbar"><div class="zs-tool-left"><button type="button" data-zs-undo title="Undo">↶</button><button type="button" data-zs-redo title="Redo">↷</button><span></span><button type="button" data-zs-zoom-out>−</button><b data-zs-zoom-label>100%</b><button type="button" data-zs-zoom-in>＋</button><button type="button" data-zs-fit>Fit</button></div><div class="zs-mode-switch"><button type="button" class="<?=$map['view_mode']==='2d'?'active':''?>" data-zs-mode="2d">2D EDIT</button><button type="button" class="<?=$map['view_mode']==='2.5d'?'active':''?>" data-zs-mode="2.5d">2.5D PREVIEW</button><input type="hidden" name="view_mode" id="zsViewMode" value="<?=h((string)$map['view_mode'])?>"></div><div class="zs-tool-right"><button type="button" data-zs-open-map-settings>⚙ Map</button><button type="button" data-zs-duplicate>Duplicate</button><button type="button" data-zs-delete class="danger">Delete</button><button type="submit" class="primary" <?=$canManage?'':'disabled'?>>บันทึก Draft</button></div></div><div class="zs-selection-status" data-zs-selection-status><span>SELECT OBJECT</span><b>ยังไม่ได้เลือกวัตถุ</b><small>คลิกวัตถุบนผังก่อน แล้วจึงแก้ไข / Duplicate / Delete</small></div>
<section class="zs-zone-strip"><header><div><span>ZONE MANAGER</span><b>จัดโซนร้านแบบ Thumbnail</b><small>เลือกโซนเพื่อโฟกัส · เพิ่ม/เปลี่ยนชื่อ/ซ่อน/เปิดจองได้จาก Properties</small></div><em><b data-zs-zone-count>0</b> ZONES</em></header><div class="zs-zone-cards" data-zs-zones></div></section>
<div class="zs-workspace"><aside class="zs-library"><div class="zs-side-head"><span>OBJECT LIBRARY</span><b>Preset สำเร็จ · ลากวาง / คลิกเพิ่ม</b></div><div class="zs-library-tabs"><button type="button" class="active" data-zs-library-tab="table">โต๊ะสำเร็จ</button><button type="button" data-zs-library-tab="furniture">เก้าอี้ & โซฟา</button><button type="button" data-zs-library-tab="component">อุปกรณ์ร้าน</button><button type="button" data-zs-library-tab="structure">โครงสร้าง</button></div>
<div class="zs-preset-panel active" data-zs-preset-panel="table"><div class="zs-preset-grid">
<button type="button" data-zs-preset="table_rect_2"><span class="zs-preset-thumb table rect seats-2"><i></i><i></i><b></b></span><strong>โต๊ะ 2 ที่นั่ง</strong><small>Rectangle</small></button>
<button type="button" data-zs-preset="table_rect_4"><span class="zs-preset-thumb table rect seats-4"><i></i><i></i><i></i><i></i><b></b></span><strong>โต๊ะ 4 ที่นั่ง</strong><small>Rectangle</small></button>
<button type="button" data-zs-preset="table_round_4"><span class="zs-preset-thumb table round seats-4"><i></i><i></i><i></i><i></i><b></b></span><strong>โต๊ะกลม 4</strong><small>Round</small></button>
<button type="button" data-zs-preset="table_long_6"><span class="zs-preset-thumb table long seats-6"><i></i><i></i><i></i><i></i><i></i><i></i><b></b></span><strong>โต๊ะยาว 6</strong><small>Long</small></button>
<button type="button" data-zs-preset="table_long_8"><span class="zs-preset-thumb table long seats-8"><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><b></b></span><strong>โต๊ะยาว 8</strong><small>Long</small></button>
<button type="button" data-zs-preset="table_booth_4"><span class="zs-preset-thumb booth"><i></i><i></i><b></b></span><strong>Booth 4</strong><small>Sofa booth</small></button>
<button type="button" data-zs-preset="table_sofa_4"><span class="zs-preset-thumb sofa"><i></i><b></b></span><strong>Sofa Table 4</strong><small>Lounge</small></button>
<button type="button" data-zs-preset="table_bar_2"><span class="zs-preset-thumb bartable"><i></i><i></i><b></b></span><strong>Bar Table 2</strong><small>Counter seat</small></button>
<button type="button" data-zs-preset="table_standing_4"><span class="zs-preset-thumb standing"><b></b><i></i><i></i><i></i><i></i></span><strong>Standing 4</strong><small>High table</small></button>
<button type="button" data-zs-preset="table_round_6"><span class="zs-preset-thumb table round seats-6"><i></i><i></i><i></i><i></i><i></i><i></i><b></b></span><strong>โต๊ะกลม 6</strong><small>Round 6</small></button>
<button type="button" data-zs-preset="table_round_8"><span class="zs-preset-thumb table round seats-8"><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><b></b></span><strong>โต๊ะกลม 8</strong><small>Round 8</small></button>
<button type="button" data-zs-preset="table_long_10"><span class="zs-preset-thumb table long seats-8"><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><b></b></span><strong>โต๊ะยาว 10</strong><small>Banquet</small></button>
<button type="button" data-zs-preset="table_booth_6"><span class="zs-preset-thumb booth"><i></i><i></i><b></b></span><strong>Booth 6</strong><small>Large booth</small></button>
<button type="button" data-zs-preset="table_lbooth_6"><span class="zs-preset-thumb sofa"><i></i><b></b></span><strong>L Booth 6</strong><small>Corner lounge</small></button>
</div></div>
<div class="zs-preset-panel" data-zs-preset-panel="furniture"><div class="zs-preset-grid">
<button type="button" data-zs-preset="chair_single"><span class="zs-preset-thumb furniture chair">▣</span><strong>Chair</strong><small>เก้าอี้เดี่ยว</small></button>
<button type="button" data-zs-preset="chair_luxury"><span class="zs-preset-thumb furniture luxury-chair">◆</span><strong>Luxury Chair</strong><small>เก้าอี้ Lounge</small></button>
<button type="button" data-zs-preset="stool_single"><span class="zs-preset-thumb furniture stool">●</span><strong>Bar Stool</strong><small>เก้าอี้บาร์</small></button>
<button type="button" data-zs-preset="bench_2"><span class="zs-preset-thumb furniture bench">▰</span><strong>Bench 2</strong><small>ม้านั่ง 2 คน</small></button>
<button type="button" data-zs-preset="sofa_2"><span class="zs-preset-thumb furniture sofa-seat">▱</span><strong>Sofa 2</strong><small>โซฟา 2 คน</small></button>
<button type="button" data-zs-preset="sofa_4"><span class="zs-preset-thumb furniture sofa-seat wide">▱</span><strong>Sofa 4</strong><small>โซฟายาว</small></button>
</div></div>
<div class="zs-preset-panel" data-zs-preset-panel="component"><div class="zs-preset-grid">
<button type="button" data-zs-preset="partition_heavy"><span class="zs-preset-thumb component heavy-partition">▰</span><strong>Heavy Partition</strong><small>ฉากกั้นหนา</small></button>
<button type="button" data-zs-preset="partition_zigzag"><span class="zs-preset-thumb component zigzag">〽</span><strong>Zigzag Partition</strong><small>ฉากกั้นซิกแซก</small></button>
<button type="button" data-zs-preset="counter"><span class="zs-preset-thumb component counter">▰</span><strong>Counter</strong><small>เคาน์เตอร์</small></button>
<button type="button" data-zs-preset="lamp"><span class="zs-preset-thumb component lamp">◉</span><strong>Lamp</strong><small>โคมไฟ</small></button>
<button type="button" data-zs-preset="plant"><span class="zs-preset-thumb component plant">♣</span><strong>Plant</strong><small>ต้นไม้ / ตกแต่ง</small></button>
<button type="button" data-zs-preset="stage"><span class="zs-preset-thumb component stage">▱</span><strong>Stage</strong><small>เวที</small></button>
<button type="button" data-zs-preset="dj"><span class="zs-preset-thumb component dj">♫</span><strong>DJ Booth</strong><small>DJ / Sound</small></button>
<button type="button" data-zs-preset="bar"><span class="zs-preset-thumb component bar">▰</span><strong>Bar</strong><small>บาร์เครื่องดื่ม</small></button>
<button type="button" data-zs-preset="cashier"><span class="zs-preset-thumb component cashier">฿</span><strong>Cashier</strong><small>จุดชำระเงิน</small></button>
<button type="button" data-zs-preset="pool"><span class="zs-preset-thumb component pool">≈</span><strong>Pool</strong><small>สระ / Water</small></button>
<button type="button" data-zs-preset="welcome"><span class="zs-preset-thumb component welcome">WELCOME</span><strong>Welcome Sign</strong><small>ป้ายต้อนรับ</small></button>
</div></div>
<div class="zs-preset-panel" data-zs-preset-panel="structure"><div class="zs-preset-grid">
<button type="button" data-zs-preset="zone_basic"><span class="zs-preset-thumb component zone">▧</span><strong>Zone</strong><small>พื้นที่หลัก</small></button>
<button type="button" data-zs-preset="wall"><span class="zs-preset-thumb component wall">━</span><strong>Wall</strong><small>กำแพง</small></button>
<button type="button" data-zs-preset="pillar"><span class="zs-preset-thumb component pillar">●</span><strong>Pillar</strong><small>เสา</small></button>
<button type="button" data-zs-preset="walkway"><span class="zs-preset-thumb component walkway">━</span><strong>Walkway</strong><small>ทางเดิน</small></button>
<button type="button" data-zs-preset="toilet"><span class="zs-preset-thumb component toilet">WC</span><strong>Restroom</strong><small>ห้องน้ำ</small></button>
<button type="button" data-zs-preset="entrance"><span class="zs-preset-thumb component entrance">→</span><strong>Entrance</strong><small>ทางเข้า</small></button>
<button type="button" data-zs-preset="exit"><span class="zs-preset-thumb component exit">↗</span><strong>Exit</strong><small>ทางออก</small></button>
<button type="button" data-zs-preset="text"><span class="zs-preset-thumb component text">T</span><strong>Text / Label</strong><small>ข้อความ</small></button>
</div></div>
<div class="zs-reference"><div class="zs-side-head"><span>REFERENCE IMAGE</span><b>Trace ผังร้านจริง</b></div><?php if($bgUrl!==''):?><img src="<?=h($bgUrl)?>" alt="Floor plan reference"><?php else:?><div class="zs-ref-empty">ยังไม่มีรูปอ้างอิง</div><?php endif;?></div><div class="zs-layer-head"><span>LAYERS</span><small>คลิกเลือกวัตถุ</small></div><div class="zs-layers" data-zs-layers></div></aside>
<section class="zs-center"><div class="zs-canvas-tools"><span class="zs-editor-hint">ดับเบิลคลิก = รายละเอียด · คลิกขวา = Copy / Paste</span><label>Grid <input type="number" name="grid_size" id="zsGridSize" min="5" max="100" value="<?=(int)$map['grid_size']?>"></label><label class="check"><input type="checkbox" name="snap_enabled" id="zsSnap" <?=$map['snap_enabled']?'checked':''?>> Snap</label><label>W <input type="number" name="canvas_width" id="zsCanvasWidth" min="600" max="4000" value="<?=(int)$map['canvas_width']?>"></label><label>H <input type="number" name="canvas_height" id="zsCanvasHeight" min="500" max="4000" value="<?=(int)$map['canvas_height']?>"></label></div><div class="zs-viewport" data-zs-viewport><div class="zs-stage <?=$map['view_mode']==='2.5d'?'mode-25d ':''?><?=$map['layout_mode']==='image_hotspot'?'is-hotspot-mode':''?>" data-zs-stage style="--zs-w:<?=(int)$map['canvas_width']?>px;--zs-h:<?=(int)$map['canvas_height']?>px;--zs-grid:<?=(int)$map['grid_size']?>px"><div class="zs-floor-grid"></div><?php if($bgUrl!==''):?><img class="zs-bg-reference" data-zs-bg src="<?=h($bgUrl)?>" alt="" style="opacity:<?=number_format(((int)$map['background_opacity'])/100,2,'.','')?>"><?php endif;?><div data-zs-items></div></div></div></section>
<aside class="zs-inspector" data-zs-inspector aria-hidden="true" hidden><div class="zs-inspector-top"><div><span>OBJECT / MAP INSPECTOR</span><b data-zs-selected-title>ยังไม่ได้เลือกวัตถุ</b></div><div class="zs-inspector-tabs"><button type="button" class="active" data-zs-inspector-tab="object">รายละเอียด</button><button type="button" data-zs-inspector-tab="map">Map</button></div><button type="button" class="zs-inspector-close" data-zs-inspector-close aria-label="ปิด">×</button></div><div class="zs-no-selection" data-zs-empty-props>เลือกวัตถุบน Canvas, Layer หรือ Zone Thumbnail เพื่อแก้รายละเอียด</div><div class="zs-props" data-zs-props hidden>
<div class="zs-inspector-section"><header><b>IDENTITY</b><small>ชนิด / ชื่อ / โซน</small></header><div class="zs-prop-row two"><label>Type<input data-prop="type" readonly></label><label>Preset<input data-prop="preset" readonly></label></div><label>Code<input data-prop="code" maxlength="30"></label><label>Name / Label<input data-prop="name" maxlength="80"></label><label>Zone<input data-prop="zone" maxlength="60" list="zsZoneNames"></label><datalist id="zsZoneNames" data-zs-zone-names></datalist><label class="table-only">เชื่อม Table Directory<select data-prop="table_id"><option value="0">— Mockup / ยังไม่เชื่อม —</option><?php foreach($tables as $t):?><option value="<?=(int)$t['id']?>"><?=h((string)$t['code'].' · '.(string)($t['zone']??'Main').' · '.(int)($t['capacity']??4).' ที่นั่ง')?></option><?php endforeach;?></select></label></div>
<div class="zs-inspector-section"><header><b>SIZE & DIRECTION</b><small>ขนาด / มุม / ทิศทาง</small></header><div class="zs-prop-row four"><label>X<input type="number" data-prop="x"></label><label>Y<input type="number" data-prop="y"></label><label>W<input type="number" min="24" data-prop="w"></label><label>H<input type="number" min="24" data-prop="h"></label></div><div class="zs-prop-row two"><label>Rotate °<input type="number" min="-359" max="359" data-prop="rotation"></label><label>Layer<input type="number" min="0" max="999" data-prop="z_index"></label></div><div class="zs-quick-transform"><button type="button" data-zs-rotate="-90">↺ 90°</button><button type="button" data-zs-rotate="90">↻ 90°</button><button type="button" data-zs-flip="x">⇆ Flip X</button><button type="button" data-zs-flip="y">⇅ Flip Y</button></div></div>
<div class="zs-inspector-section"><header><b>STYLE</b><small>สี / ขอบ / ความโปร่ง</small></header><div class="zs-prop-row three"><label>Fill<input type="color" data-prop="color"></label><label>Border<input type="color" data-prop="border_color"></label><label>Text<input type="color" data-prop="label_color"></label></div><div class="zs-prop-row two"><label>Border px<input type="number" min="0" max="14" data-prop="border_width"></label><label>Radius<input type="number" min="0" max="120" data-prop="radius"></label></div><label>Opacity <span data-zs-opacity-label>100%</span><input type="range" min="10" max="100" data-prop="opacity"></label><label>Shape<select data-prop="shape"><option value="rect">Rectangle</option><option value="round">Round</option><option value="oval">Oval</option><option value="long">Long</option><option value="sofa">Sofa</option><option value="booth">Booth</option><option value="lbooth">L Booth</option><option value="counter">Counter</option><option value="standing">Standing</option><option value="chair">Chair</option><option value="stool">Stool</option><option value="bench">Bench</option><option value="line">Line</option><option value="zigzag">Zigzag</option><option value="label">Label</option></select></label><div class="zs-prop-row two"><label>Material<select data-prop="material"><option value="classic">Classic</option><option value="wood">Wood</option><option value="black">Black</option><option value="gold">Gold</option><option value="glass">Glass</option><option value="neon">Neon</option><option value="velvet">Velvet</option></select></label><label>Shadow<select data-prop="shadow_level"><option value="0">None</option><option value="1">Soft</option><option value="2">Medium</option><option value="3">Strong</option></select></label></div><label class="check"><input type="checkbox" data-prop="label_visible"> แสดงชื่อ/Label บนผัง</label></div>
<div class="zs-inspector-section table-only"><header><b>TABLE & BOOKING</b><small>รายละเอียดโต๊ะและการขอจอง</small></header><div class="zs-prop-row two"><label>Capacity<input type="number" min="0" max="30" data-prop="capacity"></label><label>Seats แสดงผล<input type="number" min="0" max="30" data-prop="seat_count"></label></div><label>รูปแบบเก้าอี้<select data-prop="seat_layout"><option value="auto">Auto</option><option value="top-bottom">บน / ล่าง</option><option value="left-right">ซ้าย / ขวา</option><option value="around">รอบโต๊ะ</option><option value="one-side">ด้านเดียว</option><option value="booth">Booth / Sofa</option></select></label><div class="zs-prop-row three"><label>Seat style<select data-prop="seat_style"><option value="chair">Chair</option><option value="stool">Stool</option><option value="sofa">Sofa</option><option value="bench">Bench</option><option value="luxury">Luxury</option></select></label><label>Seat color<input type="color" data-prop="seat_color"></label><label>Seat size<input type="number" min="10" max="40" data-prop="seat_size"></label></div><label>Minimum Spend<input type="number" min="0" step="1" data-prop="min_spend"></label><label>ข้อความให้ลูกค้า<textarea rows="2" data-prop="customer_note" placeholder="เช่น ใกล้เวที / วิวสระ / เหมาะ 4-6 คน"></textarea></label><label>หมายเหตุการจองภายใน<textarea rows="2" data-prop="booking_note" placeholder="เช่น ต้องมัดจำ / รับเฉพาะแพ็กเกจ VIP"></textarea></label><div class="zs-checks"><label><input type="checkbox" data-prop="reservable"> ลูกค้ากดจองได้</label><label><input type="checkbox" data-prop="customer_visible"> แสดงให้ลูกค้าเห็น</label></div></div>
<div class="zs-inspector-section zone-only"><header><b>SMART ZONE</b><small>ประเภท / ความจุ / ช่วงเวลาจอง</small></header><div class="zs-prop-row two"><label>ประเภทโซน<select data-prop="zone_type"><option value="main">Main</option><option value="vip">VIP</option><option value="stage">Stage side</option><option value="pool">Pool</option><option value="karaoke">Karaoke</option><option value="outdoor">Outdoor</option><option value="private">Private</option><option value="bar">Bar</option></select></label><label>ลำดับ<input type="number" min="0" max="9999" data-prop="sort_order"></label></div><div class="zs-prop-row two"><label>Capacity limit<input type="number" min="0" max="999" data-prop="capacity_limit" placeholder="0 = Auto"></label><label>Minimum Spend<input type="number" min="0" step="1" data-prop="min_spend"></label></div><div class="zs-prop-row two"><label>เปิดรับจอง<input type="time" data-prop="booking_start"></label><label>ปิดรับจอง<input type="time" data-prop="booking_end"></label></div><div class="zs-zone-days"><span>วันที่เปิดรับจอง</span><div><button type="button" data-zs-zone-day="1">จ</button><button type="button" data-zs-zone-day="2">อ</button><button type="button" data-zs-zone-day="3">พ</button><button type="button" data-zs-zone-day="4">พฤ</button><button type="button" data-zs-zone-day="5">ศ</button><button type="button" data-zs-zone-day="6">ส</button><button type="button" data-zs-zone-day="0">อา</button></div></div><div class="zs-checks"><label><input type="checkbox" data-prop="vip"> VIP / Premium Zone</label><label><input type="checkbox" data-prop="reservable"> ลูกค้าเลือกโซนนี้เพื่อจองได้</label><label><input type="checkbox" data-prop="customer_visible"> แสดงโซนให้ลูกค้าเห็น</label></div><label>คำอธิบายโซน<textarea rows="2" data-prop="customer_note" placeholder="เช่น VIP ใกล้เวที / เหมาะสำหรับกลุ่มใหญ่"></textarea></label><div class="zs-zone-actions"><button type="button" data-zs-clone-zone>Clone Zone + โต๊ะ</button><button type="button" data-zs-zone-auto-capacity>คำนวณ Capacity จากโต๊ะ</button></div></div>
<div class="zs-inspector-section"><header><b>DISPLAY & ACCESS</b><small>สถานะของวัตถุ</small></header><label>Description<textarea rows="3" data-prop="description"></textarea></label><div class="zs-checks"><label><input type="checkbox" data-prop="active"> Active</label><label class="generic-visible-only"><input type="checkbox" data-prop="customer_visible"> แสดงลูกค้า</label><label><input type="checkbox" data-prop="locked"> Lock</label></div><div class="zs-layer-actions"><button type="button" data-zs-layer-down>↓ Layer</button><button type="button" data-zs-layer-up>↑ Layer</button></div></div></div>
<div class="zs-map-settings" data-zs-inspector-map hidden><div class="zs-side-head"><span>MAP SETTINGS</span><b>Draft / Publish</b></div><label>รูปแบบ Layout<select data-zs-layout-mode-secondary><option value="objects" <?=$map['layout_mode']==='objects'?'selected':''?>>วางวัตถุ 2D / 2.5D แบบเดิม</option><option value="image_hotspot" <?=$map['layout_mode']==='image_hotspot'?'selected':''?>>ภาพ Layout จริง + Hotspot โต๊ะ</option></select></label><div class="zs-map-mode-note">โหมด Hotspot จะแสดงภาพพื้นหลังเต็ม 100% และซ่อนเฟอร์นิเจอร์จำลองจากหน้าลูกค้า เหลือเฉพาะจุดโต๊ะที่กดเลือกได้</div><label>ชื่อ Layout<input name="name" value="<?=h((string)$map['name'])?>" required></label><label>สาขา<select name="branch_id"><option value="0">ทุกสาขา / Default</option><?php foreach($branches as $b):?><option value="<?=(int)$b['id']?>" <?=(int)($map['branch_id']??0)===(int)$b['id']?'selected':''?>><?=h((string)$b['code'].' · '.(string)$b['name'])?></option><?php endforeach;?></select></label><label>Reference opacity <span data-bg-opacity-label><?=(int)$map['background_opacity']?>%</span><input type="range" name="background_opacity" min="0" max="100" value="<?=(int)$map['background_opacity']?>" data-zs-bg-opacity></label><label class="check"><input type="checkbox" name="background_locked" <?=$map['background_locked']?'checked':''?>> Lock reference</label><label class="check"><input type="checkbox" name="customer_enabled" <?=$map['customer_enabled']?'checked':''?>> เปิดแผนผังให้ลูกค้า</label></div></aside><div class="zs-context-menu" data-zs-context-menu hidden><button type="button" data-zs-context-copy><span>⧉</span><b>Copy</b><small>Ctrl+C</small></button><button type="button" data-zs-context-paste><span>▣</span><b>Paste Here</b><small>Ctrl+V</small></button><i></i><button type="button" data-zs-context-duplicate><span>＋</span><b>Duplicate</b></button><button type="button" data-zs-context-properties><span>⚙</span><b>รายละเอียด</b></button><button type="button" data-zs-context-delete class="danger"><span>×</span><b>Delete</b></button></div></div></form>
<section class="zs-publish-bar"><div><span>STATUS</span><b><?=h(strtoupper((string)$map['status']))?></b><small><?=!empty($map['published_at'])?'Published '.h(date('d/m/Y H:i',strtotime((string)$map['published_at']))):'ยังไม่เคย Publish'?></small></div><?php if($canManage):?><form method="post" enctype="multipart/form-data" class="zs-bg-upload"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><input type="hidden" name="action" value="background_upload"><input type="hidden" name="map_id" value="<?=$mapId?>"><label>รูป Layout ร้าน<input type="file" name="background" accept="image/jpeg,image/png,image/webp" required></label><label class="zs-upload-check"><input type="checkbox" name="use_as_layout" checked> ใช้เป็น Layout หลัก + Hotspot</label><label class="zs-upload-check"><input type="checkbox" name="fit_canvas" checked> ปรับ Canvas ตามสัดส่วนรูป</label><button>อัปโหลดและใช้ Layout</button></form><?php if($bgUrl!==''):?><form method="post"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><input type="hidden" name="action" value="background_remove"><input type="hidden" name="map_id" value="<?=$mapId?>"><button class="ghost">เอารูปอ้างอิงออก</button></form><?php endif;?><form method="post"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><input type="hidden" name="action" value="clone"><input type="hidden" name="map_id" value="<?=$mapId?>"><button class="ghost">Clone Layout</button></form><form method="post" onsubmit="return confirm('Publish Layout ปัจจุบันให้ลูกค้าเห็น?')"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><input type="hidden" name="action" value="publish"><input type="hidden" name="map_id" value="<?=$mapId?>"><button class="publish">PUBLISH TO CUSTOMER ↗</button></form><?php endif;?></section>
<?php if($versions):?><section class="zs-versions"><header><span>PUBLISH HISTORY</span><h2>Version & Rollback</h2></header><div><?php foreach(array_slice($versions,0,8) as $v):?><article><b>v<?=(int)$v['version_no']?></b><span><?=h(date('d/m/Y H:i',strtotime((string)$v['created_at'])))?></span><small><?=count((array)($v['items']??[]))?> objects</small><?php if($canManage):?><form method="post" onsubmit="return confirm('ย้อนกลับไป Version นี้เป็น Draft?')"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><input type="hidden" name="action" value="rollback"><input type="hidden" name="map_id" value="<?=$mapId?>"><input type="hidden" name="version_id" value="<?=(int)$v['id']?>"><button>Restore Draft</button></form><?php endif;?></article><?php endforeach;?></div></section><?php endif;?>
<script type="application/json" id="zoneStudioState"><?=json_encode($state,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)?></script><script src="assets/zone-studio-v12911.js?v=12911"></script><script src="assets/zone-studio-usability-v12911.js?v=12911"></script><script src="assets/zone-studio-layout-delete-v12912.js?v=12912"></script>
<?php endif;?><footer>MR BAR Zone Studio · v<?=h((string)(app_config()['version']??''))?> · additive Floor Plan data · Booking Table Directory remains source of truth</footer></main></body></html>
