<?php
declare(strict_types=1);
require __DIR__.'/../app/bootstrap.php';
require_once __DIR__.'/../app/privacy.php';
$d=db_load();$s=$d['settings']??[];$shop=(string)($s['shop_name']??'MR BAR');$version=privacy_policy_version($s);$cats=privacy_category_flags($s);$days=max(1,min(365,(int)($s['customer_privacy_consent_days']??183)));
?><!doctype html><html lang="th"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="theme-color" content="#08111f"><title>Cookie Policy — <?=h($shop)?></title><meta name="description" content="นโยบายคุกกี้ของ <?=h($shop)?>"><link rel="stylesheet" href="assets/customer.css?v=1220"></head><body class="cw-body cw-legal-body"><div class="cw-noise"></div><div class="cw-aurora a"></div><div class="cw-aurora b"></div><header class="cw-legal-top"><a class="cw-logo" href="./"><span>✦</span><b><?=h($shop)?><small>COOKIE POLICY</small></b></a><a href="./">← กลับหน้า Customer</a></header><main class="cw-legal-shell"><section class="cw-legal-hero"><span class="micro">COOKIE POLICY · VERSION <?=h($version)?></span><h1>นโยบายคุกกี้</h1><p><?=nl2br(h((string)($s['customer_cookie_policy']??'')))?></p><div class="cw-legal-actions"><a href="./?privacy=settings">จัดการคุกกี้ / ถอน Consent</a><a href="privacy.php">Privacy / PDPA ↗</a></div></section>
<section class="cw-legal-card"><h2>Necessary — จำเป็นต่อระบบ</h2><p>ใช้สำหรับ Session, CSRF, ความปลอดภัย การเข้าสู่ระบบ และการทำงานพื้นฐานของเว็บไซต์ รวมถึงคุกกี้ <code>mrbar_consent_id</code> ที่ใช้จำตัวเลือก Consent ของเบราว์เซอร์นี้ หมวดนี้จำเป็นต่อการทำงานและไม่สามารถปิดจาก Preference Center ได้</p></section>
<section class="cw-legal-card"><h2>Functional — บริการเสริม</h2><p>สถานะระบบ: <b><?=$cats['functional']?'เปิดหมวด':'ปิดหมวด'?></b></p><p>ใช้กับบริการเสริมที่เพิ่มประสบการณ์ใช้งาน เช่น Google Maps แบบฝัง หน้า Customer v1.22.0 จะเก็บ URL ไว้ใน <code>data-cookie-src</code> และไม่ตั้งค่า <code>src</code> จนกว่าจะได้รับ Functional consent ดังนั้น browser จะไม่เรียก Google Maps จาก iframe ก่อนการอนุญาต</p></section>
<section class="cw-legal-card"><h2>Analytics — การวิเคราะห์</h2><p>สถานะหมวด: <b><?=$cats['analytics']?'เปิดให้เลือก Consent':'ปิด'?></b></p><p>v1.22.0 ยังไม่ได้ติดตั้ง Analytics Tracking Script ใด ๆ หมวดนี้เตรียมโครงไว้สำหรับการเชื่อมต่อในอนาคต หากเพิ่มบริการ Analytics ภายหลัง ต้องโหลดเฉพาะเมื่อได้รับ consent ของหมวดนี้แล้ว</p></section>
<section class="cw-legal-card"><h2>Marketing — การตลาด</h2><p>สถานะหมวด: <b><?=$cats['marketing']?'เปิดให้เลือก Consent':'ปิด'?></b></p><p>v1.22.0 ยังไม่ได้ติดตั้ง Marketing Pixel หรือ Advertising Tracker ใด ๆ หากมีการเพิ่มในอนาคต ต้องผูกการโหลดกับ Marketing consent ก่อนทุกครั้ง</p></section>
<section class="cw-legal-card"><h2>อายุ Consent และ Re-consent</h2><p>Consent cookie ตั้งอายุประมาณ <?=$days?> วัน เมื่อหมดอายุหรือเมื่อ Admin เปลี่ยน Policy Version ระบบจะถือว่าไม่มี consent สำหรับ policy เวอร์ชันใหม่และแสดง Cookie Banner อีกครั้ง</p><p>ท่านสามารถเปลี่ยนจาก “ยอมรับทั้งหมด” เป็น “เฉพาะ Necessary” หรือปรับแต่ละหมวดได้ทุกเมื่อ โดยการบันทึกตัวเลือกใหม่ถือเป็นการถอน/แก้ไข consent สำหรับหมวดเสริม</p><div class="cw-legal-actions"><a href="./?privacy=settings">เปิด Cookie Preferences</a><a href="privacy.php">อ่าน Privacy Notice</a></div></section></main></body></html>
