<?php $floorEntryHotspot=$floorPlan&&(($floorPlan['layout_mode']??'objects')==='image_hotspot');if(cw_on($settings,'customer_web_show_zones')):?><section class="cw-section<?= $zonesMedia?' has-section-media':''?>" id="zones"<?= $zonesMedia?' style="--cm-overlay:'.h(cm_overlay($zonesMedia)).'"':''?>><?php if($zonesMedia):?><div class="cw-section-media"><img src="customer-media.php?id=<?=(int)$zonesMedia['id']?>&v=<?=urlencode((string)($zonesMedia['updated_at']??''))?>" alt="" style="<?=h(cm_style($zonesMedia))?>"><i></i></div><?php endif;?>
<div class="cw-section-head cw-zone-entry-head"><div><span class="micro">ZONE & TABLE</span><h2>เลือกพื้นที่ของคืนนี้</h2></div><p><?=$floorPlan?'ดูภาพผังร้านก่อน แล้วเข้าไปเลือกโต๊ะจากผังจริงได้ทันที':'เช็กโต๊ะว่างแล้วส่งคำขอจองได้จากตรงนี้'?></p></div>
<div class="cw-zone-booking-entry">
<div class="cw-zone-booking-copy">
<div class="cw-availability-hero">
<span class="cw-availability-kicker"><i></i> LIVE AVAILABILITY</span>
<div class="cw-availability-number"><b><?=$customerAvailableCount?></b><div><strong>โต๊ะว่างตอนนี้</strong><small>พร้อมส่งคำขอจอง</small></div></div>
<p>อัปเดตจากโต๊ะที่เปิดใช้งานและเปิดรับจองจริงในระบบ</p>
<i class="cw-availability-orb o1"></i><i class="cw-availability-orb o2"></i>
</div>
<div class="cw-zone-available-head"><div><span>AVAILABLE ZONES</span><b>โซนที่ยังมีโต๊ะว่าง</b></div><strong>● อัปเดตสด</strong></div>
<div class="cw-zone-mini-list cw-zone-available-list"><?php if($customerAvailableZones):$zi=0;foreach($customerAvailableZones as $zName=>$zData):if($zi++>=8)break;?><span><i style="--zone-color:<?=h((string)($zData['color']??'#7b5cff'))?>"></i><div><b><?=h((string)$zName)?></b><small><?=!empty($zData['vip'])?'VIP / PREMIUM':'พร้อมรับจอง'?></small></div><strong><?=(int)$zData['available']?><small>โต๊ะว่าง</small></strong></span><?php endforeach;else:?><span class="empty"><div><b>คืนนี้ยังไม่มีโต๊ะว่าง</b><small>ลองติดต่อร้านหรือกลับมาตรวจสอบอีกครั้ง</small></div></span><?php endif;?></div>
<div class="cw-zone-booking-actions"><?php if($floorPlan&&$floorItems):?><a class="cw-floor-open" href="floor-plan.php?public_branch=<?=urlencode($publicBranchSlug)?>"><span>ดูตำแหน่งจริงก่อนจอง</span><b>เลือกโซน / โต๊ะ ↗</b></a><?php endif;?><button class="cw-zone-quick-book" type="button" data-booking-open><span>จองแบบรวดเร็ว</span><b>เปิดแบบฟอร์มจอง ↗</b></button></div>
<?php if($floorPlan):?><small class="cw-floor-publish-note">LIVE FLOOR STATUS<?= $floorPublishedLabel!==''?' · '.h($floorPublishedLabel):''?> · <?=$customerAvailableCount?> โต๊ะพร้อมรับคำขอ</small><?php endif;?>
</div>
<div class="cw-floor-preview-column">
<?php if($floorPreviewMedia):?>
<<?php echo $floorPlan?'a':'div';?> class="cw-floor-preview-card cw-floor-preview-custom"<?php if($floorPlan):?> href="floor-plan.php?public_branch=<?=urlencode($publicBranchSlug)?>" aria-label="เปิดผังร้านจริง"<?php endif;?>><div class="cw-custom-preview-media"><img src="customer-media.php?id=<?=(int)$floorPreviewMedia['id']?>&v=<?=urlencode((string)($floorPreviewMedia['updated_at']??''))?>" alt="<?=h((string)($floorPreviewMedia['alt']?:'ผังร้าน'))?>" style="<?=h(cm_style($floorPreviewMedia))?>"><span class="cw-custom-preview-vignette"></span><span class="cw-custom-preview-sweep"></span><div class="cw-custom-preview-badge"><i></i><span>FLOOR PREVIEW</span></div><div class="cw-custom-preview-copy"><small><?=h((string)($floorPreviewMedia['caption']?:'ภาพผังร้านสำหรับประกอบการเลือกโซนและโต๊ะ'))?></small><b><?=$floorPlan?'แตะเพื่อดูผัง Interactive จริง':'ภาพผังร้าน'?></b></div></div><div class="cw-floor-preview-bottom"><div><span><?=$floorPlan?'INTERACTIVE FLOOR MAP':'VENUE FLOOR PREVIEW'?></span><b><?=$floorPlan?'ดูตำแหน่งโต๊ะจริงและเลือกจอง':'ดูภาพประกอบก่อนจอง'?></b></div><?php if($floorPlan):?><strong>↗</strong><?php endif;?></div></<?php echo $floorPlan?'a':'div';?>>
<?php elseif($floorPlan&&$floorItems):?>
<a class="cw-floor-preview-card" href="floor-plan.php?public_branch=<?=urlencode($publicBranchSlug)?>" aria-label="เปิดผังร้านจริง"><div class="cw-floor-preview-top"><span>LIVE FLOOR PREVIEW</span><b><?=h((string)$floorPlan['name'])?></b><small><?=h(fp_branch_name($d,$floorPlan['branch_id']))?></small></div><div class="cw-floor-preview-stage <?=$floorEntryHotspot?'is-hotspot-preview':''?><?=($floorEntryHotspot&&$floorBg!=='')?' has-floor-artwork':''?>" style="--preview-ratio:<?=h(number_format(((int)$floorPlan['canvas_width'])/max(1,(int)$floorPlan['canvas_height']),5,'.',''))?>;<?php if($floorBg!==''):?>--preview-bg:url('<?=h($floorBg)?>');--preview-bg-opacity:<?=h(number_format($floorEntryHotspot?1:((int)$floorPlan['background_opacity'])/100,2,'.',''))?>;<?php endif;?>"><?php if($floorEntryHotspot&&$floorBg!==''):?><img class="cw-floor-preview-artwork" data-floor-artwork src="<?=h($floorBg)?>" alt="ภาพผังร้าน <?=h((string)$floorPlan['name'])?>"><?php endif;?><?php foreach($floorItems as $fi):if($floorEntryHotspot&&((string)($fi['type']??'')!=='table'))continue;$pfs=fp_table_state($d,$fi);$pl=((float)$fi['x']/max(1,(int)$floorPlan['canvas_width']))*100;$pt=((float)$fi['y']/max(1,(int)$floorPlan['canvas_height']))*100;$pw=((float)$fi['w']/max(1,(int)$floorPlan['canvas_width']))*100;$ph=((float)$fi['h']/max(1,(int)$floorPlan['canvas_height']))*100;$ptype=(string)$fi['type'];$pname=(string)($fi['name']?:$pfs['code']?:$fi['code']?:strtoupper($ptype));?><span class="cw-floor-preview-item type-<?=h($ptype)?> status-<?=h((string)$pfs['status'])?>" style="left:<?=h(number_format($pl,3,'.',''))?>%;top:<?=h(number_format($pt,3,'.',''))?>%;width:<?=h(number_format($pw,3,'.',''))?>%;height:<?=h(number_format($ph,3,'.',''))?>%;--item-color:<?=h((string)$fi['color'])?>;--item-border:<?=h((string)($fi['border_color']??'#ffffff'))?>;--item-radius:<?=(int)($fi['radius']??14)?>px;--item-rot:<?=(int)($fi['rotation']??0)?>deg;z-index:<?=(int)($fi['z_index']??10)?>"><i><?=in_array($ptype,['table','stage','pool','entrance','toilet','bar'],true)?h($pname):''?></i></span><?php endforeach;?><span class="cw-floor-preview-scan"></span></div><div class="cw-floor-preview-bottom"><div><span>INTERACTIVE MAP</span><b>แตะเพื่อเปิดผังเต็ม</b></div><strong>↗</strong></div></a>
<?php else:?><div class="cw-floor-preview-empty"><span>FLOOR PREVIEW</span><b>กำลังเตรียมผังร้าน</b><p>Admin สามารถอัปโหลดภาพผังสวยจากภายนอกได้ใน Customer Web → Sections</p></div><?php endif;?></div>
</div>
</section><?php endif;?>