<?php if(cw_on($settings,'customer_web_show_zones')):?><section class="cw-section<?= $zonesMedia?' has-section-media':''?>" id="zones"<?= $zonesMedia?' style="--cm-overlay:'.h(cm_overlay($zonesMedia)).'"':''?>><?php if($zonesMedia):?><div class="cw-section-media"><img src="customer-media.php?id=<?=(int)$zonesMedia['id']?>&v=<?=urlencode((string)($zonesMedia['updated_at']??''))?>" alt="" style="<?=h(cm_style($zonesMedia))?>"><i></i></div><?php endif;?>
<div class="cw-section-head cw-zone-entry-head"><div><span class="micro">ZONE & TABLE</span><h2>เลือกพื้นที่ของคืนนี้</h2></div><p><?=$floorPlan?'ดูผังร้านจริงก่อนตัดสินใจ · แล้วเลือกโต๊ะที่ต้องการจองได้ทันที':'จำนวนโต๊ะว่างอ่านจากระบบจริง'?></p></div>
<div class="cw-zone-booking-entry">
<div class="cw-zone-booking-copy">
<div class="cw-zone-kpis"><span><b><?=$floorPlan?count($floorZoneItems):count($zones)?></b><small>โซน</small></span><span><b><?=$floorPlan?count($floorLinkedTableItems):count($allActiveTables)?></b><small>โต๊ะในผัง</small></span><span><b><?=$floorPlan?$floorAvailableCount:count($tables)?></b><small>ว่างตอนนี้</small></span></div>
<div class="cw-zone-mini-list"><?php if($floorZoneItems):foreach(array_slice($floorZoneItems,0,6) as $fz):$fzName=(string)($fz['name']?:$fz['code']?:'Zone');?><span><i style="--zone-color:<?=h((string)$fz['color'])?>"></i><b><?=h($fzName)?></b><small><?=!empty($fz['vip'])?'VIP / PREMIUM':(!empty($fz['reservable'])?'เปิดรับจอง':'ดูพื้นที่')?></small></span><?php endforeach;elseif($zones):foreach(array_slice($zones,0,6,true) as $name=>$z):?><span><i></i><b><?=h((string)$name)?></b><small><?=$z['available']?> / <?=$z['total']?> โต๊ะว่าง</small></span><?php endforeach;else:?><span class="empty"><b>ยังไม่มีข้อมูล Zone</b><small>ตั้งค่าโต๊ะและ Publish Layout จากหลังบ้าน</small></span><?php endif;?></div>
<div class="cw-zone-booking-actions"><?php if($floorPlan&&$floorItems):?><a class="cw-floor-open" href="floor-plan.php"><span>ดูผังร้านจริง</span><b>เลือกโซน / โต๊ะ ↗</b></a><?php endif;?><button class="cw-zone-quick-book" type="button" data-booking-open><span>จองโต๊ะตอนนี้</span><b>เปิดแบบฟอร์ม ↗</b></button></div>
<?php if($floorPlan):?><small class="cw-floor-publish-note">PUBLISHED FLOOR PLAN<?= $floorPublishedLabel!==''?' · '.h($floorPublishedLabel):''?> · <?=$floorBookableCount?> โต๊ะส่งคำขอจองได้</small><?php endif;?>
</div>
<div class="cw-floor-preview-column"><?php if($floorPlan&&$floorItems):?><a class="cw-floor-preview-card" href="floor-plan.php" aria-label="เปิดผังร้านจริง"><div class="cw-floor-preview-top"><span>LIVE FLOOR PREVIEW</span><b><?=h((string)$floorPlan['name'])?></b><small><?=h(fp_branch_name($d,$floorPlan['branch_id']))?></small></div><div class="cw-floor-preview-stage" style="--preview-ratio:<?=h(number_format(((int)$floorPlan['canvas_width'])/max(1,(int)$floorPlan['canvas_height']),5,'.',''))?>;<?php if($floorBg!==''):?>--preview-bg:url('<?=h($floorBg)?>');--preview-bg-opacity:<?=h(number_format(((int)$floorPlan['background_opacity'])/100,2,'.',''))?>;<?php endif;?>"><?php foreach($floorItems as $fi):$pfs=fp_table_state($d,$fi);$pl=((float)$fi['x']/max(1,(int)$floorPlan['canvas_width']))*100;$pt=((float)$fi['y']/max(1,(int)$floorPlan['canvas_height']))*100;$pw=((float)$fi['w']/max(1,(int)$floorPlan['canvas_width']))*100;$ph=((float)$fi['h']/max(1,(int)$floorPlan['canvas_height']))*100;$ptype=(string)$fi['type'];$pname=(string)($fi['name']?:$pfs['code']?:$fi['code']?:strtoupper($ptype));?><span class="cw-floor-preview-item type-<?=h($ptype)?> status-<?=h((string)$pfs['status'])?>" style="left:<?=h(number_format($pl,3,'.',''))?>%;top:<?=h(number_format($pt,3,'.',''))?>%;width:<?=h(number_format($pw,3,'.',''))?>%;height:<?=h(number_format($ph,3,'.',''))?>%;--item-color:<?=h((string)$fi['color'])?>;--item-border:<?=h((string)($fi['border_color']??'#ffffff'))?>;--item-radius:<?=(int)($fi['radius']??14)?>px;--item-rot:<?=(int)($fi['rotation']??0)?>deg;z-index:<?=(int)($fi['z_index']??10)?>"><i><?=in_array($ptype,['table','stage','pool','entrance','toilet','bar'],true)?h($pname):''?></i></span><?php endforeach;?><span class="cw-floor-preview-scan"></span></div><div class="cw-floor-preview-bottom"><div><span>INTERACTIVE MAP</span><b>แตะเพื่อเปิดผังเต็ม</b></div><strong>↗</strong></div></a><?php else:?><div class="cw-floor-preview-empty"><span>FLOOR PLAN</span><b>กำลังเตรียมผังร้าน</b><p>เมื่อ Admin Publish Layout จาก Zone Studio ผังจริงจะปรากฏตรงนี้อัตโนมัติ</p></div><?php endif;?></div>
</div>
</section><?php endif;?>