<?php
require __DIR__.'/../app/bootstrap.php';
require_once __DIR__.'/../app/floor-plan.php';
$d=db_load();$currentBranch=branch_current($d);$publicBranchSlug=(string)($currentBranch['slug']??'');$settings=$d['settings']??[];$shop=(string)($settings['shop_name']??'MR BAR');
if(($settings['maintenance']??'0')==='1'||($settings['customer_web_enabled']??'1')!=='1'){header('Location: index.php');exit;}
$branch=$currentBranch;
$floorPlan=fp_public_plan($d,$branch?(int)($branch['id']??0):null);$floorItems=$floorPlan?fp_public_items($d,(int)$floorPlan['id']):[];$floorBg=$floorPlan?fp_media_url($d,(int)($floorPlan['background_media_id']??0),''):'';$floorZoneItems=$floorPlan?array_values(array_filter($floorItems,fn($i)=>(string)($i['type']??'')==='zone'&&!empty($i['customer_visible']))):[];
$floorTables=array_values(array_filter($floorItems,fn($i)=>(string)($i['type']??'')==='table'));$available=0;$bookable=0;foreach($floorTables as $ft){$s=fp_table_state($d,$ft);if(($s['status']??'')==='available')$available++;if(!empty($s['can_book']))$bookable++;}
?><!doctype html><html lang="th"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="theme-color" content="#08111f"><title><?=h($shop)?> — Floor Plan</title><meta name="description" content="ดูผังร้าน เลือกโซนและโต๊ะที่ต้องการจอง"><link rel="stylesheet" href="assets/customer.css?v=1220"><link rel="stylesheet" href="assets/customer-floor-map-v1280.css?v=1280"><link rel="stylesheet" href="assets/customer-floor-map-v1281.css?v=1281"><link rel="stylesheet" href="assets/customer-floor-map-v1282.css?v=1282"><link rel="stylesheet" href="assets/customer-floor-map-v1284.css?v=1284"><link rel="stylesheet" href="assets/customer-floor-page-v1292.css?v=1292"><link rel="stylesheet" href="assets/customer-floor-hotspot-v12910.css?v=12910"><link rel="stylesheet" href="assets/customer-floor-artwork-v12913.css?v=12913"></head><body class="cw-body cw-floor-page"><div class="cw-noise"></div><div class="cw-aurora a"></div><div class="cw-aurora b"></div>
<header class="cw-floor-page-header"><a href="index.php?public_branch=<?=urlencode($publicBranchSlug)?>#zones" class="cw-floor-back">← <span>กลับหน้าหลัก</span></a><a class="cw-logo" href="index.php?public_branch=<?=urlencode($publicBranchSlug)?>"><span>✦</span><b><?=h($shop)?><small>FLOOR PLAN & BOOKING</small></b></a><div class="cw-floor-head-actions" data-theme-slot><a href="reserve.php?public_branch=<?=urlencode($publicBranchSlug)?>" class="cw-floor-direct-book">จองแบบฟอร์ม ↗</a></div></header>
<main class="cw-floor-page-main"><section class="cw-floor-page-hero"><div><span class="micro">INTERACTIVE FLOOR PLAN</span><h1>เลือกโต๊ะที่เหมาะกับคืนนี้ของคุณ</h1><p>ดูผังร้านจริงจาก Layout ที่ร้าน Publish ล่าสุด เลือกจำนวนคน โซน หรือ VIP แล้วแตะโต๊ะที่ต้องการเพื่อส่งคำขอจอง</p></div><div class="cw-floor-page-kpis"><span><b><?=count($floorZoneItems)?></b><small>โซน</small></span><span><b><?=count($floorTables)?></b><small>โต๊ะในผัง</small></span><span><b><?=$available?></b><small>ว่างตอนนี้</small></span><span><b><?=$bookable?></b><small>ส่งคำขอจองได้</small></span></div></section><?php require __DIR__.'/floor-map-full-v1292.php';?><div class="cw-floor-page-note"><b>หมายเหตุ</b><p>โต๊ะที่เลือกจากผังเป็น “คำขอเลือกโต๊ะ” จนกว่าร้านจะยืนยัน การจัดโต๊ะจริงยังขึ้นกับสถานะโต๊ะและการดำเนินงานของร้านในเวลานั้น</p></div></main>
<footer class="cw-floor-page-footer"><span>© <?=date('Y')?> <?=h($shop)?> · Customer Floor Plan</span><a href="index.php?public_branch=<?=urlencode($publicBranchSlug)?>#zones">กลับหน้าโต๊ะ</a><a href="reserve.php?public_branch=<?=urlencode($publicBranchSlug)?>">Reservation</a></footer><script src="assets/customer.js?v=1220"></script><script src="assets/customer-floor-map-v1292.js?v=1292"></script><script src="assets/customer-floor-artwork-v12913.js?v=12913"></script></body></html>