<?php if($floorPlan&&$floorItems):$floorLayoutMode=(string)($floorPlan['layout_mode']??'objects');$floorHotspotMode=$floorLayoutMode==='image_hotspot';$floorRenderItems=$floorHotspotMode?array_values(array_filter($floorItems,fn($i)=>(string)($i['type']??'')==='table')):$floorItems;?>
<div class="cw-floor-map-wrap cw-floor-map-full <?=$floorHotspotMode?'is-hotspot-mode':''?>" data-floor-map data-layout-mode="<?=h($floorLayoutMode)?>">
  <div class="cw-floor-map-head">
    <div><span>INTERACTIVE FLOOR PLAN</span><b><?=h((string)$floorPlan['name'])?></b><small><?=h(fp_branch_name($d,$floorPlan['branch_id']))?></small></div>
    <div class="cw-floor-map-tools"><button type="button" class="active" data-floor-mode="2d">2D</button><?php if(!$floorHotspotMode):?><button type="button" data-floor-mode="2.5d">2.5D</button><?php endif;?><button type="button" data-floor-fit>FIT</button></div>
  </div>
  <?php if($floorZoneItems):?><div class="cw-floor-zone-nav" aria-label="เลือกโซน"><?php foreach($floorZoneItems as $fz):$fzName=(string)($fz['name']?:$fz['code']?:'Zone');?><button type="button" data-floor-zone="<?=h($fzName)?>" data-zone-vip="<?=!empty($fz['vip'])?'1':'0'?>"><i style="--zone-color:<?=h((string)$fz['color'])?>"></i><span><?=h($fzName)?></span><small><?=!empty($fz['vip'])?'VIP · ':''?><?=!empty($fz['reservable'])?'เลือกจองได้':'ดูพื้นที่'?><?=(($fz['booking_start']??'')!==''&&($fz['booking_end']??'')!=='')?' · '.h((string)$fz['booking_start']).'–'.h((string)$fz['booking_end']):''?></small></button><?php endforeach;?></div><?php endif;?>
  <div class="cw-floor-map-shell"><div class="cw-floor-map-stage <?=$floorHotspotMode?'is-hotspot-stage':''?><?=($floorHotspotMode&&$floorBg!=='')?' has-floor-artwork':''?>" data-floor-stage style="--floor-ratio:<?=h(number_format(((int)$floorPlan['canvas_width'])/max(1,(int)$floorPlan['canvas_height']),5,'.',''))?>;<?php if($floorBg!==''):?>--floor-bg:url('<?=h($floorBg)?>');--floor-bg-opacity:<?=h(number_format($floorHotspotMode?1:((int)$floorPlan['background_opacity'])/100,2,'.',''))?>;<?php endif;?>">
  <?php if($floorHotspotMode&&$floorBg!==''):?><img class="cw-floor-artwork" data-floor-artwork src="<?=h($floorBg)?>" alt="ภาพผังร้าน <?=h((string)$floorPlan['name'])?>"><span class="cw-floor-artwork-error" data-floor-artwork-error hidden>ไม่สามารถโหลดภาพผังร้านได้ กรุณารีเฟรชหรือติดต่อร้าน</span><?php endif;?>
  <?php foreach($floorRenderItems as $fi):$fs=fp_table_state($d,$fi);$left=((float)$fi['x']/max(1,(int)$floorPlan['canvas_width']))*100;$top=((float)$fi['y']/max(1,(int)$floorPlan['canvas_height']))*100;$fw=((float)$fi['w']/max(1,(int)$floorPlan['canvas_width']))*100;$fh=((float)$fi['h']/max(1,(int)$floorPlan['canvas_height']))*100;$isTable=$fi['type']==='table';?>
    <button type="button" class="cw-floor-item type-<?=h((string)$fi['type'])?> shape-<?=h((string)$fi['shape'])?> material-<?=h((string)($fi['material']??'classic'))?> shadow-<?=(int)($fi['shadow_level']??1)?> status-<?=h((string)$fs['status'])?><?=$isTable?' is-table':''?>" style="left:<?=h(number_format($left,3,'.',''))?>%;top:<?=h(number_format($top,3,'.',''))?>%;width:<?=h(number_format($fw,3,'.',''))?>%;height:<?=h(number_format($fh,3,'.',''))?>%;--fi-color:<?=h((string)$fi['color'])?>;--fi-text:<?=h((string)$fi['label_color'])?>;--fi-border:<?=h((string)($fi['border_color']??'#ffffff'))?>;--fi-border-w:<?=(int)($fi['border_width']??2)?>px;--fi-opacity:<?=h(number_format(((int)($fi['opacity']??100))/100,2,'.',''))?>;--fi-radius:<?=(int)($fi['radius']??14)?>px;--seat-color:<?=h((string)($fi['seat_color']??'#6f7890'))?>;--seat-size:<?=(int)($fi['seat_size']??18)?>px;--fi-rot:<?=h((string)(int)$fi['rotation'])?>deg;--fi-flip-x:<?=!empty($fi['flip_x'])?'-1':'1'?>;--fi-flip-y:<?=!empty($fi['flip_y'])?'-1':'1'?>;z-index:<?=(int)$fi['z_index']?>" data-floor-item data-type="<?=h((string)$fi['type'])?>" data-code="<?=h((string)$fs['code'])?>" data-name="<?=h((string)($fi['name']?:$fs['code']))?>" data-zone="<?=h((string)$fs['zone'])?>" data-capacity="<?=(int)$fs['capacity']?>" data-status="<?=h((string)$fs['status'])?>" data-table-id="<?=(int)($fi['table_id']??0)?>" data-can-book="<?=$fs['can_book']?'1':'0'?>" data-min-spend="<?=h((string)($fi['min_spend']??'0'))?>" data-description="<?=h((string)($fi['description']??''))?>" data-customer-note="<?=h((string)($fi['customer_note']??''))?>" data-preset="<?=h((string)($fi['preset']??'basic'))?>" data-seat-count="<?=(int)($fi['seat_count']??$fi['capacity']??0)?>" data-seat-layout="<?=h((string)($fi['seat_layout']??'auto'))?>" data-seat-style="<?=h((string)($fi['seat_style']??'chair'))?>" data-seat-size="<?=(int)($fi['seat_size']??18)?>" data-seat-color="<?=h((string)($fi['seat_color']??'#6f7890'))?>" data-label-visible="<?=!empty($fi['label_visible'])?'1':'0'?>" aria-label="<?=h((string)($fi['name']?:$fs['code']?:$fi['type']))?>"><span class="cw-floor-label<?=empty($fi['label_visible'])?' is-hidden':''?>"><?=h((string)($fi['name']?:$fs['code']?:strtoupper((string)$fi['type'])))?></span><?php if($isTable):?><i class="cw-floor-status-dot"></i><?php endif;?></button>
  <?php endforeach;?></div></div>
  <div class="cw-floor-map-foot"><div class="cw-floor-legend"><span><i class="available"></i>ว่าง</span><span><i class="occupied"></i>ไม่ว่าง</span><span><i class="blocked"></i>ปิด</span><span><i class="mockup"></i>ยังไม่เชื่อมโต๊ะ</span></div><div class="cw-floor-tip"><?=$floorHotspotMode?'แตะบริเวณโต๊ะบนภาพเพื่อดูรายละเอียด · จุดสีเขียวคือโต๊ะที่ว่าง':'แตะโต๊ะเพื่อดูรายละเอียด · เลื่อน/ซูมด้วย FIT บนมือถือ'?></div></div>
  <aside class="cw-floor-detail" data-floor-detail hidden><button type="button" class="cw-floor-detail-close" data-floor-detail-close>×</button><small data-floor-detail-kicker>TABLE</small><h3 data-floor-detail-title>—</h3><p data-floor-detail-desc></p><div class="cw-floor-detail-meta"><span><b data-floor-detail-zone>—</b><small>ZONE</small></span><span><b data-floor-detail-capacity>—</b><small>CAPACITY</small></span><span><b data-floor-detail-status>—</b><small>STATUS</small></span><span><b data-floor-detail-spend>—</b><small>MIN SPEND</small></span></div><button type="button" class="cw-floor-book" data-floor-book>จองโต๊ะนี้ ↗</button></aside>
</div>
<?php else:?><div class="cw-floor-page-empty"><span>FLOOR PLAN</span><h2>ยังไม่มีผังร้านที่ Publish</h2><p>กรุณาติดต่อร้านหรือใช้แบบฟอร์มจองโต๊ะตามปกติ</p><a href="index.php#zones">กลับหน้าหลัก</a></div><?php endif;?>