<?php
declare(strict_types=1);
require __DIR__.'/../app/bootstrap.php';
require_once __DIR__.'/../app/privacy.php';
$d=db_load();$s=$d['settings']??[];$shop=(string)($s['shop_name']??'MR BAR');$version=privacy_policy_version($s);$contact=trim((string)($s['customer_privacy_contact']??''));if($contact==='')$contact=trim((string)($s['shop_phone']??''));if($contact==='')$contact='กรุณาติดต่อร้านผ่านช่องทางที่แสดงบนเว็บไซต์';
?><!doctype html><html lang="th"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="theme-color" content="#08111f"><title>Privacy Notice / PDPA — <?=h($shop)?></title><meta name="description" content="ประกาศความเป็นส่วนตัวและ PDPA ของ <?=h($shop)?>"><link rel="stylesheet" href="assets/customer.css?v=1220"></head><body class="cw-body cw-legal-body"><div class="cw-noise"></div><div class="cw-aurora a"></div><div class="cw-aurora b"></div><header class="cw-legal-top"><a class="cw-logo" href="./"><span>✦</span><b><?=h($shop)?><small>PRIVACY / PDPA</small></b></a><a href="./">← กลับหน้า Customer</a></header><main class="cw-legal-shell"><section class="cw-legal-hero"><span class="micro">PRIVACY NOTICE · POLICY <?=h($version)?></span><h1>ประกาศความเป็นส่วนตัว</h1><p><?=nl2br(h((string)($s['customer_privacy_notice']??'')))?></p><div class="cw-legal-actions"><a href="cookies.php">Cookie Policy ↗</a><a href="./?privacy=settings">จัดการคุกกี้ / ถอน Consent</a></div></section>
<section class="cw-legal-card"><h2>1. ข้อมูลที่เราอาจเก็บ</h2><ul><li>ข้อมูลที่ท่านให้โดยตรง เช่น ชื่อ/Nickname เบอร์โทร รายละเอียดการจอง โต๊ะ วันเวลา และหมายเหตุ</li><li>ข้อมูล Check-in และข้อมูลการให้บริการที่จำเป็นต่อการดำเนินงานในคืนที่ใช้บริการ</li><li>ข้อมูลทางเทคนิคที่จำเป็นต่อ Session ความปลอดภัย CSRF และการทำงานของเว็บไซต์</li><li>บันทึก Cookie Consent ได้แก่ Consent ID, Policy Version, เวลา และ hash ของข้อมูลเทคนิค โดยระบบไม่เก็บ IP Address หรือ User-Agent แบบ raw ใน Consent Log</li></ul></section>
<section class="cw-legal-card"><h2>2. วัตถุประสงค์และฐานการประมวลผล</h2><ul><li>ดำเนินการตามคำขอจองโต๊ะ Check-in ติดต่อกลับ และให้บริการที่ท่านร้องขอ</li><li>รักษาความปลอดภัย ป้องกันการใช้งานผิดปกติ และบริหารระบบ/การปฏิบัติงานของร้าน</li><li>ปฏิบัติตามหน้าที่หรือข้อกำหนดตามกฎหมายที่เกี่ยวข้องเมื่อมี</li><li>บริการหรือคุกกี้ที่ไม่จำเป็น เช่น Google Maps แบบฝัง จะใช้เมื่อได้รับความยินยอมในหมวดที่เกี่ยวข้องเท่านั้น</li></ul><p>การประมวลผลแต่ละรายการอาจอาศัยฐานที่แตกต่างกันตามบริบท เช่น ความจำเป็นเพื่อดำเนินการตามคำขอ/การให้บริการ ประโยชน์โดยชอบด้วยกฎหมาย หน้าที่ตามกฎหมาย หรือความยินยอมสำหรับกิจกรรมที่ต้องใช้ความยินยอม</p></section>
<section class="cw-legal-card"><h2>3. การเปิดเผยข้อมูล</h2><p>เราเปิดเผยข้อมูลเท่าที่จำเป็นแก่พนักงานหรือผู้ที่เกี่ยวข้องกับการให้บริการ ผู้ให้บริการระบบที่จำเป็น หรือหน่วยงานที่มีอำนาจตามกฎหมายเท่านั้น สำหรับบริการภายนอกบนหน้าเว็บ เช่น Google Maps ระบบจะไม่โหลด iframe ก่อน Functional consent เมื่อระบบ Cookie/PDPA เปิดใช้งาน</p></section>
<section class="cw-legal-card"><h2>4. ระยะเวลาการเก็บรักษา</h2><p>ข้อมูลจะถูกเก็บเท่าที่จำเป็นตามวัตถุประสงค์การให้บริการ การรักษาความปลอดภัย ข้อกำหนดทางบัญชี/กฎหมาย และนโยบายภายในที่เกี่ยวข้อง ส่วน Consent Log ถูกตั้งค่าให้เก็บประมาณ <?=h((string)($s['customer_privacy_log_retention_days']??365))?> วัน และระบบจำกัดจำนวน Log สูงสุดเพื่อควบคุมการเก็บข้อมูลเกินจำเป็น</p></section>
<section class="cw-legal-card"><h2>5. สิทธิของเจ้าของข้อมูล</h2><p>ภายใต้เงื่อนไขของกฎหมาย ท่านอาจมีสิทธิขอเข้าถึงหรือรับสำเนา ขอแก้ไข ขอให้ลบหรือทำลาย ขอจำกัดการใช้ คัดค้านการประมวลผล ขอรับ/โอนข้อมูลในกรณีที่ใช้บังคับ ถอนความยินยอมสำหรับกิจกรรมที่อาศัยความยินยอม และร้องเรียนต่อหน่วยงานกำกับดูแล การถอนความยินยอมจะไม่กระทบการประมวลผลที่ได้ดำเนินการโดยชอบก่อนถอน</p></section>
<section class="cw-legal-card"><h2>6. ติดต่อเรื่องข้อมูลส่วนบุคคล</h2><p><?=h($contact)?></p><p>หากมีการเปลี่ยนแปลงสาระสำคัญของนโยบาย ร้านสามารถเปลี่ยน Policy Version เพื่อให้ระบบขอ Cookie Re-consent ใหม่โดยอัตโนมัติ</p><div class="cw-legal-actions"><a href="./?privacy=settings">เปลี่ยน / ถอน Cookie Consent</a><a href="./">กลับหน้า Customer</a></div></section></main></body></html>
